#include "RGUFWriter.hpp"
#include "RGUFPlatform.hpp"
#include "RGUFQuant.hpp"
#include <fstream>
#include <cstring>
#include <algorithm>
#include <functional>
#include <cmath>
namespace rguf {
static bool readall(const std::string&p,std::vector<uint8_t>&b){std::ifstream f(p,std::ios::binary);if(!f)return false;f.seekg(0,std::ios::end);auto n=f.tellg();if(n<0)return false;f.seekg(0);b.resize((size_t)n);return (bool)f.read((char*)b.data(),n);}
template<class T>static bool rd(const std::vector<uint8_t>&b,size_t&o,T&v){if(o> b.size()||sizeof(T)>b.size()-o)return false;std::memcpy(&v,b.data()+o,sizeof(T));o+=sizeof(T);return true;}
static bool str(const std::vector<uint8_t>&b,size_t&o,std::string&s){uint64_t n;if(!rd(b,o,n)||n>SIZE_MAX-o)return false;s.assign((const char*)b.data()+o,(size_t)n);o+=(size_t)n;return true;}
static bool skipv(const std::vector<uint8_t>&b,size_t&o,uint32_t t){switch(t){case 0:case 1:case 7:{uint8_t v;return rd(b,o,v);}case 2:{uint16_t v;return rd(b,o,v);}case 3:{int16_t v;return rd(b,o,v);}case 4:{uint32_t v;return rd(b,o,v);}case 5:{int32_t v;return rd(b,o,v);}case 6:{float v;return rd(b,o,v);}case 8:return str(b,o,*new std::string);case 9:{uint32_t et;uint64_t n;if(!rd(b,o,et)||!rd(b,o,n))return false;for(uint64_t i=0;i<n;i++)if(!skipv(b,o,et))return false;return true;}case 10:{uint64_t v;return rd(b,o,v);}case 11:{int64_t v;return rd(b,o,v);}case 12:{double v;return rd(b,o,v);}default:return false;}}
static uint64_t elems(const std::vector<uint64_t>&d){uint64_t n=1;for(auto x:d){if(x&&n>UINT64_MAX/x)return 0;n*=x;}return n;}
static size_t type_bytes(uint32_t t,uint64_t e){switch(t){case 0:return e*4;case 1:return e*2;case 30:return ((e+31)/32)*18;case 31:return ((e+31)/32)*20;case 32:return ((e+31)/32)*22;case 33:return ((e+31)/32)*24;case 34:return ((e+31)/32)*34;case 36:return ((e+31)/32)*36;case 10:return ((e+255)/256)*84;case 11:return ((e+255)/256)*110;case 12:return ((e+255)/256)*144;case 13:return ((e+255)/256)*176;case 14:return ((e+255)/256)*210;default:return 0;}}
static uint16_t f32to16(float x){uint32_t u;std::memcpy(&u,&x,4);uint32_t s=(u>>31),e=(u>>23)&255,m=u&0x7fffff;if(e==255)return (uint16_t)((s<<15)|0x7c00|(m?0x200:0));int ne=(int)e-127+15;if(ne>=31)return (uint16_t)((s<<15)|0x7c00);if(ne<=0){if(ne<-10)return (uint16_t)(s<<15);m|=0x800000;return (uint16_t)((s<<15)|(m>>(14-ne)));}return (uint16_t)((s<<15)|((uint32_t)ne<<10)|(m>>13));}
static float f16to32(uint16_t h){uint32_t s=(h>>15)&1,e=(h>>10)&31,m=h&1023,u;if(!e){if(!m)return s?-0.f:0.f;float v=(float)m/1024.0f;return s?-std::ldexp(v,-14):std::ldexp(v,-14);}if(e==31){u=(s<<31)|0x7f800000|(m<<13);float f;std::memcpy(&f,&u,4);return f;}return std::ldexp((s?-1.f:1.f)*(1.f+m/1024.f),e-15);}
static void append(std::vector<uint8_t>&v,const void*p,size_t n){auto*q=(const uint8_t*)p;v.insert(v.end(),q,q+n);} 
bool Writer::pack(const std::string&gguf,const std::string&out,bool encrypt,const uint8_t key[32],std::string&err){
 std::vector<uint8_t>b;if(!readall(gguf,b)){err="cannot read GGUF";return false;}
 // Fully parse header + metadata and tensor directory.
 size_t o=0;uint32_t magic,ver;uint64_t nt,nkv;if(!rd(b,o,magic)||magic!=0x46554747u||!rd(b,o,ver)||ver<2||ver>3||!rd(b,o,nt)||!rd(b,o,nkv)){err="invalid GGUF header";return false;}uint64_t align=32;
 for(uint64_t i=0;i<nkv;i++){std::string k;if(!str(b,o,k))return false;uint32_t t;if(!rd(b,o,t))return false;if(t==9){uint32_t et;uint64_t n;if(!rd(b,o,et)||!rd(b,o,n))return false;for(uint64_t j=0;j<n;j++){if(et==8){std::string s;if(!str(b,o,s))return false;}else if(!skipv(b,o,et))return false;}}else if(t==8){std::string s;if(!str(b,o,s))return false;}else if(t==4){uint32_t v;if(!rd(b,o,v))return false;if(k=="general.alignment")align=v;}else if(!skipv(b,o,t))return false;}
 std::vector<Tensor>ts((size_t)nt);std::vector<uint64_t>srcOff(nt);for(uint64_t i=0;i<nt;i++){auto&t=ts[(size_t)i];if(!str(b,o,t.name)){err="bad tensor name";return false;}uint32_t nd;if(!rd(b,o,nd)||nd>8){err="bad tensor dims";return false;}t.dims.resize(nd);for(auto&d:t.dims)if(!rd(b,o,d))return false;t.elements=elems(t.dims);if(!rd(b,o,t.source_type)||!rd(b,o,srcOff[i])){err="bad tensor record";return false;}t.bytes=type_bytes(t.source_type,t.elements);if(!t.bytes){err="unsupported GGUF tensor type for RGUF: "+std::to_string(t.source_type);return false;}t.runtime_type=(t.source_type==0||t.source_type==1)?1:0;}
 uint64_t dataStart=(o+(align-1))&~(align-1);if(dataStart>b.size()){err="bad GGUF alignment";return false;}
 Header h{};h.flags=encrypt?1u:0u;h.manifest_off=sizeof(Header);h.manifest_size=sizeof(uint64_t)+sizeof(uint64_t);h.blocks_off=0;h.block_count=0;std::vector<Block> blocks;std::vector<std::vector<uint8_t>> payloads;
 // One block per tensor. Float tensors are converted to custom Q4; existing GGUF quantized tensors are preserved byte-for-byte for direct dequant-kernel integration.
 for(size_t ti=0;ti<ts.size();ti++){auto&t=ts[ti];uint64_t src=dataStart+srcOff[ti];if(src> b.size()||t.bytes>b.size()-src){err="tensor payload outside GGUF";return false;}std::vector<uint8_t> plain;Quant q=Quant::Raw;if(t.source_type==0){std::vector<float>x(t.elements);std::memcpy(x.data(),b.data()+src,(size_t)t.bytes);if(!quantize_q4(x.data(),x.size(),plain)){err="Q4 quantization failed";return false;}q=Quant::Q4;t.runtime_type=1;}else if(t.source_type==1){std::vector<float>x(t.elements);for(size_t j=0;j<t.elements;j++){uint16_t h;std::memcpy(&h,b.data()+src+j*2,2);x[j]=f16to32(h);}if(!quantize_q4(x.data(),x.size(),plain)){err="Q4 quantization failed";return false;}q=Quant::Q4;t.runtime_type=1;}else plain.assign(b.begin()+src,b.begin()+src+t.bytes);
 Block bl{};bl.tensor=ti;bl.index=0;bl.plain=plain.size();bl.generation=1;bl.quant=q;if(encrypt){random_bytes(bl.nonce,12);std::vector<uint8_t>enc;if(!aes256gcm_encrypt(key,bl.nonce,plain.data(),plain.size(),enc,bl.tag,err))return false;plain.swap(enc);}bl.stored=plain.size();bl.crc=crc32(plain.data(),plain.size());blocks.push_back(bl);payloads.push_back(std::move(plain));t.first_block=blocks.size()-1;t.block_count=1;}
 // Serialize a compact manifest: tensor count, tensor records, block table.
 std::vector<uint8_t>manifest;uint64_t tc=ts.size();append(manifest,&tc,8);for(auto&t:ts){uint64_t n=t.name.size();append(manifest,&n,8);append(manifest,t.name.data(),n);uint32_t nd=t.dims.size();append(manifest,&nd,4);for(auto d:t.dims)append(manifest,&d,8);append(manifest,&t.source_type,4);append(manifest,&t.runtime_type,4);append(manifest,&t.elements,8);append(manifest,&t.first_block,8);append(manifest,&t.block_count,8);}uint64_t bc=blocks.size();append(manifest,&bc,8);uint64_t manOff=sizeof(Header),blocksOff=manOff+manifest.size();h.manifest_off=manOff;h.manifest_size=manifest.size();h.blocks_off=blocksOff;h.block_count=blocks.size();uint64_t pos=blocksOff+blocks.size()*sizeof(Block);for(size_t i=0;i<blocks.size();i++){blocks[i].file_off=pos;pos+=blocks[i].stored;}
 std::ofstream f(out,std::ios::binary|std::ios::trunc);if(!f){err="cannot create RGUF";return false;}f.write((char*)&h,sizeof(h));f.write((char*)manifest.data(),manifest.size());for(auto&bl:blocks)f.write((char*)&bl,sizeof(bl));for(auto&p:payloads)f.write((char*)p.data(),p.size());if(!f){err="RGUF write failed";return false;}return true;
}
bool Writer::make_patch(const std::string&,const std::string&patch,uint64_t tensor,uint64_t block,const uint8_t*data,size_t n,std::string&err){std::ofstream f(patch,std::ios::binary|std::ios::trunc);if(!f){err="cannot create patch";return false;}uint32_t magic=PATCH_MAGIC,ver=1,gen=2;uint64_t sz=n;f.write((char*)&magic,4);f.write((char*)&ver,4);f.write((char*)&tensor,8);f.write((char*)&block,8);f.write((char*)&gen,4);f.write((char*)&sz,8);f.write((char*)data,n);return !!f;}
}
