; Generated by RawrXD Minimal C Compiler
; x64 Assembly (MASM syntax)

bits 64
default rel

section .text
global main
extern ExitProcess

main:
    push rbp
    mov rbp, rsp
    sub rsp, 32
    mov rax, 42
    mov rcx, rax
    call ExitProcess
    mov rsp, rbp
    pop rbp
    ret

