;=============================================================================
; test_program.asm - Generated by RawrXD Language Backend Generator
; Target: x64 Windows
; Calling Convention: Microsoft x64
;=============================================================================

option casemap:none

; Include x64 instruction set
; include x64_instructions.inc

.data

.text

.data
message db 'Hello from RawrXD Native Toolchain!', 0Dh, 0Ah, 0
counter dq 0
result dq 0

.text

_start PROC
    sub     rsp, 40
    lea     rcx, message
    call    print_string
    mov     rax, 42
    add     rsp, 40
    ret
_start ENDP

print_string PROC
    sub     rsp, 40
    mov     rdx, rcx
    mov     r8, 50
    lea     r9, [rsp + 32]
    mov     qword ptr [rsp + 32], 0
    mov     rcx, -11
    call    GetStdHandle
    mov     rcx, rax
    mov     rdx, rdx
    mov     r8, r8
    lea     r9, [rsp + 32]
    mov     qword ptr [rsp + 32], 0
    call    WriteFile
    add     rsp, 40
    ret
print_string ENDP


;=============================================================================
; Main Entry Point
;=============================================================================
_start:
    sub     rsp, 40
    jmp     main

;=============================================================================
; Import Table
;=============================================================================
extrn ExitProcess : proc
extrn GetStdHandle : proc
extrn WriteFile : proc
extrn ReadFile : proc
extrn GetLastError : proc

;=============================================================================
; End of generated code
;=============================================================================
end
