;=============================================================================
; generated_from_ir.asm - Generated by RawrXD Language Backend Generator
; Target: x64 Windows
; Calling Convention: Microsoft x64
;=============================================================================

option casemap:none

; Include x64 instruction set
; include x64_instructions.inc

.data

.code

.data
return_value dq 0

.code

    pop     r15
    pop     r14
    pop     r13
    pop     r12
    pop     rdi
    pop     rsi
    pop     rbx
    mov     rsp, rbp
    pop     rbp
    ret

;=============================================================================
; Main Entry Point
;=============================================================================
main PROC
    sub     rsp, 40
    call    _start
    mov     rcx, rax
    call    ExitProcess
main ENDP

;=============================================================================
; Import Table
;=============================================================================
extrn ExitProcess : proc
extrn GetStdHandle : proc
extrn WriteFile : proc
extrn ReadFile : proc
extrn GetLastError : proc

;=============================================================================
; End of generated code
;=============================================================================
end
