// ============================================================================
// Layer-wise Numerical Comparison vs Reference
// Compares Deep2Engine layer outputs against llama.cpp
// ============================================================================

#include <cstdio>
#include <cstring>
#include <cmath>
#include <vector>
#include <string>

// Minimal GGUF loader for test
struct TestTensor {
    std::string name;
    std::vector<float> data;
    std::vector<size_t> shape;
};

// Comparison metrics
struct LayerComparison {
    const char* layerName;
    float maxAbsDiff;
    float meanAbsDiff;
    float maxRelDiff;      // Relative to reference magnitude
    float cosineSim;       // Cosine similarity
    bool passed;
    float tolerance;
};

// Load test vectors from file (generated by reference implementation)
// Format: binary file with header + tensor data
bool loadTestVectors(const char* path, 
                     std::vector<float>& inputTokens,
                     std::vector<TestTensor>& expectedOutputs) {
    FILE* f = fopen(path, "rb");
    if (!f) {
        printf("ERROR: Cannot open test vectors: %s\n", path);
        return false;
    }
    
    // Read header
    uint32_t numTensors;
    fread(&numTensors, sizeof(uint32_t), 1, f);
    
    // Read input tokens
    uint32_t numTokens;
    fread(&numTokens, sizeof(uint32_t), 1, f);
    inputTokens.resize(numTokens);
    fread(inputTokens.data(), sizeof(float), numTokens, f);
    
    // Read expected outputs
    for (uint32_t i = 0; i < numTensors; ++i) {
        TestTensor tensor;
        
        // Read name length and name
        uint32_t nameLen;
        fread(&nameLen, sizeof(uint32_t), 1, f);
        tensor.name.resize(nameLen);
        fread(&tensor.name[0], 1, nameLen, f);
        
        // Read shape
        uint32_t numDims;
        fread(&numDims, sizeof(uint32_t), 1, f);
        tensor.shape.resize(numDims);
        fread(tensor.shape.data(), sizeof(size_t), numDims, f);
        
        // Read data
        size_t numElements = 1;
        for (auto dim : tensor.shape) numElements *= dim;
        tensor.data.resize(numElements);
        fread(tensor.data.data(), sizeof(float), numElements, f);
        
        expectedOutputs.push_back(std::move(tensor));
    }
    
    fclose(f);
    return true;
}

// Compare two tensors
LayerComparison compareTensors(const char* name,
                                const float* ref, const float* opt, size_t n,
                                float tolerance = 1e-4f) {
    LayerComparison result = {};
    result.layerName = name;
    result.tolerance = tolerance;
    
    if (n == 0) {
        result.passed = true;
        return result;
    }
    
    double dot = 0.0, normRef = 0.0, normOpt = 0.0;
    result.maxAbsDiff = 0.0f;
    double sumAbsDiff = 0.0;
    
    for (size_t i = 0; i < n; ++i) {
        float diff = std::abs(ref[i] - opt[i]);
        result.maxAbsDiff = std::max(result.maxAbsDiff, diff);
        sumAbsDiff += diff;
        
        float relDiff = (std::abs(ref[i]) > 1e-8f) ? diff / std::abs(ref[i]) : diff;
        result.maxRelDiff = std::max(result.maxRelDiff, relDiff);
        
        dot += ref[i] * opt[i];
        normRef += ref[i] * ref[i];
        normOpt += opt[i] * opt[i];
    }
    
    result.meanAbsDiff = static_cast<float>(sumAbsDiff / n);
    result.cosineSim = static_cast<float>(dot / (std::sqrt(normRef) * std::sqrt(normOpt) + 1e-8));
    result.passed = (result.maxAbsDiff < tolerance) && (result.cosineSim > 0.999f);
    
    return result;
}

// ============================================================================
// Test: Embedding Layer
// ============================================================================
LayerComparison testEmbedding(Deep2Engine& engine,
                             const std::vector<float>& expected) {
    const int tokenId = 100;  // Test token
    size_t hiddenDim = engine.getConfig().hiddenDim;
    std::vector<float> output(hiddenDim);
    
    engine.embedToken(tokenId, output.data());
    
    return compareTensors("Embedding", expected.data(), output.data(), hiddenDim);
}

// ============================================================================
// Test: Single Layer Forward
// ============================================================================
LayerComparison testLayerForward(Deep2Engine& engine, size_t layerIdx,
                                  const float* input,
                                  const std::vector<float>& expected) {
    size_t hiddenDim = engine.getConfig().hiddenDim;
    std::vector<float> output(hiddenDim);
    
    // Use internal buffers
    engine.forwardLayer(layerIdx, input, output.data(), 1);
    
    return compareTensors(("Layer_" + std::to_string(layerIdx)).c_str(),
                          expected.data(), output.data(), hiddenDim);
}

// ============================================================================
// Test: Attention Output
// ============================================================================
LayerComparison testAttention(Deep2Engine& engine, size_t layerIdx,
                               const float* input,
                               const std::vector<float>& expected) {
    size_t hiddenDim = engine.getConfig().hiddenDim;
    std::vector<float> output(hiddenDim);
    
    engine.computeAttention(layerIdx, input, output.data(), 1);
    
    return compareTensors(("Attention_" + std::to_string(layerIdx)).c_str(),
                          expected.data(), output.data(), hiddenDim,
                          5e-4f);  // Attention has higher variance
}

// ============================================================================
// Test: FFN Output
// ============================================================================
LayerComparison testFFN(Deep2Engine& engine, size_t layerIdx,
                       const float* input,
                       const std::vector<float>& expected) {
    size_t hiddenDim = engine.getConfig().hiddenDim;
    std::vector<float> output(hiddenDim);
    
    engine.computeFFN(layerIdx, input, output.data());
    
    return compareTensors(("FFN_" + std::to_string(layerIdx)).c_str(),
                          expected.data(), output.data(), hiddenDim);
}

// ============================================================================
// Test: Logits
// ============================================================================
LayerComparison testLogits(Deep2Engine& engine,
                           const float* hiddenState,
                           const std::vector<float>& expected) {
    size_t vocabSize = engine.getConfig().vocabSize;
    std::vector<float> logits(vocabSize);
    
    engine.computeLogits(hiddenState, logits.data());
    
    // Logits can have high magnitude, use relative tolerance
    return compareTensors("Logits", expected.data(), logits.data(), vocabSize, 1e-3f);
}

// ============================================================================
// Main Comparison Runner
// ============================================================================
int main(int argc, char** argv) {
    printf("=================================================================\n");
    printf("Deep2Engine Layer-wise Numerical Validation\n");
    printf("=================================================================\n\n");
    
    if (argc < 3) {
        printf("Usage: %s <gguf_path> <test_vectors.bin>\n", argv[0]);
        printf("\n");
        printf("Test vectors format (binary):\n");
        printf("  [uint32] num_tensors\n");
        printf("  [uint32] num_tokens\n");
        printf("  [float[num_tokens]] input_tokens\n");
        printf("  For each tensor:\n");
        printf("    [uint32] name_len, [char[name_len]] name\n");
        printf("    [uint32] num_dims, [size_t[num_dims]] shape\n");
        printf("    [float[...]] data\n");
        return 1;
    }
    
    const char* ggufPath = argv[1];
    const char* testVectorsPath = argv[2];
    
    // Load test vectors
    std::vector<float> inputTokens;
    std::vector<TestTensor> expectedOutputs;
    
    if (!loadTestVectors(testVectorsPath, inputTokens, expectedOutputs)) {
        return 1;
    }
    
    printf("Loaded %zu test tensors\n", expectedOutputs.size());
    printf("Input: %zu tokens\n\n", inputTokens.size());
    
    // Initialize Deep2Engine
    Deep2Engine engine;
    EngineConfig config;
    // ... configure from GGUF ...
    
    if (!engine.initialize(config)) {
        printf("ERROR: Failed to initialize Deep2Engine\n");
        return 1;
    }
    
    if (!engine.loadModel(ggufPath)) {
        printf("ERROR: Failed to load model: %s\n", ggufPath);
        return 1;
    }
    
    // Run layer-wise comparisons
    std::vector<LayerComparison> results;
    
    // Test embedding
    // results.push_back(testEmbedding(engine, findTensor(expectedOutputs, "embedding")));
    
    // Test each layer
    for (size_t layer = 0; layer < config.numLayers; ++layer) {
        // results.push_back(testLayerForward(engine, layer, ...));
        // results.push_back(testAttention(engine, layer, ...));
        // results.push_back(testFFN(engine, layer, ...));
    }
    
    // Test final logits
    // results.push_back(testLogits(engine, ...));
    
    // Print results
    printf("%-20s %8s %12s %12s %12s %12s\n",
           "Layer", "Status", "Max Abs", "Mean Abs", "Max Rel", "Cosine");
    printf("-----------------------------------------------------------------\n");
    
    int passed = 0, failed = 0;
    for (const auto& r : results) {
        printf("%-20s %8s %12.6f %12.6f %12.6f %12.6f\n",
               r.layerName,
               r.passed ? "PASS" : "FAIL",
               r.maxAbsDiff,
               r.meanAbsDiff,
               r.maxRelDiff,
               r.cosineSim);
        
        if (r.passed) passed++; else failed++;
    }
    
    printf("-----------------------------------------------------------------\n");
    printf("Results: %d passed, %d failed\n", passed, failed);
    printf("=================================================================\n");
    
    return failed > 0 ? 1 : 0;
}

// Helper to find tensor by name
const std::vector<float>* findTensor(const std::vector<TestTensor>& tensors, 
                                      const char* name) {
    for (const auto& t : tensors) {
        if (t.name == name) return &t.data;
    }
    return nullptr;
}
