; masm_source_stub_gen.asm - Pure MASM x64 C/C++ header → MASM source stub generator
; Scans a directory for .h/.hpp files and emits a .asm with PUBLIC/PROC stubs
; Usage: masm_source_stub_gen.exe <input_dir> <output_file>

option casemap:none

.data
    CRLF            db 13,10,0
    USAGE_TEXT      db "Usage: masm_source_stub_gen <input_dir> <output_file>",13,10,0
    GEN_HEADER_1    db "; Generated by masm_source_stub_gen (pure MASM)",13,10,0
    GEN_HEADER_2    db "; Function stubs extracted heuristically from headers.",13,10,13,10,0
    DBG_START       db "[dbg] masm_source_stub_gen start",13,10,0
    DBG_OPEN_OK     db "[dbg] open_out: ok",13,10,0
    DBG_OPEN_FAIL   db "[dbg] open_out: FAIL",13,10,0
    DBG_ENUM_H      db "[dbg] enumerate: *.h",13,10,0
    DBG_ENUM_HPP    db "[dbg] enumerate: *.hpp",13,10,0
    DBG_NO_MATCH    db "[dbg] no matches",13,10,0
    DBG_PROC_FILE   db "[dbg] process file",13,10,0
    DBG_FINISH      db "[dbg] finish",13,10,0
    LOG_PATH        db ".\\masm_source_stub_gen.log",0

    patternSuffixH      db "\\*.h",0
    patternSuffixHPP    db "\\*.hpp",0
    backslash       db "\\",0

    inDir           db 512 dup(0)
    outPath         db 512 dup(0)
    searchPattern   db 1024 dup(0)
    filePath        db 1024 dup(0)

    findData        db 320 dup(0)

    readBuf         db 65536 dup(0)
    lineBuf         db 4096 dup(0)
    tokenBuf        db 512 dup(0)

    hFind           dq 0
    hIn             dq 0
    hOut            dq 0
    bytesIO         dq 0
    hLog            dq 0

.code

extern  GetCommandLineA:proc
extern  WriteFile:proc
extern  CreateFileA:proc
extern  CloseHandle:proc
extern  ReadFile:proc
extern  FindFirstFileA:proc
extern  FindNextFileA:proc
extern  FindClose:proc
extern  ExitProcess:proc
extern  GetStdHandle:proc

STD_OUTPUT_HANDLE equ -11
GENERIC_READ   equ 80000000h
GENERIC_WRITE  equ 40000000h
FILE_SHARE_READ equ 1
OPEN_EXISTING  equ 3
CREATE_ALWAYS  equ 2
FILE_ATTRIBUTE_NORMAL equ 80h
INVALID_HANDLE_VALUE equ -1

strlenA proc uses rdi rax rcx, psz:QWORD
    mov rdi, psz
    xor rax, rax
@@:
    cmp byte ptr [rdi+rax], 0
    je @f
    inc rax
    jmp @B
@@:
    ret
strlenA endp

strcpyA proc uses rsi rdi rcx, dst:QWORD, src:QWORD
    mov rdi, dst
    mov rsi, src
@@:
    mov al, [rsi]
    mov [rdi], al
    inc rsi
    inc rdi
    test al, al
    jnz @B
    ret
strcpyA endp

strcatA proc uses rsi rdi rax, dst:QWORD, src:QWORD
    mov rdi, dst
@seek:
    mov al, [rdi]
    test al, al
    jz @copy
    inc rdi
    jmp @seek
@copy:
    mov rsi, src
@@:
    mov al, [rsi]
    mov [rdi], al
    inc rsi
    inc rdi
    test al, al
    jnz @B
    ret
strcatA endp

; write null-terminated string to handle in rcx
writeZ proc uses rdx r8 r9 rax, h:QWORD, psz:QWORD
    mov rcx, psz
    call strlenA
    mov r8d, eax
    mov rcx, h
    mov rdx, psz
    lea r9, bytesIO
    sub rsp, 32
    call WriteFile
    add rsp, 32
    ret
writeZ endp

; open log file for appends (create/truncate)
log_open proc
    sub rsp, 32
    lea rcx, LOG_PATH
    mov edx, GENERIC_WRITE
    xor r8d, r8d
    xor r9d, r9d
    mov dword ptr [rsp+20h], CREATE_ALWAYS
    mov dword ptr [rsp+28h], FILE_ATTRIBUTE_NORMAL
    mov qword ptr [rsp+30h], 0
    mov qword ptr [rsp+38h], 0
    call CreateFileA
    add rsp, 32
    cmp rax, INVALID_HANDLE_VALUE
    je @ret
    mov hLog, rax
@ret:
    ret
log_open endp

; write Z string to log if open
log_write proc uses rcx rdx
    mov rax, hLog
    test rax, rax
    jz @ret
    mov rcx, rax
    call writeZ
@ret:
    ret
log_write endp

; Simple inline trim for lineBuf: replace CR/LF and tabs with spaces, null-terminate
trim_line proc uses rsi, psz:QWORD
    mov rsi, psz
@@:
    mov al, [rsi]
    test al, al
    jz @f
    cmp al, 13
    je @sp
    cmp al, 10
    je @sp
    cmp al, 9
    je @sp
    jmp @cont
@sp:
    mov byte ptr [rsi], ' '
@cont:
    inc rsi
    jmp @B
@@:
    ret
trim_line endp

; locate character in buffer; returns offset or -1
find_char proc uses rsi rax, psz:QWORD, chv:BYTE
    mov rsi, psz
    mov al, chv
@@:
    mov dl, [rsi]
    test dl, dl
    jz @nf
    cmp dl, al
    je @fd
    inc rsi
    jmp @B
@nf:
    mov rax, -1
    ret
@fd:
    mov rax, rsi
    sub rax, psz
    ret
find_char endp

; check if substring ") ;" exists in the line (very rough)
ends_with_paren_semicolon proc uses rsi rax rbx, psz:QWORD
    mov rsi, psz
@seek0:
    mov bl, [rsi]
    test bl, bl
    jz @nf
    inc rsi
    jmp @seek0
@nf:
    ; rsi at end (null). Check previous two bytes for ")" and ";" with optional spaces
    mov rax, rsi
    sub rax, 1
@back_ws:
    cmp rax, psz
    jbe @no
    cmp byte ptr [rax], ' '
    jne @chk
    dec rax
    jmp @back_ws
@chk:
    cmp byte ptr [rax], ';'
    jne @no
    dec rax
@back_ws2:
    cmp rax, psz
    jbe @no
    cmp byte ptr [rax], ' '
    jne @chk2
    dec rax
    jmp @back_ws2
@chk2:
    cmp byte ptr [rax], ')'
    jne @no
    mov rax, 1
    ret
@no:
    xor rax, rax
    ret
ends_with_paren_semicolon endp

; extract function name before '(' into tokenBuf; returns 1 if ok
extract_name proc uses rsi rdi rax rbx, psz:QWORD
    ; find '('
    sub rsp, 32
    mov rcx, psz
    mov dl, '('
    call find_char
    add rsp, 32
    cmp rax, -1
    je @fail
    ; rax = offset of '('
    lea rsi, [psz+rax-1]
    ; scan backward skipping spaces and '*'
@skip:
    cmp rsi, psz
    jbe @fail
    mov bl, [rsi]
    cmp bl, ' '
    je @dec
    cmp bl, '*'
    je @dec
    jmp @start
@dec:
    dec rsi
    jmp @skip
@start:
    ; rsi at last char of name; find start (non-alnum/_)
    mov rdi, rsi
@bw:
    cmp rdi, psz
    jbe @bw_done
    mov bl, [rdi]
    ; allowed [A-Za-z0-9_]
    cmp bl, '0'
    jb @bw_done
    cmp bl, '9'
    jbe @ok
    cmp bl, 'A'
    jb @bw_done
    cmp bl, 'Z'
    jbe @ok
    cmp bl, '_'
    je @ok
    cmp bl, 'a'
    jb @bw_done
    cmp bl, 'z'
    jbe @ok
    jmp @bw_done
@ok:
    dec rdi
    jmp @bw
@bw_done:
    inc rdi ; now at first char of name
    ; copy into tokenBuf
    mov rax, 0
    lea rbx, tokenBuf
@cpy:
    mov bl, [rdi+rax]
    ; stop on non-identifier char
    cmp bl, '0'
    jb @cpy_done
    cmp bl, '9'
    jbe @cp
    cmp bl, 'A'
    jb @cpy_done
    cmp bl, 'Z'
    jbe @cp
    cmp bl, '_'
    je @cp
    cmp bl, 'a'
    jb @cpy_done
    cmp bl, 'z'
    jbe @cp
    jmp @cpy_done
@cp:
    mov [rbx+rax], bl
    inc rax
    cmp rax, 510
    jb @cpy
@cpy_done:
    mov byte ptr [rbx+rax], 0
    ; reject destructor (~name) or operators
    cmp byte ptr [rbx], '~'
    je @fail
    ; simple check for operator prefix
    cmp byte ptr [rbx+0], 'o'
    jne @ok2
    cmp byte ptr [rbx+1], 'p'
    jne @ok2
    mov rax, 0
    ret
@ok2:
    mov rax, 1
    ret
@fail:
    xor rax, rax
    ret
extract_name endp

; open output file for writing and emit header
open_out proc
    sub rsp, 32
    lea rcx, outPath
    mov edx, GENERIC_WRITE
    xor r8d, r8d
    xor r9d, r9d
    mov dword ptr [rsp+20h], CREATE_ALWAYS
    mov dword ptr [rsp+28h], FILE_ATTRIBUTE_NORMAL
    mov qword ptr [rsp+30h], 0
    mov qword ptr [rsp+38h], 0
    call CreateFileA
    add rsp, 32
    cmp rax, INVALID_HANDLE_VALUE
    jne @ok
    ; debug fail
    lea rdx, DBG_OPEN_FAIL
    call log_write
    jmp @ret
@ok:
    mov hOut, rax
    ; debug ok
    lea rdx, DBG_OPEN_OK
    call log_write
    mov rcx, hOut
    lea rdx, GEN_HEADER_1
    call writeZ
    mov rcx, hOut
    lea rdx, GEN_HEADER_2
    call writeZ
    ; start .code
    lea rdi, lineBuf
    mov byte ptr [rdi+0], '.'
    mov byte ptr [rdi+1], 'c'
    mov byte ptr [rdi+2], 'o'
    mov byte ptr [rdi+3], 'd'
    mov byte ptr [rdi+4], 'e'
    mov byte ptr [rdi+5], 13
    mov byte ptr [rdi+6], 10
    mov byte ptr [rdi+7], 0
    mov rcx, hOut
    lea rdx, lineBuf
    call writeZ
@ret:
    ret
open_out endp

; write one stub from tokenBuf
write_stub proc uses rax rbx rcx rdx
    mov rcx, hOut
    ; PUBLIC line
    mov byte ptr [lineBuf+0], 'P'
    mov byte ptr [lineBuf+1], 'U'
    mov byte ptr [lineBuf+2], 'B'
    mov byte ptr [lineBuf+3], 'L'
    mov byte ptr [lineBuf+4], 'I'
    mov byte ptr [lineBuf+5], 'C'
    mov byte ptr [lineBuf+6], ' '
    ; copy name
    xor rax, rax
    lea rsi, tokenBuf
    lea rdi, lineBuf
@c1:
    mov bl, [rsi+rax]
    mov byte ptr [rdi+rax+7], bl
    test bl, bl
    jz @p0
    inc rax
    jmp @c1
@p0:
    mov byte ptr [rdi+7+rax], 13
    mov byte ptr [rdi+8+rax], 10
    mov byte ptr [rdi+9+rax], 0
    lea rdx, lineBuf
    call writeZ

    ; PROC header
    mov rcx, hOut
    xor rax, rax
@c2:
    mov bl, [rsi+rax]
    mov byte ptr [rdi+rax], bl
    test bl, bl
    jz @p1
    inc rax
    jmp @c2
@p1:
    mov byte ptr [rdi+rax], ' '
    mov byte ptr [rdi+rax+1], 'P'
    mov byte ptr [rdi+rax+2], 'R'
    mov byte ptr [rdi+rax+3], 'O'
    mov byte ptr [rdi+rax+4], 'C'
    mov byte ptr [rdi+rax+5], 13
    mov byte ptr [rdi+rax+6], 10
    mov byte ptr [rdi+rax+7], 0
    lea rdx, lineBuf
    call writeZ

    ; body + ret
    mov rcx, hOut
    mov byte ptr [rdi+0], ' '
    mov byte ptr [rdi+1], ' '
    mov byte ptr [rdi+2], 'r'
    mov byte ptr [rdi+3], 'e'
    mov byte ptr [rdi+4], 't'
    mov byte ptr [rdi+5], 13
    mov byte ptr [rdi+6], 10
    mov byte ptr [rdi+7], 0
    lea rdx, lineBuf
    call writeZ

    ; ENDP
    mov rcx, hOut
    xor rax, rax
@c3:
    mov bl, [rsi+rax]
    mov byte ptr [rdi+rax], bl
    test bl, bl
    jz @p2
    inc rax
    jmp @c3
@p2:
    mov byte ptr [rdi+rax], ' '
    mov byte ptr [rdi+rax+1], 'E'
    mov byte ptr [rdi+rax+2], 'N'
    mov byte ptr [rdi+rax+3], 'D'
    mov byte ptr [rdi+rax+4], 'P'
    mov byte ptr [rdi+rax+5], 13
    mov byte ptr [rdi+rax+6], 10
    mov byte ptr [rdi+rax+7], 13
    mov byte ptr [rdi+rax+8], 10
    mov byte ptr [rdi+rax+9], 0
    lea rdx, lineBuf
    call writeZ

    ret
write_stub endp

; process a header file line by line, emitting stubs
process_header_file proc uses rax rbx rcx rdx rsi rdi, psz:QWORD
    ; open
    sub rsp, 32
    mov rcx, psz
    mov edx, GENERIC_READ
    mov r8d, FILE_SHARE_READ
    xor r9d, r9d
    mov dword ptr [rsp+20h], OPEN_EXISTING
    mov dword ptr [rsp+28h], FILE_ATTRIBUTE_NORMAL
    mov qword ptr [rsp+30h], 0
    mov qword ptr [rsp+38h], 0
    call CreateFileA
    add rsp, 32
    cmp rax, INVALID_HANDLE_VALUE
    je @done
    mov hIn, rax

    xor rdi, rdi ; buf index
    xor rsi, rsi ; line len

@read:
    sub rsp, 32
    mov rcx, hIn
    lea rdx, readBuf
    mov r8d, 65536
    lea r9, bytesIO
    call ReadFile
    add rsp, 32
    test eax, eax
    jz @close
    mov rbx, bytesIO
    mov rbx, [rbx]
    cmp rbx, 0
    je @close
    xor rdi, rdi
    lea r10, readBuf
    lea r11, lineBuf
@loop:
    cmp rdi, rbx
    jae @read
    mov al, [r10+rdi]
    inc rdi
    cmp al, 13
    je @nl
    cmp al, 10
    je @nl
    mov [r11+rsi], al
    inc rsi
    cmp rsi, 4094
    jb @loop
@nl:
    mov byte ptr [r11+rsi], 0
    cmp rsi, 0
    je @reset
    ; strip '//' comments: replace first '/' then next '/' then null-terminate
    ; simple: find first '/', if next is '/', set to 0
    lea rcx, lineBuf
    call trim_line
    ; check end ") ;"
    lea rcx, lineBuf
    call ends_with_paren_semicolon
    test rax, rax
    jz @reset
    ; extract name
    lea rcx, lineBuf
    call extract_name
    test rax, rax
    jz @reset
    ; write stub
    call write_stub
@reset:
    xor rsi, rsi
    jmp @loop

@close:
    mov rcx, hIn
    call CloseHandle
@done:
    ret
process_header_file endp

; Build file path = inDir + "\\" + findData.cFileName
build_filepath proc uses rax rbx rcx rdx
    lea rcx, filePath
    lea rdx, inDir
    call strcpyA
    ; ensure backslash
    lea rcx, filePath
    call strlenA
    lea rdx, filePath
    cmp rax, 0
    je @append
    dec rax
    mov bl, [rdx+rax]
    inc rax
    cmp bl, 92
    je @append
    lea rcx, filePath
    lea rdx, backslash
    call strcatA
@append:
    lea rbx, findData
    add rbx, 44h
    lea rcx, filePath
    mov rdx, rbx
    call strcatA
    ret
build_filepath endp

; Minimal command line parse: expects two args after program name
parse_args proc uses rax rbx rcx rdx rsi rdi
    sub rsp, 32
    call GetCommandLineA
    add rsp, 32
    mov rsi, rax
    ; Skip program path (handle quotes)
    mov al, [rsi]
    cmp al, '"'
    jne @skp1
    inc rsi
@q1:
    mov al, [rsi]
    test al, al
    jz @usage
    cmp al, '"'
    je @q1e
    inc rsi
    jmp @q1
@q1e:
    inc rsi
    jmp @sp1
@skp1:
@s1:
    mov al, [rsi]
    test al, al
    jz @usage
    cmp al, ' '
    je @sp1
    inc rsi
    jmp @s1
@sp1:
@sk1:
    mov al, [rsi]
    test al, al
    jz @usage
    cmp al, ' '
    jne @arg1
    inc rsi
    jmp @sk1
@arg1:
    lea rdi, inDir
@a1:
    mov al, [rsi]
    test al, al
    jz @a1e
    cmp al, ' '
    je @a1e
    mov [rdi], al
    inc rdi
    inc rsi
    jmp @a1
@a1e:
    mov byte ptr [rdi], 0
@sk2:
    mov al, [rsi]
    test al, al
    jz @usage
    cmp al, ' '
    jne @arg2
    inc rsi
    jmp @sk2
@arg2:
    lea rdi, outPath
@a2:
    mov al, [rsi]
    test al, al
    jz @a2e
    cmp al, ' '
    je @a2e
    mov [rdi], al
    inc rdi
    inc rsi
    jmp @a2
@a2e:
    mov byte ptr [rdi], 0
    ret
@usage:
    ; Leave args empty; main will supply defaults
    mov byte ptr [inDir], 0
    mov byte ptr [outPath], 0
    ret
parse_args endp

; enumerate and process .h and .hpp files
run_enum proc uses rax rbx rcx rdx
    ; open output
    call open_out

    ; pattern *.h
    lea rdx, DBG_ENUM_H
    call log_write
    lea rcx, searchPattern
    lea rdx, inDir
    call strcpyA
    lea rcx, searchPattern
    lea rdx, patternSuffixH
    call strcatA
    sub rsp, 32
    lea rcx, searchPattern
    lea rdx, findData
    call FindFirstFileA
    add rsp, 32
    cmp rax, INVALID_HANDLE_VALUE
    jne @have_h
    lea rdx, DBG_NO_MATCH
    call log_write
    jmp @hpp
@have_h:
    mov hFind, rax
@next_h:
    ; skip directories
    mov eax, dword ptr [findData]
    test eax, 10h
    jnz @cont_h
    call build_filepath
    lea rdx, DBG_PROC_FILE
    call log_write
    lea rcx, filePath
    call process_header_file
@cont_h:
    sub rsp, 32
    mov rcx, hFind
    lea rdx, findData
    call FindNextFileA
    add rsp, 32
    test eax, eax
    jnz @next_h
    mov rcx, hFind
    call FindClose

@hpp:
    ; pattern *.hpp
    lea rdx, DBG_ENUM_HPP
    call log_write
    lea rcx, searchPattern
    lea rdx, inDir
    call strcpyA
    lea rcx, searchPattern
    lea rdx, patternSuffixHPP
    call strcatA
    sub rsp, 32
    lea rcx, searchPattern
    lea rdx, findData
    call FindFirstFileA
    add rsp, 32
    cmp rax, INVALID_HANDLE_VALUE
    jne @have_hpp
    lea rdx, DBG_NO_MATCH
    call log_write
    jmp @finish
@have_hpp:
    mov hFind, rax
@next_hpp:
    mov eax, dword ptr [findData]
    test eax, 10h
    jnz @cont_hpp
    call build_filepath
    lea rdx, DBG_PROC_FILE
    call log_write
    lea rcx, filePath
    call process_header_file
@cont_hpp:
    sub rsp, 32
    mov rcx, hFind
    lea rdx, findData
    call FindNextFileA
    add rsp, 32
    test eax, eax
    jnz @next_hpp
    mov rcx, hFind
    call FindClose

@finish:
    ; write end
    mov rcx, hOut
    lea rdi, lineBuf
    mov byte ptr [rdi+0], 'e'
    mov byte ptr [rdi+1], 'n'
    mov byte ptr [rdi+2], 'd'
    mov byte ptr [rdi+3], 13
    mov byte ptr [rdi+4], 10
    mov byte ptr [rdi+5], 0
    lea rdx, lineBuf
    call writeZ
    mov rcx, hOut
    call CloseHandle
    lea rdx, DBG_FINISH
    call log_write
    ret
run_enum endp

main proc
    ; debug start
    call log_open
    lea rdx, DBG_START
    call log_write
    call parse_args
    ; if args missing, set sensible defaults: .\\include and .\\generated_stubs.asm
    mov al, [inDir]
    test al, al
    jnz @have_in
    lea rcx, inDir
    mov byte ptr [rcx+0], '.'
    mov byte ptr [rcx+1], 92
    mov byte ptr [rcx+2], 'i'
    mov byte ptr [rcx+3], 'n'
    mov byte ptr [rcx+4], 'c'
    mov byte ptr [rcx+5], 'l'
    mov byte ptr [rcx+6], 'u'
    mov byte ptr [rcx+7], 'd'
    mov byte ptr [rcx+8], 'e'
    mov byte ptr [rcx+9], 0
@have_in:
    mov al, [outPath]
    test al, al
    jnz @have_out
    lea rcx, outPath
    mov byte ptr [rcx+0], '.'
    mov byte ptr [rcx+1], 92
    mov byte ptr [rcx+2], 'g'
    mov byte ptr [rcx+3], 'e'
    mov byte ptr [rcx+4], 'n'
    mov byte ptr [rcx+5], 'e'
    mov byte ptr [rcx+6], 'r'
    mov byte ptr [rcx+7], 'a'
    mov byte ptr [rcx+8], 't'
    mov byte ptr [rcx+9], 'e'
    mov byte ptr [rcx+10], 'd'
    mov byte ptr [rcx+11], '_'
    mov byte ptr [rcx+12], 's'
    mov byte ptr [rcx+13], 't'
    mov byte ptr [rcx+14], 'u'
    mov byte ptr [rcx+15], 'b'
    mov byte ptr [rcx+16], 's'
    mov byte ptr [rcx+17], '.'
    mov byte ptr [rcx+18], 'a'
    mov byte ptr [rcx+19], 's'
    mov byte ptr [rcx+20], 'm'
    mov byte ptr [rcx+21], 0
@have_out:
    call run_enum
    sub rsp, 32
    xor ecx, ecx
    call ExitProcess
main endp

END main
