/**
 * RawrXD Reference Data Loader Header
 */

#pragma once

#include <cstddef>
#include <vector>
#include <string>

namespace rawrxd {
namespace validation {

struct TensorRecord {
    int layer_idx;
    std::string name;
    std::vector<int> shape;
    std::vector<float> data;
};

class ReferenceLoader {
public:
    ReferenceLoader() = default;
    
    /**
     * Load reference data from binary file
     * @param filename Path to .bin file generated by instrumented llama.cpp
     * @return true on success
     */
    bool load(const char* filename);
    
    /**
     * Find a specific tensor by name and layer
     * @param name Tensor name (e.g., "rms_norm", "attn_q", "logits")
     * @param layer_idx Layer index (-1 for non-layer tensors like logits)
     * @return Pointer to record or nullptr if not found
     */
    const TensorRecord* findTensor(const char* name, int layer_idx = -1) const;
    
    /**
     * Get all tensors for a specific layer
     * @param layer_idx Layer index
     * @return Vector of matching tensor records
     */
    std::vector<const TensorRecord*> getLayerTensors(int layer_idx) const;
    
    /**
     * Print summary of loaded data
     */
    void printSummary() const;
    
    /**
     * Get total number of records
     */
    size_t getRecordCount() const { return records_.size(); }
    
    /**
     * Get all records
     */
    const std::vector<TensorRecord>& getRecords() const { return records_; }

private:
    std::vector<TensorRecord> records_;
};

} // namespace validation
} // namespace rawrxd
