<#
    RawrXD bounded response agent (template).

    Generated by tools/New-RawrResponseAgent.ps1 — do not edit the generated
    copy; edit this template and regenerate.

    USER -> MODEL -> optional authorized tool -> SAME MODEL -> RESPONSE -> STOP

    NOT included, by design: continuous loop, background execution, scheduler,
    self-prompting, self-assigned tasks, repository mutation, arbitrary shell.
#>

$Rawr     = '__RAWR__'
$Model    = '__MODEL__'
$RepoRoot = '__REPO__'
$Tokens   = __TOKENS__

# Bound every string that gets embedded in a later prompt. A real `git status`
# in a busy worktree is thousands of characters, and a native argv on Windows
# is capped well below that. Without this the second inference dies with
# "The filename or extension is too long".
function Limit-Text {
    param([string]$Text, [int]$Max = 1500)
    if ($null -eq $Text) { return '' }
    if ($Text.Length -le $Max) { return $Text }
    return $Text.Substring(0, $Max) + "`n...[truncated at $Max chars]"
}

# ---------------------------------------------------------------------------
# Inference authority: the already-proven `rawr run`.
# Flags precede the model, per the CLI contract: run [--tokens N] <model> <prompt>
# ---------------------------------------------------------------------------
function Invoke-RawrInference {
    param(
        [Parameter(Mandatory)][string]$Prompt,
        [int]$MaxTokens = $Tokens
    )
    if (-not (Test-Path -LiteralPath $Rawr)) { throw "rawr.exe missing: $Rawr" }
    $out = & $Rawr run --tokens $MaxTokens $Model $Prompt 2>&1
    return ($out -join "`n")
}

# ---------------------------------------------------------------------------
# The complete authorized capability set. The model can only NAME one of these.
# There is no mutating entry, so no request can change the repository.
# ---------------------------------------------------------------------------
function Invoke-AuthorizedTool {
    param(
        [Parameter(Mandatory)][string]$Name,
        [string]$Arg = ''
    )
    switch ($Name.Trim().ToLowerInvariant()) {
        'git_status' { return ((& git -C $RepoRoot status --short --branch 2>&1) -join "`n") }
        'git_log'    { return ((& git -C $RepoRoot log -5 --oneline 2>&1) -join "`n") }
        'git_diff'   { return ((& git -C $RepoRoot diff --stat -- 2>&1) -join "`n") }
        'list_files' {
            return ((& Get-ChildItem -LiteralPath $RepoRoot -Force |
                     Select-Object -First 60 Name, Length |
                     Format-Table -AutoSize | Out-String).Trim())
        }
        'read_file' {
            $rootFull = [System.IO.Path]::GetFullPath($RepoRoot)
            $target   = [System.IO.Path]::GetFullPath((Join-Path $RepoRoot $Arg))
            if (-not $target.StartsWith($rootFull, [System.StringComparison]::OrdinalIgnoreCase)) {
                throw "DENIED_PATH=$Arg"
            }
            if (-not (Test-Path -LiteralPath $target)) { throw "NO_SUCH_FILE=$Arg" }
            $text = [System.IO.File]::ReadAllText($target)
            if ($text.Length -gt 1500) { $text = $text.Substring(0, 1500) + "`n...[truncated]" }
            return $text
        }
        default { throw "DENIED_TOOL=$Name" }
    }
}

# Two prompt framings. The observation framing lists the real capabilities; the
# direct framing forbids tool use. Which one is used is decided here, in the
# host, from the request wording -- NOT from anything the model returned.
function Get-PromptFraming {
    param([Parameter(Mandatory)][string]$UserRequest)

    $needsState = $UserRequest -match '(?i)\b(branch|worktree|clean|dirty|status|commit|diff|log|files?|contents? of|read)\b'

    if ($needsState) {
        return @'
You are RawrXD.

Answer ONLY the user's current request. If it depends on the real current state
of the repository, you MUST observe first.

Reply in EXACTLY one of two forms.

Form 1 - when you already know the answer, for example if the user asks what
prefill means:

RAWR_RESPONSE
Prefill is the pass that processes the whole prompt before the first token is
emitted. Decode then generates one token at a time.

Form 2 - when you need one real fact from the machine:

RAWR_TOOL
name=git_status

Authorized read-only tools:
  git_status  - current branch and worktree status
  git_log     - the five most recent commits
  git_diff    - a diffstat of uncommitted changes
  list_files  - files at the repository root
  read_file   - read one file inside the repository (needs arg=<path>)

Rules:
  Request at most ONE tool.
  Write your own real sentences. Never copy the example wording above.
  Never output angle-bracket placeholders.
  Never state a repository fact you have not observed in this conversation.
  Never invent tool output.
  Do not output shell commands.
  Do not request writes or mutations.

USER_REQUEST:
'@ + $UserRequest
    }

    return @'
You are RawrXD.

Answer the user's request directly and only. No repository state is needed.

Reply in EXACTLY this form:

RAWR_RESPONSE
<your own real answer, written as plain sentences>

Do not request any tool. Do not invent observations. Never output
angle-bracket placeholders.

USER_REQUEST:
'@ + $UserRequest
}

function Invoke-RawrResponse {
    param([Parameter(Mandatory)][string]$UserRequest)

    $system = Get-PromptFraming -UserRequest $UserRequest

    Write-Host "`n[INFERENCE 1]" -ForegroundColor Cyan
    $first = Invoke-RawrInference -Prompt $system

    # `rawr run` emits a large trace, so match the protocol tag rather than
    # consuming the whole stream.
    $respMatch = [regex]::Match($first, '(?ms)RAWR_RESPONSE\s*\r?\n(.*?)(?:\r?\n\s*\r?\n|$)')
    $toolMatch = [regex]::Match($first, '(?ms)RAWR_TOOL\s*\r?\nname\s*=\s*([A-Za-z0-9_.-]+)(?:\s*\r?\narg\s*=\s*([^\r\n]*))?')

    if ($respMatch.Success -and -not $toolMatch.Success) {
        return $respMatch.Groups[1].Value.Trim()
    }

    if (-not $toolMatch.Success) {
        Write-Host "[PROTOCOL] no recognised tag; raw output follows" -ForegroundColor Red
        return $first.Trim()
    }

    $tool = $toolMatch.Groups[1].Value.Trim()
    $arg  = $toolMatch.Groups[2].Value.Trim()
    Write-Host "[TOOL REQUEST] $tool $arg" -ForegroundColor Yellow

    try {
        $observation = Invoke-AuthorizedTool -Name $tool -Arg $arg
        $status = 'executed'
    } catch {
        $observation = "TOOL_DENIED: $($_.Exception.Message)"
        $status = 'denied'
    }

    Write-Host "[OBSERVATION] $status" -ForegroundColor Yellow
    Write-Host $observation

    # `rawr run` is one-shot, so the logical conversation is preserved by
    # replaying the request, the model's first output, and the real observation.
    # This is NOT an in-memory KV session: do not certify SAME_KV_SESSION=1.
    # Both replayed strings are bounded so the native argv stays legal.
    $firstBounded     = Limit-Text -Text $first     -Max 800
    $observationBound = Limit-Text -Text $observation -Max 1500

    $secondPrompt = @"
$system

YOUR_PREVIOUS_OUTPUT:
$firstBounded

RAWR_OBSERVATION
tool=$tool
status=$status
output:
$observationBound

You now have the real observation. Answer the original request using it.
Request no further tool. Do not state any repository fact absent from the
observation above.

Reply in EXACTLY this form:

RAWR_RESPONSE
<final answer>
"@

    Write-Host "`n[INFERENCE 2]" -ForegroundColor Cyan
    $second = Invoke-RawrInference -Prompt $secondPrompt

    $m = [regex]::Match($second, '(?ms)RAWR_RESPONSE\s*\r?\n(.*?)(?:\r?\n\s*\r?\n|$)')
    if ($m.Success) { return $m.Groups[1].Value.Trim() }
    return $second.Trim()
}

Write-Host "RawrXD bounded response agent ready." -ForegroundColor Green
Write-Host "  model   : $Model"
Write-Host "  rawr    : $Rawr"
Write-Host "  repo    : $RepoRoot"
Write-Host "  usage   : Invoke-RawrResponse 'your request here'"
Write-Host "  same KV : NO (one-shot rawr run; logical context only)"
