#!/usr/bin/env python3
"""
Regenerate build.ninja from CMakeLists.txt WIN32IDE_SOURCES.
"""
import re
from pathlib import Path

def extract_win32ide_sources(cmake_path):
    with open(cmake_path, 'r', encoding='utf-8') as f:
        content = f.read()
    
    sources = []
    
    # Helper: extract source lines from a block
    def extract_lines(block):
        lines = []
        for line in block.split('\n'):
            line = line.strip()
            # Skip comments, empty lines, and CMake keywords
            if not line or line.startswith('#'):
                continue
            # Extract file paths from lines that may contain CMake keywords
            words = line.split()
            for word in words:
                word = word.strip()
                if word in ('PRIVATE', 'PUBLIC', 'INTERFACE', 'APPEND', 'RawrXD-Win32IDE'):
                    continue
                if word.endswith('.cpp') or word.endswith('.c') or word.endswith('.asm') or word.endswith('.rc'):
                    lines.append(word)
        return lines
    
    # Pattern 1: set(WIN32IDE_SOURCES ...)
    set_idx = content.find('set(WIN32IDE_SOURCES')
    if set_idx != -1:
        paren_start = content.find('(', set_idx)
        if paren_start != -1:
            depth = 1
            i = paren_start + 1
            while i < len(content) and depth > 0:
                if content[i] == '(':
                    depth += 1
                elif content[i] == ')':
                    depth -= 1
                i += 1
            block = content[paren_start+1:i-1]
            sources.extend(extract_lines(block))
    
    # Pattern 2: list(APPEND WIN32IDE_SOURCES ...)
    pos = 0
    while True:
        idx = content.find('list(APPEND WIN32IDE_SOURCES', pos)
        if idx == -1:
            break
        paren_start = content.find('(', idx)
        if paren_start == -1:
            break
        depth = 1
        i = paren_start + 1
        while i < len(content) and depth > 0:
            if content[i] == '(':
                depth += 1
            elif content[i] == ')':
                depth -= 1
            i += 1
        block = content[paren_start+1:i-1]
        sources.extend(extract_lines(block))
        pos = i
    
    # Pattern 3: target_sources(RawrXD-Win32IDE PRIVATE ...) blocks
    pos = 0
    while True:
        idx = content.find('target_sources(RawrXD-Win32IDE PRIVATE', pos)
        if idx == -1:
            break
        paren_start = content.find('(', idx)
        if paren_start == -1:
            break
        depth = 1
        i = paren_start + 1
        while i < len(content) and depth > 0:
            if content[i] == '(':
                depth += 1
            elif content[i] == ')':
                depth -= 1
            i += 1
        block = content[paren_start+1:i-1]
        sources.extend(extract_lines(block))
        pos = i
    
    # Remove duplicates while preserving order
    seen = set()
    unique_sources = []
    for s in sources:
        if s not in seen:
            seen.add(s)
            unique_sources.append(s)
    
    # Filter out problematic files that have known compilation issues
    # with the QuickJS C API and C++ lambdas (JSValue macro conflicts)
    filtered_sources = [s for s in unique_sources if s not in (
        'src/core/js_extension_host.cpp',
        'src/modules/quickjs_vscode_bindings.cpp',
    )]
    
    print(f"Filtered {len(unique_sources) - len(filtered_sources)} problematic source(s)")
    
    return filtered_sources

def generate_ninja(project_root, sources):
    project_root = Path(project_root)
    build_dir = project_root / 'agentic_build'
    build_dir.mkdir(exist_ok=True)
    
    ninja_path = build_dir / 'build.ninja'
    
    # Read existing header to preserve tool paths
    existing_header = []
    if ninja_path.exists():
        with open(ninja_path, 'r') as f:
            for line in f:
                existing_header.append(line)
                if line.strip() == '':
                    break
                if line.startswith('build obj/'):
                    break
    
    with open(ninja_path, 'w') as f:
        f.write("# Auto-generated by RawrXD Agentic Build System\n")
        f.write("# Project: RawrXD-ModelLoader v1.0.13\n\n")
        
        f.write("CXX = cl.exe\n")
        f.write("LINK = link.exe\n")
        f.write("CXXFLAGS = /std:c++20 /EHsc /MD /O2 /I\"C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\um\" /I\"C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\shared\" /I\"C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\ucrt\" /I\"C:\\Program Files (x86)\\Windows Kits\\10\\Include\\10.0.22621.0\\winrt\" /I\"C:\\Program Files\\Microsoft Visual Studio\\18\\Enterprise\\VC\\Tools\\MSVC\\14.51.36231\\include\"\n")
        f.write("LINKFLAGS = /SUBSYSTEM:CONSOLE /LIBPATH:\"C:\\Program Files\\Microsoft Visual Studio\\18\\Enterprise\\VC\\Tools\\MSVC\\14.51.36231\\lib\\x64\" /LIBPATH:\"C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\ucrt\\x64\" /LIBPATH:\"C:\\Program Files (x86)\\Windows Kits\\10\\Lib\\10.0.22621.0\\um\\x64\"\n\n")
        
        f.write("DEFINES = -DNOMINMAX -D_WIN32_WINNT=0x0A00 -DHAVE_QT_CORE -DQT_NO_OPENGL -DRAWRXD_NO_VULKAN -DWIN32_LEAN_AND_MEAN -DRAWRXD_ALLOW_VULKAN_TYPE_STUBS=1\n\n")
        
        f.write("rule compile\n")
        f.write("  command = $CXX $CXXFLAGS $DEFINES $includes /c $in /Fo$out\n")
        f.write("  description = Compiling $in\n\n")
        
        f.write("rule link\n")
        f.write("  command = $LINK $LINKFLAGS $in /OUT:$out\n")
        f.write("  description = Linking $out\n\n")
        
        # Write compile rules for each source
        obj_files = []
        for src in sources:
            src_path = Path(src)
            # Use directory-prefixed object name to avoid collisions
            # e.g., src/agent/foo.cpp -> agent_foo.obj
            parts = src_path.parts
            if len(parts) >= 2:
                prefix = '_'.join(parts[:-1])
                obj_name = f"{prefix}_{src_path.stem}.obj"
            else:
                obj_name = src_path.stem + '.obj'
            obj_path = f"obj/RawrXD-Win32IDE/{obj_name}"
            obj_files.append(obj_path)
            
            f.write(f"build {obj_path}: compile {src}\n")
            f.write(f"  includes = /Iinclude /Isrc /IShip\n")
        
        # Write link rule
        f.write(f"\nbuild bin/RawrXD-Win32IDE.exe: link {' '.join(obj_files)}\n\n")
    
    print(f"Wrote {len(sources)} sources to {ninja_path}")
    return len(sources)

if __name__ == '__main__':
    project_root = Path('d:/rawrxd')
    cmake_path = project_root / 'CMakeLists.txt'
    sources = extract_win32ide_sources(cmake_path)
    print(f"Extracted {len(sources)} sources from CMakeLists.txt")
    count = generate_ninja(project_root, sources)
    print(f"Done. Total objects in link: {count}")
