# CMake generated Testfile for 
# Source directory: C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init
# Build directory: C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_Compression]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running compression smoke test...")
  set_tests_properties([=[SmokeTest_Compression]=] PROPERTIES  PASS_REGULAR_EXPRESSION "compression smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;7;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_Compression]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running compression smoke test...")
  set_tests_properties([=[SmokeTest_Compression]=] PROPERTIES  PASS_REGULAR_EXPRESSION "compression smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;7;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_Compression]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running compression smoke test...")
  set_tests_properties([=[SmokeTest_Compression]=] PROPERTIES  PASS_REGULAR_EXPRESSION "compression smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;7;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_Compression]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running compression smoke test...")
  set_tests_properties([=[SmokeTest_Compression]=] PROPERTIES  PASS_REGULAR_EXPRESSION "compression smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;7;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_Compression]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_FlashAttention]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running flash attention smoke test...")
  set_tests_properties([=[SmokeTest_FlashAttention]=] PROPERTIES  PASS_REGULAR_EXPRESSION "flash attention smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;18;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_FlashAttention]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running flash attention smoke test...")
  set_tests_properties([=[SmokeTest_FlashAttention]=] PROPERTIES  PASS_REGULAR_EXPRESSION "flash attention smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;18;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_FlashAttention]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running flash attention smoke test...")
  set_tests_properties([=[SmokeTest_FlashAttention]=] PROPERTIES  PASS_REGULAR_EXPRESSION "flash attention smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;18;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_FlashAttention]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running flash attention smoke test...")
  set_tests_properties([=[SmokeTest_FlashAttention]=] PROPERTIES  PASS_REGULAR_EXPRESSION "flash attention smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;18;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_FlashAttention]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_Checkpoints]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running checkpoint manager smoke test...")
  set_tests_properties([=[SmokeTest_Checkpoints]=] PROPERTIES  PASS_REGULAR_EXPRESSION "checkpoint manager smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;29;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_Checkpoints]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running checkpoint manager smoke test...")
  set_tests_properties([=[SmokeTest_Checkpoints]=] PROPERTIES  PASS_REGULAR_EXPRESSION "checkpoint manager smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;29;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_Checkpoints]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running checkpoint manager smoke test...")
  set_tests_properties([=[SmokeTest_Checkpoints]=] PROPERTIES  PASS_REGULAR_EXPRESSION "checkpoint manager smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;29;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_Checkpoints]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running checkpoint manager smoke test...")
  set_tests_properties([=[SmokeTest_Checkpoints]=] PROPERTIES  PASS_REGULAR_EXPRESSION "checkpoint manager smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;29;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_Checkpoints]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_CICD]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running CI/CD pipeline smoke test...")
  set_tests_properties([=[SmokeTest_CICD]=] PROPERTIES  PASS_REGULAR_EXPRESSION "CI/CD pipeline smoke test" TIMEOUT "15" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;40;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_CICD]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running CI/CD pipeline smoke test...")
  set_tests_properties([=[SmokeTest_CICD]=] PROPERTIES  PASS_REGULAR_EXPRESSION "CI/CD pipeline smoke test" TIMEOUT "15" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;40;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_CICD]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running CI/CD pipeline smoke test...")
  set_tests_properties([=[SmokeTest_CICD]=] PROPERTIES  PASS_REGULAR_EXPRESSION "CI/CD pipeline smoke test" TIMEOUT "15" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;40;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_CICD]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running CI/CD pipeline smoke test...")
  set_tests_properties([=[SmokeTest_CICD]=] PROPERTIES  PASS_REGULAR_EXPRESSION "CI/CD pipeline smoke test" TIMEOUT "15" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;40;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_CICD]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_Encryption]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running AES-GCM encryption smoke test...")
  set_tests_properties([=[SmokeTest_Encryption]=] PROPERTIES  PASS_REGULAR_EXPRESSION "AES-GCM encryption smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;51;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_Encryption]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running AES-GCM encryption smoke test...")
  set_tests_properties([=[SmokeTest_Encryption]=] PROPERTIES  PASS_REGULAR_EXPRESSION "AES-GCM encryption smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;51;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_Encryption]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running AES-GCM encryption smoke test...")
  set_tests_properties([=[SmokeTest_Encryption]=] PROPERTIES  PASS_REGULAR_EXPRESSION "AES-GCM encryption smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;51;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_Encryption]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running AES-GCM encryption smoke test...")
  set_tests_properties([=[SmokeTest_Encryption]=] PROPERTIES  PASS_REGULAR_EXPRESSION "AES-GCM encryption smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;51;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_Encryption]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_GGUFLoader]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running GGUF loader smoke test...")
  set_tests_properties([=[SmokeTest_GGUFLoader]=] PROPERTIES  PASS_REGULAR_EXPRESSION "GGUF loader smoke test" TIMEOUT "20" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;62;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_GGUFLoader]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running GGUF loader smoke test...")
  set_tests_properties([=[SmokeTest_GGUFLoader]=] PROPERTIES  PASS_REGULAR_EXPRESSION "GGUF loader smoke test" TIMEOUT "20" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;62;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_GGUFLoader]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running GGUF loader smoke test...")
  set_tests_properties([=[SmokeTest_GGUFLoader]=] PROPERTIES  PASS_REGULAR_EXPRESSION "GGUF loader smoke test" TIMEOUT "20" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;62;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_GGUFLoader]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running GGUF loader smoke test...")
  set_tests_properties([=[SmokeTest_GGUFLoader]=] PROPERTIES  PASS_REGULAR_EXPRESSION "GGUF loader smoke test" TIMEOUT "20" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;62;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_GGUFLoader]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[SmokeTest_AgenticBridge]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running agentic copilot bridge smoke test...")
  set_tests_properties([=[SmokeTest_AgenticBridge]=] PROPERTIES  PASS_REGULAR_EXPRESSION "agentic copilot bridge smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;73;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[SmokeTest_AgenticBridge]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running agentic copilot bridge smoke test...")
  set_tests_properties([=[SmokeTest_AgenticBridge]=] PROPERTIES  PASS_REGULAR_EXPRESSION "agentic copilot bridge smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;73;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test([=[SmokeTest_AgenticBridge]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running agentic copilot bridge smoke test...")
  set_tests_properties([=[SmokeTest_AgenticBridge]=] PROPERTIES  PASS_REGULAR_EXPRESSION "agentic copilot bridge smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;73;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[SmokeTest_AgenticBridge]=] "C:/Program Files/CMake/bin/cmake.exe" "-E" "echo" "Running agentic copilot bridge smoke test...")
  set_tests_properties([=[SmokeTest_AgenticBridge]=] PROPERTIES  PASS_REGULAR_EXPRESSION "agentic copilot bridge smoke test" TIMEOUT "10" WORKING_DIRECTORY "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init" _BACKTRACE_TRIPLES "C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;73;add_test;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/smoke_tests.cmake;0;;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;2307;include;C:/Users/HiH8e/Downloads/RawrXD-production-lazy-init/CMakeLists.txt;0;")
else()
  add_test([=[SmokeTest_AgenticBridge]=] NOT_AVAILABLE)
endif()
subdirs("src/masm")
subdirs("3rdparty/ggml")
subdirs("src/orchestration")
subdirs("src/git")
subdirs("src/terminal")
subdirs("src")
