#pragma once
#include <string>
#include <sstream>
#include "TITAN_PREFETCH_ABI.hpp"
#include "TITAN_PHASE_SYNCHRONIZED_SCHEDULER.hpp"
#include "TITAN_MULTI_TILE_DATAFLOW.hpp"

// =============================================================================
// TITAN MACRO ASSEMBLER (FINAL)
// =============================================================================
// The final C++ emission layer. Links the phase-synchronized memory subsystem
// the prefetch ABI, and the multi-tile dataflow engines to emit a complete,
// compliant MASM64 function.
// =============================================================================

namespace Titan {
namespace Assembler {

    class MacroAssembler {
    public:
        // Emits the full, ABI-compliant MASM64 function encapsulating the dataflow core.
        // RCX = float* dst (for writing back accumulators or just the test harness)
        // RDX = const float* src (our RSI equivalent here)
        // R8  = num_elements (must be multiple of 64 for 256-byte tile)
        static std::string EmitComputeKernel(const std::string& functionName = "Titan_MicroFused_N8_Kernel") {
            std::stringstream ss;
            
            ss << "; ==================================================================\n";
            ss << "; AUTO-GENERATED BY TITAN MACRO ASSEMBLER\n";
            ss << "; Micro-Architecture Target: Zen 4 / Golden Cove (Tri-Coupled Saturation)\n";
            ss << "; ==================================================================\n\n";

            ss << ".CODE\n";
            ss << functionName << " PROC FRAME\n";
            ss << "    ; Windows x64 ABI Prologue\n";
            ss << "    push rsi\n";
            ss << "    .pushreg rsi\n";
            ss << "    push rbx\n";
            ss << "    .pushreg rbx\n";
            ss << "    .allocstack 32\n";
            ss << "    sub rsp, 32\n";
            ss << "    .endprolog\n\n";

            ss << "    ; Standardize input pointers\n";
            ss << "    mov rsi, rdx        ; RSI = Data Stream\n";
            ss << "    lea rbx, [rsi + r8*4] ; RBX = End of Stream (assume float elements)\n\n";
            
            ss << "    ; Initialize YMM0-YMM7 Accumulators to zero\n";
            for (int i = 0; i < 8; ++i) {
                ss << "    vxorps ymm" << i << ", ymm" << i << ", ymm" << i << "\n";
            }
            ss << "\n";

            // Emit the Pre-warm ABI
            ss << Memory::PrefetchOrchestrator::EmitPreWarmPreamble("rsi");

            // Emit the Multi-Tile Double Buffered Dataflow plane
            // This natively hides the micro-fused L1 constraints and AGU loads.
            ss << Dataflow::MultiTilePipeline::EmitTemporalOverlapLoop(256, 2);

            ss << "    ; [POST-LOOP] Accumulator Reduction or Write-back could go here.\n";
            ss << "    ; (Skipped for pure throughput saturation demonstration)\n\n";

            ss << "    ; Windows x64 ABI Epilogue\n";
            ss << "    add rsp, 32\n";
            ss << "    pop rbx\n";
            ss << "    pop rsi\n";
            ss << "    ret\n";
            ss << functionName << " ENDP\n";
            ss << "END\n";
            
            return ss.str();
        }
    };

} // namespace Assembler
} // namespace Titan