#pragma once
#include "RawrStreamerTypes.hpp"

enum RawrTerminationClass : RAWR_U32 {
    RAWR_TERM_NONE = 0,
    RAWR_TERM_COMPLETED,
    RAWR_TERM_BLOCKED_BEFORE_EXECUTION,
    RAWR_TERM_BLOCKED_DURING_EXECUTION,
    RAWR_TERM_FAILED_BEFORE_STREAM,
    RAWR_TERM_FAILED_DURING_STREAM,
    RAWR_TERM_ABORTED_DURING_STREAM,
    RAWR_TERM_CANCELLED,
    RAWR_TERM_DEVICE_LOST,
    RAWR_TERM_PROCESS_LOST
};

enum RawrFailureDomain : RAWR_U32 {
    RAWR_FAILURE_NONE = 0,
    RAWR_FAILURE_INPUT,
    RAWR_FAILURE_MODEL,
    RAWR_FAILURE_FORMAT,
    RAWR_FAILURE_TOKENIZER,
    RAWR_FAILURE_ADDRESS,
    RAWR_FAILURE_MEMORY,
    RAWR_FAILURE_RESIDENCY,
    RAWR_FAILURE_DEVICE,
    RAWR_FAILURE_SHADER,
    RAWR_FAILURE_KERNEL,
    RAWR_FAILURE_NUMERIC,
    RAWR_FAILURE_SCHEDULER,
    RAWR_FAILURE_QUEUE,
    RAWR_FAILURE_IO,
    RAWR_FAILURE_STREAM,
    RAWR_FAILURE_TEARDOWN,
    RAWR_FAILURE_ENVIRONMENT,
    RAWR_FAILURE_INTERNAL
};

enum RawrBlockOwner : RAWR_U32 {
    RAWR_OWNER_NONE = 0,
    RAWR_OWNER_CALLER,
    RAWR_OWNER_MODEL_RESOLVER,
    RAWR_OWNER_GGUF,
    RAWR_OWNER_TOKENIZER,
    RAWR_OWNER_RMV,
    RAWR_OWNER_RESIDENCY,
    RAWR_OWNER_CAPABILITY_SOLVER,
    RAWR_OWNER_KERNEL_SOLVER,
    RAWR_OWNER_SHADER_PIPELINE,
    RAWR_OWNER_DEVICE,
    RAWR_OWNER_QKV,
    RAWR_OWNER_KVA,
    RAWR_OWNER_O_PROJ,
    RAWR_OWNER_FFN,
    RAWR_OWNER_LOGITS,
    RAWR_OWNER_SAMPLER,
    RAWR_OWNER_STREAMER,
    RAWR_OWNER_TEARDOWN,
    RAWR_OWNER_ENVIRONMENT
};
