#pragma once
#include "RawrStreamerTypes.hpp"

enum RawrExecutionScope : RAWR_U32 {
    RAWR_SCOPE_NONE = 0,
    RAWR_SCOPE_DISCOVER,
    RAWR_SCOPE_INDEX,
    RAWR_SCOPE_VALIDATE,
    RAWR_SCOPE_PLAN,
    RAWR_SCOPE_TUNE,
    RAWR_SCOPE_PREFILL,
    RAWR_SCOPE_DECODE,
    RAWR_SCOPE_GENERATE,
    RAWR_SCOPE_STREAM,
    RAWR_SCOPE_TEARDOWN,
    RAWR_SCOPE_END_TO_END
};

enum RawrOutputClass : RAWR_U32 {
    RAWR_OUTPUT_NONE = 0,
    RAWR_OUTPUT_DIAGNOSTIC,
    RAWR_OUTPUT_PROGRESS,
    RAWR_OUTPUT_RECEIPT,
    RAWR_OUTPUT_MEASUREMENT,
    RAWR_OUTPUT_MODEL_TOKEN,
    RAWR_OUTPUT_MODEL_TEXT,
    RAWR_OUTPUT_COMPLETION,
    RAWR_OUTPUT_BLOCKED,
    RAWR_OUTPUT_FAILURE
};

enum RawrProductionState : RAWR_U32 {
    RAWR_PRODUCTION_NONE = 0,
    RAWR_PRODUCTION_NOT_ENTERED,
    RAWR_PRODUCTION_ENTERED,
    RAWR_PRODUCTION_PREFILL_ACTIVE,
    RAWR_PRODUCTION_DECODE_ACTIVE,
    RAWR_PRODUCTION_TOKEN_PRODUCED,
    RAWR_PRODUCTION_STREAM_ACTIVE,
    RAWR_PRODUCTION_FINISHED
};

enum RawrCompletionReason : RAWR_U32 {
    RAWR_COMPLETE_NONE = 0,
    RAWR_COMPLETE_EOS,
    RAWR_COMPLETE_MAX_TOKENS,
    RAWR_COMPLETE_STOP_SEQUENCE,
    RAWR_COMPLETE_USER_CANCEL_AFTER_OUTPUT,
    RAWR_COMPLETE_REQUEST_SATISFIED,
    RAWR_COMPLETE_STREAM_CLOSED,
    RAWR_COMPLETE_TEARDOWN_CLEAN
};
