#pragma once
#include "RawrStreamerTypes.hpp"

enum RawrStreamState : RAWR_U32 {
    RAWR_STREAM_COLD = 0,
    RAWR_STREAM_BOOT,
    RAWR_STREAM_MODEL_RESOLVE,
    RAWR_STREAM_MODEL_OPEN,
    RAWR_STREAM_MODEL_INDEX,
    RAWR_STREAM_MODEL_FACTS,
    RAWR_STREAM_TOKENIZER_OPEN,
    RAWR_STREAM_EXEC_CREATE,
    RAWR_STREAM_CAP_DISCOVER,
    RAWR_STREAM_SPACE_SNAPSHOT,
    RAWR_STREAM_PLAN,
    RAWR_STREAM_PREFILL,
    RAWR_STREAM_DECODE,
    RAWR_STREAM_EMIT,
    RAWR_STREAM_COMPLETE,
    RAWR_STREAM_BLOCKED,
    RAWR_STREAM_FAIL
};

enum RawrStreamStatus : RAWR_U32 {
    RAWR_STATUS_UNKNOWN = 0,
    RAWR_STATUS_PASS,
    RAWR_STATUS_OPEN,
    RAWR_STATUS_BLOCKED,
    RAWR_STATUS_FAIL,
    RAWR_STATUS_SKIP,
    RAWR_STATUS_RETRY,
    RAWR_STATUS_RECOVERED
};

enum RawrTokenState : RAWR_U32 {
    RAWR_TOKEN_NONE = 0,
    RAWR_TOKEN_PROMPT,
    RAWR_TOKEN_PREFILL,
    RAWR_TOKEN_DECODE,
    RAWR_TOKEN_SAMPLE,
    RAWR_TOKEN_EMIT,
    RAWR_TOKEN_STOP
};
