#pragma once
#include "RawrStreamerTypes.hpp"

enum RawrStreamBlocker : RAWR_U32 {
    RAWR_BLOCK_NONE = 0,
    RAWR_BLOCK_MODEL_NOT_FOUND,
    RAWR_BLOCK_MODEL_OPEN_FAIL,
    RAWR_BLOCK_GGUF_INVALID,
    RAWR_BLOCK_TENSOR_MISSING,
    RAWR_BLOCK_TENSOR_UNADDRESSED,
    RAWR_BLOCK_TENSOR_UNACQUIRED,
    RAWR_BLOCK_TOKENIZER_MISSING,
    RAWR_BLOCK_MODEL_FACT_INVALID,
    RAWR_BLOCK_EXEC_INSTANCE_INVALID,
    RAWR_BLOCK_NO_DEVICE,
    RAWR_BLOCK_NO_LEGAL_SHAPE,
    RAWR_BLOCK_NO_SHADER_VARIANT,
    RAWR_BLOCK_NO_PARITY_PASS,
    RAWR_BLOCK_NO_MEASURE,
    RAWR_BLOCK_NO_WINNER,
    RAWR_BLOCK_EMBED_ZERO,
    RAWR_BLOCK_LAYER_ZERO,
    RAWR_BLOCK_FINAL_NORM_ZERO,
    RAWR_BLOCK_LOGITS_ZERO,
    RAWR_BLOCK_SAMPLE_INVALID,
    RAWR_BLOCK_MEMORY_PRESSURE,
    RAWR_BLOCK_DEVICE_LOST,
    RAWR_BLOCK_QUEUE_FAIL,
    RAWR_BLOCK_DISPATCH_FAIL,
    RAWR_BLOCK_PARITY_FAIL,
    RAWR_BLOCK_TIMEOUT
};

enum RawrBufferKind : RAWR_U32 {
    RAWR_BUFFER_NONE = 0,
    RAWR_BUFFER_TOKEN_IDS,
    RAWR_BUFFER_EMBED,
    RAWR_BUFFER_HIDDEN_A,
    RAWR_BUFFER_HIDDEN_B,
    RAWR_BUFFER_ATTN_SCRATCH,
    RAWR_BUFFER_FFN_SCRATCH,
    RAWR_BUFFER_FINAL_HIDDEN,
    RAWR_BUFFER_LOGITS,
    RAWR_BUFFER_KV_K,
    RAWR_BUFFER_KV_V,
    RAWR_BUFFER_TENSOR_VIEW,
    RAWR_BUFFER_DEVICE_STORAGE,
    RAWR_BUFFER_HOST_STAGING
};

enum RawrTensorAccess : RAWR_U32 {
    RAWR_ACCESS_NONE = 0,
    RAWR_ACCESS_HOST_READ,
    RAWR_ACCESS_HOST_WRITE,
    RAWR_ACCESS_DEVICE_READ,
    RAWR_ACCESS_DEVICE_WRITE,
    RAWR_ACCESS_HOST_DEVICE_COPY,
    RAWR_ACCESS_EXECUTE
};
