#pragma once
#include "RawrStreamerTypes.hpp"

enum RawrReceiptField : RAWR_U32 {
    RAWR_FIELD_NONE = 0,
    RAWR_FIELD_STREAM_STATE,
    RAWR_FIELD_STAGE,
    RAWR_FIELD_EVENT,
    RAWR_FIELD_STATUS,
    RAWR_FIELD_BLOCKED_AT,
    RAWR_FIELD_BLOCKED_OWNER,
    RAWR_FIELD_MODEL_PATH,
    RAWR_FIELD_MODEL_ARCH,
    RAWR_FIELD_MODEL_HIDDEN,
    RAWR_FIELD_MODEL_LAYERS,
    RAWR_FIELD_MODEL_HEADS,
    RAWR_FIELD_MODEL_KV_HEADS,
    RAWR_FIELD_MODEL_HEAD_DIM,
    RAWR_FIELD_MODEL_FFN,
    RAWR_FIELD_MODEL_VOCAB,
    RAWR_FIELD_TENSORS_DISCOVERED,
    RAWR_FIELD_TENSORS_ADDRESSED,
    RAWR_FIELD_TENSORS_REGISTERED,
    RAWR_FIELD_INVALID_SHARD,
    RAWR_FIELD_INVALID_RANGE,
    RAWR_FIELD_OVERFLOW_RANGE,
    RAWR_FIELD_ZERO_SIZE,
    RAWR_FIELD_UNADDRESSED,
    RAWR_FIELD_HOST_AVAIL_BYTES,
    RAWR_FIELD_DEVICE_BUDGET_BYTES,
    RAWR_FIELD_DEVICE_USAGE_BYTES,
    RAWR_FIELD_DEVICE_HEADROOM_BYTES,
    RAWR_FIELD_KERNEL_NAME,
    RAWR_FIELD_ROWS_PER_WG,
    RAWR_FIELD_LOCAL_X,
    RAWR_FIELD_LOCAL_Y,
    RAWR_FIELD_LOCAL_Z,
    RAWR_FIELD_SHARED_BYTES,
    RAWR_FIELD_LEGAL,
    RAWR_FIELD_PARITY,
    RAWR_FIELD_MEASURE_COMPLETE,
    RAWR_FIELD_GPU_TIME_US,
    RAWR_FIELD_WALL_TIME_US,
    RAWR_FIELD_WINNER_INDEX,
    RAWR_FIELD_PROMPT_BYTES,
    RAWR_FIELD_PROMPT_TOKENS,
    RAWR_FIELD_POSITION,
    RAWR_FIELD_TOKEN_ID,
    RAWR_FIELD_TOKEN_TEXT,
    RAWR_FIELD_EMBED_NORM,
    RAWR_FIELD_LAYER_IN_NORM,
    RAWR_FIELD_LAYER_OUT_NORM,
    RAWR_FIELD_FINAL_NORM_BEFORE,
    RAWR_FIELD_FINAL_NORM_AFTER,
    RAWR_FIELD_LOGITS_NORM,
    RAWR_FIELD_PREFILL_MS,
    RAWR_FIELD_DECODE_MS,
    RAWR_FIELD_FIRST_TOKEN_MS,
    RAWR_FIELD_NS_PER_TOKEN,
    RAWR_FIELD_DECODE_TPS,
    RAWR_FIELD_GENERATED_TOKENS
};

struct RawrStreamReceipt {
    RAWR_U64 generation;
    RAWR_U64 sequence;
    RAWR_U32 state;
    RAWR_U32 stage;
    RAWR_U32 event;
    RAWR_U32 status;
    RAWR_U32 blocker;
    RAWR_U64 timestamp_ns;
    RAWR_U64 wall_us;
    RAWR_U64 value_u64;
    RAWR_F64 value_f64;
    const char* key;
    const char* text;
};
