# CMake generated Testfile for 
# Source directory: D:/rawrxd/tests
# Build directory: D:/rawrxd/build-ninja2/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[agent_workflow_orchestrator_smoke]=] "D:/rawrxd/build-ninja2/bin/Debug/agent_workflow_orchestrator_smoke.exe")
  set_tests_properties([=[agent_workflow_orchestrator_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;87;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[agent_workflow_orchestrator_smoke]=] "D:/rawrxd/build-ninja2/bin/Release/agent_workflow_orchestrator_smoke.exe")
  set_tests_properties([=[agent_workflow_orchestrator_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;87;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[agent_workflow_orchestrator_smoke]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/agent_workflow_orchestrator_smoke.exe")
  set_tests_properties([=[agent_workflow_orchestrator_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;87;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[agent_workflow_orchestrator_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_ai_completions]=] "D:/rawrxd/build-ninja2/tests/Debug/test_ai_completions.exe")
  set_tests_properties([=[test_ai_completions]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;103;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_ai_completions]=] "D:/rawrxd/build-ninja2/tests/Release/test_ai_completions.exe")
  set_tests_properties([=[test_ai_completions]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;103;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_ai_completions]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_ai_completions.exe")
  set_tests_properties([=[test_ai_completions]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;103;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_ai_completions]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_llm_connectivity]=] "D:/rawrxd/build-ninja2/tests/Debug/test_llm_connectivity.exe")
  set_tests_properties([=[test_llm_connectivity]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;115;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_llm_connectivity]=] "D:/rawrxd/build-ninja2/tests/Release/test_llm_connectivity.exe")
  set_tests_properties([=[test_llm_connectivity]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;115;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_llm_connectivity]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_llm_connectivity.exe")
  set_tests_properties([=[test_llm_connectivity]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;115;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_llm_connectivity]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_tool_registry]=] "D:/rawrxd/build-ninja2/tests/Debug/test_tool_registry.exe")
  set_tests_properties([=[test_tool_registry]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;127;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_tool_registry]=] "D:/rawrxd/build-ninja2/tests/Release/test_tool_registry.exe")
  set_tests_properties([=[test_tool_registry]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;127;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_tool_registry]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_tool_registry.exe")
  set_tests_properties([=[test_tool_registry]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;127;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_tool_registry]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_zero_retention_manager]=] "D:/rawrxd/build-ninja2/tests/Debug/test_zero_retention_manager.exe")
  set_tests_properties([=[test_zero_retention_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;141;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_zero_retention_manager]=] "D:/rawrxd/build-ninja2/tests/Release/test_zero_retention_manager.exe")
  set_tests_properties([=[test_zero_retention_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;141;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_zero_retention_manager]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_zero_retention_manager.exe")
  set_tests_properties([=[test_zero_retention_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;141;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_zero_retention_manager]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_semantic_diff_analyzer]=] "D:/rawrxd/build-ninja2/tests/Debug/test_semantic_diff_analyzer.exe")
  set_tests_properties([=[test_semantic_diff_analyzer]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;150;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_semantic_diff_analyzer]=] "D:/rawrxd/build-ninja2/tests/Release/test_semantic_diff_analyzer.exe")
  set_tests_properties([=[test_semantic_diff_analyzer]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;150;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_semantic_diff_analyzer]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_semantic_diff_analyzer.exe")
  set_tests_properties([=[test_semantic_diff_analyzer]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;150;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_semantic_diff_analyzer]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_ai_merge_resolver]=] "D:/rawrxd/build-ninja2/tests/Debug/test_ai_merge_resolver.exe")
  set_tests_properties([=[test_ai_merge_resolver]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;162;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_ai_merge_resolver]=] "D:/rawrxd/build-ninja2/tests/Release/test_ai_merge_resolver.exe")
  set_tests_properties([=[test_ai_merge_resolver]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;162;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_ai_merge_resolver]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_ai_merge_resolver.exe")
  set_tests_properties([=[test_ai_merge_resolver]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;162;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_ai_merge_resolver]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_ide_model_autonomy]=] "D:/rawrxd/build-ninja2/tests/Debug/test_ide_model_autonomy.exe")
  set_tests_properties([=[test_ide_model_autonomy]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;186;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_ide_model_autonomy]=] "D:/rawrxd/build-ninja2/tests/Release/test_ide_model_autonomy.exe")
  set_tests_properties([=[test_ide_model_autonomy]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;186;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_ide_model_autonomy]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_ide_model_autonomy.exe")
  set_tests_properties([=[test_ide_model_autonomy]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;186;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_ide_model_autonomy]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_extreme_memory_optimizer]=] "D:/rawrxd/build-ninja2/tests/Debug/test_extreme_memory_optimizer.exe")
  set_tests_properties([=[test_extreme_memory_optimizer]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;200;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_extreme_memory_optimizer]=] "D:/rawrxd/build-ninja2/tests/Release/test_extreme_memory_optimizer.exe")
  set_tests_properties([=[test_extreme_memory_optimizer]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;200;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_extreme_memory_optimizer]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_extreme_memory_optimizer.exe")
  set_tests_properties([=[test_extreme_memory_optimizer]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;200;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_extreme_memory_optimizer]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_quality_corrector]=] "D:/rawrxd/build-ninja2/tests/Debug/test_quality_corrector.exe")
  set_tests_properties([=[test_quality_corrector]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;214;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_quality_corrector]=] "D:/rawrxd/build-ninja2/tests/Release/test_quality_corrector.exe")
  set_tests_properties([=[test_quality_corrector]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;214;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_quality_corrector]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_quality_corrector.exe")
  set_tests_properties([=[test_quality_corrector]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;214;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_quality_corrector]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_sandboxed_terminal]=] "D:/rawrxd/build-ninja2/tests/Debug/test_sandboxed_terminal.exe")
  set_tests_properties([=[test_sandboxed_terminal]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;223;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_sandboxed_terminal]=] "D:/rawrxd/build-ninja2/tests/Release/test_sandboxed_terminal.exe")
  set_tests_properties([=[test_sandboxed_terminal]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;223;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_sandboxed_terminal]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_sandboxed_terminal.exe")
  set_tests_properties([=[test_sandboxed_terminal]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;223;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_sandboxed_terminal]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_agentic_file_operations]=] "D:/rawrxd/build-ninja2/tests/Debug/test_agentic_file_operations.exe")
  set_tests_properties([=[test_agentic_file_operations]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;232;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_agentic_file_operations]=] "D:/rawrxd/build-ninja2/tests/Release/test_agentic_file_operations.exe")
  set_tests_properties([=[test_agentic_file_operations]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;232;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_agentic_file_operations]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_agentic_file_operations.exe")
  set_tests_properties([=[test_agentic_file_operations]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;232;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_agentic_file_operations]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[smoke_split_answers_toggle]=] "D:/rawrxd/build-ninja2/tests/Debug/smoke_split_answers_toggle.exe")
  set_tests_properties([=[smoke_split_answers_toggle]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;248;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[smoke_split_answers_toggle]=] "D:/rawrxd/build-ninja2/tests/Release/smoke_split_answers_toggle.exe")
  set_tests_properties([=[smoke_split_answers_toggle]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;248;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[smoke_split_answers_toggle]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/smoke_split_answers_toggle.exe")
  set_tests_properties([=[smoke_split_answers_toggle]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;248;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[smoke_split_answers_toggle]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[agentic_repair_stress_test]=] "D:/rawrxd/build-ninja2/tests/Debug/agentic_repair_stress_test.exe")
  set_tests_properties([=[agentic_repair_stress_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;257;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[agentic_repair_stress_test]=] "D:/rawrxd/build-ninja2/tests/Release/agentic_repair_stress_test.exe")
  set_tests_properties([=[agentic_repair_stress_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;257;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[agentic_repair_stress_test]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/agentic_repair_stress_test.exe")
  set_tests_properties([=[agentic_repair_stress_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;257;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[agentic_repair_stress_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_adaptive_credit_governor]=] "D:/rawrxd/build-ninja2/tests/Debug/test_adaptive_credit_governor.exe")
  set_tests_properties([=[test_adaptive_credit_governor]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;271;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_adaptive_credit_governor]=] "D:/rawrxd/build-ninja2/tests/Release/test_adaptive_credit_governor.exe")
  set_tests_properties([=[test_adaptive_credit_governor]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;271;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_adaptive_credit_governor]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_adaptive_credit_governor.exe")
  set_tests_properties([=[test_adaptive_credit_governor]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;271;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_adaptive_credit_governor]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[model_registry_test]=] "D:/rawrxd/build-ninja2/tests/Debug/model_registry_test.exe")
  set_tests_properties([=[model_registry_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;280;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[model_registry_test]=] "D:/rawrxd/build-ninja2/tests/Release/model_registry_test.exe")
  set_tests_properties([=[model_registry_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;280;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[model_registry_test]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/model_registry_test.exe")
  set_tests_properties([=[model_registry_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;280;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[model_registry_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_gguf_integration]=] "D:/rawrxd/build-ninja2/tests/Debug/test_gguf_integration.exe")
  set_tests_properties([=[test_gguf_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;290;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_gguf_integration]=] "D:/rawrxd/build-ninja2/tests/Release/test_gguf_integration.exe")
  set_tests_properties([=[test_gguf_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;290;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_gguf_integration]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_gguf_integration.exe")
  set_tests_properties([=[test_gguf_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;290;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_gguf_integration]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_engine_revolver]=] "D:/rawrxd/build-ninja2/tests/Debug/test_engine_revolver.exe")
  set_tests_properties([=[test_engine_revolver]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;298;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_engine_revolver]=] "D:/rawrxd/build-ninja2/tests/Release/test_engine_revolver.exe")
  set_tests_properties([=[test_engine_revolver]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;298;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_engine_revolver]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_engine_revolver.exe")
  set_tests_properties([=[test_engine_revolver]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;298;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_engine_revolver]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_swarm_scheduler_pin]=] "D:/rawrxd/build-ninja2/tests/Debug/test_swarm_scheduler_pin.exe")
  set_tests_properties([=[test_swarm_scheduler_pin]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;311;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_swarm_scheduler_pin]=] "D:/rawrxd/build-ninja2/tests/Release/test_swarm_scheduler_pin.exe")
  set_tests_properties([=[test_swarm_scheduler_pin]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;311;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_swarm_scheduler_pin]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_swarm_scheduler_pin.exe")
  set_tests_properties([=[test_swarm_scheduler_pin]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;311;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_swarm_scheduler_pin]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_swarm_expert_heatmap_stress]=] "D:/rawrxd/build-ninja2/tests/Debug/test_swarm_expert_heatmap_stress.exe")
  set_tests_properties([=[test_swarm_expert_heatmap_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;324;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_swarm_expert_heatmap_stress]=] "D:/rawrxd/build-ninja2/tests/Release/test_swarm_expert_heatmap_stress.exe")
  set_tests_properties([=[test_swarm_expert_heatmap_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;324;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_swarm_expert_heatmap_stress]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_swarm_expert_heatmap_stress.exe")
  set_tests_properties([=[test_swarm_expert_heatmap_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;324;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_swarm_expert_heatmap_stress]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_moe_mixture_reference]=] "D:/rawrxd/build-ninja2/tests/Debug/test_moe_mixture_reference.exe")
  set_tests_properties([=[test_moe_mixture_reference]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;332;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_moe_mixture_reference]=] "D:/rawrxd/build-ninja2/tests/Release/test_moe_mixture_reference.exe")
  set_tests_properties([=[test_moe_mixture_reference]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;332;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_moe_mixture_reference]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_moe_mixture_reference.exe")
  set_tests_properties([=[test_moe_mixture_reference]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;332;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_moe_mixture_reference]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_moe_down_project_policy]=] "D:/rawrxd/build-ninja2/tests/Debug/test_moe_down_project_policy.exe")
  set_tests_properties([=[test_moe_down_project_policy]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;340;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_moe_down_project_policy]=] "D:/rawrxd/build-ninja2/tests/Release/test_moe_down_project_policy.exe")
  set_tests_properties([=[test_moe_down_project_policy]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;340;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_moe_down_project_policy]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_moe_down_project_policy.exe")
  set_tests_properties([=[test_moe_down_project_policy]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;340;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_moe_down_project_policy]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_moe_plan_row_mixture_pack_cache]=] "D:/rawrxd/build-ninja2/tests/Debug/test_moe_plan_row_mixture_pack_cache.exe")
  set_tests_properties([=[test_moe_plan_row_mixture_pack_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;348;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_moe_plan_row_mixture_pack_cache]=] "D:/rawrxd/build-ninja2/tests/Release/test_moe_plan_row_mixture_pack_cache.exe")
  set_tests_properties([=[test_moe_plan_row_mixture_pack_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;348;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_moe_plan_row_mixture_pack_cache]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_moe_plan_row_mixture_pack_cache.exe")
  set_tests_properties([=[test_moe_plan_row_mixture_pack_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;348;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_moe_plan_row_mixture_pack_cache]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_moe_batched_down_project]=] "D:/rawrxd/build-ninja2/tests/Debug/test_moe_batched_down_project.exe")
  set_tests_properties([=[test_moe_batched_down_project]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;356;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_moe_batched_down_project]=] "D:/rawrxd/build-ninja2/tests/Release/test_moe_batched_down_project.exe")
  set_tests_properties([=[test_moe_batched_down_project]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;356;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_moe_batched_down_project]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_moe_batched_down_project.exe")
  set_tests_properties([=[test_moe_batched_down_project]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;356;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_moe_batched_down_project]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_moe_pack_hud_metrics]=] "D:/rawrxd/build-ninja2/tests/Debug/test_moe_pack_hud_metrics.exe")
  set_tests_properties([=[test_moe_pack_hud_metrics]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;364;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_moe_pack_hud_metrics]=] "D:/rawrxd/build-ninja2/tests/Release/test_moe_pack_hud_metrics.exe")
  set_tests_properties([=[test_moe_pack_hud_metrics]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;364;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_moe_pack_hud_metrics]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_moe_pack_hud_metrics.exe")
  set_tests_properties([=[test_moe_pack_hud_metrics]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;364;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_moe_pack_hud_metrics]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_basic_profiler]=] "D:/rawrxd/build-ninja2/tests/Debug/test_basic_profiler.exe")
  set_tests_properties([=[test_basic_profiler]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;384;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_basic_profiler]=] "D:/rawrxd/build-ninja2/tests/Release/test_basic_profiler.exe")
  set_tests_properties([=[test_basic_profiler]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;384;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_basic_profiler]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_basic_profiler.exe")
  set_tests_properties([=[test_basic_profiler]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;384;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_basic_profiler]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_batch3_profiler_smoke]=] "D:/rawrxd/build-ninja2/tests/Debug/test_batch3_profiler_smoke.exe")
  set_tests_properties([=[test_batch3_profiler_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;397;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_batch3_profiler_smoke]=] "D:/rawrxd/build-ninja2/tests/Release/test_batch3_profiler_smoke.exe")
  set_tests_properties([=[test_batch3_profiler_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;397;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_batch3_profiler_smoke]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_batch3_profiler_smoke.exe")
  set_tests_properties([=[test_batch3_profiler_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;397;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_batch3_profiler_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_state_subscription_engine_smoke]=] "D:/rawrxd/build-ninja2/tests/Debug/test_state_subscription_engine_smoke.exe")
  set_tests_properties([=[test_state_subscription_engine_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;414;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_state_subscription_engine_smoke]=] "D:/rawrxd/build-ninja2/tests/Release/test_state_subscription_engine_smoke.exe")
  set_tests_properties([=[test_state_subscription_engine_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;414;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_state_subscription_engine_smoke]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_state_subscription_engine_smoke.exe")
  set_tests_properties([=[test_state_subscription_engine_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;414;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_state_subscription_engine_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_ai_execution_guardrails_smoke]=] "D:/rawrxd/build-ninja2/tests/Debug/test_ai_execution_guardrails_smoke.exe")
  set_tests_properties([=[test_ai_execution_guardrails_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;432;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_ai_execution_guardrails_smoke]=] "D:/rawrxd/build-ninja2/tests/Release/test_ai_execution_guardrails_smoke.exe")
  set_tests_properties([=[test_ai_execution_guardrails_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;432;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_ai_execution_guardrails_smoke]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_ai_execution_guardrails_smoke.exe")
  set_tests_properties([=[test_ai_execution_guardrails_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;432;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_ai_execution_guardrails_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_ai_execution_guardrails_chaos]=] "D:/rawrxd/build-ninja2/tests/Debug/test_ai_execution_guardrails_chaos.exe")
  set_tests_properties([=[test_ai_execution_guardrails_chaos]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;450;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_ai_execution_guardrails_chaos]=] "D:/rawrxd/build-ninja2/tests/Release/test_ai_execution_guardrails_chaos.exe")
  set_tests_properties([=[test_ai_execution_guardrails_chaos]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;450;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_ai_execution_guardrails_chaos]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_ai_execution_guardrails_chaos.exe")
  set_tests_properties([=[test_ai_execution_guardrails_chaos]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;450;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_ai_execution_guardrails_chaos]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_safe_inference_session_integration]=] "D:/rawrxd/build-ninja2/tests/Debug/test_safe_inference_session_integration.exe")
  set_tests_properties([=[test_safe_inference_session_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;469;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_safe_inference_session_integration]=] "D:/rawrxd/build-ninja2/tests/Release/test_safe_inference_session_integration.exe")
  set_tests_properties([=[test_safe_inference_session_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;469;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_safe_inference_session_integration]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_safe_inference_session_integration.exe")
  set_tests_properties([=[test_safe_inference_session_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;469;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_safe_inference_session_integration]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_kv_cache_ownership]=] "D:/rawrxd/build-ninja2/tests/Debug/test_kv_cache_ownership.exe")
  set_tests_properties([=[test_kv_cache_ownership]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;492;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_kv_cache_ownership]=] "D:/rawrxd/build-ninja2/tests/Release/test_kv_cache_ownership.exe")
  set_tests_properties([=[test_kv_cache_ownership]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;492;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_kv_cache_ownership]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_kv_cache_ownership.exe")
  set_tests_properties([=[test_kv_cache_ownership]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;492;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_kv_cache_ownership]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_speculative_pipeline]=] "D:/rawrxd/build-ninja2/tests/Debug/test_speculative_pipeline.exe")
  set_tests_properties([=[test_speculative_pipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;511;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_speculative_pipeline]=] "D:/rawrxd/build-ninja2/tests/Release/test_speculative_pipeline.exe")
  set_tests_properties([=[test_speculative_pipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;511;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_speculative_pipeline]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_speculative_pipeline.exe")
  set_tests_properties([=[test_speculative_pipeline]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;511;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_speculative_pipeline]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_int4kv_bridge_integration]=] "D:/rawrxd/build-ninja2/tests/Debug/test_int4kv_bridge_integration.exe")
  set_tests_properties([=[test_int4kv_bridge_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;537;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_int4kv_bridge_integration]=] "D:/rawrxd/build-ninja2/tests/Release/test_int4kv_bridge_integration.exe")
  set_tests_properties([=[test_int4kv_bridge_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;537;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_int4kv_bridge_integration]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_int4kv_bridge_integration.exe")
  set_tests_properties([=[test_int4kv_bridge_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;537;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_int4kv_bridge_integration]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_iq2m_dequant_kernel]=] "D:/rawrxd/build-ninja2/tests/Debug/test_iq2m_dequant_kernel.exe")
  set_tests_properties([=[test_iq2m_dequant_kernel]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;559;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_iq2m_dequant_kernel]=] "D:/rawrxd/build-ninja2/tests/Release/test_iq2m_dequant_kernel.exe")
  set_tests_properties([=[test_iq2m_dequant_kernel]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;559;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_iq2m_dequant_kernel]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_iq2m_dequant_kernel.exe")
  set_tests_properties([=[test_iq2m_dequant_kernel]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;559;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_iq2m_dequant_kernel]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_extension_host]=] "D:/rawrxd/build-ninja2/tests/Debug/test_extension_host.exe")
  set_tests_properties([=[test_extension_host]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;589;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_extension_host]=] "D:/rawrxd/build-ninja2/tests/Release/test_extension_host.exe")
  set_tests_properties([=[test_extension_host]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;589;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_extension_host]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_extension_host.exe")
  set_tests_properties([=[test_extension_host]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;589;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_extension_host]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[extension_host_smoke_test]=] "D:/rawrxd/build-ninja2/tests/Debug/extension_host_smoke_test.exe")
  set_tests_properties([=[extension_host_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;627;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[extension_host_smoke_test]=] "D:/rawrxd/build-ninja2/tests/Release/extension_host_smoke_test.exe")
  set_tests_properties([=[extension_host_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;627;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[extension_host_smoke_test]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/extension_host_smoke_test.exe")
  set_tests_properties([=[extension_host_smoke_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;627;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[extension_host_smoke_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[batch4_ipc_spec_ast_arb_smoke]=] "D:/rawrxd/build-ninja2/bin/Debug/batch4_ipc_spec_ast_arb_smoke.exe")
  set_tests_properties([=[batch4_ipc_spec_ast_arb_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;652;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[batch4_ipc_spec_ast_arb_smoke]=] "D:/rawrxd/build-ninja2/bin/Release/batch4_ipc_spec_ast_arb_smoke.exe")
  set_tests_properties([=[batch4_ipc_spec_ast_arb_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;652;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[batch4_ipc_spec_ast_arb_smoke]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/batch4_ipc_spec_ast_arb_smoke.exe")
  set_tests_properties([=[batch4_ipc_spec_ast_arb_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;652;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[batch4_ipc_spec_ast_arb_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[autocomplete_kernel_wire_smoke]=] "D:/rawrxd/build-ninja2/bin/Debug/autocomplete_kernel_wire_smoke.exe")
  set_tests_properties([=[autocomplete_kernel_wire_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;675;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[autocomplete_kernel_wire_smoke]=] "D:/rawrxd/build-ninja2/bin/Release/autocomplete_kernel_wire_smoke.exe")
  set_tests_properties([=[autocomplete_kernel_wire_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;675;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[autocomplete_kernel_wire_smoke]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/autocomplete_kernel_wire_smoke.exe")
  set_tests_properties([=[autocomplete_kernel_wire_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;675;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[autocomplete_kernel_wire_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[cross_repo_router_smoke]=] "D:/rawrxd/build-ninja2/bin/Debug/cross_repo_router_smoke.exe")
  set_tests_properties([=[cross_repo_router_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;714;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[cross_repo_router_smoke]=] "D:/rawrxd/build-ninja2/bin/Release/cross_repo_router_smoke.exe")
  set_tests_properties([=[cross_repo_router_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;714;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[cross_repo_router_smoke]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/cross_repo_router_smoke.exe")
  set_tests_properties([=[cross_repo_router_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;714;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[cross_repo_router_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[autocomplete_p95_latency_harness]=] "D:/rawrxd/build-ninja2/bin/Debug/autocomplete_p95_latency_harness.exe")
  set_tests_properties([=[autocomplete_p95_latency_harness]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;737;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[autocomplete_p95_latency_harness]=] "D:/rawrxd/build-ninja2/bin/Release/autocomplete_p95_latency_harness.exe")
  set_tests_properties([=[autocomplete_p95_latency_harness]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;737;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[autocomplete_p95_latency_harness]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/autocomplete_p95_latency_harness.exe")
  set_tests_properties([=[autocomplete_p95_latency_harness]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;737;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[autocomplete_p95_latency_harness]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[titan_rx_hotpath_smoke]=] "D:/rawrxd/build-ninja2/bin/Debug/titan_rx_hotpath_smoke.exe")
  set_tests_properties([=[titan_rx_hotpath_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;759;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[titan_rx_hotpath_smoke]=] "D:/rawrxd/build-ninja2/bin/Release/titan_rx_hotpath_smoke.exe")
  set_tests_properties([=[titan_rx_hotpath_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;759;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[titan_rx_hotpath_smoke]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/titan_rx_hotpath_smoke.exe")
  set_tests_properties([=[titan_rx_hotpath_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;759;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[titan_rx_hotpath_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_sovereign_kernels]=] "D:/rawrxd/build-ninja2/tests/Debug/test_sovereign_kernels.exe")
  set_tests_properties([=[test_sovereign_kernels]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;805;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_sovereign_kernels]=] "D:/rawrxd/build-ninja2/tests/Release/test_sovereign_kernels.exe")
  set_tests_properties([=[test_sovereign_kernels]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;805;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_sovereign_kernels]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_sovereign_kernels.exe")
  set_tests_properties([=[test_sovereign_kernels]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;805;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_sovereign_kernels]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[bench_sovereign_kernels]=] "D:/rawrxd/build-ninja2/tests/Debug/bench_sovereign_kernels.exe")
  set_tests_properties([=[bench_sovereign_kernels]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;838;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[bench_sovereign_kernels]=] "D:/rawrxd/build-ninja2/tests/Release/bench_sovereign_kernels.exe")
  set_tests_properties([=[bench_sovereign_kernels]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;838;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[bench_sovereign_kernels]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/bench_sovereign_kernels.exe")
  set_tests_properties([=[bench_sovereign_kernels]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;838;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[bench_sovereign_kernels]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[sovereign_baseline_regression]=] "D:/rawrxd/build-ninja2/tests/Debug/sovereign_baseline_regression.exe")
  set_tests_properties([=[sovereign_baseline_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;858;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[sovereign_baseline_regression]=] "D:/rawrxd/build-ninja2/tests/Release/sovereign_baseline_regression.exe")
  set_tests_properties([=[sovereign_baseline_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;858;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[sovereign_baseline_regression]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/sovereign_baseline_regression.exe")
  set_tests_properties([=[sovereign_baseline_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;858;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[sovereign_baseline_regression]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_production_regression]=] "D:/rawrxd/build-ninja2/tests/Debug/test_production_regression.exe")
  set_tests_properties([=[test_production_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;893;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_production_regression]=] "D:/rawrxd/build-ninja2/tests/Release/test_production_regression.exe")
  set_tests_properties([=[test_production_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;893;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_production_regression]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_production_regression.exe")
  set_tests_properties([=[test_production_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;893;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_production_regression]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[agentic_hello_world]=] "D:/rawrxd/build-ninja2/bin/Debug/agentic_hello_world.exe")
  set_tests_properties([=[agentic_hello_world]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;912;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[agentic_hello_world]=] "D:/rawrxd/build-ninja2/bin/Release/agentic_hello_world.exe")
  set_tests_properties([=[agentic_hello_world]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;912;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[agentic_hello_world]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/agentic_hello_world.exe")
  set_tests_properties([=[agentic_hello_world]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;912;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[agentic_hello_world]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[titan_model_load_smoke]=] "D:/rawrxd/build-ninja2/bin/Debug/titan_model_load_smoke.exe")
  set_tests_properties([=[titan_model_load_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;930;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[titan_model_load_smoke]=] "D:/rawrxd/build-ninja2/bin/Release/titan_model_load_smoke.exe")
  set_tests_properties([=[titan_model_load_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;930;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[titan_model_load_smoke]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/titan_model_load_smoke.exe")
  set_tests_properties([=[titan_model_load_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;930;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[titan_model_load_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_instructions_provider]=] "D:/rawrxd/build-ninja2/tests/Debug/test_instructions_provider.exe")
  set_tests_properties([=[test_instructions_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;951;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_instructions_provider]=] "D:/rawrxd/build-ninja2/tests/Release/test_instructions_provider.exe")
  set_tests_properties([=[test_instructions_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;951;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_instructions_provider]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_instructions_provider.exe")
  set_tests_properties([=[test_instructions_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;951;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_instructions_provider]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[sovereign_assembler_smoke]=] "D:/rawrxd/build-ninja2/bin/Debug/sovereign_assembler_smoke.exe")
  set_tests_properties([=[sovereign_assembler_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;956;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[sovereign_assembler_smoke]=] "D:/rawrxd/build-ninja2/bin/Release/sovereign_assembler_smoke.exe")
  set_tests_properties([=[sovereign_assembler_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;956;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[sovereign_assembler_smoke]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/sovereign_assembler_smoke.exe")
  set_tests_properties([=[sovereign_assembler_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;956;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[sovereign_assembler_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[rawrengine_copilot_smoke]=] "D:/rawrxd/build-ninja2/bin/Debug/RawrEngine.exe" "--copilot-smoke")
  set_tests_properties([=[rawrengine_copilot_smoke]=] PROPERTIES  LABELS "smoke;copilot;inference" TIMEOUT "600" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;962;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[rawrengine_copilot_smoke]=] "D:/rawrxd/build-ninja2/bin/Release/RawrEngine.exe" "--copilot-smoke")
  set_tests_properties([=[rawrengine_copilot_smoke]=] PROPERTIES  LABELS "smoke;copilot;inference" TIMEOUT "600" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;962;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[rawrengine_copilot_smoke]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/RawrEngine.exe" "--copilot-smoke")
  set_tests_properties([=[rawrengine_copilot_smoke]=] PROPERTIES  LABELS "smoke;copilot;inference" TIMEOUT "600" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;962;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[rawrengine_copilot_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[win32ide_agentic_smoke]=] "D:/rawrxd/build-ninja2/bin/Debug/RawrXD-Win32IDE.exe" "--agentic-smoke")
  set_tests_properties([=[win32ide_agentic_smoke]=] PROPERTIES  LABELS "smoke;agentic;win32ide" TIMEOUT "600" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;972;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[win32ide_agentic_smoke]=] "D:/rawrxd/build-ninja2/bin/Release/RawrXD-Win32IDE.exe" "--agentic-smoke")
  set_tests_properties([=[win32ide_agentic_smoke]=] PROPERTIES  LABELS "smoke;agentic;win32ide" TIMEOUT "600" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;972;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[win32ide_agentic_smoke]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/RawrXD-Win32IDE.exe" "--agentic-smoke")
  set_tests_properties([=[win32ide_agentic_smoke]=] PROPERTIES  LABELS "smoke;agentic;win32ide" TIMEOUT "600" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;972;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[win32ide_agentic_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[win32ide_high_pressure_ui]=] "pwsh" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "D:/rawrxd/tests/smoke/win32ide_high_pressure_ui.ps1" "-ExePath" "D:/rawrxd/build-ninja2/bin/Debug/RawrXD-Win32IDE.exe")
  set_tests_properties([=[win32ide_high_pressure_ui]=] PROPERTIES  LABELS "smoke;stress;win32ide;lsp;model" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;980;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[win32ide_high_pressure_ui]=] "pwsh" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "D:/rawrxd/tests/smoke/win32ide_high_pressure_ui.ps1" "-ExePath" "D:/rawrxd/build-ninja2/bin/Release/RawrXD-Win32IDE.exe")
  set_tests_properties([=[win32ide_high_pressure_ui]=] PROPERTIES  LABELS "smoke;stress;win32ide;lsp;model" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;980;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[win32ide_high_pressure_ui]=] "pwsh" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "D:/rawrxd/tests/smoke/win32ide_high_pressure_ui.ps1" "-ExePath" "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/RawrXD-Win32IDE.exe")
  set_tests_properties([=[win32ide_high_pressure_ui]=] PROPERTIES  LABELS "smoke;stress;win32ide;lsp;model" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;980;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[win32ide_high_pressure_ui]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[ollama_stream_routing_env_smoke]=] "pwsh" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "D:/rawrxd/scripts/Test-OllamaStreamRoutingEnv.ps1")
  set_tests_properties([=[ollama_stream_routing_env_smoke]=] PROPERTIES  LABELS "smoke;agentic;ollama" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;993;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[ollama_stream_routing_env_smoke]=] "pwsh" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "D:/rawrxd/scripts/Test-OllamaStreamRoutingEnv.ps1")
  set_tests_properties([=[ollama_stream_routing_env_smoke]=] PROPERTIES  LABELS "smoke;agentic;ollama" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;993;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[ollama_stream_routing_env_smoke]=] "pwsh" "-NoProfile" "-ExecutionPolicy" "Bypass" "-File" "D:/rawrxd/scripts/Test-OllamaStreamRoutingEnv.ps1")
  set_tests_properties([=[ollama_stream_routing_env_smoke]=] PROPERTIES  LABELS "smoke;agentic;ollama" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;993;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[ollama_stream_routing_env_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[production_readiness_expansion_quality_gate]=] "C:/Program Files/CMake/bin/cmake.exe" "-D" "BINARY_DIR=D:/rawrxd/build-ninja2" "-D" "CONFIG=Debug" "-D" "BUILD_TARGET=self_test_gate" "-P" "D:/rawrxd/tests/smoke/build_target_with_retry.cmake")
  set_tests_properties([=[production_readiness_expansion_quality_gate]=] PROPERTIES  LABELS "quality-gate;production;aggregate" TIMEOUT "1800" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;1006;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[production_readiness_expansion_quality_gate]=] "C:/Program Files/CMake/bin/cmake.exe" "-D" "BINARY_DIR=D:/rawrxd/build-ninja2" "-D" "CONFIG=Release" "-D" "BUILD_TARGET=self_test_gate" "-P" "D:/rawrxd/tests/smoke/build_target_with_retry.cmake")
  set_tests_properties([=[production_readiness_expansion_quality_gate]=] PROPERTIES  LABELS "quality-gate;production;aggregate" TIMEOUT "1800" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;1006;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[production_readiness_expansion_quality_gate]=] "C:/Program Files/CMake/bin/cmake.exe" "-D" "BINARY_DIR=D:/rawrxd/build-ninja2" "-D" "CONFIG=RelWithDebInfo" "-D" "BUILD_TARGET=self_test_gate" "-P" "D:/rawrxd/tests/smoke/build_target_with_retry.cmake")
  set_tests_properties([=[production_readiness_expansion_quality_gate]=] PROPERTIES  LABELS "quality-gate;production;aggregate" TIMEOUT "1800" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;1006;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[production_readiness_expansion_quality_gate]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_model_loader_streamer_smoke]=] "D:/rawrxd/build-ninja2/tests/Debug/test_model_loader_streamer_smoke.exe")
  set_tests_properties([=[test_model_loader_streamer_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;1046;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_model_loader_streamer_smoke]=] "D:/rawrxd/build-ninja2/tests/Release/test_model_loader_streamer_smoke.exe")
  set_tests_properties([=[test_model_loader_streamer_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;1046;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_model_loader_streamer_smoke]=] "D:/rawrxd/build-ninja2/tests/RelWithDebInfo/test_model_loader_streamer_smoke.exe")
  set_tests_properties([=[test_model_loader_streamer_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;1046;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
else()
  add_test([=[test_model_loader_streamer_smoke]=] NOT_AVAILABLE)
endif()
subdirs("../_deps/googletest-build")
