# CMake generated Testfile for 
# Source directory: F:/~dev/rawrxd
# Build directory: F:/~dev/rawrxd/certbuild
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("test_llama_native" "F:/~dev/rawrxd/certbuild/tests/Debug/test_llama_native.exe")
  set_tests_properties("test_llama_native" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;14967;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("test_llama_native" "F:/~dev/rawrxd/certbuild/tests/Release/test_llama_native.exe")
  set_tests_properties("test_llama_native" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;14967;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("test_llama_native" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/test_llama_native.exe")
  set_tests_properties("test_llama_native" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;14967;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("test_llama_native" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/test_llama_native.exe")
  set_tests_properties("test_llama_native" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;14967;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("test_llama_native" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_runtime_validation" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_runtime_validation.exe")
  set_tests_properties("k2_runtime_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15019;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_runtime_validation" "F:/~dev/rawrxd/certbuild/tests/Release/k2_runtime_validation.exe")
  set_tests_properties("k2_runtime_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15019;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_runtime_validation" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_runtime_validation.exe")
  set_tests_properties("k2_runtime_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15019;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_runtime_validation" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_runtime_validation.exe")
  set_tests_properties("k2_runtime_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15019;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_runtime_validation" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("test_q4k_decoder" "F:/~dev/rawrxd/certbuild/tests/Debug/test_q4k_decoder.exe")
  set_tests_properties("test_q4k_decoder" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15031;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("test_q4k_decoder" "F:/~dev/rawrxd/certbuild/tests/Release/test_q4k_decoder.exe")
  set_tests_properties("test_q4k_decoder" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15031;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("test_q4k_decoder" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/test_q4k_decoder.exe")
  set_tests_properties("test_q4k_decoder" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15031;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("test_q4k_decoder" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/test_q4k_decoder.exe")
  set_tests_properties("test_q4k_decoder" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15031;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("test_q4k_decoder" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_native_smoke_test" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_native_smoke_test.exe")
  set_tests_properties("k2_native_smoke_test" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15088;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_native_smoke_test" "F:/~dev/rawrxd/certbuild/tests/Release/k2_native_smoke_test.exe")
  set_tests_properties("k2_native_smoke_test" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15088;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_native_smoke_test" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_native_smoke_test.exe")
  set_tests_properties("k2_native_smoke_test" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15088;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_native_smoke_test" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_native_smoke_test.exe")
  set_tests_properties("k2_native_smoke_test" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15088;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_native_smoke_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_002_tensor_streaming" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_002_tensor_streaming.exe")
  set_tests_properties("k2_002_tensor_streaming" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15137;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_002_tensor_streaming" "F:/~dev/rawrxd/certbuild/tests/Release/k2_002_tensor_streaming.exe")
  set_tests_properties("k2_002_tensor_streaming" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15137;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_002_tensor_streaming" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_002_tensor_streaming.exe")
  set_tests_properties("k2_002_tensor_streaming" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15137;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_002_tensor_streaming" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_002_tensor_streaming.exe")
  set_tests_properties("k2_002_tensor_streaming" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15137;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_002_tensor_streaming" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_003_layer_execution" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_003_layer_execution.exe")
  set_tests_properties("k2_003_layer_execution" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15186;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_003_layer_execution" "F:/~dev/rawrxd/certbuild/tests/Release/k2_003_layer_execution.exe")
  set_tests_properties("k2_003_layer_execution" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15186;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_003_layer_execution" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_003_layer_execution.exe")
  set_tests_properties("k2_003_layer_execution" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15186;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_003_layer_execution" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_003_layer_execution.exe")
  set_tests_properties("k2_003_layer_execution" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15186;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_003_layer_execution" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_003b_native_gemv_validation" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_003b_native_gemv_validation.exe")
  set_tests_properties("k2_003b_native_gemv_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15200;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_003b_native_gemv_validation" "F:/~dev/rawrxd/certbuild/tests/Release/k2_003b_native_gemv_validation.exe")
  set_tests_properties("k2_003b_native_gemv_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15200;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_003b_native_gemv_validation" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_003b_native_gemv_validation.exe")
  set_tests_properties("k2_003b_native_gemv_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15200;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_003b_native_gemv_validation" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_003b_native_gemv_validation.exe")
  set_tests_properties("k2_003b_native_gemv_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15200;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_003b_native_gemv_validation" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_003c_single_layer_forward" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_003c_single_layer_forward.exe")
  set_tests_properties("k2_003c_single_layer_forward" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15214;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_003c_single_layer_forward" "F:/~dev/rawrxd/certbuild/tests/Release/k2_003c_single_layer_forward.exe")
  set_tests_properties("k2_003c_single_layer_forward" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15214;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_003c_single_layer_forward" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_003c_single_layer_forward.exe")
  set_tests_properties("k2_003c_single_layer_forward" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15214;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_003c_single_layer_forward" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_003c_single_layer_forward.exe")
  set_tests_properties("k2_003c_single_layer_forward" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15214;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_003c_single_layer_forward" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_004_bounded_prefill" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_004_bounded_prefill.exe")
  set_tests_properties("k2_004_bounded_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15263;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_004_bounded_prefill" "F:/~dev/rawrxd/certbuild/tests/Release/k2_004_bounded_prefill.exe")
  set_tests_properties("k2_004_bounded_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15263;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_004_bounded_prefill" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_004_bounded_prefill.exe")
  set_tests_properties("k2_004_bounded_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15263;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_004_bounded_prefill" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_004_bounded_prefill.exe")
  set_tests_properties("k2_004_bounded_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15263;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_004_bounded_prefill" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_004_bounded_multi_layer_prefill" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_004_bounded_multi_layer_prefill.exe")
  set_tests_properties("k2_004_bounded_multi_layer_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15277;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_004_bounded_multi_layer_prefill" "F:/~dev/rawrxd/certbuild/tests/Release/k2_004_bounded_multi_layer_prefill.exe")
  set_tests_properties("k2_004_bounded_multi_layer_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15277;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_004_bounded_multi_layer_prefill" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_004_bounded_multi_layer_prefill.exe")
  set_tests_properties("k2_004_bounded_multi_layer_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15277;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_004_bounded_multi_layer_prefill" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_004_bounded_multi_layer_prefill.exe")
  set_tests_properties("k2_004_bounded_multi_layer_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15277;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_004_bounded_multi_layer_prefill" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_005_autoregressive_kv_cache" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_005_autoregressive_kv_cache.exe")
  set_tests_properties("k2_005_autoregressive_kv_cache" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15292;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_005_autoregressive_kv_cache" "F:/~dev/rawrxd/certbuild/tests/Release/k2_005_autoregressive_kv_cache.exe")
  set_tests_properties("k2_005_autoregressive_kv_cache" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15292;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_005_autoregressive_kv_cache" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_005_autoregressive_kv_cache.exe")
  set_tests_properties("k2_005_autoregressive_kv_cache" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15292;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_005_autoregressive_kv_cache" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_005_autoregressive_kv_cache.exe")
  set_tests_properties("k2_005_autoregressive_kv_cache" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15292;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_005_autoregressive_kv_cache" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_006_bounded_token_generation" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_006_bounded_token_generation.exe")
  set_tests_properties("k2_006_bounded_token_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15307;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_006_bounded_token_generation" "F:/~dev/rawrxd/certbuild/tests/Release/k2_006_bounded_token_generation.exe")
  set_tests_properties("k2_006_bounded_token_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15307;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_006_bounded_token_generation" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_006_bounded_token_generation.exe")
  set_tests_properties("k2_006_bounded_token_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15307;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_006_bounded_token_generation" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_006_bounded_token_generation.exe")
  set_tests_properties("k2_006_bounded_token_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15307;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_006_bounded_token_generation" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_007_real_output_projection" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_007_real_output_projection.exe")
  set_tests_properties("k2_007_real_output_projection" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15320;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_007_real_output_projection" "F:/~dev/rawrxd/certbuild/tests/Release/k2_007_real_output_projection.exe")
  set_tests_properties("k2_007_real_output_projection" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15320;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_007_real_output_projection" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_007_real_output_projection.exe")
  set_tests_properties("k2_007_real_output_projection" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15320;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_007_real_output_projection" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_007_real_output_projection.exe")
  set_tests_properties("k2_007_real_output_projection" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15320;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_007_real_output_projection" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_007b_projection_logits_interface" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_007b_projection_logits_interface.exe")
  set_tests_properties("k2_007b_projection_logits_interface" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15338;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_007b_projection_logits_interface" "F:/~dev/rawrxd/certbuild/tests/Release/k2_007b_projection_logits_interface.exe")
  set_tests_properties("k2_007b_projection_logits_interface" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15338;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_007b_projection_logits_interface" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_007b_projection_logits_interface.exe")
  set_tests_properties("k2_007b_projection_logits_interface" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15338;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_007b_projection_logits_interface" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_007b_projection_logits_interface.exe")
  set_tests_properties("k2_007b_projection_logits_interface" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15338;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_007b_projection_logits_interface" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_008_end_to_end_semantic_generation" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_008_end_to_end_semantic_generation.exe")
  set_tests_properties("k2_008_end_to_end_semantic_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15355;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_008_end_to_end_semantic_generation" "F:/~dev/rawrxd/certbuild/tests/Release/k2_008_end_to_end_semantic_generation.exe")
  set_tests_properties("k2_008_end_to_end_semantic_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15355;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_008_end_to_end_semantic_generation" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_008_end_to_end_semantic_generation.exe")
  set_tests_properties("k2_008_end_to_end_semantic_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15355;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_008_end_to_end_semantic_generation" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_008_end_to_end_semantic_generation.exe")
  set_tests_properties("k2_008_end_to_end_semantic_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15355;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_008_end_to_end_semantic_generation" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_009_token_embedding_lookup" "F:/~dev/rawrxd/certbuild/tests/Debug/k2_009_token_embedding_lookup.exe")
  set_tests_properties("k2_009_token_embedding_lookup" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15372;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_009_token_embedding_lookup" "F:/~dev/rawrxd/certbuild/tests/Release/k2_009_token_embedding_lookup.exe")
  set_tests_properties("k2_009_token_embedding_lookup" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15372;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_009_token_embedding_lookup" "F:/~dev/rawrxd/certbuild/tests/MinSizeRel/k2_009_token_embedding_lookup.exe")
  set_tests_properties("k2_009_token_embedding_lookup" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15372;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_009_token_embedding_lookup" "F:/~dev/rawrxd/certbuild/tests/RelWithDebInfo/k2_009_token_embedding_lookup.exe")
  set_tests_properties("k2_009_token_embedding_lookup" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15372;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_009_token_embedding_lookup" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("git_safety_authority_cert" "F:/~dev/rawrxd/certbuild/bin/Debug/git_safety_authority_cert.exe")
  set_tests_properties("git_safety_authority_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;17585;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("git_safety_authority_cert" "F:/~dev/rawrxd/certbuild/bin/Release/git_safety_authority_cert.exe")
  set_tests_properties("git_safety_authority_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;17585;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("git_safety_authority_cert" "F:/~dev/rawrxd/certbuild/bin/MinSizeRel/git_safety_authority_cert.exe")
  set_tests_properties("git_safety_authority_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;17585;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("git_safety_authority_cert" "F:/~dev/rawrxd/certbuild/bin/RelWithDebInfo/git_safety_authority_cert.exe")
  set_tests_properties("git_safety_authority_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/rawrxd/certbuild" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;17585;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("git_safety_authority_cert" NOT_AVAILABLE)
endif()
subdirs("src/reverse_engineering")
subdirs("src/ceo")
subdirs("src/repository")
subdirs("src/generation")
subdirs("rguf_source")
