# CMake generated Testfile for 
# Source directory: D:/rawrxd
# Build directory: D:/rawrxd/build-ninja2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[smoke_test_measurement_integration]=] "D:/rawrxd/build-ninja2/bin/Debug/smoke_test_measurement_integration.exe")
  set_tests_properties([=[smoke_test_measurement_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6090;add_test;D:/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[smoke_test_measurement_integration]=] "D:/rawrxd/build-ninja2/bin/Release/smoke_test_measurement_integration.exe")
  set_tests_properties([=[smoke_test_measurement_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6090;add_test;D:/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[smoke_test_measurement_integration]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/smoke_test_measurement_integration.exe")
  set_tests_properties([=[smoke_test_measurement_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6090;add_test;D:/rawrxd/CMakeLists.txt;0;")
else()
  add_test([=[smoke_test_measurement_integration]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[e2e_integration_test]=] "D:/rawrxd/build-ninja2/bin/Debug/e2e_integration_test.exe")
  set_tests_properties([=[e2e_integration_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6106;add_test;D:/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[e2e_integration_test]=] "D:/rawrxd/build-ninja2/bin/Release/e2e_integration_test.exe")
  set_tests_properties([=[e2e_integration_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6106;add_test;D:/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[e2e_integration_test]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/e2e_integration_test.exe")
  set_tests_properties([=[e2e_integration_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6106;add_test;D:/rawrxd/CMakeLists.txt;0;")
else()
  add_test([=[e2e_integration_test]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[agent_workflow_orchestrator_smoke]=] "D:/rawrxd/build-ninja2/bin/Debug/agent_workflow_orchestrator_smoke.exe")
  set_tests_properties([=[agent_workflow_orchestrator_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6134;add_test;D:/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[agent_workflow_orchestrator_smoke]=] "D:/rawrxd/build-ninja2/bin/Release/agent_workflow_orchestrator_smoke.exe")
  set_tests_properties([=[agent_workflow_orchestrator_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6134;add_test;D:/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[agent_workflow_orchestrator_smoke]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/agent_workflow_orchestrator_smoke.exe")
  set_tests_properties([=[agent_workflow_orchestrator_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6134;add_test;D:/rawrxd/CMakeLists.txt;0;")
else()
  add_test([=[agent_workflow_orchestrator_smoke]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[RawrXD-GhostSoak]=] "D:/rawrxd/build-ninja2/bin/Debug/RawrXD-GhostSoak.exe" "--iterations" "200" "--max-inflight" "16" "--timeout-ms" "1500")
  set_tests_properties([=[RawrXD-GhostSoak]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6161;add_test;D:/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[RawrXD-GhostSoak]=] "D:/rawrxd/build-ninja2/bin/Release/RawrXD-GhostSoak.exe" "--iterations" "200" "--max-inflight" "16" "--timeout-ms" "1500")
  set_tests_properties([=[RawrXD-GhostSoak]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6161;add_test;D:/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[RawrXD-GhostSoak]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/RawrXD-GhostSoak.exe" "--iterations" "200" "--max-inflight" "16" "--timeout-ms" "1500")
  set_tests_properties([=[RawrXD-GhostSoak]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6161;add_test;D:/rawrxd/CMakeLists.txt;0;")
else()
  add_test([=[RawrXD-GhostSoak]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_api_stress]=] "D:/rawrxd/build-ninja2/bin/Debug/test_api_stress.exe")
  set_tests_properties([=[test_api_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6184;add_test;D:/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_api_stress]=] "D:/rawrxd/build-ninja2/bin/Release/test_api_stress.exe")
  set_tests_properties([=[test_api_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6184;add_test;D:/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_api_stress]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/test_api_stress.exe")
  set_tests_properties([=[test_api_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6184;add_test;D:/rawrxd/CMakeLists.txt;0;")
else()
  add_test([=[test_api_stress]=] NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test([=[test_model_stress]=] "D:/rawrxd/build-ninja2/bin/Debug/test_model_stress.exe")
  set_tests_properties([=[test_model_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6206;add_test;D:/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test([=[test_model_stress]=] "D:/rawrxd/build-ninja2/bin/Release/test_model_stress.exe")
  set_tests_properties([=[test_model_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6206;add_test;D:/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test([=[test_model_stress]=] "D:/rawrxd/build-ninja2/bin/RelWithDebInfo/test_model_stress.exe")
  set_tests_properties([=[test_model_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;6206;add_test;D:/rawrxd/CMakeLists.txt;0;")
else()
  add_test([=[test_model_stress]=] NOT_AVAILABLE)
endif()
subdirs("src")
subdirs("src/reverse_engineering")
subdirs("src/tools/tokenizer_roundtrip_test")
subdirs("tests")
subdirs("src/tools")
