# CMake generated Testfile for 
# Source directory: D:/rawrxd/tests
# Build directory: D:/rawrxd/build-ninja/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_ai_completions]=] "D:/rawrxd/build-ninja/tests/test_ai_completions.exe")
set_tests_properties([=[test_ai_completions]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;125;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_llm_connectivity]=] "D:/rawrxd/build-ninja/tests/test_llm_connectivity.exe")
set_tests_properties([=[test_llm_connectivity]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;142;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_tool_registry]=] "D:/rawrxd/build-ninja/tests/test_tool_registry.exe")
set_tests_properties([=[test_tool_registry]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;151;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_voice_processor]=] "D:/rawrxd/build-ninja/tests/test_voice_processor.exe")
set_tests_properties([=[test_voice_processor]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;161;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_zero_retention_manager]=] "D:/rawrxd/build-ninja/tests/test_zero_retention_manager.exe")
set_tests_properties([=[test_zero_retention_manager]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;171;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_gui_components]=] "D:/rawrxd/build-ninja/tests/test_gui_components.exe")
set_tests_properties([=[test_gui_components]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;180;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_semantic_diff_analyzer]=] "D:/rawrxd/build-ninja/tests/test_semantic_diff_analyzer.exe")
set_tests_properties([=[test_semantic_diff_analyzer]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;189;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_ai_merge_resolver]=] "D:/rawrxd/build-ninja/tests/test_ai_merge_resolver.exe")
set_tests_properties([=[test_ai_merge_resolver]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;201;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_sandboxed_terminal]=] "D:/rawrxd/build-ninja/tests/test_sandboxed_terminal.exe")
set_tests_properties([=[test_sandboxed_terminal]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;210;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_agentic_file_operations]=] "D:/rawrxd/build-ninja/tests/test_agentic_file_operations.exe")
set_tests_properties([=[test_agentic_file_operations]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;219;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[model_registry_test]=] "D:/rawrxd/build-ninja/tests/model_registry_test.exe")
set_tests_properties([=[model_registry_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;228;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_gguf_integration]=] "D:/rawrxd/build-ninja/tests/test_gguf_integration.exe")
set_tests_properties([=[test_gguf_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;246;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_swarm_scheduler_pin]=] "D:/rawrxd/build-ninja/tests/test_swarm_scheduler_pin.exe")
set_tests_properties([=[test_swarm_scheduler_pin]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;259;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[deterministic_replay_gate]=] "D:/rawrxd/build-ninja/tests/deterministic_replay_gate.exe")
set_tests_properties([=[deterministic_replay_gate]=] PROPERTIES  LABELS "deterministic;ide;ghosttext" TIMEOUT "120" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;274;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[VAL063_InferenceGatewayHarness]=] "D:/rawrxd/build-ninja/tests/VAL063_InferenceGatewayHarness.exe")
set_tests_properties([=[VAL063_InferenceGatewayHarness]=] PROPERTIES  LABELS "certification;val-063;inference;gateway" TIMEOUT "300" _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;310;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_swarm_expert_heatmap_stress]=] "D:/rawrxd/build-ninja/tests/test_swarm_expert_heatmap_stress.exe")
set_tests_properties([=[test_swarm_expert_heatmap_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;327;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_mixture_reference]=] "D:/rawrxd/build-ninja/tests/test_moe_mixture_reference.exe")
set_tests_properties([=[test_moe_mixture_reference]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;335;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_down_project_policy]=] "D:/rawrxd/build-ninja/tests/test_moe_down_project_policy.exe")
set_tests_properties([=[test_moe_down_project_policy]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;343;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_moe_plan_row_mixture_pack_cache]=] "D:/rawrxd/build-ninja/tests/test_moe_plan_row_mixture_pack_cache.exe")
set_tests_properties([=[test_moe_plan_row_mixture_pack_cache]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;351;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_basic_profiler]=] "D:/rawrxd/build-ninja/tests/test_basic_profiler.exe")
set_tests_properties([=[test_basic_profiler]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;370;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_batch3_profiler_smoke]=] "D:/rawrxd/build-ninja/tests/test_batch3_profiler_smoke.exe")
set_tests_properties([=[test_batch3_profiler_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;382;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_production_regression]=] "D:/rawrxd/build-ninja/tests/test_production_regression.exe")
set_tests_properties([=[test_production_regression]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;417;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_instructions_provider]=] "D:/rawrxd/build-ninja/tests/test_instructions_provider.exe")
set_tests_properties([=[test_instructions_provider]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;438;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_model_loader_streamer_smoke]=] "D:/rawrxd/build-ninja/tests/test_model_loader_streamer_smoke.exe")
set_tests_properties([=[test_model_loader_streamer_smoke]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;537;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_predictive_memory_subsystem]=] "D:/rawrxd/build-ninja/tests/test_predictive_memory_subsystem.exe")
set_tests_properties([=[test_predictive_memory_subsystem]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;567;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[smoke_core]=] "D:/rawrxd/build-ninja/tests/smoke_core.exe")
set_tests_properties([=[smoke_core]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;578;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_rmsnorm_avx2]=] "D:/rawrxd/build-ninja/tests/test_rmsnorm_avx2.exe")
set_tests_properties([=[test_rmsnorm_avx2]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;599;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_softmax_avx2]=] "D:/rawrxd/build-ninja/tests/test_softmax_avx2.exe")
set_tests_properties([=[test_softmax_avx2]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;620;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[sovereign_integrated_test]=] "D:/rawrxd/build-ninja/bin/sovereign_integrated_test.exe")
set_tests_properties([=[sovereign_integrated_test]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;648;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
add_test([=[test_agentic_supervisor]=] "D:/rawrxd/build-ninja/bin/test_agentic_supervisor.exe")
set_tests_properties([=[test_agentic_supervisor]=] PROPERTIES  _BACKTRACE_TRIPLES "D:/rawrxd/tests/CMakeLists.txt;671;add_test;D:/rawrxd/tests/CMakeLists.txt;0;")
