#pragma once
#include <string>
#include <vector>

struct CompilerInfo {
    std::string name;
    std::string displayName;
    std::string version;
    std::string category;
    std::string path;
};

inline std::vector<CompilerInfo> GetAllCompilers() {
    return {
        {"universal_compiler_runtime", "Universal Compiler Runtime", "1.0", "Core", "d:\rawrxd\compilers\final_69_working\universal_compiler_runtime.exe"},
        {"bash_compiler_from_scratch", "Bash Compiler", "1.0", "Shell", "d:\rawrxd\compilers\final_69_working\bash_compiler_from_scratch.exe"},
        {"powershell_compiler_from_scratch", "PowerShell Compiler", "1.0", "Shell", "d:\rawrxd\compilers\final_69_working\powershell_compiler_from_scratch.exe"},
        {"eon_bootstrap_compiler", "EON Bootstrap Compiler", "1.0", "Language", "d:\rawrxd\compilers\final_69_working\eon_bootstrap_compiler.exe"},
        {"omega_pro", "Omega Pro Compiler", "1.0", "Omega", "d:\rawrxd\compilers\final_69_working\omega_pro.exe"},
        {"masm_ide_compiler", "MASM IDE Compiler", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\masm_ide_compiler.exe"},
        {"agentic_compiler", "Agentic Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\agentic_compiler.exe"},
        {"rawrxd_core_compiler", "RawrXD Core Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_core_compiler.exe"},
        {"rawrxd_ultimate_compiler", "RawrXD Ultimate Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_ultimate_compiler.exe"},
        {"rawrxd_master_compiler", "RawrXD Master Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_master_compiler.exe"},
        {"rawrxd_sovereign_compiler", "RawrXD Sovereign Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_sovereign_compiler.exe"},
        {"rawrxd_phase10_compiler", "RawrXD Phase 10 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase10_compiler.exe"},
        {"rawrxd_phase11_compiler", "RawrXD Phase 11 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase11_compiler.exe"},
        {"rawrxd_phase12_compiler", "RawrXD Phase 12 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase12_compiler.exe"},
        {"rawrxd_phase13_compiler", "RawrXD Phase 13 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase13_compiler.exe"},
        {"rawrxd_phase14_compiler", "RawrXD Phase 14 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase14_compiler.exe"},
        {"rawrxd_phase15_compiler", "RawrXD Phase 15 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase15_compiler.exe"},
        {"rawrxd_phase16_compiler", "RawrXD Phase 16 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase16_compiler.exe"},
        {"rawrxd_phase17_compiler", "RawrXD Phase 17 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase17_compiler.exe"},
        {"rawrxd_phase18_compiler", "RawrXD Phase 18 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase18_compiler.exe"},
        {"rawrxd_phase19_compiler", "RawrXD Phase 19 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase19_compiler.exe"},
        {"rawrxd_phase20_compiler", "RawrXD Phase 20 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase20_compiler.exe"},
        {"rawrxd_phase21_compiler", "RawrXD Phase 21 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase21_compiler.exe"},
        {"rawrxd_phase22_compiler", "RawrXD Phase 22 Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_phase22_compiler.exe"},
        {"universal_compiler_v2", "Universal Compiler Runtime v2", "2.0", "Core", "d:\rawrxd\compilers\final_69_working\universal_compiler_v2.exe"},
        {"universal_compiler_v3", "Universal Compiler Runtime v3", "3.0", "Core", "d:\rawrxd\compilers\final_69_working\universal_compiler_v3.exe"},
        {"universal_compiler_fixed", "Universal Compiler Fixed", "1.1", "Core", "d:\rawrxd\compilers\final_69_working\universal_compiler_fixed.exe"},
        {"universal_cross_platform_compiler", "Universal Cross-Platform Compiler", "1.0", "Core", "d:\rawrxd\compilers\final_69_working\universal_cross_platform_compiler.exe"},
        {"universal_compiler_runtime_final", "Universal Compiler Runtime Final", "1.0", "Core", "d:\rawrxd\compilers\final_69_working\universal_compiler_runtime_final.exe"},
        {"universal_compiler_runtime_production", "Universal Compiler Production", "1.0", "Core", "d:\rawrxd\compilers\final_69_working\universal_compiler_runtime_production.exe"},
        {"universal_compiler_real", "Universal Compiler Real", "1.0", "Core", "d:\rawrxd\compilers\final_69_working\universal_compiler_real.exe"},
        {"bash_compiler_fixed", "Bash Compiler Fixed", "1.1", "Shell", "d:\rawrxd\compilers\final_69_working\bash_compiler_fixed.exe"},
        {"bash_compiler_v2", "Bash Compiler v2", "2.0", "Shell", "d:\rawrxd\compilers\final_69_working\bash_compiler_v2.exe"},
        {"powershell_compiler_fixed", "PowerShell Compiler Fixed", "1.1", "Shell", "d:\rawrxd\compilers\final_69_working\powershell_compiler_fixed.exe"},
        {"powershell_compiler_v2", "PowerShell Compiler v2", "2.0", "Shell", "d:\rawrxd\compilers\final_69_working\powershell_compiler_v2.exe"},
        {"eon_compiler_fixed", "EON Compiler Fixed", "1.1", "Language", "d:\rawrxd\compilers\final_69_working\eon_compiler_fixed.exe"},
        {"eon_compiler_v2", "EON Compiler v2", "2.0", "Language", "d:\rawrxd\compilers\final_69_working\eon_compiler_v2.exe"},
        {"omega_pro_v3", "Omega Pro v3 Compiler", "3.0", "Omega", "d:\rawrxd\compilers\final_69_working\omega_pro_v3.exe"},
        {"omega_pro_v3_fixed", "Omega Pro v3 Fixed", "3.1", "Omega", "d:\rawrxd\compilers\final_69_working\omega_pro_v3_fixed.exe"},
        {"omega_polyglot", "Omega Polyglot Compiler", "1.0", "Omega", "d:\rawrxd\compilers\final_69_working\omega_polyglot.exe"},
        {"omega_universal", "Omega Universal Compiler", "1.0", "Omega", "d:\rawrxd\compilers\final_69_working\omega_universal.exe"},
        {"nasm_ide_compiler", "NASM IDE Compiler", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\nasm_ide_compiler.exe"},
        {"directx_ide_compiler", "DirectX IDE Compiler", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\directx_ide_compiler.exe"},
        {"vulkan_ide_compiler", "Vulkan IDE Compiler", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\vulkan_ide_compiler.exe"},
        {"advanced_ide_compiler", "Advanced IDE Compiler", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\advanced_ide_compiler.exe"},
        {"ultimate_ide_compiler", "Ultimate IDE Compiler", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\ultimate_ide_compiler.exe"},
        {"custom_asm_compiler", "Custom ASM Compiler", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\custom_asm_compiler.exe"},
        {"full_working_ide", "Full Working IDE", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\full_working_ide.exe"},
        {"massive_asm_ide", "Massive ASM IDE", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\massive_asm_ide.exe"},
        {"pure_assembly_ide", "Pure Assembly IDE", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\pure_assembly_ide.exe"},
        {"working_assembly_ide", "Working Assembly IDE", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\working_assembly_ide.exe"},
        {"working_ide", "Working IDE", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\working_ide.exe"},
        {"ultimate_multilang_ide", "Ultimate Multi-Language IDE", "2.0", "IDE", "d:\rawrxd\compilers\final_69_working\ultimate_multilang_ide.exe"},
        {"neon_vulkan_compiler", "NEON Vulkan Compiler", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\neon_vulkan_compiler.exe"},
        {"fabric_compiler", "Fabric Compiler", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\fabric_compiler.exe"},
        {"sovereign_compiler", "Sovereign Compiler", "1.0", "IDE", "d:\rawrxd\compilers\final_69_working\sovereign_compiler.exe"},
        {"phase3_master_compiler", "Phase 3 Master Compiler", "1.0", "Phase", "d:\rawrxd\compilers\final_69_working\phase3_master_compiler.exe"},
        {"phase4_master_compiler", "Phase 4 Master Compiler", "1.0", "Phase", "d:\rawrxd\compilers\final_69_working\phase4_master_compiler.exe"},
        {"phase4_test_harness", "Phase 4 Test Harness", "1.0", "Phase", "d:\rawrxd\compilers\final_69_working\phase4_test_harness.exe"},
        {"phase5_master_compiler", "Phase 5 Master Compiler", "1.0", "Phase", "d:\rawrxd\compilers\final_69_working\phase5_master_compiler.exe"},
        {"phase5_test_harness", "Phase 5 Test Harness", "1.0", "Phase", "d:\rawrxd\compilers\final_69_working\phase5_test_harness.exe"},
        {"week2_3_master_compiler", "Week 2-3 Master Compiler", "1.0", "Phase", "d:\rawrxd\compilers\final_69_working\week2_3_master_compiler.exe"},
        {"phase6_master_compiler", "Phase 6 Master Compiler", "1.0", "Phase", "d:\rawrxd\compilers\final_69_working\phase6_master_compiler.exe"},
        {"phase7_master_compiler", "Phase 7 Master Compiler", "1.0", "Phase", "d:\rawrxd\compilers\final_69_working\phase7_master_compiler.exe"},
        {"phase8_master_compiler", "Phase 8 Master Compiler", "1.0", "Phase", "d:\rawrxd\compilers\final_69_working\phase8_master_compiler.exe"},
        {"phase9_master_compiler", "Phase 9 Master Compiler", "1.0", "Phase", "d:\rawrxd\compilers\final_69_working\phase9_master_compiler.exe"},
        {"autonomous_compiler", "Autonomous Compiler", "1.0", "Specialized", "d:\rawrxd\compilers\final_69_working\autonomous_compiler.exe"},
        {"rawrxd_v2_compiler", "RawrXD v2 Compiler", "2.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_v2_compiler.exe"},
        {"rawrxd_v3_compiler", "RawrXD v3 Compiler", "3.0", "Specialized", "d:\rawrxd\compilers\final_69_working\rawrxd_v3_compiler.exe"},
    };
}
