#
# Module manifest for module 'RawrXDSecurity'
#
# Generated by: RawrXD Team
# Generated on: 2026-07-13
#

@{

    # Script module or binary module file associated with this manifest.
    RootModule = 'RawrXDSecurity.psm1'

    # Version number of this module.
    ModuleVersion = '1.0.0'

    # Supported PSEditions
    CompatiblePSEditions = @('Core', 'Desktop')

    # ID used to uniquely identify this module
    GUID = 'a1b2c3d4-e5f6-7890-abcd-ef1234567890'

    # Author of this module
    Author = 'RawrXD Team'

    # Company or vendor of this module
    CompanyName = 'RawrXD'

    # Copyright statement for this module
    Copyright = '(c) 2026 RawrXD. All rights reserved.'

    # Description of the functionality provided by this module
    Description = 'Enterprise-grade Security & Hotpatch System for RawrXD'

    # Minimum version of the PowerShell engine required by this module
    PowerShellVersion = '7.0'

    # Minimum version of Microsoft .NET Framework required by this module
    DotNetFrameworkVersion = '4.7.2'

    # Minimum version of the common language runtime (CLR) required by this module
    ClrVersion = '4.0'

    # Processor architecture (None, X86, Amd64) required by this module
    ProcessorArchitecture = 'None'

    # Modules that must be imported into the global environment prior to importing this module
    RequiredModules = @()

    # Assemblies that must be loaded prior to importing this module
    RequiredAssemblies = @()

    # Script files (.ps1) that are run in the caller's environment prior to importing this module.
    ScriptsToProcess = @()

    # Type files (.ps1xml) to be loaded when importing this module
    TypesToProcess = @()

    # Format files (.ps1xml) to be loaded when importing this module
    FormatsToProcess = @()

    # Modules to import as nested modules of the module specified in RootModule/ModuleToProcess
    NestedModules = @()

    # Functions to export from this module
    FunctionsToExport = @(
        'Initialize-RawrXDSecurity',
        'Get-RawrXDRole',
        'Set-RawrXDUserRole',
        'Test-RawrXDPermission',
        'Remove-RawrXDUserRole',
        'Get-RawrXDAuditLog',
        'Write-RawrXDAuditEvent',
        'Invoke-RawrXDHealthCheck',
        'New-RawrXDBackup',
        'Invoke-RawrXDComplianceCheck',
        'Get-RawrXDPatchStatus',
        'Register-RawrXDPatch',
        'Update-RawrXDPatchStatus'
    )

    # Cmdlets to export from this module
    CmdletsToExport = @()

    # Variables to export from this module
    VariablesToExport = @()

    # Aliases to export from this module
    AliasesToExport = @(
        'irxs',
        'grr',
        'sur',
        'trp',
        'rur',
        'gral',
        'wxal',
        'irhc',
        'nrb',
        'ircc',
        'grps',
        'regp',
        'upps'
    )

    # DSC resources to export from this module
    DscResourcesToExport = @()

    # List of all modules packaged with this module
    ModuleList = @()

    # List of all files packaged with this module
    FileList = @()

    # Private data to pass to the module specified in RootModule/ModuleToProcess
    PrivateData = @{

        PSData = @{

            # Tags applied to this module
            Tags = @('Security', 'RBAC', 'Hotpatch', 'Compliance', 'Audit', 'RawrXD')

            # A URL to the license for this module
            LicenseUri = 'https://rawrxd.local/LICENSE'

            # A URL to the main website for this project
            ProjectUri = 'https://rawrxd.local'

            # A URL to an icon representing this module
            IconUri = 'https://rawrxd.local/icon.png'

            # ReleaseNotes of this module
            ReleaseNotes = @'
## Version 1.0.0 (2026-07-13)

### Features
- Enterprise-grade RBAC with 5-tier role system
- Zero-downtime hotpatching
- Comprehensive audit logging
- SOC2/ISO27001/NIST compliance checking
- Automated backup and recovery
- Health monitoring and alerting

### Functions
- Initialize-RawrXDSecurity
- Get-RawrXDRole / Set-RawrXDUserRole
- Test-RawrXDPermission / Remove-RawrXDUserRole
- Get-RawrXDAuditLog / Write-RawrXDAuditEvent
- Invoke-RawrXDHealthCheck
- New-RawrXDBackup
- Invoke-RawrXDComplianceCheck
- Get-RawrXDPatchStatus / Register-RawrXDPatch

### Aliases
- irxs (Initialize-RawrXDSecurity)
- grr (Get-RawrXDRole)
- sur (Set-RawrXDUserRole)
- trp (Test-RawrXDPermission)
- rur (Remove-RawrXDUserRole)
- gral (Get-RawrXDAuditLog)
- wxal (Write-RawrXDAuditEvent)
- irhc (Invoke-RawrXDHealthCheck)
- nrb (New-RawrXDBackup)
- ircc (Invoke-RawrXDComplianceCheck)
- grps (Get-RawrXDPatchStatus)
- regp (Register-RawrXDPatch)
- upps (Update-RawrXDPatchStatus)
'@

            # Prerelease string of this module
            Prerelease = ''

            # Flag to indicate whether the module requires explicit user acceptance
            RequireLicenseAcceptance = $false

            # External dependent modules of this module
            ExternalModuleDependencies = @()

        } # End of PSData hashtable

    } # End of PrivateData hashtable

    # HelpInfo URI of this module
    HelpInfoURI = 'https://rawrxd.local/docs'

    # Default prefix for commands exported from this module
    DefaultCommandPrefix = 'RawrXD'

}
