# CMake generated Testfile for 
# Source directory: F:/~dev/rawrxd
# Build directory: F:/~dev/kilo_tmp/ga_run1
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("test_llama_native" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/test_llama_native.exe")
  set_tests_properties("test_llama_native" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15999;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("test_llama_native" "F:/~dev/kilo_tmp/ga_run1/tests/Release/test_llama_native.exe")
  set_tests_properties("test_llama_native" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15999;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("test_llama_native" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/test_llama_native.exe")
  set_tests_properties("test_llama_native" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15999;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("test_llama_native" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/test_llama_native.exe")
  set_tests_properties("test_llama_native" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;15999;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("test_llama_native" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_runtime_validation" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_runtime_validation.exe")
  set_tests_properties("k2_runtime_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16053;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_runtime_validation" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_runtime_validation.exe")
  set_tests_properties("k2_runtime_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16053;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_runtime_validation" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_runtime_validation.exe")
  set_tests_properties("k2_runtime_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16053;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_runtime_validation" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_runtime_validation.exe")
  set_tests_properties("k2_runtime_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16053;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_runtime_validation" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("test_q4k_decoder" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/test_q4k_decoder.exe")
  set_tests_properties("test_q4k_decoder" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16065;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("test_q4k_decoder" "F:/~dev/kilo_tmp/ga_run1/tests/Release/test_q4k_decoder.exe")
  set_tests_properties("test_q4k_decoder" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16065;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("test_q4k_decoder" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/test_q4k_decoder.exe")
  set_tests_properties("test_q4k_decoder" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16065;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("test_q4k_decoder" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/test_q4k_decoder.exe")
  set_tests_properties("test_q4k_decoder" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16065;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("test_q4k_decoder" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_native_smoke_test" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_native_smoke_test.exe")
  set_tests_properties("k2_native_smoke_test" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16124;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_native_smoke_test" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_native_smoke_test.exe")
  set_tests_properties("k2_native_smoke_test" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16124;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_native_smoke_test" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_native_smoke_test.exe")
  set_tests_properties("k2_native_smoke_test" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16124;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_native_smoke_test" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_native_smoke_test.exe")
  set_tests_properties("k2_native_smoke_test" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16124;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_native_smoke_test" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_002_tensor_streaming" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_002_tensor_streaming.exe")
  set_tests_properties("k2_002_tensor_streaming" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16175;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_002_tensor_streaming" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_002_tensor_streaming.exe")
  set_tests_properties("k2_002_tensor_streaming" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16175;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_002_tensor_streaming" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_002_tensor_streaming.exe")
  set_tests_properties("k2_002_tensor_streaming" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16175;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_002_tensor_streaming" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_002_tensor_streaming.exe")
  set_tests_properties("k2_002_tensor_streaming" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16175;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_002_tensor_streaming" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_003_layer_execution" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_003_layer_execution.exe")
  set_tests_properties("k2_003_layer_execution" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16226;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_003_layer_execution" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_003_layer_execution.exe")
  set_tests_properties("k2_003_layer_execution" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16226;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_003_layer_execution" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_003_layer_execution.exe")
  set_tests_properties("k2_003_layer_execution" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16226;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_003_layer_execution" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_003_layer_execution.exe")
  set_tests_properties("k2_003_layer_execution" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16226;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_003_layer_execution" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_003b_native_gemv_validation" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_003b_native_gemv_validation.exe")
  set_tests_properties("k2_003b_native_gemv_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16240;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_003b_native_gemv_validation" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_003b_native_gemv_validation.exe")
  set_tests_properties("k2_003b_native_gemv_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16240;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_003b_native_gemv_validation" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_003b_native_gemv_validation.exe")
  set_tests_properties("k2_003b_native_gemv_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16240;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_003b_native_gemv_validation" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_003b_native_gemv_validation.exe")
  set_tests_properties("k2_003b_native_gemv_validation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16240;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_003b_native_gemv_validation" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_003c_single_layer_forward" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_003c_single_layer_forward.exe")
  set_tests_properties("k2_003c_single_layer_forward" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16254;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_003c_single_layer_forward" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_003c_single_layer_forward.exe")
  set_tests_properties("k2_003c_single_layer_forward" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16254;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_003c_single_layer_forward" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_003c_single_layer_forward.exe")
  set_tests_properties("k2_003c_single_layer_forward" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16254;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_003c_single_layer_forward" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_003c_single_layer_forward.exe")
  set_tests_properties("k2_003c_single_layer_forward" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16254;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_003c_single_layer_forward" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_004_bounded_prefill" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_004_bounded_prefill.exe")
  set_tests_properties("k2_004_bounded_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16305;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_004_bounded_prefill" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_004_bounded_prefill.exe")
  set_tests_properties("k2_004_bounded_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16305;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_004_bounded_prefill" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_004_bounded_prefill.exe")
  set_tests_properties("k2_004_bounded_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16305;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_004_bounded_prefill" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_004_bounded_prefill.exe")
  set_tests_properties("k2_004_bounded_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16305;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_004_bounded_prefill" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_004_bounded_multi_layer_prefill" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_004_bounded_multi_layer_prefill.exe")
  set_tests_properties("k2_004_bounded_multi_layer_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16319;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_004_bounded_multi_layer_prefill" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_004_bounded_multi_layer_prefill.exe")
  set_tests_properties("k2_004_bounded_multi_layer_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16319;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_004_bounded_multi_layer_prefill" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_004_bounded_multi_layer_prefill.exe")
  set_tests_properties("k2_004_bounded_multi_layer_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16319;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_004_bounded_multi_layer_prefill" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_004_bounded_multi_layer_prefill.exe")
  set_tests_properties("k2_004_bounded_multi_layer_prefill" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16319;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_004_bounded_multi_layer_prefill" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_005_autoregressive_kv_cache" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_005_autoregressive_kv_cache.exe")
  set_tests_properties("k2_005_autoregressive_kv_cache" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16334;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_005_autoregressive_kv_cache" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_005_autoregressive_kv_cache.exe")
  set_tests_properties("k2_005_autoregressive_kv_cache" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16334;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_005_autoregressive_kv_cache" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_005_autoregressive_kv_cache.exe")
  set_tests_properties("k2_005_autoregressive_kv_cache" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16334;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_005_autoregressive_kv_cache" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_005_autoregressive_kv_cache.exe")
  set_tests_properties("k2_005_autoregressive_kv_cache" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16334;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_005_autoregressive_kv_cache" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_006_bounded_token_generation" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_006_bounded_token_generation.exe")
  set_tests_properties("k2_006_bounded_token_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16349;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_006_bounded_token_generation" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_006_bounded_token_generation.exe")
  set_tests_properties("k2_006_bounded_token_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16349;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_006_bounded_token_generation" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_006_bounded_token_generation.exe")
  set_tests_properties("k2_006_bounded_token_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16349;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_006_bounded_token_generation" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_006_bounded_token_generation.exe")
  set_tests_properties("k2_006_bounded_token_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16349;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_006_bounded_token_generation" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_007_real_output_projection" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_007_real_output_projection.exe")
  set_tests_properties("k2_007_real_output_projection" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16362;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_007_real_output_projection" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_007_real_output_projection.exe")
  set_tests_properties("k2_007_real_output_projection" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16362;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_007_real_output_projection" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_007_real_output_projection.exe")
  set_tests_properties("k2_007_real_output_projection" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16362;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_007_real_output_projection" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_007_real_output_projection.exe")
  set_tests_properties("k2_007_real_output_projection" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16362;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_007_real_output_projection" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_007b_projection_logits_interface" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_007b_projection_logits_interface.exe")
  set_tests_properties("k2_007b_projection_logits_interface" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16380;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_007b_projection_logits_interface" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_007b_projection_logits_interface.exe")
  set_tests_properties("k2_007b_projection_logits_interface" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16380;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_007b_projection_logits_interface" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_007b_projection_logits_interface.exe")
  set_tests_properties("k2_007b_projection_logits_interface" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16380;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_007b_projection_logits_interface" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_007b_projection_logits_interface.exe")
  set_tests_properties("k2_007b_projection_logits_interface" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16380;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_007b_projection_logits_interface" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_008_end_to_end_semantic_generation" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_008_end_to_end_semantic_generation.exe")
  set_tests_properties("k2_008_end_to_end_semantic_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16397;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_008_end_to_end_semantic_generation" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_008_end_to_end_semantic_generation.exe")
  set_tests_properties("k2_008_end_to_end_semantic_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16397;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_008_end_to_end_semantic_generation" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_008_end_to_end_semantic_generation.exe")
  set_tests_properties("k2_008_end_to_end_semantic_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16397;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_008_end_to_end_semantic_generation" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_008_end_to_end_semantic_generation.exe")
  set_tests_properties("k2_008_end_to_end_semantic_generation" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16397;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_008_end_to_end_semantic_generation" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("k2_009_token_embedding_lookup" "F:/~dev/kilo_tmp/ga_run1/tests/Debug/k2_009_token_embedding_lookup.exe")
  set_tests_properties("k2_009_token_embedding_lookup" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16414;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("k2_009_token_embedding_lookup" "F:/~dev/kilo_tmp/ga_run1/tests/Release/k2_009_token_embedding_lookup.exe")
  set_tests_properties("k2_009_token_embedding_lookup" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16414;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("k2_009_token_embedding_lookup" "F:/~dev/kilo_tmp/ga_run1/tests/MinSizeRel/k2_009_token_embedding_lookup.exe")
  set_tests_properties("k2_009_token_embedding_lookup" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16414;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("k2_009_token_embedding_lookup" "F:/~dev/kilo_tmp/ga_run1/tests/RelWithDebInfo/k2_009_token_embedding_lookup.exe")
  set_tests_properties("k2_009_token_embedding_lookup" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1/tests" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;16414;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("k2_009_token_embedding_lookup" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("git_safety_authority_cert" "F:/~dev/kilo_tmp/ga_run1/bin/Debug/git_safety_authority_cert.exe")
  set_tests_properties("git_safety_authority_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;18998;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("git_safety_authority_cert" "F:/~dev/kilo_tmp/ga_run1/bin/Release/git_safety_authority_cert.exe")
  set_tests_properties("git_safety_authority_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;18998;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("git_safety_authority_cert" "F:/~dev/kilo_tmp/ga_run1/bin/MinSizeRel/git_safety_authority_cert.exe")
  set_tests_properties("git_safety_authority_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;18998;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("git_safety_authority_cert" "F:/~dev/kilo_tmp/ga_run1/bin/RelWithDebInfo/git_safety_authority_cert.exe")
  set_tests_properties("git_safety_authority_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;18998;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("git_safety_authority_cert" NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("refactor_chain_cert" "F:/~dev/kilo_tmp/ga_run1/bin/Debug/refactor_chain_cert.exe" "--fixture" "F:/~dev/rawrxd/audit/RAWRXD_P1_REFACTOR_CHAIN_001/fixture" "--out" "F:/~dev/rawrxd/audit/RAWRXD_P1_REFACTOR_CHAIN_001/RECEIPT.txt")
  set_tests_properties("refactor_chain_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;19198;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("refactor_chain_cert" "F:/~dev/kilo_tmp/ga_run1/bin/Release/refactor_chain_cert.exe" "--fixture" "F:/~dev/rawrxd/audit/RAWRXD_P1_REFACTOR_CHAIN_001/fixture" "--out" "F:/~dev/rawrxd/audit/RAWRXD_P1_REFACTOR_CHAIN_001/RECEIPT.txt")
  set_tests_properties("refactor_chain_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;19198;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test("refactor_chain_cert" "F:/~dev/kilo_tmp/ga_run1/bin/MinSizeRel/refactor_chain_cert.exe" "--fixture" "F:/~dev/rawrxd/audit/RAWRXD_P1_REFACTOR_CHAIN_001/fixture" "--out" "F:/~dev/rawrxd/audit/RAWRXD_P1_REFACTOR_CHAIN_001/RECEIPT.txt")
  set_tests_properties("refactor_chain_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;19198;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test("refactor_chain_cert" "F:/~dev/kilo_tmp/ga_run1/bin/RelWithDebInfo/refactor_chain_cert.exe" "--fixture" "F:/~dev/rawrxd/audit/RAWRXD_P1_REFACTOR_CHAIN_001/fixture" "--out" "F:/~dev/rawrxd/audit/RAWRXD_P1_REFACTOR_CHAIN_001/RECEIPT.txt")
  set_tests_properties("refactor_chain_cert" PROPERTIES  WORKING_DIRECTORY "F:/~dev/kilo_tmp/ga_run1" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/CMakeLists.txt;19198;add_test;F:/~dev/rawrxd/CMakeLists.txt;0;")
else()
  add_test("refactor_chain_cert" NOT_AVAILABLE)
endif()
subdirs("src/reverse_engineering")
subdirs("src/ceo")
subdirs("src/repository")
subdirs("src/generation")
subdirs("rguf_source")
