; USG_output.asm - USG with output display
; =============================================================================

OPTION CASEMAP:NONE
OPTION DOTNAME

; =============================================================================
; GENERATION MODES (bitflags)
; =============================================================================
MODE_PEACEFUL       EQU     00000001h
MODE_UNPEACEFUL     EQU     00000002h
MODE_CENSORED       EQU     00000004h
MODE_UNCENSORED     EQU     00000008h
MODE_LYRICAL        EQU     00000010h
MODE_UNLYRICAL      EQU     00000020h
MODE_DIGITAL        EQU     00000040h
MODE_ANALOG         EQU     00000080h
MODE_UNDER_CLOUDS   EQU     00000100h
MODE_ABOVE_CLOUDS   EQU     00000200h
MODE_RAP            EQU     00000400h
MODE_NON_BLAP       EQU     00000800h
MODE_METAMORPHIC    EQU     80000000h

BARS_TOTAL          EQU     21
BARS_UNBARRED       EQU     11
BARS_BARRED         EQU     10
MAX_STUB_SIZE       EQU     4096

; =============================================================================
; DATA SECTION
; =============================================================================
.DATA
ALIGN 16

USG_State STRUCT
    ModeFlags       DWORD   ?
    CurrentBar      BYTE    ?
    IsBarred        BYTE    ?
    MorphSeed       DWORD   ?
    OutputPtr       QWORD   ?
    OutputEnd       QWORD   ?
USG_State ENDS

ALIGN 16
State       USG_State   <>

ALIGN 16
MutTable:
    DB  090h, 090h, 090h, 090h
    DB  048h, 089h, 0C0h, 048h
    DB  048h, 031h, 0C0h, 048h
    DB  048h, 001h, 0C0h, 048h
    DB  048h, 0FFh, 0C0h, 048h
    DB  048h, 0FFh, 0C8h, 048h
    DB  0EBh, 000h, 090h, 090h
    DB  074h, 000h, 00Fh, 084h
    DB  075h, 000h, 00Fh, 085h
    DB  0C3h, 0C2h, 000h, 000h

ALIGN 16
BarTemplates:
    DB  "USG_INIT", 0, 0, 0, 0, 0, 0, 0
    DB  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    DB  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    DB  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    DB  "BAR_START", 0, 0, 0, 0, 0, 0
    DB  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    DB  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    DB  0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
    DB  64 * 19 DUP(0)

ALIGN 16
OutputBuffer    DB  MAX_STUB_SIZE DUP(0)

; Output strings
szHeader        DB  "=== USG Output ===", 13, 10, 0
szMode          DB  "Mode: PEACEFUL | DIGITAL", 13, 10, 0
szBarCount      DB  "Bars: 21 (11 unbarred + 10 barred)", 13, 10, 0
szOutput        DB  "Generated bytes:", 13, 10, 0
szDone          DB  "=== USG Complete ===", 13, 10, 0
szNewline       DB  13, 10, 0
hexChars        DB  "0123456789ABCDEF", 0

; =============================================================================
; CODE SECTION
; =============================================================================
.CODE

; ---------------------------------------------------------------------------
; USG_Init
; ---------------------------------------------------------------------------
USG_Init PROC FRAME
    .endprolog
    mov     [State.ModeFlags], ecx
    mov     BYTE PTR [State.CurrentBar], 0
    mov     BYTE PTR [State.IsBarred], 0
    mov     DWORD PTR [State.MorphSeed], 0DEADBEEFh
    lea     rax, [OutputBuffer]
    mov     [State.OutputPtr], rax
    lea     rax, [OutputBuffer + MAX_STUB_SIZE]
    mov     [State.OutputEnd], rax
    xor     eax, eax
    ret
USG_Init ENDP

; ---------------------------------------------------------------------------
; USG_PRNG
; ---------------------------------------------------------------------------
USG_PRNG PROC FRAME
    .endprolog
    mov     eax, [State.MorphSeed]
    imul    eax, eax, 1103515245
    add     eax, 12345
    mov     [State.MorphSeed], eax
    ret
USG_PRNG ENDP

; ---------------------------------------------------------------------------
; USG_SelectMorph
; ---------------------------------------------------------------------------
USG_SelectMorph PROC FRAME
    .endprolog
    push    rcx
    call    USG_PRNG
    pop     rcx
    and     eax, 3
    shl     ecx, 2
    lea     rdx, [MutTable]
    add     edx, ecx
    movzx   eax, BYTE PTR [rdx + rax]
    ret
USG_SelectMorph ENDP

; ---------------------------------------------------------------------------
; USG_WriteByte
; ---------------------------------------------------------------------------
USG_WriteByte PROC FRAME
    .endprolog
    mov     rax, [State.OutputPtr]
    cmp     rax, [State.OutputEnd]
    jae     WriteFull
    mov     BYTE PTR [rax], cl
    inc     QWORD PTR [State.OutputPtr]
    mov     al, 1
    ret
WriteFull:
    xor     al, al
    ret
USG_WriteByte ENDP

; ---------------------------------------------------------------------------
; USG_GenerateBar
; ---------------------------------------------------------------------------
USG_GenerateBar PROC FRAME
    push    rbp
    .pushreg rbp
    push    rbx
    .pushreg rbx
    mov     rbp, rsp
    .setframe rbp, 0
    sub     rsp, 32
    .allocstack 32
    .endprolog

    mov     ebx, ecx
    cmp     ebx, BARS_UNBARRED
    jb      UnbarredBar
    mov     BYTE PTR [State.IsBarred], 1
    jmp     GenerateContent
UnbarredBar:
    mov     BYTE PTR [State.IsBarred], 0

GenerateContent:
    mov     eax, [State.ModeFlags]
    test    eax, MODE_METAMORPHIC
    jz      StandardGen
    mov     ecx, ebx
    and     ecx, 7
    call    USG_SelectMorph
    mov     cl, al
    call    USG_WriteByte
    jmp     BarDone

StandardGen:
    test    eax, MODE_PEACEFUL
    jnz     GenPeaceful
    test    eax, MODE_UNPEACEFUL
    jnz     GenUnpeaceful
    test    eax, MODE_DIGITAL
    jnz     GenDigital
    mov     cl, 090h
    call    USG_WriteByte

BarDone:
    mov     rsp, rbp
    pop     rbx
    pop     rbp
    ret

GenPeaceful:
    mov     cl, 048h
    call    USG_WriteByte
    mov     cl, 031h
    call    USG_WriteByte
    mov     cl, 0C0h
    call    USG_WriteByte
    jmp     BarDone

GenUnpeaceful:
    mov     cl, 048h
    call    USG_WriteByte
    mov     cl, 0FFh
    call    USG_WriteByte
    mov     cl, 0C0h
    call    USG_WriteByte
    jmp     BarDone

GenDigital:
    mov     cl, 00Fh
    call    USG_WriteByte
    mov     cl, 038h
    call    USG_WriteByte
    jmp     BarDone

USG_GenerateBar ENDP

; ---------------------------------------------------------------------------
; USG_Generate21
; ---------------------------------------------------------------------------
USG_Generate21 PROC FRAME
    push    rbp
    .pushreg rbp
    push    rbx
    .pushreg rbx
    mov     rbp, rsp
    .setframe rbp, 0
    sub     rsp, 32
    .allocstack 32
    .endprolog

    xor     ebx, ebx

BarLoop:
    cmp     bl, BARS_TOTAL
    jae     GenerationDone
    mov     ecx, ebx
    call    USG_GenerateBar
    inc     bl
    jmp     BarLoop

GenerationDone:
    mov     rsp, rbp
    pop     rbx
    pop     rbp
    ret
USG_Generate21 ENDP

; ---------------------------------------------------------------------------
; PrintString - Output null-terminated string to console
; RCX = string pointer
; ---------------------------------------------------------------------------
PrintString PROC FRAME
    push    rbp
    .pushreg rbp
    mov     rbp, rsp
    .setframe rbp, 0
    sub     rsp, 48
    .allocstack 48
    .endprolog

    mov     rsi, rcx
    mov     rdi, rcx

CountLoop:
    cmp     BYTE PTR [rdi], 0
    je      CountDone
    inc     rdi
    jmp     CountLoop

CountDone:
    mov     r8, rdi
    sub     r8, rsi

    mov     rcx, -11
    call    GetStdHandle
    mov     rcx, rax
    mov     rdx, rsi
    xor     r9, r9
    lea     r10, [rsp + 32]
    mov     QWORD PTR [r10], 0
    call    WriteConsoleA

    mov     rsp, rbp
    pop     rbp
    ret
PrintString ENDP

; ---------------------------------------------------------------------------
; PrintHexByte - Output byte as hex
; CL = byte to print
; ---------------------------------------------------------------------------
PrintHexByte PROC FRAME
    push    rbp
    .pushreg rbp
    push    rbx
    .pushreg rbx
    mov     rbp, rsp
    .setframe rbp, 0
    sub     rsp, 48
    .allocstack 48
    .endprolog

    mov     bl, cl
    shr     cl, 4
    and     cl, 0Fh
    lea     rax, [hexChars]
    movzx   ecx, BYTE PTR [rax + rcx]
    mov     BYTE PTR [rsp + 32], cl

    mov     cl, bl
    and     cl, 0Fh
    movzx   ecx, BYTE PTR [rax + rcx]
    mov     BYTE PTR [rsp + 33], cl

    mov     rcx, -11
    call    GetStdHandle
    mov     rcx, rax
    lea     rdx, [rsp + 32]
    mov     r8, 2
    xor     r9, r9
    lea     r10, [rsp + 40]
    mov     QWORD PTR [r10], 0
    call    WriteConsoleA

    mov     rsp, rbp
    pop     rbx
    pop     rbp
    ret
PrintHexByte ENDP

; ---------------------------------------------------------------------------
; ENTRY POINT
; ---------------------------------------------------------------------------
USG_Entry PROC FRAME
    push    rbp
    .pushreg rbp
    mov     rbp, rsp
    .setframe rbp, 0
    sub     rsp, 48
    .allocstack 48
    .endprolog

    ; Print header
    lea     rcx, [szHeader]
    call    PrintString

    ; Print mode info
    lea     rcx, [szMode]
    call    PrintString
    lea     rcx, [szBarCount]
    call    PrintString
    lea     rcx, [szOutput]
    call    PrintString

    ; Initialize USG with MODE_PEACEFUL | MODE_DIGITAL
    mov     ecx, 00000041h
    call    USG_Init

    ; Generate 21 bars
    call    USG_Generate21

    ; Calculate generated size
    mov     rax, [State.OutputPtr]
    lea     rdx, [OutputBuffer]
    sub     rax, rdx
    mov     r12, rax

    ; Print generated bytes (first 64 max)
    cmp     r12, 64
    jbe     PrintAll
    mov     r12, 64

PrintAll:
    xor     rbx, rbx

PrintLoop:
    cmp     rbx, r12
    jae     PrintDone

    ; Print space every 16 bytes
    test    bl, 0Fh
    jnz     NoNewline
    cmp     rbx, 0
    je      NoNewline
    lea     rcx, [szNewline]
    call    PrintString

NoNewline:
    lea     rax, [OutputBuffer]
    movzx   ecx, BYTE PTR [rax + rbx]
    call    PrintHexByte
    mov     cl, ' '
    call    PrintChar
    inc     rbx
    jmp     PrintLoop

PrintDone:
    lea     rcx, [szNewline]
    call    PrintString
    lea     rcx, [szNewline]
    call    PrintString
    lea     rcx, [szDone]
    call    PrintString

    ; Exit
    xor     ecx, ecx
    call    ExitProcess

USG_Entry ENDP

; ---------------------------------------------------------------------------
; PrintChar - Output single character
; CL = character
; ---------------------------------------------------------------------------
PrintChar PROC FRAME
    push    rbp
    .pushreg rbp
    mov     rbp, rsp
    .setframe rbp, 0
    sub     rsp, 48
    .allocstack 48
    .endprolog

    mov     BYTE PTR [rsp + 32], cl

    mov     rcx, -11
    call    GetStdHandle
    mov     rcx, rax
    lea     rdx, [rsp + 32]
    mov     r8, 1
    xor     r9, r9
    lea     r10, [rsp + 40]
    mov     QWORD PTR [r10], 0
    call    WriteConsoleA

    mov     rsp, rbp
    pop     rbp
    ret
PrintChar ENDP

; =============================================================================
; EXPORTS
; =============================================================================
PUBLIC USG_Init
PUBLIC USG_Generate21
PUBLIC USG_Entry

EXTERN ExitProcess:PROC
EXTERN GetStdHandle:PROC
EXTERN WriteConsoleA:PROC

; =============================================================================
; END
; =============================================================================
END

