#pragma once
/* ACTUAL_E2E_GENERATION_ONLY — tuner/cert ≠ generation PASS. */
#define RAWRXD_EXECUTION_POLICY_ACTUAL_E2E_GENERATION_ONLY 1
#define ACTUAL_E2E_GENERATION_001 1
#define SPV_PRESENT_NE_PASS 1
#define KERNEL_EXECUTABLE_NE_PASS 1
#define PARITY_NE_PASS 1
#define MEASURED_NE_PASS 1
#define WINNER_SELECTED_NE_PASS 1
#define TUNER_PASS_NE_GENERATION_PASS 1
#define MODEL_OPEN_NE_PASS 1
#define PREFILL_PASS_NE_FULL_RUN_PASS 1
#define HEARTBEAT_NE_PASS 1
/*
  REQUIRED_PATH:
    MODEL_OPEN → INDEX → TOKENIZER → PROMPT_TOKENIZE → PREFILL →
    REAL_LAYER_FORWARD → QKV/KVA/O_PROJ/FFN → FINAL_NORM → LOGITS →
    SAMPLE → DETOKENIZE → TOKEN_EMIT → CONTINUED_DECODE → CLEAN_TEARDOWN

  Tuner is a transient sub-operation of production decode, not a destination.
  PASS only when MODEL_OUTPUT_PRODUCED=1 and GENERATED_TOKENS>0 with
  TERMINATION_CLASS=COMPLETED and TEARDOWN_WITNESS=1.
  WALL_WITHIN_BUDGET is a separate final line (PRODUCT_E2E).
*/
