#pragma once
/* Minimal closed completion — classify D2H; no new stacks. */
#define RAWRXD_BRAID_COMPLETION_LAYER_001 1
#define DISCARD_FORBIDDEN 1
#define WORD_FAIL_RECLASSIFY_NOT_STRIP 1
#define COMPLETE_WITH_EXISTING_GOODS_ONLY 1
#define COMPLEXITY_BUDGET 0
#define TIP_BOT_HOLD 1
#define SLINGSHOT_REBUILD 0
#define NO_REOPEN_QB_KVA_LOGITS 1
#define DOWNSTREAM_READBACK_BLOCKED 1
#define COMPLETION_DELTA_D2H_CLASSIFICATION 1
#define STOP_AFTER_D2H_RECEIPT 1
/*
  FOR_EACH_D2H:
    HOST → KEEP_OR_SHRINK
    DEVICE → DELETE_D2H
    TRACE/METRIC/DEBUG → DELETE_PRODUCT_D2H
    UNKNOWN → FAIL_CLOSED
  Measure: GENERATION_WALL_NS only. No adjacent opt after seal.
*/
