// LocalModelE2ELaw.hpp — RAWRXD_LOCAL_MODEL_E2E_001
#pragma once
#define RAWRXD_LOCAL_MODEL_E2E_001 1
#define ONE_LOCAL_MODEL_AUTHORITY 1
#define LOCAL_MODEL_AUTHORITY_DEEP2 1
#define SYNTHETIC_TOKEN_PATH_ILLEGAL 1
/*
  Product local-model acceptance (runtime-backed only):

  IDE/CLI/HTTP/Agent → Deep2Bridge/Deep2Engine → generateStream → token callback

  PASS requires:
    MODEL_FILE_OR_DIRECTORY=1
    SPLIT_GGUF_AUTO_DISCOVERY=1
    METADATA_BEFORE_MATERIALIZATION=1
    ARCH_CONTRACT_RESOLVED=1
    QUANT_CONTRACT_RESOLVED=1
    TOKENIZER_CONTRACT_RESOLVED=1
    TENSOR_SCHEMA_COMPLETE=1
    REAL_PREFILL=1 REAL_DECODE=1 REAL_TOKEN_STREAM=1
    SYNTHETIC_TOKEN_PATH=0
    ACTUAL_TEXT_BYTES>0 GENERATED_TOKENS>0
    PRODUCTION_DECODE_PATH=1
    CLEAN_TEARDOWN_WITNESS=1 HARNESS_ABORT=0
*/
