#pragma once
#define MOUNT_COUNT 3
#define LEFT_MOUNT_SOURCE_AUTHORITY 1
#define RIGHT_MOUNT_EXECUTION_AUTHORITY 1
#define REAR_MOUNT_STATE_AUTHORITY 1
#define AUTHORITY_MOVEMENT 0
#define WORK_MOVEMENT 1
#define PROCESSION_COUNT 1
#define SOLID_MOUNT_NE_SOLID_BYTES 1
#define MOUNT_REENTRY_ALLOWED 0
#define PERFORMANCE_FAULT_NE_AUTHORITY_FAULT 1
#define SPEND_ONLY_ON_CURRENT_WALL_OWNER 1
#define REQUIREMENT_HAVE_MODEL_OR_CAN_ADVANCE 1
#define NEGATIVE_GENERATION_TRACKED 1
/*
  MOUNT_SOLID=1 => MOUNT_ACTION_ELIGIBLE=0 unless mount observably broken.
  Wall slow ≠ remount. PERFORMANCE_PROCESSION spends only on current owner.
*/
