#pragma once
/* Downvolt = envelope reducer, not capacity reducer. PERFORMANCE only. */
#define DOWNVOLT_ALLOWED 1
#define DOWNVOLT_REDUCES_HARDWARE_PRESSURE 1
#define DOWNVOLT_REDUCES_MODEL_REQUIREMENTS 0
#define VRAM_REQUIREMENT_UNCHANGED 1
#define RAM_REQUIREMENT_UNCHANGED 1
#define TENSOR_BYTES_UNCHANGED 1
#define KV_BYTES_UNCHANGED 1
#define POWER_REQUIREMENT_CAN_DROP 1
#define THERMAL_REQUIREMENT_CAN_DROP 1
#define PSU_HEADROOM_REQUIREMENT_CAN_DROP 1
#define COOLING_PRESSURE_CAN_DROP 1
#define DOWNVOLT_SCOPE_PERFORMANCE_PROCESSION 1
#define DOWNVOLT_AUTHORITY 0
#define DOWNVOLT_CAN_BLOCK_GENERATE 0
#define DOWNVOLT_CAN_REDUCE_ENV_PRESSURE 1
#define CAPACITY_REQUIREMENT_BYTES 1
#define ENVELOPE_REQUIREMENT_WATTS 1
#define DOWNVOLT_REDUCES_ENVELOPE_REQUIREMENT 1
#define DOWNVOLT_REDUCES_CAPACITY_REQUIREMENT 0
#define POWER_CAP_ALLOWED 1
#define HARDWARE_ENVELOPE_REDUCED 1
/*
  Halo / DGX Spark law: bounded watt/thermal appliance.
  Capacity = bytes. Envelope = watts (+ bandwidth class).
  Downvolt/power-cap reduce envelope, never byte truth.
*/
