#pragma once
/* Ownership, recovery, progress, resource, perf, teardown enums. */
#include "RawrStreamerVocabularyExt.hpp"

enum RawrBlockOwner : RAWR_U32 {
    RAWR_OWNER_NONE = 0,
    RAWR_OWNER_CALLER,
    RAWR_OWNER_MODEL_RESOLVER,
    RAWR_OWNER_GGUF,
    RAWR_OWNER_TOKENIZER,
    RAWR_OWNER_RMV,
    RAWR_OWNER_RESIDENCY,
    RAWR_OWNER_CAPABILITY_SOLVER,
    RAWR_OWNER_KERNEL_SOLVER,
    RAWR_OWNER_SHADER_PIPELINE,
    RAWR_OWNER_DEVICE,
    RAWR_OWNER_QKV,
    RAWR_OWNER_KVA,
    RAWR_OWNER_O_PROJ,
    RAWR_OWNER_FFN,
    RAWR_OWNER_LOGITS,
    RAWR_OWNER_SAMPLER,
    RAWR_OWNER_STREAMER,
    RAWR_OWNER_TEARDOWN,
    RAWR_OWNER_ENVIRONMENT
};

enum RawrRecoveryAction : RAWR_U32 {
    RAWR_RECOVERY_NONE = 0,
    RAWR_RECOVERY_RETRY,
    RAWR_RECOVERY_REOPEN,
    RAWR_RECOVERY_REINDEX,
    RAWR_RECOVERY_REACQUIRE,
    RAWR_RECOVERY_REBIND,
    RAWR_RECOVERY_REBUILD_PIPELINE,
    RAWR_RECOVERY_REPLAN,
    RAWR_RECOVERY_REDUCE_WORKING_SET,
    RAWR_RECOVERY_EVICT,
    RAWR_RECOVERY_RECLAIM,
    RAWR_RECOVERY_SWITCH_LEGAL_VARIANT,
    RAWR_RECOVERY_SWITCH_DEVICE,
    RAWR_RECOVERY_FALLBACK_HOST,
    RAWR_RECOVERY_RESUME,
    RAWR_RECOVERY_ABORT
};

enum RawrRecoveryDisposition : RAWR_U32 {
    RAWR_RECOVERY_DISPOSITION_NONE = 0,
    RAWR_RECOVERY_NOT_APPLICABLE,
    RAWR_RECOVERY_AVAILABLE,
    RAWR_RECOVERY_IN_PROGRESS,
    RAWR_RECOVERY_SUCCEEDED,
    RAWR_RECOVERY_EXHAUSTED,
    RAWR_RECOVERY_FORBIDDEN
};

enum RawrProgressKind : RAWR_U32 {
    RAWR_PROGRESS_NONE = 0,
    RAWR_PROGRESS_HEARTBEAT,
    RAWR_PROGRESS_MODEL_INDEX,
    RAWR_PROGRESS_TENSOR_ADDRESS,
    RAWR_PROGRESS_TENSOR_ACQUIRE,
    RAWR_PROGRESS_PREFILL_LAYER,
    RAWR_PROGRESS_DECODE_LAYER,
    RAWR_PROGRESS_DECODE_TOKEN,
    RAWR_PROGRESS_TOKEN_EMIT,
    RAWR_PROGRESS_RELEASE,
    RAWR_PROGRESS_TEARDOWN
};

enum RawrResourceState : RAWR_U32 {
    RAWR_RESOURCE_NONE = 0,
    RAWR_RESOURCE_DESCRIBED,
    RAWR_RESOURCE_ADDRESSED,
    RAWR_RESOURCE_ACQUIRING,
    RAWR_RESOURCE_ACQUIRED,
    RAWR_RESOURCE_RESIDENT,
    RAWR_RESOURCE_IN_USE,
    RAWR_RESOURCE_RELEASING,
    RAWR_RESOURCE_RELEASED,
    RAWR_RESOURCE_INVALID
};

enum RawrOwnershipState : RAWR_U32 {
    RAWR_OWNERSHIP_NONE = 0,
    RAWR_OWNERSHIP_CALLER,
    RAWR_OWNERSHIP_MODEL,
    RAWR_OWNERSHIP_RUNTIME,
    RAWR_OWNERSHIP_DEVICE,
    RAWR_OWNERSHIP_KERNEL,
    RAWR_OWNERSHIP_STREAM,
    RAWR_OWNERSHIP_TRANSFER,
    RAWR_OWNERSHIP_RELEASED
};

enum RawrDataValidity : RAWR_U32 {
    RAWR_DATA_UNKNOWN = 0,
    RAWR_DATA_UNINITIALIZED,
    RAWR_DATA_INITIALIZED,
    RAWR_DATA_FINITE,
    RAWR_DATA_NONZERO,
    RAWR_DATA_NUMERIC_VALID,
    RAWR_DATA_PARITY_VALID,
    RAWR_DATA_INVALID
};

enum RawrPerformanceClass : RAWR_U32 {
    RAWR_PERF_UNKNOWN = 0,
    RAWR_PERF_UNMEASURED,
    RAWR_PERF_MEASURED,
    RAWR_PERF_OVER_BUDGET,
    RAWR_PERF_WITHIN_BUDGET,
    RAWR_PERF_WINNER
};

enum RawrTeardownState : RAWR_U32 {
    RAWR_TEARDOWN_NONE = 0,
    RAWR_TEARDOWN_ENTERED,
    RAWR_TEARDOWN_STREAM_STOPPED,
    RAWR_TEARDOWN_WORK_DRAINED,
    RAWR_TEARDOWN_QUEUES_IDLE,
    RAWR_TEARDOWN_RESOURCES_RELEASED,
    RAWR_TEARDOWN_DEVICE_IDLE,
    RAWR_TEARDOWN_WITNESS,
    RAWR_TEARDOWN_COMPLETE
};
