#pragma once
/* Streamer vocabulary — enums only (names in RawrStreamerNames.hpp). */
#ifndef RAWR_U32
#define RAWR_U32 unsigned int
#endif
#ifndef RAWR_U64
#define RAWR_U64 unsigned long long
#endif
#ifndef RAWR_F64
#define RAWR_F64 double
#endif

enum RawrStreamState : RAWR_U32 {
    RAWR_STREAM_COLD = 0,
    RAWR_STREAM_BOOT,
    RAWR_STREAM_MODEL_RESOLVE,
    RAWR_STREAM_MODEL_OPEN,
    RAWR_STREAM_MODEL_INDEX,
    RAWR_STREAM_MODEL_FACTS,
    RAWR_STREAM_TOKENIZER_OPEN,
    RAWR_STREAM_EXEC_CREATE,
    RAWR_STREAM_CAP_DISCOVER,
    RAWR_STREAM_SPACE_SNAPSHOT,
    RAWR_STREAM_PLAN,
    RAWR_STREAM_PREFILL,
    RAWR_STREAM_DECODE,
    RAWR_STREAM_EMIT,
    RAWR_STREAM_COMPLETE,
    RAWR_STREAM_BLOCKED,
    RAWR_STREAM_FAIL
};

enum RawrStreamStage : RAWR_U32 {
    RAWR_STAGE_NONE = 0,
    RAWR_STAGE_CLI_PARSE,
    RAWR_STAGE_ENV_BIND,
    RAWR_STAGE_MODEL_LOCATE,
    RAWR_STAGE_GGUF_OPEN,
    RAWR_STAGE_GGUF_INDEX,
    RAWR_STAGE_TENSOR_INDEX,
    RAWR_STAGE_ARCH_FACTS,
    RAWR_STAGE_TOKENIZER_LOAD,
    RAWR_STAGE_EXEC_INSTANCE,
    RAWR_STAGE_DEVICE_DISCOVER,
    RAWR_STAGE_CAPABILITY_SOLVE,
    RAWR_STAGE_GEOMETRY_PROBE,
    RAWR_STAGE_SHADER_VARIANTS,
    RAWR_STAGE_KERNEL_CANDIDATES,
    RAWR_STAGE_LEGALITY_FILTER,
    RAWR_STAGE_PARITY_MEASURE,
    RAWR_STAGE_WINNER_SELECT,
    RAWR_STAGE_PROMPT_TOKENIZE,
    RAWR_STAGE_EMBED,
    RAWR_STAGE_PREFILL_LAYER,
    RAWR_STAGE_DECODE_LAYER,
    RAWR_STAGE_ATTENTION,
    RAWR_STAGE_Q_PROJ,
    RAWR_STAGE_K_PROJ,
    RAWR_STAGE_V_PROJ,
    RAWR_STAGE_QKV_PROJ,
    RAWR_STAGE_KVA,
    RAWR_STAGE_O_PROJ,
    RAWR_STAGE_FFN_GATE,
    RAWR_STAGE_FFN_UP,
    RAWR_STAGE_FFN_DOWN,
    RAWR_STAGE_RMSNORM,
    RAWR_STAGE_FINAL_NORM,
    RAWR_STAGE_LOGITS,
    RAWR_STAGE_SAMPLE,
    RAWR_STAGE_DETOKENIZE,
    RAWR_STAGE_TOKEN_EMIT,
    RAWR_STAGE_STOP_CHECK,
    RAWR_STAGE_TEARDOWN
};

enum RawrStreamEvent : RAWR_U32 {
    RAWR_EVENT_NONE = 0,
    RAWR_EVENT_RUN_BEGIN,
    RAWR_EVENT_RUN_READY,
    RAWR_EVENT_RUN_BLOCKED,
    RAWR_EVENT_RUN_FAIL,
    RAWR_EVENT_RUN_COMPLETE,
    RAWR_EVENT_MODEL_FOUND,
    RAWR_EVENT_MODEL_OPENED,
    RAWR_EVENT_MODEL_INDEXED,
    RAWR_EVENT_MODEL_FACTS_BOUND,
    RAWR_EVENT_MODEL_EXEC_CREATED,
    RAWR_EVENT_TENSOR_DISCOVERED,
    RAWR_EVENT_TENSOR_ADDRESSED,
    RAWR_EVENT_TENSOR_REGISTERED,
    RAWR_EVENT_TENSOR_ACQUIRE_BEGIN,
    RAWR_EVENT_TENSOR_ACQUIRE_DONE,
    RAWR_EVENT_TENSOR_RELEASE,
    RAWR_EVENT_CAPS_DISCOVERED,
    RAWR_EVENT_SPACE_SNAPSHOT,
    RAWR_EVENT_SHAPE_LEGAL,
    RAWR_EVENT_SHAPE_REJECTED,
    RAWR_EVENT_KERNEL_DISPATCH,
    RAWR_EVENT_KERNEL_PARITY_PASS,
    RAWR_EVENT_KERNEL_PARITY_FAIL,
    RAWR_EVENT_KERNEL_MEASURED,
    RAWR_EVENT_KERNEL_WINNER,
    RAWR_EVENT_PREFILL_BEGIN,
    RAWR_EVENT_PREFILL_DONE,
    RAWR_EVENT_DECODE_BEGIN,
    RAWR_EVENT_DECODE_STEP_BEGIN,
    RAWR_EVENT_DECODE_STEP_DONE,
    RAWR_EVENT_EMBED_WRITTEN,
    RAWR_EVENT_LAYER_WRITTEN,
    RAWR_EVENT_FINAL_NORM_WRITTEN,
    RAWR_EVENT_LOGITS_WRITTEN,
    RAWR_EVENT_TOKEN_SAMPLED,
    RAWR_EVENT_TOKEN_EMITTED,
    RAWR_EVENT_STOP_EOS,
    RAWR_EVENT_STOP_MAX_TOKENS,
    RAWR_EVENT_STOP_USER_CANCEL,
    RAWR_EVENT_STOP_ERROR
};

enum RawrStreamStatus : RAWR_U32 {
    RAWR_STATUS_UNKNOWN = 0,
    RAWR_STATUS_PASS,
    RAWR_STATUS_OPEN,
    RAWR_STATUS_BLOCKED,
    RAWR_STATUS_FAIL,
    RAWR_STATUS_SKIP,
    RAWR_STATUS_RETRY,
    RAWR_STATUS_RECOVERED
};

enum RawrStreamBlocker : RAWR_U32 {
    RAWR_BLOCK_NONE = 0,
    RAWR_BLOCK_MODEL_NOT_FOUND,
    RAWR_BLOCK_MODEL_OPEN_FAIL,
    RAWR_BLOCK_GGUF_INVALID,
    RAWR_BLOCK_TENSOR_MISSING,
    RAWR_BLOCK_TENSOR_UNADDRESSED,
    RAWR_BLOCK_TENSOR_UNACQUIRED,
    RAWR_BLOCK_TOKENIZER_MISSING,
    RAWR_BLOCK_MODEL_FACT_INVALID,
    RAWR_BLOCK_EXEC_INSTANCE_INVALID,
    RAWR_BLOCK_NO_DEVICE,
    RAWR_BLOCK_NO_LEGAL_SHAPE,
    RAWR_BLOCK_NO_SHADER_VARIANT,
    RAWR_BLOCK_NO_PARITY_PASS,
    RAWR_BLOCK_NO_MEASURE,
    RAWR_BLOCK_NO_WINNER,
    RAWR_BLOCK_EMBED_ZERO,
    RAWR_BLOCK_LAYER_ZERO,
    RAWR_BLOCK_FINAL_NORM_ZERO,
    RAWR_BLOCK_LOGITS_ZERO,
    RAWR_BLOCK_SAMPLE_INVALID,
    RAWR_BLOCK_MEMORY_PRESSURE,
    RAWR_BLOCK_DEVICE_LOST,
    RAWR_BLOCK_QUEUE_FAIL,
    RAWR_BLOCK_DISPATCH_FAIL,
    RAWR_BLOCK_PARITY_FAIL,
    RAWR_BLOCK_TIMEOUT
};

struct RawrStreamReceipt {
    RAWR_U64 generation;
    RAWR_U64 sequence;
    RAWR_U32 state;
    RAWR_U32 stage;
    RAWR_U32 event;
    RAWR_U32 status;
    RAWR_U32 blocker;
    RAWR_U64 timestamp_ns;
    RAWR_U64 wall_us;
    RAWR_U64 value_u64;
    RAWR_F64 value_f64;
    const char* key;
    const char* text;
};
