// ResidencyPlan.generated.hpp — auto-generated residency policy frontier from GGUF tensor directory
// This file is generated by GgufStaticResidency tool during model admission.
// DO NOT EDIT MANUALLY.

#pragma once
#include <cstdint>
#include <array>
#include "GgufDynamicGeometry.hpp"

namespace Deep2 {

// Residency policy enumeration
enum class ResidencyPolicy : uint8_t {
    PIN_EMBED_AND_HEAD = 0,   // Standard: embedding + output head pinned, one layer streamed
    PIN_EMBED_ONLY = 1,       // Only embedding pinned, head streamable
    FULLY_STREAMABLE = 2,     // Theoretical floor: nothing pinned
};

// Integrity verdict for GGUF ROM verification
enum class IntegrityVerdict : uint8_t {
    UNVERIFIED = 0,
    COMPLETE = 1,
    TRUNCATED = 2,
    OVERSIZE = 3,
    UNKNOWN_TYPES_WEAKENED = 4,
};

// Single point on the residency frontier
struct ResidencyPoint {
    uint32_t ringDepth;
    uint64_t requiredBytes;
    double maximumReduction;
};

// Static residency plan derived from GGUF tensor directory
struct ResidencyPlan {
    // Model identification
    char modelName[128] = {};
    uint64_t modelFileBytes = 0;
    uint32_t modelVersion = 0;
    char arch[64] = {};
    uint32_t layers = 0;
    uint32_t hidden = 0;
    uint32_t ffn = 0;
    uint32_t heads = 0;
    uint32_t kvHeads = 0;
    uint32_t headDim = 0;
    uint32_t context = 0;
    
    // ROM bytes
    uint64_t totalWeightBytes = 0;
    uint64_t embedBytes = 0;
    uint64_t outputHeadBytes = 0;
    uint64_t maxLayerBytes = 0;
    uint64_t minLayerBytes = 0;
    uint64_t kvCacheBytesPerToken = 0;
    
    // M_min policy floor
    uint64_t mMinPinEmbedAndHead = 0;
    uint64_t mMinPinEmbedOnly = 0;
    uint64_t mMinFullyStreamable = 0;
    
    // Ring depth frontier (feasible static bounds)
    uint64_t ringK1 = 0;
    uint64_t ringK2 = 0;
    uint64_t ringK3 = 0;
    uint64_t ringK4 = 0;
    uint64_t ringK6 = 0;
    uint64_t ringK8 = 0;
    
    // Integrity verification
    IntegrityVerdict integrityVerdict = IntegrityVerdict::UNVERIFIED;
    uint64_t actualFileBytes = 0;
    uint64_t requiredFileBytes = 0;
    uint64_t shortfallBytes = 0;
    uint8_t unknownTypeCount = 0;
    uint8_t overlappingTensors = 0;
    uint8_t misalignedOffsets = 0;
    uint8_t offsetOverflows = 0;
    
    // Feasible frontier as array (for static initialization)
    static constexpr uint32_t MAX_FRONTIER_POINTS = 8;
    ResidencyPoint frontier[MAX_FRONTIER_POINTS] = {};
    uint32_t frontierCount = 0;
    
    // Helpers
    inline bool isTruncated() const { return integrityVerdict == IntegrityVerdict::TRUNCATED; }
    inline bool isAdmissible() const { return integrityVerdict == IntegrityVerdict::COMPLETE; }
    inline double maxReduction() const { return frontierCount > 0 ? frontier[frontierCount - 1].maximumReduction : 0.0; }
    
    // Find the deepest ring that fits within a memory budget
    inline int maxRingDepth(uint64_t budgetBytes) const {
        for (int i = (int)frontierCount - 1; i >= 0; --i) {
            if (frontier[i].requiredBytes <= budgetBytes) return frontier[i].ringDepth;
        }
        return -1;
    }
};

// Generate ResidencyPlan from GGUF file (populates 'plan' from 'geom')
// Returns true on success, false on failure.
bool GenerateResidencyPlan(const GgufDynamicGeometry& geom, ResidencyPlan& plan);

} // namespace Deep2