#pragma once
/* 0(*) — AUTOTUNE ⊂ GENERATION. Never AUTOTUNE → EXIT → GENERATION. */
#define RAWRXD_ZERO_STAR_CONTRACT 1
#define SEPARATE_HARNESS 0
#define SYNTHETIC_OPERANDS 0
#define BENCHMARK_ONLY_RUN 0
#define RESTART_AFTER_TUNE 0
#define FAKE_GENERATION 0
#define PARITY_BEFORE_PROMOTION 1
#define MEASURE_BEFORE_WINNER 1
#define WINNER_PERSISTS_FOR_REMAINDER 1
#define TERMINAL_RECEIPT_REQUIRES_TEXT 1
#define CLEAN_TEARDOWN_WITNESS_REQUIRED 1
/*
  REQUIRED:
    MODEL_OPEN → INDEX → TOKENIZER → PROMPT_TOKENIZE → PREFILL →
    LIVE_LAYER_FORWARD → {FIRST_QKV climb | FIRST_KVA tune} on LIVE operands →
    REMAINING_LAYERS → FINAL_NORM → LOGITS → SAMPLE → DETOKENIZE →
    EMIT_TEXT → DECODE[N] → CLEAN_TEARDOWN → TERMINAL_RECEIPT

  TUNE_GENERATION_ID == CONTINUED_GENERATION_ID
  QKV/KVA_TUNE_OPERANDS == LIVE_GENERATION_OPERANDS

  PASS only if ACTUAL_TEXT_BYTES>0 && GENERATED_TOKENS>0 &&
  PRODUCTION_DECODE_PATH=1 && TEARDOWN_WITNESS=1 && HARNESS_ABORT=0.
*/
