//=============================================================================
// HeaderEmitter Implementation
// RAWRXD_MODEL_GENIE_HEADER_EXPORT_001
//=============================================================================

#include "HeaderEmitter.hpp"
#include <filesystem>
#include <iomanip>
#include <iostream>

namespace RawrXD {
namespace Deep2 {
namespace ModelGenie {

HeaderEmitter::HeaderEmitter(const std::string& outputDir) : outputDir_(outputDir) {
    std::filesystem::create_directories(outputDir_);
}

std::ofstream HeaderEmitter::OpenHeader(const std::string& filename, const std::string& guardName) {
    std::filesystem::path fullPath = std::filesystem::path(outputDir_) / filename;
    std::ofstream out(fullPath);
    
    if (!out.is_open()) {
        return out;
    }
    
    out << "#ifndef " << guardName << "\n";
    out << "#define " << guardName << "\n\n";
    out << "//=============================================================================\n";
    out << "// AUTO-GENERATED by RAWRXD_MODEL_GENIE_HEADER_EXPORT_001\n";
    out << "// DO NOT EDIT MANUALLY\n";
    out << "// Source: NUGVERSE_ESTIMATOR_001 (frozen)\n";
    out << "//=============================================================================\n\n";
    out << "#pragma once\n\n";
    out << "#include <cstdint>\n";
    out << "#include <array>\n";
    out << "#include <optional>\n";
    out << "#include \"ModelGenome.hpp\"\n\n";
    
    return out;
}

void HeaderEmitter::WritePreamble(std::ofstream& out, const std::string& guardName, const std::string& description) {
    out << "// " << description << "\n";
    out << "// Generated from ModelGenome: " << guardName << "\n\n";
}

void HeaderEmitter::Indent(std::ofstream& out, int level) {
    for (int i = 0; i < level; ++i) out << "    ";
}

std::string HeaderEmitter::FormatDims(const std::array<uint32_t, 4>& dims) {
    std::stringstream ss;
    ss << "{";
    bool first = true;
    for (uint32_t d : dims) {
        if (d > 0) {
            if (!first) ss << ", ";
            ss << d;
            first = false;
        }
    }
    ss << "}";
    return ss.str();
}

std::string HeaderEmitter::FormatTensorRole(TensorRole role) {
    switch (role) {
        case TensorRole::Embed: return "TensorRole::Embed";
        case TensorRole::Output: return "TensorRole::Output";
        case TensorRole::Norm: return "TensorRole::Norm";
        case TensorRole::Attn: return "TensorRole::Attn";
        case TensorRole::FFN: return "TensorRole::FFN";
        case TensorRole::Router: return "TensorRole::Router";
        case TensorRole::Expert: return "TensorRole::Expert";
        case TensorRole::KVLatent: return "TensorRole::KVLatent";
        default: return "TensorRole::Unknown";
    }
}

std::string HeaderEmitter::FormatOpCode(OpCode opcode) {
    return std::to_string(static_cast<uint32_t>(opcode));
}

std::string HeaderEmitter::FormatPrimitive(Primitive prim) {
    return std::to_string(static_cast<uint32_t>(prim));
}

std::string HeaderEmitter::FormatOperandDomain(OperandDomain domain) {
    return std::to_string(static_cast<uint32_t>(domain));
}

std::string HeaderEmitter::FormatOperandRef(const OperandRef& ref) {
    std::stringstream ss;
    ss << "{" << FormatOperandDomain(ref.domain) << ", " << ref.id << "}";
    return ss.str();
}

std::string HeaderEmitter::FormatArchitecture(Architecture arch) {
    switch (arch) {
        case Architecture::DeepSeek2: return "Architecture::DeepSeek2";
        case Architecture::Llama: return "Architecture::Llama";
        case Architecture::Mistral: return "Architecture::Mistral";
        case Architecture::Qwen: return "Architecture::Qwen";
        case Architecture::GptOss: return "Architecture::GptOss";
        default: return "Architecture::Unknown";
    }
}

std::string HeaderEmitter::FormatRopeScaling(RopeScalingType scaling) {
    switch (scaling) {
        case RopeScalingType::Yarn: return "RopeScalingType::Yarn";
        case RopeScalingType::Linear: return "RopeScalingType::Linear";
        default: return "RopeScalingType::None";
    }
}

std::string HeaderEmitter::FormatWeightTying(WeightTying tying) {
    return tying == WeightTying::Tied ? "WeightTying::Tied" : "WeightTying::Untied";
}

bool HeaderEmitter::EmitAll(const ModelGenome& genome) {
    bool ok = true;
    ok &= EmitModelIdentity(genome);
    ok &= EmitModelConfig(genome);
    ok &= EmitTensorROM(genome);
    ok &= EmitBlockGenome(genome);
    ok &= EmitExecutionIR(genome);
    ok &= EmitCapabilityManifest(genome);
    ok &= EmitResidencyPlan(genome);
    ok &= EmitModelExport(genome);
    return ok;
}

//=============================================================================
// ModelIdentity.generated.hpp
//=============================================================================
bool HeaderEmitter::EmitModelIdentity(const ModelGenome& genome) {
    auto out = OpenHeader("ModelIdentity.generated.hpp", "MODEL_IDENTITY_GENERATED_HPP");
    if (!out.is_open()) return false;
    
    WritePreamble(out, "MODEL_IDENTITY_GENERATED_HPP", "Model identity and architecture type");
    
    out << "namespace RawrXD {\n";
    out << "namespace Deep2 {\n";
    out << "namespace Generated {\n\n";
    
    out << "inline constexpr const char* kModelName = \"" << genome.modelName << "\";\n";
    out << "inline constexpr Architecture kArchitecture = " << FormatArchitecture(genome.architecture) << ";\n";
    out << "inline constexpr const char* kArchitectureName = \"" << ArchitectureToString(genome.architecture) << "\";\n\n";
    
    out << "} // namespace Generated\n";
    out << "} // namespace Deep2\n";
    out << "} // namespace RawrXD\n\n";
    
    out << "#endif // MODEL_IDENTITY_GENERATED_HPP\n";
    return true;
}

//=============================================================================
// ModelConfig.generated.hpp
//=============================================================================
bool HeaderEmitter::EmitModelConfig(const ModelGenome& genome) {
    auto out = OpenHeader("ModelConfig.generated.hpp", "MODEL_CONFIG_GENERATED_HPP");
    if (!out.is_open()) return false;
    
    WritePreamble(out, "MODEL_CONFIG_GENERATED_HPP", "Model architecture configuration parameters");
    
    out << "namespace RawrXD {\n";
    out << "namespace Deep2 {\n";
    out << "namespace Generated {\n\n";
    
    out << "struct ModelConfig {\n";
    Indent(out, 1); out << "static constexpr uint32_t kBlockCount = " << genome.blockCount << ";\n";
    Indent(out, 1); out << "static constexpr uint32_t kEmbeddingLength = " << genome.embeddingLength << ";\n";
    Indent(out, 1); out << "static constexpr uint32_t kFeedForwardLength = " << genome.feedForwardLength << ";\n";
    Indent(out, 1); out << "static constexpr uint64_t kContextLength = " << genome.contextLength << "ULL;\n";
    Indent(out, 1); out << "static constexpr uint32_t kVocabSize = " << genome.vocabSize << ";\n";
    Indent(out, 1); out << "static constexpr uint32_t kHeadCount = " << genome.headCount << ";\n";
    Indent(out, 1); out << "static constexpr uint32_t kHeadCountKv = " << genome.headCountKv << ";\n";
    Indent(out, 1); out << "static constexpr uint64_t kRopeFreqBase = " << genome.ropeFreqBase << "ULL;\n";
    Indent(out, 1); out << "static constexpr uint32_t kRopeDimensionCount = " << genome.ropeDimensionCount << ";\n";
    Indent(out, 1); out << "static constexpr RopeScalingType kRopeScalingType = " << FormatRopeScaling(genome.ropeScalingType) << ";\n";
    Indent(out, 1); out << "static constexpr double kRmsEps = " << genome.rmsEps << ";\n\n";
    
    Indent(out, 1); out << "// MoE\n";
    Indent(out, 1); out << "static constexpr uint32_t kExpertCount = " << genome.expertCount << ";\n";
    Indent(out, 1); out << "static constexpr uint32_t kExpertUsedCount = " << genome.expertUsedCount << ";\n";
    Indent(out, 1); out << "static constexpr uint32_t kExpertSharedCount = " << genome.expertSharedCount << ";\n";
    Indent(out, 1); out << "static constexpr uint32_t kExpertFfnLength = " << genome.expertFfnLength << ";\n";
    Indent(out, 1); out << "static constexpr uint32_t kLeadingDenseBlocks = " << genome.leadingDenseBlocks << ";\n\n";
    
    Indent(out, 1); out << "// MLA\n";
    Indent(out, 1); out << "static constexpr uint32_t kKvLoraRank = " << genome.kvLoraRank << ";\n";
    Indent(out, 1); out << "static constexpr uint32_t kKeyLength = " << genome.keyLength << ";\n";
    Indent(out, 1); out << "static constexpr uint32_t kValueLength = " << genome.valueLength << ";\n";
    Indent(out, 1); out << "static constexpr WeightTying kWeightTying = " << FormatWeightTying(genome.weightTying) << ";\n\n";
    
    Indent(out, 1); out << "// Derived\n";
    Indent(out, 1); out << "static constexpr uint64_t kExactParams = " << genome.exactParams << "ULL;\n";
    Indent(out, 1); out << "static constexpr uint64_t kEncodedWeightBytes = " << genome.encodedWeightBytes << "ULL;\n";
    Indent(out, 1); out << "static constexpr double kEffectiveBpw = " << genome.effectiveBpw << ";\n\n";
    
    Indent(out, 1); out << "// Physical\n";
    Indent(out, 1); out << "static constexpr uint64_t kFileBytes = " << genome.fileBytes << "ULL;\n";
    Indent(out, 1); out << "static constexpr uint32_t kGgufVersion = " << genome.ggufVersion << ";\n";
    Indent(out, 1); out << "static constexpr uint32_t kTensorCount = " << genome.tensorCount << ";\n";
    Indent(out, 1); out << "static constexpr uint32_t kAlignment = " << genome.alignment << ";\n";
    Indent(out, 1); out << "static constexpr uint64_t kDataStart = " << genome.dataStart << "ULL;\n";
    
    out << "};\n\n";
    
    out << "} // namespace Generated\n";
    out << "} // namespace Deep2\n";
    out << "} // namespace RawrXD\n\n";
    
    out << "#endif // MODEL_CONFIG_GENERATED_HPP\n";
    return true;
}

//=============================================================================
// TensorROM.generated.hpp
//=============================================================================
bool HeaderEmitter::EmitTensorROM(const ModelGenome& genome) {
    auto out = OpenHeader("TensorROM.generated.hpp", "TENSOR_ROM_GENERATED_HPP");
    if (!out.is_open()) return false;
    
    WritePreamble(out, "TENSOR_ROM_GENERATED_HPP", "Tensor ROM descriptors (no runtime name parsing)");
    
    out << "namespace RawrXD {\n";
    out << "namespace Deep2 {\n";
    out << "namespace Generated {\n\n";
    
    out << "struct TensorROM {\n";
    Indent(out, 1); out << "uint32_t tensorId;\n";
    Indent(out, 1); out << "const char* name;\n";
    Indent(out, 1); out << "TensorRole role;\n";
    Indent(out, 1); out << "int32_t blockIndex;\n";
    Indent(out, 1); out << "GGMLType type;\n";
    Indent(out, 1); out << "std::array<uint32_t, 4> dims;\n";
    Indent(out, 1); out << "uint32_t rank;\n";
    Indent(out, 1); out << "uint64_t encodedBytes;\n";
    Indent(out, 1); out << "uint64_t dataOffset;\n";
    Indent(out, 1); out << "uint64_t elementCount;\n";
    out << "};\n\n";
    
    out << "inline constexpr uint64_t kModelDataStart = " << genome.dataStart << "ULL;\n\n";
    
    // TensorId enum
    out << "enum class TensorId : uint32_t {\n";
    for (const auto& t : genome.tensors) {
        // Sanitize name for C++ enum
        std::string enumName = t.name;
        std::replace(enumName.begin(), enumName.end(), '.', '_');
        std::replace(enumName.begin(), enumName.end(), '-', '_');
        Indent(out, 1); out << enumName << " = " << t.tensorId << ",\n";
    }
    Indent(out, 1); out << "Count = " << genome.tensors.size() << "\n";
    out << "};\n\n";
    
    // ROM table
    out << "inline constexpr TensorROM kTensorROMTable[" << genome.tensors.size() << "] = {\n";
    for (const auto& t : genome.tensors) {
        Indent(out, 1); out << "{\n";
        Indent(out, 2); out << ".tensorId = " << t.tensorId << ",\n";
        Indent(out, 2); out << ".name = \"" << t.name << "\",\n";
        Indent(out, 2); out << ".role = " << FormatTensorRole(t.role) << ",\n";
        Indent(out, 2); out << ".blockIndex = " << t.blockIndex << ",\n";
        Indent(out, 2); out << ".type = GGMLType::" << (t.type == GGMLType::F32 ? "F32" : 
                            t.type == GGMLType::Q4_K ? "Q4_K" :
                            t.type == GGMLType::Q5_0 ? "Q5_0" :
                            t.type == GGMLType::Q6_K ? "Q6_K" : "Q8_0") << ",\n";
        Indent(out, 2); out << ".dims = " << FormatDims(t.dims) << ",\n";
        Indent(out, 2); out << ".rank = " << t.rank << ",\n";
        Indent(out, 2); out << ".encodedBytes = " << t.encodedBytes << "ULL,\n";
        Indent(out, 2); out << ".dataOffset = " << t.fileOffset << "ULL,\n";
        Indent(out, 2); out << ".elementCount = " << t.elementCount << "ULL\n";
        Indent(out, 1); out << "},\n";
    }
    out << "};\n\n";
    
    out << "inline constexpr uint32_t kTensorCount = " << genome.tensors.size() << ";\n\n";
    
    out << "} // namespace Generated\n";
    out << "} // namespace Deep2\n";
    out << "} // namespace RawrXD\n\n";
    
    out << "#endif // TENSOR_ROM_GENERATED_HPP\n";
    return true;
}

//=============================================================================
// BlockGenome.generated.hpp
//=============================================================================
bool HeaderEmitter::EmitBlockGenome(const ModelGenome& genome) {
    auto out = OpenHeader("BlockGenome.generated.hpp", "BLOCK_GENOME_GENERATED_HPP");
    if (!out.is_open()) return false;
    
    WritePreamble(out, "BLOCK_GENOME_GENERATED_HPP", "Per-block tensor topology");
    
    out << "namespace RawrXD {\n";
    out << "namespace Deep2 {\n";
    out << "namespace Generated {\n\n";
    
    out << "struct BlockGenome {\n";
    Indent(out, 1); out << "uint32_t blockIndex;\n";
    Indent(out, 1); out << "bool isDense;\n";
    Indent(out, 1); out << "bool isMoE;\n\n";
    
    Indent(out, 1); out << "// Dense block tensors (block 0)\n";
    Indent(out, 1); out << "std::optional<uint32_t> attnNorm;\n";
    Indent(out, 1); out << "std::optional<uint32_t> ffnNorm;\n";
    Indent(out, 1); out << "std::optional<uint32_t> attnKvANorm;\n";
    Indent(out, 1); out << "std::optional<uint32_t> attnKvAMqa;\n";
    Indent(out, 1); out << "std::optional<uint32_t> attnKvB;\n";
    Indent(out, 1); out << "std::optional<uint32_t> attnOutput;\n";
    Indent(out, 1); out << "std::optional<uint32_t> attnQ;\n";
    Indent(out, 1); out << "std::optional<uint32_t> ffnDown;\n";
    Indent(out, 1); out << "std::optional<uint32_t> ffnGate;\n";
    Indent(out, 1); out << "std::optional<uint32_t> ffnUp;\n\n";
    
    Indent(out, 1); out << "// MoE block tensors (blocks 1..N-1)\n";
    Indent(out, 1); out << "std::optional<uint32_t> ffnDownExps;\n";
    Indent(out, 1); out << "std::optional<uint32_t> ffnGateExps;\n";
    Indent(out, 1); out << "std::optional<uint32_t> ffnUpExps;\n";
    Indent(out, 1); out << "std::optional<uint32_t> ffnGateInp;\n";
    Indent(out, 1); out << "std::optional<uint32_t> ffnDownShExp;\n";
    Indent(out, 1); out << "std::optional<uint32_t> ffnGateShExp;\n";
    Indent(out, 1); out << "std::optional<uint32_t> ffnUpShExp;\n";
    out << "};\n\n";
    
    // ExpertBank
    out << "struct ExpertBank {\n";
    Indent(out, 1); out << "uint32_t blockIndex;\n";
    Indent(out, 1); out << "uint32_t routedExpertCount;\n";
    Indent(out, 1); out << "uint32_t activeExpertCount;\n";
    Indent(out, 1); out << "uint32_t sharedExpertCount;\n";
    Indent(out, 1); out << "uint32_t routerTensorId;\n";
    Indent(out, 1); out << "uint32_t sharedDownTensorId;\n";
    Indent(out, 1); out << "uint32_t sharedGateTensorId;\n";
    Indent(out, 1); out << "uint32_t sharedUpTensorId;\n";
    Indent(out, 1); out << "std::array<uint32_t, 64> routedDownTensorIds;\n";
    Indent(out, 1); out << "std::array<uint32_t, 64> routedGateTensorIds;\n";
    Indent(out, 1); out << "std::array<uint32_t, 64> routedUpTensorIds;\n";
    Indent(out, 1); out << "double expertRomSharePercent;\n";
    out << "};\n\n";
    
    // Block table
    out << "inline constexpr BlockGenome kBlockGenomeTable[" << genome.blockCount << "] = {\n";
    for (const auto& b : genome.blocks) {
        Indent(out, 1); out << "{\n";
        Indent(out, 2); out << ".blockIndex = " << b.blockIndex << ",\n";
        Indent(out, 2); out << ".isDense = " << (b.isDense ? "true" : "false") << ",\n";
        Indent(out, 2); out << ".isMoE = " << (b.isMoE ? "true" : "false") << ",\n";
        Indent(out, 2); out << ".attnNorm = " << (b.attnNorm ? std::to_string(b.attnNorm.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".ffnNorm = " << (b.ffnNorm ? std::to_string(b.ffnNorm.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".attnKvANorm = " << (b.attnKvANorm ? std::to_string(b.attnKvANorm.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".attnKvAMqa = " << (b.attnKvAMqa ? std::to_string(b.attnKvAMqa.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".attnKvB = " << (b.attnKvB ? std::to_string(b.attnKvB.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".attnOutput = " << (b.attnOutput ? std::to_string(b.attnOutput.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".attnQ = " << (b.attnQ ? std::to_string(b.attnQ.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".ffnDown = " << (b.ffnDown ? std::to_string(b.ffnDown.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".ffnGate = " << (b.ffnGate ? std::to_string(b.ffnGate.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".ffnUp = " << (b.ffnUp ? std::to_string(b.ffnUp.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".ffnDownExps = " << (b.ffnDownExps ? std::to_string(b.ffnDownExps.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".ffnGateExps = " << (b.ffnGateExps ? std::to_string(b.ffnGateExps.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".ffnUpExps = " << (b.ffnUpExps ? std::to_string(b.ffnUpExps.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".ffnGateInp = " << (b.ffnGateInp ? std::to_string(b.ffnGateInp.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".ffnDownShExp = " << (b.ffnDownShExp ? std::to_string(b.ffnDownShExp.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".ffnGateShExp = " << (b.ffnGateShExp ? std::to_string(b.ffnGateShExp.value()) : "std::nullopt") << ",\n";
        Indent(out, 2); out << ".ffnUpShExp = " << (b.ffnUpShExp ? std::to_string(b.ffnUpShExp.value()) : "std::nullopt") << "\n";
        Indent(out, 1); out << "},\n";
    }
    out << "};\n\n";
    
    // Expert bank table
    out << "inline constexpr ExpertBank kExpertBankTable[" << genome.expertBanks.size() << "] = {\n";
    for (const auto& bank : genome.expertBanks) {
        Indent(out, 1); out << "{\n";
        Indent(out, 2); out << ".blockIndex = " << bank.blockIndex << ",\n";
        Indent(out, 2); out << ".routedExpertCount = " << bank.routedExpertCount << ",\n";
        Indent(out, 2); out << ".activeExpertCount = " << bank.activeExpertCount << ",\n";
        Indent(out, 2); out << ".sharedExpertCount = " << bank.sharedExpertCount << ",\n";
        Indent(out, 2); out << ".routerTensorId = " << bank.routerTensorId << ",\n";
        Indent(out, 2); out << ".sharedDownTensorId = " << bank.sharedDownTensorId << ",\n";
        Indent(out, 2); out << ".sharedGateTensorId = " << bank.sharedGateTensorId << ",\n";
        Indent(out, 2); out << ".sharedUpTensorId = " << bank.sharedUpTensorId << ",\n";
        Indent(out, 2); out << ".routedDownTensorIds = {";
        for (size_t i = 0; i < bank.routedDownTensorIds.size(); ++i) {
            if (i > 0) out << ", ";
            out << bank.routedDownTensorIds[i];
        }
        out << "},\n";
        Indent(out, 2); out << ".routedGateTensorIds = {";
        for (size_t i = 0; i < bank.routedGateTensorIds.size(); ++i) {
            if (i > 0) out << ", ";
            out << bank.routedGateTensorIds[i];
        }
        out << "},\n";
        Indent(out, 2); out << ".routedUpTensorIds = {";
        for (size_t i = 0; i < bank.routedUpTensorIds.size(); ++i) {
            if (i > 0) out << ", ";
            out << bank.routedUpTensorIds[i];
        }
        out << "},\n";
        Indent(out, 2); out << ".expertRomSharePercent = " << bank.expertRomSharePercent << "\n";
        Indent(out, 1); out << "},\n";
    }
    out << "};\n\n";
    
    out << "inline constexpr uint32_t kBlockCount = " << genome.blockCount << ";\n";
    out << "inline constexpr uint32_t kLeadingDenseBlocks = " << genome.leadingDenseBlocks << ";\n\n";
    
    out << "} // namespace Generated\n";
    out << "} // namespace Deep2\n";
    out << "} // namespace RawrXD\n\n";
    
    out << "#endif // BLOCK_GENOME_GENERATED_HPP\n";
    return true;
}

//=============================================================================
// SSA Validation Gate (pre-emission)
//=============================================================================
bool HeaderEmitter::ValidateExecutionIR(const ModelGenome& genome) {
    // Track activation definitions and uses
    std::unordered_set<uint32_t> definedActivations;
    std::unordered_map<uint32_t, uint32_t> activationDefCount;
    std::unordered_map<uint32_t, std::vector<uint32_t>> activationUses;
    std::unordered_set<uint32_t> romTensorIds;
    
    // Collect all ROM tensor IDs
    for (const auto& t : genome.tensors) {
        romTensorIds.insert(t.tensorId);
    }
    
    // RuntimeScalar 0 is the token input
    const uint32_t kTokenRuntimeScalarId = 0;
    
    for (const auto& op : genome.executionOps) {
        // Check ROM operands (weights)
        for (uint32_t i = 0; i < op.weightCount; ++i) {
            const auto& w = op.weight(i);
            if (w.domain == OperandDomain::RomTensor) {
                if (romTensorIds.find(w.id) == romTensorIds.end()) {
                    std::cerr << "SSA Validation FAIL: Op " << op.opId 
                              << " references ROM tensor " << w.id << " not in tensor directory\n";
                    return false;
                }
            } else if (w.domain != OperandDomain::None) {
                std::cerr << "SSA Validation FAIL: Op " << op.opId 
                          << " weight operand must be RomTensor, got " << (int)w.domain << "\n";
                return false;
            }
        }
        
        // Check input operands
        for (uint32_t i = 0; i < op.inputCount; ++i) {
            const auto& in = op.input(i);
            if (in.domain == OperandDomain::RuntimeScalar) {
                if (in.id != kTokenRuntimeScalarId) {
                    std::cerr << "SSA Validation FAIL: Op " << op.opId 
                              << " uses unknown RuntimeScalar " << in.id << "\n";
                    return false;
                }
            } else if (in.domain == OperandDomain::Activation) {
                activationUses[in.id].push_back(op.opId);
                // Activation must have exactly one producer (checked below)
            } else if (in.domain == OperandDomain::RomTensor) {
                if (romTensorIds.find(in.id) == romTensorIds.end()) {
                    std::cerr << "SSA Validation FAIL: Op " << op.opId 
                              << " input references ROM tensor " << in.id << " not in directory\n";
                    return false;
                }
            } else if (in.domain != OperandDomain::None) {
                std::cerr << "SSA Validation FAIL: Op " << op.opId 
                          << " input has invalid domain " << (int)in.domain << "\n";
                return false;
            }
        }
        
        // Check output
        if (op.output.domain != OperandDomain::Activation) {
            std::cerr << "SSA Validation FAIL: Op " << op.opId 
                      << " output must be Activation domain\n";
            return false;
        }
        
        // Unique definition check
        if (definedActivations.find(op.output.id) != definedActivations.end()) {
            std::cerr << "SSA Validation FAIL: Activation " << op.output.id 
                      << " defined multiple times (op " << op.opId << ")\n";
            return false;
        }
        definedActivations.insert(op.output.id);
        activationDefCount[op.output.id] = op.opId;
    }
    
    // Dominance check: every Activation input must have a producer
    for (const auto& [actId, users] : activationUses) {
        if (definedActivations.find(actId) == definedActivations.end()) {
            std::cerr << "SSA Validation FAIL: Activation " << actId 
                      << " used by ops " << users[0];
            for (size_t i = 1; i < users.size(); ++i) {
                std::cerr << ", " << users[i];
            }
            std::cerr << " but never defined\n";
            return false;
        }
    }
    
    // Block chain validation: block N+1 must consume block N's final activation
    // (This is implicitly checked by SSA dominance since blockInput is chained)
    
    // Placeholder alias count check: no None-domain operands inside active input/weight slots
    uint32_t noneAliasCount = 0;
    for (const auto& op : genome.executionOps) {
        for (uint32_t i = 0; i < op.inputCount; ++i) {
            if (op.input(i).domain == OperandDomain::None) noneAliasCount++;
        }
        for (uint32_t i = 0; i < op.weightCount; ++i) {
            if (op.weight(i).domain == OperandDomain::None) noneAliasCount++;
        }
    }
    if (noneAliasCount > 0) {
        std::cerr << "SSA Validation FAIL: " << noneAliasCount 
                  << " None-domain operands inside active input/weight slots\n";
        return false;
    }
    
    // Missing required operands check (handled by reader fail-closed)
    
    std::cout << "[HeaderEmitter] SSA Validation PASS: " 
              << genome.executionOps.size() << " ops, " 
              << definedActivations.size() << " activations\n";
    return true;
}

//=============================================================================
// ExecutionIR.generated.hpp
//=============================================================================
bool HeaderEmitter::EmitExecutionIR(const ModelGenome& genome) {
    if (!ValidateExecutionIR(genome)) {
        std::cerr << "ExecutionIR validation failed, aborting emission\n";
        return false;
    }
    
    auto out = OpenHeader("ExecutionIR.generated.hpp", "EXECUTION_IR_GENERATED_HPP");
    if (!out.is_open()) return false;
    
    WritePreamble(out, "EXECUTION_IR_GENERATED_HPP", "Operation graph (execution IR)");
    
    out << "namespace RawrXD {\n";
    out << "namespace Deep2 {\n";
    out << "namespace Generated {\n\n";
    
    // Flat constexpr POD for MSVC /W4 compatibility
    // Compiler IR (ModelGenome) uses vectors; runtime IR uses fixed arrays
    out << "struct OperationIR {\n";
    Indent(out, 1); out << "uint32_t opId;\n";
    Indent(out, 1); out << "ModelGenie::OpCode opcode;\n";
    Indent(out, 1); out << "ModelGenie::Primitive requiredPrimitive;\n\n";
    
    Indent(out, 1); out << "// Inputs (max 8)\n";
    Indent(out, 1); out << "ModelGenie::OperandRef input0;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef input1;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef input2;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef input3;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef input4;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef input5;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef input6;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef input7;\n";
    Indent(out, 1); out << "uint32_t inputCount;\n\n";
    
    Indent(out, 1); out << "// Weights (max 8)\n";
    Indent(out, 1); out << "ModelGenie::OperandRef weight0;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef weight1;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef weight2;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef weight3;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef weight4;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef weight5;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef weight6;\n";
    Indent(out, 1); out << "ModelGenie::OperandRef weight7;\n";
    Indent(out, 1); out << "uint32_t weightCount;\n\n";
    
    Indent(out, 1); out << "// Output\n";
    Indent(out, 1); out << "ModelGenie::OperandRef output;\n";
    Indent(out, 1); out << "uint32_t blockIndex;\n";
    out << "};\n\n";
    
    out << "inline constexpr OperationIR kExecutionIRTable[" << genome.executionOps.size() << "] = {\n";
    for (const auto& op : genome.executionOps) {
        Indent(out, 1); out << "{\n";
        Indent(out, 2); out << op.opId << ",\n";
        Indent(out, 2); out << FormatOpCode(op.opcode) << ",\n";
        Indent(out, 2); out << FormatPrimitive(op.requiredPrimitive) << ",\n";
        
        // inputs
        Indent(out, 2); out << FormatOperandRef(op.inputCount > 0 ? op.input(0) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.inputCount > 1 ? op.input(1) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.inputCount > 2 ? op.input(2) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.inputCount > 3 ? op.input(3) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.inputCount > 4 ? op.input(4) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.inputCount > 5 ? op.input(5) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.inputCount > 6 ? op.input(6) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.inputCount > 7 ? op.input(7) : OperandRef{}) << ",\n";
        Indent(out, 2); out << op.inputCount << ",\n";
        
        // weights
        Indent(out, 2); out << FormatOperandRef(op.weightCount > 0 ? op.weight(0) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.weightCount > 1 ? op.weight(1) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.weightCount > 2 ? op.weight(2) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.weightCount > 3 ? op.weight(3) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.weightCount > 4 ? op.weight(4) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.weightCount > 5 ? op.weight(5) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.weightCount > 6 ? op.weight(6) : OperandRef{}) << ",\n";
        Indent(out, 2); out << FormatOperandRef(op.weightCount > 7 ? op.weight(7) : OperandRef{}) << ",\n";
        Indent(out, 2); out << op.weightCount << ",\n";
        
        // output
        Indent(out, 2); out << FormatOperandRef(op.output) << ",\n";
        
        // blockIndex
        Indent(out, 2); out << op.blockIndex << "\n";
        
        Indent(out, 1); out << "},\n";
    }
    out << "};\n\n";
    
    out << "inline constexpr uint32_t kExecutionOpCount = " << genome.executionOps.size() << ";\n\n";
    
    out << "} // namespace Generated\n";
    out << "} // namespace Deep2\n";
    out << "} // namespace RawrXD\n\n";
    
    out << "#endif // EXECUTION_IR_GENERATED_HPP\n";
    return true;
}

//=============================================================================
// CapabilityManifest.generated.hpp
//=============================================================================
bool HeaderEmitter::EmitCapabilityManifest(const ModelGenome& genome) {
    auto out = OpenHeader("CapabilityManifest.generated.hpp", "CAPABILITY_MANIFEST_GENERATED_HPP");
    if (!out.is_open()) return false;
    
    WritePreamble(out, "CAPABILITY_MANIFEST_GENERATED_HPP", "Primitive requirements and availability");
    
    out << "namespace RawrXD {\n";
    out << "namespace Deep2 {\n";
    out << "namespace Generated {\n\n";
    
    out << "struct CapabilityManifest {\n";
    Indent(out, 1); out << "std::array<Primitive, 10> requiredPrimitives;\n";
    Indent(out, 1); out << "uint32_t requiredCount;\n";
    Indent(out, 1); out << "std::array<Primitive, 9> availablePrimitives;\n";
    Indent(out, 1); out << "uint32_t availableCount;\n";
    Indent(out, 1); out << "std::array<Primitive, 1> unimplementedPrimitives;\n";
    Indent(out, 1); out << "uint32_t unimplementedCount;\n";
    Indent(out, 1); out << "Primitive firstUnimplementedPrimitive;\n";
    Indent(out, 1); out << "bool runtimeExecutable;\n";
    Indent(out, 1); out << "const char* modelGenomeHash;\n";
    out << "};\n\n";
    
    out << "inline constexpr CapabilityManifest kCapabilityManifest = {\n";
    Indent(out, 1); out << ".requiredPrimitives = {";
    for (size_t i = 0; i < genome.capabilities.requiredPrimitives.size(); ++i) {
        if (i > 0) out << ", ";
        out << FormatPrimitive(genome.capabilities.requiredPrimitives[i]);
    }
    out << "},\n";
    Indent(out, 1); out << ".requiredCount = " << genome.capabilities.requiredPrimitives.size() << ",\n";
    Indent(out, 1); out << ".availablePrimitives = {";
    for (size_t i = 0; i < genome.capabilities.availablePrimitives.size(); ++i) {
        if (i > 0) out << ", ";
        out << FormatPrimitive(genome.capabilities.availablePrimitives[i]);
    }
    out << "},\n";
    Indent(out, 1); out << ".availableCount = " << genome.capabilities.availablePrimitives.size() << ",\n";
    Indent(out, 1); out << ".unimplementedPrimitives = {";
    for (size_t i = 0; i < genome.capabilities.unimplementedPrimitives.size(); ++i) {
        if (i > 0) out << ", ";
        out << FormatPrimitive(genome.capabilities.unimplementedPrimitives[i]);
    }
    out << "},\n";
    Indent(out, 1); out << ".unimplementedCount = " << genome.capabilities.unimplementedPrimitives.size() << ",\n";
    Indent(out, 1); out << ".firstUnimplementedPrimitive = " << FormatPrimitive(genome.capabilities.firstUnimplementedPrimitive) << ",\n";
    Indent(out, 1); out << ".runtimeExecutable = " << (genome.capabilities.runtimeExecutable ? "true" : "false") << ",\n";
    Indent(out, 1); out << ".modelGenomeHash = \"" << genome.computeCanonicalHash() << "\"\n";
    out << "};\n\n";
    
    out << "} // namespace Generated\n";
    out << "} // namespace Deep2\n";
    out << "} // namespace RawrXD\n\n";
    
    out << "#endif // CAPABILITY_MANIFEST_GENERATED_HPP\n";
    return true;
}

//=============================================================================
// ResidencyPlan.generated.hpp
//=============================================================================
bool HeaderEmitter::EmitResidencyPlan(const ModelGenome& genome) {
    auto out = OpenHeader("ResidencyPlan.generated.hpp", "RESIDENCY_PLAN_GENERATED_HPP");
    if (!out.is_open()) return false;
    
    WritePreamble(out, "RESIDENCY_PLAN_GENERATED_HPP", "Residency bounds (not allocation decisions)");
    
    out << "namespace RawrXD {\n";
    out << "namespace Deep2 {\n";
    out << "namespace Generated {\n\n";
    
    out << "struct ResidencyBounds {\n";
    Indent(out, 1); out << "uint64_t maxPinnedTensorBytes;\n";
    Indent(out, 1); out << "uint64_t minBlockBytes;\n";
    Indent(out, 1); out << "uint64_t meanBlockBytes;\n";
    Indent(out, 1); out << "uint64_t maxBlockBytes;\n";
    Indent(out, 1); out << "bool uniformTensorSlotsSufficient;\n";
    Indent(out, 1); out << "bool meanBlockCapacitySafe;\n\n";
    Indent(out, 1); out << "// Expert-specific\n";
    Indent(out, 1); out << "double expertRomSharePercent;\n";
    Indent(out, 1); out << "uint64_t expertRomBytes;\n";
    Indent(out, 1); out << "uint64_t maxExpertBlockBytes;\n";
    out << "};\n\n";
    
    out << "inline constexpr ResidencyBounds kResidencyBounds = {\n";
    Indent(out, 1); out << ".maxPinnedTensorBytes = " << genome.residencyBounds.maxPinnedTensorBytes << "ULL,\n";
    Indent(out, 1); out << ".minBlockBytes = " << genome.residencyBounds.minBlockBytes << "ULL,\n";
    Indent(out, 1); out << ".meanBlockBytes = " << genome.residencyBounds.meanBlockBytes << "ULL,\n";
    Indent(out, 1); out << ".maxBlockBytes = " << genome.residencyBounds.maxBlockBytes << "ULL,\n";
    Indent(out, 1); out << ".uniformTensorSlotsSufficient = " << (genome.residencyBounds.uniformTensorSlotsSufficient ? "true" : "false") << ",\n";
    Indent(out, 1); out << ".meanBlockCapacitySafe = " << (genome.residencyBounds.meanBlockCapacitySafe ? "true" : "false") << ",\n";
    Indent(out, 1); out << ".expertRomSharePercent = " << genome.residencyBounds.expertRomSharePercent << ",\n";
    Indent(out, 1); out << ".expertRomBytes = " << genome.residencyBounds.expertRomBytes << "ULL,\n";
    Indent(out, 1); out << ".maxExpertBlockBytes = " << genome.residencyBounds.maxExpertBlockBytes << "ULL\n";
    out << "};\n\n";
    
    out << "} // namespace Generated\n";
    out << "} // namespace Deep2\n";
    out << "} // namespace RawrXD\n\n";
    
    out << "#endif // RESIDENCY_PLAN_GENERATED_HPP\n";
    return true;
}

//=============================================================================
// ModelExport.generated.hpp (Aggregation header)
//=============================================================================
bool HeaderEmitter::EmitModelExport(const ModelGenome& genome) {
    auto out = OpenHeader("ModelExport.generated.hpp", "MODEL_EXPORT_GENERATED_HPP");
    if (!out.is_open()) return false;
    
    WritePreamble(out, "MODEL_EXPORT_GENERATED_HPP", "Single include for all generated model headers");
    
    out << "#include \"ModelIdentity.generated.hpp\"\n";
    out << "#include \"ModelConfig.generated.hpp\"\n";
    out << "#include \"TensorROM.generated.hpp\"\n";
    out << "#include \"BlockGenome.generated.hpp\"\n";
    out << "#include \"ExecutionIR.generated.hpp\"\n";
    out << "#include \"CapabilityManifest.generated.hpp\"\n";
    out << "#include \"ResidencyPlan.generated.hpp\"\n\n";
    
    out << "namespace RawrXD {\n";
    out << "namespace Deep2 {\n";
    out << "namespace Generated {\n\n";
    
    out << "// Convenience: all generated tables in one place\n";
    out << "struct ModelExport {\n";
    Indent(out, 1); out << "using ModelConfig = ModelConfig;\n";
    Indent(out, 1); out << "using TensorROMTable = decltype(kTensorROMTable);\n";
    Indent(out, 1); out << "using BlockGenomeTable = decltype(kBlockGenomeTable);\n";
    Indent(out, 1); out << "using ExpertBankTable = decltype(kExpertBankTable);\n";
    Indent(out, 1); out << "using ExecutionIRTable = decltype(kExecutionIRTable);\n";
    Indent(out, 1); out << "using CapabilityManifest = CapabilityManifest;\n";
    Indent(out, 1); out << "using ResidencyBounds = ResidencyBounds;\n";
    out << "};\n\n";
    
    out << "} // namespace Generated\n";
    out << "} // namespace Deep2\n";
    out << "} // namespace RawrXD\n\n";
    
    out << "#endif // MODEL_EXPORT_GENERATED_HPP\n";
    return true;
}

} // namespace ModelGenie
} // namespace Deep2
} // namespace RawrXD