#ifndef MODEL_IDENTITY_GENERATED_HPP
#define MODEL_IDENTITY_GENERATED_HPP

//=============================================================================
// AUTO-GENERATED by RAWRXD_MODEL_GENIE_HEADER_EXPORT_001
// DO NOT EDIT MANUALLY
// Source: NUGVERSE_ESTIMATOR_001 (frozen)
//=============================================================================

#pragma once

#include <cstdint>
#include <array>
#include <optional>
#include "ModelGenome.hpp"

// Model identity and architecture type
// Generated from ModelGenome: MODEL_IDENTITY_GENERATED_HPP

namespace RawrXD {
namespace Deep2 {
namespace Generated {

inline constexpr const char* kModelName = "DeepSeek-V2-Lite-Chat";
inline constexpr Architecture kArchitecture = Architecture::DeepSeek2;
inline constexpr const char* kArchitectureName = "deepseek2";

} // namespace Generated
} // namespace Deep2
} // namespace RawrXD

#endif // MODEL_IDENTITY_GENERATED_HPP
