#ifndef RESIDENCY_PLAN_GENERATED_HPP
#define RESIDENCY_PLAN_GENERATED_HPP

//=============================================================================
// AUTO-GENERATED by RAWRXD_MODEL_GENIE_HEADER_EXPORT_001
// DO NOT EDIT MANUALLY
// Source: NUGVERSE_ESTIMATOR_001 (frozen)
//=============================================================================

#pragma once

#include <cstdint>
#include <array>
#include <optional>
#include "ModelGenome.hpp"

// Residency bounds (not allocation decisions)
// Generated from ModelGenome: RESIDENCY_PLAN_GENERATED_HPP

namespace RawrXD {
namespace Deep2 {
namespace Generated {

struct ResidencyBounds {
    uint64_t maxPinnedTensorBytes;
    uint64_t minBlockBytes;
    uint64_t meanBlockBytes;
    uint64_t maxBlockBytes;
    bool uniformTensorSlotsSufficient;
    bool meanBlockCapacitySafe;

    // Expert-specific
    double expertRomSharePercent;
    uint64_t expertRomBytes;
    uint64_t maxExpertBlockBytes;
};

inline constexpr ResidencyBounds kResidencyBounds = {
    .maxPinnedTensorBytes = 290004992ULL,
    .minBlockBytes = 56788992ULL,
    .meanBlockBytes = 372978346ULL,
    .maxBlockBytes = 423204864ULL,
    .uniformTensorSlotsSufficient = false,
    .meanBlockCapacitySafe = false,
    .expertRomSharePercent = 91.9592,
    .expertRomBytes = 9527361536ULL,
    .maxExpertBlockBytes = 403701760ULL
};

} // namespace Generated
} // namespace Deep2
} // namespace RawrXD

#endif // RESIDENCY_PLAN_GENERATED_HPP
