// ============================================================================
// deepseek_pretokenizer.hpp
// Word splitter for tokenizer.ggml.pre=deepseek-llm (DeepSeek-V2-Lite-Chat and
// friends). Mirrors llama.cpp unicode_regex_split(): the text is partitioned by
// this pattern set, and the unmatched text BETWEEN matches is kept as its own
// words (a whitespace run that no pattern attaches to survives as a word, which
// is what makes "a  b" tokenize as "a" + " " + " b").
//
// The pattern set, in application order:
//   [\r\n]              newline
//   \s?[letters]+       letter run, optional single leading whitespace
//   \s?[punctuation]+   punctuation run, optional single leading whitespace
//   \s+$                trailing whitespace run inside the current word
//   [cjk]+              CJK run
//   \p{N}+              number run
// Each pattern splits every word produced so far, so a later pattern never
// looks across a boundary an earlier one already cut.
//
// Character classes come from the reference regexes (letter, punctuation, CJK)
// and the Unicode category table llama.cpp consults for \p{N} and \s; see
// deepseek_pretokenizer_ranges.inc (regenerated by
// tools/gen_deepseek_pretokenizer_ranges.py).
// ============================================================================
#pragma once

#include <cstddef>
#include <cstdint>
#include <string>
#include <string_view>
#include <utility>
#include <vector>

namespace RawrXD {
namespace Spm {

namespace deepseek_pretok_detail {

#include "deepseek_pretokenizer_ranges.inc"

    template <size_t N>
    bool InRanges(const uint32_t (&ranges)[N][2], uint32_t cp) noexcept
    {
        size_t lo = 0;
        size_t hi = N;
        while (lo < hi)
        {
            const size_t mid = lo + (hi - lo) / 2;
            if (cp < ranges[mid][0])
            {
                hi = mid;
            }
            else if (cp > ranges[mid][1])
            {
                lo = mid + 1;
            }
            else
            {
                return true;
            }
        }
        return false;
    }

    inline bool IsWhitespaceCp(uint32_t cp) noexcept
    {
        return InRanges(kWhitespaceRanges, cp);
    }

    inline bool IsLetterCp(uint32_t cp) noexcept
    {
        return InRanges(kLetterRanges, cp);
    }

    inline bool IsPunctCp(uint32_t cp) noexcept
    {
        return InRanges(kPunctRanges, cp);
    }

    inline bool IsCjkCp(uint32_t cp) noexcept
    {
        return InRanges(kCjkRanges, cp);
    }

    inline bool IsNumberCp(uint32_t cp) noexcept
    {
        return InRanges(kNumberRanges, cp);
    }

    using Codepoints = std::vector<uint32_t>;
    using Piece = std::pair<size_t, size_t>;

    // Match length for "optional single whitespace + one or more class
    // codepoints" at pos, or 0 when the pattern does not match there.
    inline size_t MatchOptionalSpaceClassRun(
        const Codepoints& cps,
        size_t pos,
        size_t end,
        bool (*isClass)(uint32_t) noexcept)
    {
        if (pos >= end)
            return 0;
        if (IsWhitespaceCp(cps[pos]))
        {
            // "\s" matched: the class run must start immediately after it.
            if (pos + 1 < end && isClass(cps[pos + 1]))
            {
                size_t len = 1;
                while (pos + len < end && isClass(cps[pos + len])) ++len;
                return len;
            }
            // Backtracking "\s?" to empty leaves whitespace, which is not a
            // class codepoint, so the whole pattern fails here.
            return 0;
        }
        if (isClass(cps[pos]))
        {
            size_t len = 0;
            while (pos + len < end && isClass(cps[pos + len])) ++len;
            return len;
        }
        return 0;
    }

    // Match length for "one or more class codepoints" at pos, else 0.
    inline size_t MatchClassRun(
        const Codepoints& cps,
        size_t pos,
        size_t end,
        bool (*isClass)(uint32_t) noexcept)
    {
        if (pos >= end || !isClass(cps[pos]))
            return 0;
        size_t len = 0;
        while (pos + len < end && isClass(cps[pos + len])) ++len;
        return len;
    }

    // Match length for "[\r\n]" at pos, else 0.
    inline size_t MatchNewline(const Codepoints& cps, size_t pos, size_t end)
    {
        if (pos >= end)
            return 0;
        const uint32_t cp = cps[pos];
        return (cp == 0x0A || cp == 0x0D) ? 1 : 0;
    }

    // Match length for "\s+$" at pos, else 0. The match must reach the end of
    // the word, so it can only start where the trailing whitespace run starts.
    inline size_t MatchTrailingWhitespace(
        const Codepoints& cps,
        size_t pos,
        size_t end)
    {
        size_t start = end;
        while (start > pos && IsWhitespaceCp(cps[start - 1])) --start;
        return start == pos && pos < end ? end - pos : 0;
    }

    // Split one word with a matcher, emitting gaps (unmatched text) and matches
    // as separate words, exactly like the llama.cpp std::regex_iterator loop in
    // unicode_regex_split_stl().
    template <typename Matcher>
    void SplitWord(
        const Codepoints& cps,
        const Piece& word,
        Matcher match,
        std::vector<Piece>& out)
    {
        const size_t end = word.first + word.second;
        size_t search = word.first;
        size_t gap = word.first;
        while (search < end)
        {
            const size_t len = match(cps, search, end);
            if (len == 0)
            {
                ++search;
                continue;
            }
            if (search > gap)
                out.emplace_back(gap, search - gap);
            out.emplace_back(search, len);
            search += len;
            gap = search;
        }
        if (gap < end)
            out.emplace_back(gap, end - gap);
    }

    template <typename Matcher>
    void PassWords(
        const Codepoints& cps,
        const std::vector<Piece>& words,
        Matcher match,
        std::vector<Piece>& out)
    {
        out.clear();
        out.reserve(words.size() * 2);
        for (const Piece& word : words)
            SplitWord(cps, word, match, out);
    }

} // namespace deepseek_pretok_detail

// Split UTF-8 text into DeepSeek-LLM pre-tokenizer words. Words are always cut
// on codepoint boundaries.
inline std::vector<std::string> SplitDeepseekLlm(std::string_view text)
{
    namespace dtl = deepseek_pretok_detail;

    dtl::Codepoints cps;
    cps.reserve(text.size());
    std::vector<size_t> offsets;
    offsets.reserve(text.size() + 1);

    size_t i = 0;
    while (i < text.size())
    {
        const unsigned char lead = static_cast<unsigned char>(text[i]);
        size_t len = 1;
        uint32_t cp = lead;
        if ((lead & 0xE0) == 0xC0 && i + 1 < text.size())
        {
            cp = ((static_cast<uint32_t>(lead) & 0x1Fu) << 6) |
                 (static_cast<unsigned char>(text[i + 1]) & 0x3Fu);
            len = 2;
        }
        else if ((lead & 0xF0) == 0xE0 && i + 2 < text.size())
        {
            cp = ((static_cast<uint32_t>(lead) & 0x0Fu) << 12) |
                 ((static_cast<unsigned char>(text[i + 1]) & 0x3Fu) << 6) |
                 (static_cast<unsigned char>(text[i + 2]) & 0x3Fu);
            len = 3;
        }
        else if ((lead & 0xF8) == 0xF0 && i + 3 < text.size())
        {
            cp = ((static_cast<uint32_t>(lead) & 0x07u) << 18) |
                 ((static_cast<unsigned char>(text[i + 1]) & 0x3Fu) << 12) |
                 ((static_cast<unsigned char>(text[i + 2]) & 0x3Fu) << 6) |
                 (static_cast<unsigned char>(text[i + 3]) & 0x3Fu);
            len = 4;
        }
        offsets.push_back(i);
        cps.push_back(cp);
        i += len;
    }
    offsets.push_back(text.size());

    if (cps.empty())
        return {};

    std::vector<dtl::Piece> words;
    std::vector<dtl::Piece> next;
    words.emplace_back(0, cps.size());

    dtl::PassWords(
        cps, words,
        [](const dtl::Codepoints& c, size_t p, size_t e) {
            return dtl::MatchNewline(c, p, e);
        },
        next);
    words.swap(next);

    dtl::PassWords(
        cps, words,
        [](const dtl::Codepoints& c, size_t p, size_t e) {
            return dtl::MatchOptionalSpaceClassRun(c, p, e, dtl::IsLetterCp);
        },
        next);
    words.swap(next);

    dtl::PassWords(
        cps, words,
        [](const dtl::Codepoints& c, size_t p, size_t e) {
            return dtl::MatchOptionalSpaceClassRun(c, p, e, dtl::IsPunctCp);
        },
        next);
    words.swap(next);

    dtl::PassWords(
        cps, words,
        [](const dtl::Codepoints& c, size_t p, size_t e) {
            return dtl::MatchTrailingWhitespace(c, p, e);
        },
        next);
    words.swap(next);

    dtl::PassWords(
        cps, words,
        [](const dtl::Codepoints& c, size_t p, size_t e) {
            return dtl::MatchClassRun(c, p, e, dtl::IsCjkCp);
        },
        next);
    words.swap(next);

    dtl::PassWords(
        cps, words,
        [](const dtl::Codepoints& c, size_t p, size_t e) {
            return dtl::MatchClassRun(c, p, e, dtl::IsNumberCp);
        },
        next);
    words.swap(next);

    std::vector<std::string> out;
    out.reserve(words.size());
    for (const dtl::Piece& word : words)
    {
        out.emplace_back(
            text.substr(offsets[word.first],
                        offsets[word.first + word.second] - offsets[word.first]));
    }
    return out;
}

} // namespace Spm
} // namespace RawrXD
