#include "RGUFLoader.hpp"
#include "RGUFPlatform.hpp"
#include <fstream>
#include <cstring>
namespace rguf {
static uint64_t key(uint64_t t,uint64_t b){return (t<<32)^b;}
bool Model::open(const std::string&p,std::string&err){std::ifstream f(p,std::ios::binary);if(!f){err="cannot open RGUF";return false;}Header h{};f.read((char*)&h,sizeof(h));if(!f||h.magic!=MAGIC||h.version!=VERSION){err="invalid RGUF";return false;}path_=p;blocks_.clear();index_.clear();f.seekg((std::streamoff)h.blocks_off);for(uint64_t i=0;i<h.block_count;i++){Block x{};f.read((char*)&x,sizeof(x));if(!f){err="truncated block table";return false;}blocks_.push_back(x);index_[key(x.tensor,x.index)]=i;}return true;}
void Model::set_key(const uint8_t key[32]) noexcept {std::memcpy(key_,key,32);has_key_=true;}
std::shared_ptr<LoadedBlock> Model::acquire(uint64_t t,uint64_t b,std::string&err){std::lock_guard<std::mutex>g(mu_);auto it=index_.find(key(t,b));if(it==index_.end()){err="block not found";return {};}const Block&m=blocks_[it->second];std::ifstream f(path_,std::ios::binary);if(!f){err="open failed";return {};}f.seekg((std::streamoff)m.file_off);std::vector<uint8_t> enc((size_t)m.stored);f.read((char*)enc.data(),enc.size());if(!f){err="short block";return {};}auto r=std::make_shared<LoadedBlock>();r->meta=m;bool encrypted=false;for(auto c:m.tag)if(c){encrypted=true;break;}if(encrypted){if(!has_key_){err="encrypted model requires key";return {};}if(!aes256gcm_decrypt(key_,m.nonce,enc.data(),enc.size(),m.tag,r->bytes,err))return {};}else r->bytes=std::move(enc);if(crc32(r->bytes.data(),r->bytes.size())!=m.crc){err="block CRC mismatch";return {};}active_.push_back(r);return r;}
bool Model::apply_patch(const std::string&p,std::string&err){std::ifstream f(p,std::ios::binary);if(!f){err="patch open failed";return false;}uint32_t magic,ver,gen;uint64_t t,b,n;f.read((char*)&magic,4);f.read((char*)&ver,4);f.read((char*)&t,8);f.read((char*)&b,8);f.read((char*)&gen,4);f.read((char*)&n,8);if(!f||magic!=PATCH_MAGIC||ver!=1||n>SIZE_MAX){err="invalid patch";return false;}auto data=std::make_shared<LoadedBlock>();data->meta.tensor=t;data->meta.index=b;data->meta.generation=gen;data->meta.stored=n;data->meta.plain=n;data->bytes.resize((size_t)n);f.read((char*)data->bytes.data(),n);if(!f){err="truncated patch";return false;}data->meta.crc=crc32(data->bytes.data(),data->bytes.size());std::lock_guard<std::mutex>g(mu_);auto it=index_.find(key(t,b));if(it==index_.end()){err="patch target missing";return false;}blocks_[it->second]=data->meta;active_.push_back(data);return true;}
}
