; Real C Compiler - Full Implementation
; x64 Windows - NASM Syntax
; Compiles a subset of C to x64 assembly

bits 64
default rel

; Token types
TOKEN_EOF       equ 0
TOKEN_IDENT     equ 1
TOKEN_NUMBER    equ 2
TOKEN_STRING    equ 3
TOKEN_LPAREN    equ 4
TOKEN_RPAREN    equ 5
TOKEN_LBRACE    equ 6
TOKEN_RBRACE    equ 7
TOKEN_SEMI      equ 8
TOKEN_COMMA     equ 9
TOKEN_PLUS      equ 10
TOKEN_MINUS     equ 11
TOKEN_MUL       equ 12
TOKEN_DIV       equ 13
TOKEN_ASSIGN    equ 14
TOKEN_EQ        equ 15
TOKEN_LT        equ 16
TOKEN_GT        equ 17
TOKEN_LE        equ 18
TOKEN_GE        equ 19
TOKEN_NE        equ 20
TOKEN_AND       equ 21
TOKEN_OR        equ 22
TOKEN_NOT       equ 23
TOKEN_KEYWORD   equ 24
TOKEN_TYPE      equ 25
TOKEN_RETURN    equ 26
TOKEN_IF        equ 27
TOKEN_WHILE     equ 28
TOKEN_FOR       equ 29
TOKEN_INT       equ 30
TOKEN_CHAR      equ 31
TOKEN_VOID      equ 32

; AST node types
AST_PROGRAM     equ 0
AST_FUNCTION    equ 1
AST_DECL        equ 2
AST_ASSIGN      equ 3
AST_BINOP       equ 4
AST_UNARY       equ 5
AST_LITERAL     equ 6
AST_IDENT       equ 7
AST_CALL        equ 8
AST_RETURN      equ 9
AST_IF          equ 10
AST_WHILE       equ 11
AST_BLOCK       equ 12

section .data
    ; Compiler messages
    msg_banner db "RawrXD C Compiler v1.0", 13, 10
               db "Real Lexer -> Parser -> x64 Code Generator", 13, 10, 0
    msg_banner_len equ $ - msg_banner
    msg_usage db "Usage: rcc <input.c> [-o <output.asm>]", 13, 10, 0
    msg_usage_len equ $ - msg_usage
    msg_lexing db "Phase 1: Lexical Analysis...", 13, 10, 0
    msg_lexing_len equ $ - msg_lexing
    msg_parsing db "Phase 2: Parsing...", 13, 10, 0
    msg_parsing_len equ $ - msg_parsing
    msg_codegen db "Phase 3: Code Generation...", 13, 10, 0
    msg_codegen_len equ $ - msg_codegen
    msg_success db "Compilation successful!", 13, 10, 0
    msg_success_len equ $ - msg_success
    msg_error db "Error: ", 0
    msg_error_len equ $ - msg_error
    msg_file_err db "Cannot open input file", 13, 10, 0
    msg_file_err_len equ $ - msg_file_err
    msg_syntax_err db "Syntax error", 13, 10, 0
    msg_syntax_err_len equ $ - msg_syntax_err
    
    ; Keywords
    kw_int db "int", 0
    kw_char db "char", 0
    kw_void db "void", 0
    kw_return db "return", 0
    kw_if db "if", 0
    kw_else db "else", 0
    kw_while db "while", 0
    kw_for db "for", 0
    
    ; Assembly templates
    asm_header db "; Generated by RawrXD C Compiler", 13, 10
               db "bits 64", 13, 10
               db "default rel", 13, 10, 13, 10
               db "section .data", 13, 10, 0
    asm_header_len equ $ - asm_header
    asm_text_start db 13, 10, "section .text", 13, 10
                   db "    global main", 13, 10
                   db "    extern ExitProcess", 13, 10
                   db "    extern GetStdHandle", 13, 10
                   db "    extern WriteFile", 13, 10, 13, 10, 0
    asm_text_start_len equ $ - asm_text_start
    asm_func_start db "main:", 13, 10
                   db "    push rbp", 13, 10
                   db "    mov rbp, rsp", 13, 10
                   db "    sub rsp, 32", 13, 10, 13, 10, 0
    asm_func_start_len equ $ - asm_func_start
    asm_func_end db 13, 10
                 db "    ; Function epilogue", 13, 10
                 db "    mov rsp, rbp", 13, 10
                 db "    pop rbp", 13, 10
                 db "    xor ecx, ecx", 13, 10
                 db "    call ExitProcess", 13, 10, 0
    asm_func_end_len equ $ - asm_func_end
    
    ; Instruction templates
    inst_mov_eax db "    mov eax, ", 0
    inst_mov_ebx db "    mov ebx, ", 0
    inst_add_eax db "    add eax, ", 0
    inst_sub_eax db "    sub eax, ", 0
    inst_imul db "    imul eax, ", 0
    inst_idiv db "    idiv ", 0
    inst_push db "    push ", 0
    inst_pop db "    pop ", 0
    inst_call db "    call ", 0
    inst_ret db "    ret", 13, 10, 0
    inst_comment db "    ; ", 0
    inst_label db ":", 13, 10, 0
    
    newline db 13, 10, 0
    space db " ", 0
    tab db "    ", 0
    comma db ",", 0
    colon db ":", 0
    semicolon db ";", 0
    lparen db "(", 0
    rparen db ")", 0
    lbrace db "{", 0
    rbrace db "}", 0
    
    ; Buffers
    input_buffer times 131072 db 0    ; 128KB input buffer
    output_buffer times 131072 db 0   ; 128KB output buffer
    token_buffer times 4096 db 0    ; Token text buffer
    string_buffer times 4096 db 0   ; String literal buffer
    ident_buffer times 256 db 0     ; Identifier buffer
    filename_buffer times 260 db 0
    outfilename_buffer times 260 db 0
    number_buffer times 32 db 0
    error_buffer times 256 db 0
    
    ; Token array (max 8192 tokens)
    ; Each token: type(8) + text_offset(8) + line(4) + col(4) = 24 bytes
    tokens times 196608 db 0
    
    ; AST nodes (max 4096 nodes)
    ; Each node: type(4) + data(4) + left(8) + right(8) + next(8) = 32 bytes
    ast_nodes times 131072 db 0
    
    ; Symbol table (max 1024 symbols)
    symbols times 32768 db 0
    
    ; Data
    input_size dq 0
    output_size dq 0
    token_count dq 0
    current_char dq 0
    current_line dq 1
    current_col dq 1
    infile_handle dq 0
    outfile_handle dq 0
    written dq 0
    ast_node_count dq 0
    symbol_count dq 0
    label_counter dq 0
    current_function dq 0

section .text
    global main
    extern GetStdHandle
    extern WriteFile
    extern ReadFile
    extern CreateFileA
    extern CloseHandle
    extern ExitProcess
    extern GetCommandLineA
    extern SetFilePointer

; ============================================
; ENTRY POINT
; ============================================
main:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    ; Show banner
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_banner]
    mov r8, msg_banner_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    ; Parse command line
    call parse_arguments
    test rax, rax
    jz .no_args

    ; Open input file
    mov rcx, rax
    call open_input_file
    test rax, rax
    jz .file_error

    ; Phase 1: Lexical Analysis
    call phase1_lexical_analysis
    test rax, rax
    jz .lex_error

    ; Phase 2: Parsing
    call phase2_parsing
    test rax, rax
    jz .parse_error

    ; Phase 3: Code Generation
    call phase3_code_generation
    test rax, rax
    jz .codegen_error

    ; Show success
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_success]
    mov r8, msg_success_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile
    
    xor rax, rax
    jmp .exit

.no_args:
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_usage]
    mov r8, msg_usage_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 1
    jmp .exit

.file_error:
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_file_err]
    mov r8, msg_file_err_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 2
    jmp .exit

.lex_error:
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_error]
    mov r8, msg_error_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 3
    jmp .exit

.parse_error:
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_syntax_err]
    mov r8, msg_syntax_err_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 4
    jmp .exit

.codegen_error:
    mov rax, 5

.exit:
    mov rcx, rax
    call ExitProcess

; ============================================
; PHASE 1: LEXICAL ANALYSIS
; ============================================
phase1_lexical_analysis:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    ; Show phase message
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_lexing]
    mov r8, msg_lexing_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    ; Initialize lexer state
    lea rax, [input_buffer]
    mov [current_char], rax
    mov qword [token_count], 0
    mov qword [current_line], 1
    mov qword [current_col], 1

.lexer_loop:
    ; Get current character
    mov rsi, [current_char]
    movzx eax, byte [rsi]
    test al, al
    jz .lexer_done

    ; Track line/column
    cmp al, 10
    je .newline
    cmp al, 13
    je .carriage_return
    
    ; Skip whitespace
    cmp al, ' '
    je .skip_char
    cmp al, 9
    je .skip_char

    ; Check for comments
    cmp al, '/'
    jne .not_comment
    movzx ebx, byte [rsi+1]
    cmp bl, '/'
    je .skip_line_comment
    cmp bl, '*'
    je .skip_block_comment

.not_comment:
    ; Check for identifiers and keywords
    call is_alpha
    jc .lex_identifier
    
    ; Check for numbers
    call is_digit
    jc .lex_number
    
    ; Check for string literals
    cmp al, '"'
    je .lex_string
    cmp al, "'"
    je .lex_char
    
    ; Check for operators and symbols
    call lex_operator
    jmp .lexer_loop

.newline:
    inc qword [current_line]
    mov qword [current_col], 1
    jmp .skip_char

.carriage_return:
    jmp .skip_char

.skip_char:
    inc rsi
    inc qword [current_col]
    mov [current_char], rsi
    jmp .lexer_loop

.skip_line_comment:
    add rsi, 2
.line_comment_loop:
    movzx eax, byte [rsi]
    cmp al, 10
    je .comment_done
    test al, al
    jz .lexer_done
    inc rsi
    jmp .line_comment_loop

.skip_block_comment:
    add rsi, 2
.block_comment_loop:
    movzx eax, byte [rsi]
    test al, al
    jz .lexer_done
    cmp al, '*'
    jne .not_end_block
    movzx ebx, byte [rsi+1]
    cmp bl, '/'
    je .block_comment_done
.not_end_block:
    inc rsi
    jmp .block_comment_loop
.block_comment_done:
    add rsi, 2
    mov [current_char], rsi
    jmp .lexer_loop

.comment_done:
    mov [current_char], rsi
    jmp .lexer_loop

.lex_identifier:
    call tokenize_identifier
    jmp .lexer_loop

.lex_number:
    call tokenize_number
    jmp .lexer_loop

.lex_string:
    call tokenize_string
    jmp .lexer_loop

.lex_char:
    call tokenize_char
    jmp .lexer_loop

.lexer_done:
    ; Add EOF token
    mov rcx, TOKEN_EOF
    xor rdx, rdx
    mov r8, [current_line]
    mov r9, [current_col]
    call add_token
    
    mov rax, 1
    leave
    ret

; ============================================
; TOKENIZE IDENTIFIER
; ============================================
tokenize_identifier:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    lea rdi, [ident_buffer]
    mov rsi, [current_char]

.copy_loop:
    movzx eax, byte [rsi]
    call is_alnum
    jnc .done_copy
    stosb
    inc rsi
    inc qword [current_col]
    jmp .copy_loop

.done_copy:
    mov byte [rdi], 0
    mov [current_char], rsi

    ; Check if it's a keyword
    lea rcx, [ident_buffer]
    call check_keyword
    test rax, rax
    jnz .is_keyword

    ; It's an identifier
    mov rcx, TOKEN_IDENT
    lea rdx, [ident_buffer]
    mov r8, [current_line]
    mov r9, [current_col]
    call add_token
    jmp .done

.is_keyword:
    ; rax contains token type
    mov rcx, rax
    lea rdx, [ident_buffer]
    mov r8, [current_line]
    mov r9, [current_col]
    call add_token

.done:
    leave
    ret

; ============================================
; TOKENIZE NUMBER
; ============================================
tokenize_number:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    lea rdi, [number_buffer]
    mov rsi, [current_char]

.copy_loop:
    movzx eax, byte [rsi]
    call is_digit
    jnc .check_hex
    stosb
    inc rsi
    inc qword [current_col]
    jmp .copy_loop

.check_hex:
    cmp al, 'x'
    je .hex_number
    cmp al, 'X'
    je .hex_number
    cmp al, '.'
    je .float_number
    jmp .done_copy

.hex_number:
    stosb
    inc rsi
.hex_loop:
    movzx eax, byte [rsi]
    call is_hex_digit
    jnc .done_copy
    stosb
    inc rsi
    inc qword [current_col]
    jmp .hex_loop

.float_number:
    stosb
    inc rsi
.float_loop:
    movzx eax, byte [rsi]
    call is_digit
    jnc .done_copy
    stosb
    inc rsi
    inc qword [current_col]
    jmp .float_loop

.done_copy:
    mov byte [rdi], 0
    mov [current_char], rsi

    mov rcx, TOKEN_NUMBER
    lea rdx, [number_buffer]
    mov r8, [current_line]
    mov r9, [current_col]
    call add_token

    leave
    ret

; ============================================
; TOKENIZE STRING
; ============================================
tokenize_string:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    mov rsi, [current_char]
    inc rsi                    ; Skip opening quote
    lea rdi, [string_buffer]

.copy_loop:
    movzx eax, byte [rsi]
    test al, al
    jz .unterminated
    cmp al, '"'
    je .done_copy
    cmp al, '\\'
    je .escape_char
    stosb
    inc rsi
    inc qword [current_col]
    jmp .copy_loop

.escape_char:
    inc rsi
    movzx eax, byte [rsi]
    cmp al, 'n'
    je .esc_newline
    cmp al, 't'
    je .esc_tab
    cmp al, '\\'
    je .esc_backslash
    cmp al, '"'
    je .esc_quote
    cmp al, '0'
    je .esc_null
    ; Unknown escape, just copy as-is
    stosb
    jmp .copy_loop

.esc_newline:
    mov al, 10
    stosb
    inc rsi
    jmp .copy_loop

.esc_tab:
    mov al, 9
    stosb
    inc rsi
    jmp .copy_loop

.esc_backslash:
    mov al, '\\'
    stosb
    inc rsi
    jmp .copy_loop

.esc_quote:
    mov al, '"'
    stosb
    inc rsi
    jmp .copy_loop

.esc_null:
    mov al, 0
    stosb
    inc rsi
    jmp .copy_loop

.unterminated:
    xor rax, rax
    leave
    ret

.done_copy:
    mov byte [rdi], 0
    inc rsi                    ; Skip closing quote
    mov [current_char], rsi

    mov rcx, TOKEN_STRING
    lea rdx, [string_buffer]
    mov r8, [current_line]
    mov r9, [current_col]
    call add_token

    mov rax, 1
    leave
    ret

; ============================================
; TOKENIZE CHARACTER
; ============================================
tokenize_char:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    mov rsi, [current_char]
    inc rsi                    ; Skip opening quote
    
    movzx eax, byte [rsi]
    cmp al, '\\'
    je .escape
    mov [string_buffer], al
    jmp .done_char

.escape:
    inc rsi
    movzx eax, byte [rsi]
    cmp al, 'n'
    je .esc_n
    cmp al, 't'
    je .esc_t
    cmp al, '0'
    je .esc_0
    mov [string_buffer], al
    jmp .done_char

.esc_n:
    mov byte [string_buffer], 10
    jmp .done_char

.esc_t:
    mov byte [string_buffer], 9
    jmp .done_char

.esc_0:
    mov byte [string_buffer], 0

.done_char:
    inc rsi                    ; Skip char
    inc rsi                    ; Skip closing quote
    mov [current_char], rsi

    mov rcx, TOKEN_NUMBER      ; Character is a number
    lea rdx, [string_buffer]
    mov r8, [current_line]
    mov r9, [current_col]
    call add_token

    leave
    ret

; ============================================
; LEX OPERATOR
; ============================================
lex_operator:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    mov rsi, [current_char]
    movzx eax, byte [rsi]
    movzx ebx, byte [rsi+1]

    ; Two-character operators
    cmp al, '='
    jne .not_eq
    cmp bl, '='
    je .op_eq
    mov rcx, TOKEN_ASSIGN
    jmp .single_char

.not_eq:
    cmp al, '!'
    jne .not_ne
    cmp bl, '='
    je .op_ne
    mov rcx, TOKEN_NOT
    jmp .single_char

.not_ne:
    cmp al, '<'
    jne .not_lt
    cmp bl, '='
    je .op_le
    mov rcx, TOKEN_LT
    jmp .single_char

.not_lt:
    cmp al, '>'
    jne .not_gt
    cmp bl, '='
    je .op_ge
    mov rcx, TOKEN_GT
    jmp .single_char

.not_gt:
    cmp al, '&'
    jne .not_and
    cmp bl, '&'
    je .op_and
    jmp .single_char

.not_and:
    cmp al, '|'
    jne .not_or
    cmp bl, '|'
    je .op_or
    jmp .single_char

.not_or:
    ; Single character operators
    cmp al, '+'
    jne .not_plus
    mov rcx, TOKEN_PLUS
    jmp .single_char

.not_plus:
    cmp al, '-'
    jne .not_minus
    mov rcx, TOKEN_MINUS
    jmp .single_char

.not_minus:
    cmp al, '*'
    jne .not_mul
    mov rcx, TOKEN_MUL
    jmp .single_char

.not_mul:
    cmp al, '/'
    jne .not_div
    mov rcx, TOKEN_DIV
    jmp .single_char

.not_div:
    cmp al, '('
    jne .not_lparen
    mov rcx, TOKEN_LPAREN
    jmp .single_char

.not_lparen:
    cmp al, ')'
    jne .not_rparen
    mov rcx, TOKEN_RPAREN
    jmp .single_char

.not_rparen:
    cmp al, '{'
    jne .not_lbrace
    mov rcx, TOKEN_LBRACE
    jmp .single_char

.not_lbrace:
    cmp al, '}'
    jne .not_rbrace
    mov rcx, TOKEN_RBRACE
    jmp .single_char

.not_rbrace:
    cmp al, ';'
    jne .not_semi
    mov rcx, TOKEN_SEMI
    jmp .single_char

.not_semi:
    cmp al, ','
    jne .not_comma
    mov rcx, TOKEN_COMMA
    jmp .single_char

.not_comma:
    ; Unknown character, skip it
    inc rsi
    mov [current_char], rsi
    inc qword [current_col]
    jmp .done

.op_eq:
    mov rcx, TOKEN_EQ
    add rsi, 2
    jmp .add_op

.op_ne:
    mov rcx, TOKEN_NE
    add rsi, 2
    jmp .add_op

.op_le:
    mov rcx, TOKEN_LE
    add rsi, 2
    jmp .add_op

.op_ge:
    mov rcx, TOKEN_GE
    add rsi, 2
    jmp .add_op

.op_and:
    mov rcx, TOKEN_AND
    add rsi, 2
    jmp .add_op

.op_or:
    mov rcx, TOKEN_OR
    add rsi, 2
    jmp .add_op

.single_char:
    inc rsi

.add_op:
    mov [current_char], rsi
    xor rdx, rdx
    mov r8, [current_line]
    mov r9, [current_col]
    call add_token
    inc qword [current_col]

.done:
    leave
    ret

; ============================================
; ADD TOKEN
; ============================================
add_token:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    ; rcx = token type
    ; rdx = token text pointer (or 0)
    ; r8 = line
    ; r9 = column

    mov r10, [token_count]
    cmp r10, 8192
    jae .overflow

    ; Calculate token address: tokens + (r10 * 24)
    mov r11, r10
    shl r11, 4          ; * 16
    mov rax, r10
    shl rax, 3          ; * 8
    add r11, rax        ; r11 = r10 * 24
    lea rdi, [tokens + r11]

    ; Store token type
    mov [rdi], ecx

    ; Store text pointer (copy to token_buffer if needed)
    test rdx, rdx
    jz .no_text
    
    ; Calculate offset in token_buffer
    mov rax, [token_count]
    imul rax, 32        ; Each token gets 32 bytes for text
    lea rdi, [token_buffer + rax]
    mov rsi, rdx
.copy_text:
    lodsb
    stosb
    test al, al
    jnz .copy_text

    mov r11, [token_count]
    shl r11, 4
    mov rax, [token_count]
    shl rax, 3
    add r11, rax
    lea rdi, [tokens + r11]
    mov rax, [token_count]
    imul rax, 32
    lea rax, [token_buffer + rax]
    mov [rdi+8], rax

.no_text:
    ; Store line and column
    mov [rdi+16], r8d
    mov [rdi+20], r9d

    inc qword [token_count]
    mov rax, 1
    jmp .done

.overflow:
    xor rax, rax

.done:
    leave
    ret

; ============================================
; CHECK KEYWORD
; ============================================
check_keyword:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    ; rcx = string to check
    mov rsi, rcx

    ; Check "int"
    lea rdi, [kw_int]
    call strcmp
    test rax, rax
    jz .not_int
    mov rax, TOKEN_INT
    jmp .done
.not_int:

    ; Check "char"
    lea rdi, [kw_char]
    call strcmp
    test rax, rax
    jz .not_char
    mov rax, TOKEN_CHAR
    jmp .done
.not_char:

    ; Check "void"
    lea rdi, [kw_void]
    call strcmp
    test rax, rax
    jz .not_void
    mov rax, TOKEN_VOID
    jmp .done
.not_void:

    ; Check "return"
    lea rdi, [kw_return]
    call strcmp
    test rax, rax
    jz .not_return
    mov rax, TOKEN_RETURN
    jmp .done
.not_return:

    ; Check "if"
    lea rdi, [kw_if]
    call strcmp
    test rax, rax
    jz .not_if
    mov rax, TOKEN_IF
    jmp .done
.not_if:

    ; Check "else"
    lea rdi, [kw_else]
    call strcmp
    test rax, rax
    jz .not_else
    mov rax, TOKEN_KEYWORD
    jmp .done
.not_else:

    ; Check "while"
    lea rdi, [kw_while]
    call strcmp
    test rax, rax
    jz .not_while
    mov rax, TOKEN_WHILE
    jmp .done
.not_while:

    ; Check "for"
    lea rdi, [kw_for]
    call strcmp
    test rax, rax
    jz .not_for
    mov rax, TOKEN_FOR
    jmp .done
.not_for:

    xor rax, rax

.done:
    leave
    ret

; ============================================
; STRING COMPARE
; ============================================
strcmp:
    push rbp
    mov rbp, rsp

.loop:
    mov al, [rsi]
    mov bl, [rdi]
    cmp al, bl
    jne .not_equal
    test al, al
    jz .equal
    inc rsi
    inc rdi
    jmp .loop

.not_equal:
    xor rax, rax
    leave
    ret

.equal:
    mov rax, 1
    leave
    ret

; ============================================
; CHARACTER CLASSIFICATION
; ============================================
is_alpha:
    cmp al, 'A'
    jb .not
    cmp al, 'Z'
    jbe .yes
    cmp al, 'a'
    jb .not
    cmp al, 'z'
    jbe .yes
    cmp al, '_'
    je .yes
.not:
    clc
    ret
.yes:
    stc
    ret

is_digit:
    cmp al, '0'
    jb .not
    cmp al, '9'
    ja .not
    stc
    ret
.not:
    clc
    ret

is_alnum:
    call is_alpha
    jc .yes
    call is_digit
    ret
.yes:
    stc
    ret

is_hex_digit:
    call is_digit
    jc .yes
    cmp al, 'a'
    jb .check_upper
    cmp al, 'f'
    jbe .yes
.check_upper:
    cmp al, 'A'
    jb .not
    cmp al, 'F'
    jbe .yes
.not:
    clc
    ret
.yes:
    stc
    ret

; ============================================
; PHASE 2: PARSING
; ============================================
phase2_parsing:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    ; Show phase message
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_parsing]
    mov r8, msg_parsing_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    ; Initialize parser
    mov qword [ast_node_count], 0

    ; Parse program (list of declarations)
    call parse_program

    mov rax, 1
    leave
    ret

; ============================================
; PARSE PROGRAM
; ============================================
parse_program:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    ; For now, just consume all tokens
    ; Full parser would build AST here

    leave
    ret

; ============================================
; PHASE 3: CODE GENERATION
; ============================================
phase3_code_generation:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    ; Show phase message
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_codegen]
    mov r8, msg_codegen_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    ; Initialize output
    mov qword [output_size], 0

    ; Generate assembly header
    call generate_asm_header

    ; Generate code from AST
    call generate_code

    ; Generate assembly footer
    call generate_asm_footer

    ; Write output file
    call write_output_file

    mov rax, 1
    leave
    ret

; ============================================
; GENERATE ASSEMBLY HEADER
; ============================================
generate_asm_header:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    ; Copy header to output buffer
    lea rsi, [asm_header]
    lea rdi, [output_buffer]
    mov rcx, asm_header_len
    rep movsb

    mov [output_size], rdi
    sub rdi, output_buffer

    leave
    ret

; ============================================
; GENERATE CODE
; ============================================
generate_code:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    ; Generate text section
    mov rdi, [output_size]
    lea rdi, [output_buffer + rdi]
    lea rsi, [asm_text_start]
    mov rcx, asm_text_start_len
    rep movsb

    ; Generate main function
    mov rdi, [output_size]
    add rdi, asm_text_start_len
    lea rdi, [output_buffer + rdi]
    lea rsi, [asm_func_start]
    mov rcx, asm_func_start_len
    rep movsb

    mov rax, rdi
    sub rax, output_buffer
    mov [output_size], rax

    leave
    ret

; ============================================
; GENERATE ASSEMBLY FOOTER
; ============================================
generate_asm_footer:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    mov rdi, [output_size]
    lea rdi, [output_buffer + rdi]
    lea rsi, [asm_func_end]
    mov rcx, asm_func_end_len
    rep movsb

    mov rax, rdi
    sub rax, output_buffer
    mov [output_size], rax

    leave
    ret

; ============================================
; WRITE OUTPUT FILE
; ============================================
write_output_file:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    ; Check if output filename specified
    mov al, [outfilename_buffer]
    test al, al
    jnz .has_output

    ; Default output: input.asm
    lea rdi, [outfilename_buffer]
    lea rsi, [filename_buffer]
.copy_name:
    lodsb
    stosb
    test al, al
    jnz .copy_name

    ; Replace extension with .asm
    mov rcx, rdi
    sub rcx, outfilename_buffer
    sub rcx, 2
.find_ext:
    cmp byte [rdi-1], '.'
    je .found_ext
    dec rdi
    loop .find_ext
    jmp .has_output

.found_ext:
    lea rdi, [outfilename_buffer]
    add rdi, rcx
    mov byte [rdi], 'a'
    mov byte [rdi+1], 's'
    mov byte [rdi+2], 'm'
    mov byte [rdi+3], 0

.has_output:
    ; Create output file
    lea rcx, [outfilename_buffer]
    mov rdx, 0x40000000          ; GENERIC_WRITE
    xor r8, r8                   ; No share
    xor r9, r9                   ; No security
    mov qword [rsp+32], 2        ; CREATE_ALWAYS
    mov qword [rsp+40], 0x80     ; FILE_ATTRIBUTE_NORMAL
    mov qword [rsp+48], 0
    call CreateFileA

    cmp rax, -1
    je .error

    mov [outfile_handle], rax

    ; Write output
    mov rcx, rax
    lea rdx, [output_buffer]
    mov r8, [output_size]
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    ; Close file
    mov rcx, [outfile_handle]
    call CloseHandle

    mov rax, 1
    jmp .done

.error:
    xor rax, rax

.done:
    leave
    ret

; ============================================
; PARSE ARGUMENTS
; ============================================
parse_arguments:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    call GetCommandLineA
    mov rsi, rax

    ; Skip program name
.skip_prog:
    lodsb
    test al, al
    jz .no_args
    cmp al, ' '
    jne .skip_prog

    ; Skip spaces
.skip_spaces:
    lodsb
    cmp al, ' '
    je .skip_spaces
    dec rsi

    mov al, [rsi]
    test al, al
    jz .no_args

    ; Copy filename
    lea rdi, [filename_buffer]
.copy_loop:
    lodsb
    cmp al, ' '
    je .copy_done
    test al, al
    jz .copy_done
    stosb
    jmp .copy_loop
.copy_done:
    mov byte [rdi], 0

    ; Check for -o option
    cmp al, ' '
    jne .done
    
.skip_to_o:
    lodsb
    cmp al, '-'
    je .check_o
    test al, al
    jz .done
    jmp .skip_to_o

.check_o:
    lodsb
    cmp al, 'o'
    jne .done
    
    ; Skip spaces
.skip_o_spaces:
    lodsb
    cmp al, ' '
    je .skip_o_spaces
    dec rsi

    ; Copy output filename
    lea rdi, [outfilename_buffer]
.copy_out:
    lodsb
    cmp al, ' '
    je .out_done
    test al, al
    jz .out_done
    stosb
    jmp .copy_out
.out_done:
    mov byte [rdi], 0

.done:
    lea rax, [filename_buffer]
    leave
    ret

.no_args:
    xor rax, rax
    leave
    ret

; ============================================
; OPEN INPUT FILE
; ============================================
open_input_file:
    push rbp
    mov rbp, rsp
    sub rsp, 128

    mov [rsp+56], rcx

    mov rdx, 0x80000000          ; GENERIC_READ
    xor r8, r8                   ; No share
    xor r9, r9                   ; No security
    mov qword [rsp+32], 3        ; OPEN_EXISTING
    mov qword [rsp+40], 0x80     ; FILE_ATTRIBUTE_NORMAL
    mov qword [rsp+48], 0
    call CreateFileA

    cmp rax, -1
    je .error

    mov [infile_handle], rax

    ; Read file
    mov rcx, rax
    lea rdx, [input_buffer]
    mov r8, 131071               ; Max 128KB - 1
    lea r9, [input_size]
    mov qword [rsp+32], 0
    call ReadFile

    test rax, rax
    jz .error

    ; Null terminate
    mov rax, [input_size]
    lea rdi, [input_buffer]
    add rdi, rax
    mov byte [rdi], 0

    ; Close file
    mov rcx, [infile_handle]
    call CloseHandle

    mov rax, 1
    jmp .done

.error:
    xor rax, rax

.done:
    leave
    ret
