; Real Universal Compiler v3 - Full Code Generator
; x64 Windows Console Application
; NASM Syntax

bits 64

; Token types
TOKEN_EOF     equ 0
TOKEN_IDENT   equ 1
TOKEN_NUMBER  equ 2
TOKEN_STRING  equ 3
TOKEN_LPAREN  equ 4
TOKEN_RPAREN  equ 5
TOKEN_LBRACE  equ 6
TOKEN_RBRACE  equ 7
TOKEN_SEMI    equ 8
TOKEN_COMMA   equ 9
TOKEN_PLUS    equ 10
TOKEN_MINUS   equ 11
TOKEN_MUL     equ 12
TOKEN_DIV     equ 13
TOKEN_ASSIGN  equ 14
TOKEN_KEYWORD equ 15

section .data
    ; Messages
    msg_banner db "RawrXD Universal Compiler v3.0", 13, 10
               db "Full Lexer + Parser + x64 Code Generator", 13, 10, 0
    msg_banner_len equ $ - msg_banner
    msg_usage db "Usage: compiler <input.c> [-o <output.asm>]", 13, 10, 0
    msg_usage_len equ $ - msg_usage
    msg_lexing db "Phase 1: Lexical Analysis...", 13, 10, 0
    msg_lexing_len equ $ - msg_lexing
    msg_tokens db "  Tokens found: ", 0
    msg_tokens_len equ $ - msg_tokens
    msg_parsing db "Phase 2: Parsing...", 13, 10, 0
    msg_parsing_len equ $ - msg_parsing
    msg_codegen db "Phase 3: Code Generation...", 13, 10, 0
    msg_codegen_len equ $ - msg_codegen
    msg_output db "Output written to: ", 0
    msg_output_len equ $ - msg_output
    msg_success db "Compilation successful!", 13, 10, 0
    msg_success_len equ $ - msg_success
    msg_file_err db "Error: Cannot open input file", 13, 10, 0
    msg_file_err_len equ $ - msg_file_err
    
    ; Code templates
    asm_header db "; Generated by RawrXD Universal Compiler v3.0", 13, 10
               db "; Source: ", 0
    asm_header2 db 13, 10, 13, 10
                db "bits 64", 13, 10
                db "default rel", 13, 10, 13, 10
                db "section .data", 13, 10, 0
    asm_data_end db 13, 10, "section .text", 13, 10
                 db "    global main", 13, 10
                 db "    extern ExitProcess", 13, 10
                 db "    extern GetStdHandle", 13, 10
                 db "    extern WriteFile", 13, 10, 13, 10
                 db "main:", 13, 10, 0
    asm_footer db 13, 10
               db "    ; Exit", 13, 10
               db "    xor rcx, rcx", 13, 10
               db "    call ExitProcess", 13, 10, 0
    
    ; Instruction templates
    inst_push db "    push rbp", 13, 10, 0
    inst_mov_rbp db "    mov rbp, rsp", 13, 10, 0
    inst_sub_rsp db "    sub rsp, ", 0
    inst_mov_rcx db "    mov rcx, ", 0
    inst_call db "    call ", 0
    inst_leave db "    leave", 13, 10, 0
    inst_ret db "    ret", 13, 10, 0
    inst_xor_rcx db "    xor rcx, rcx", 13, 10, 0
    inst_comment db "    ; ", 0
    
    newline db 13, 10, 0
    tab db "    ", 0
    
    ; Buffers
    input_buffer times 65536 db 0
    output_buffer times 65536 db 0
    token_buffer times 1024 db 0
    filename_buffer times 260 db 0
    outfilename_buffer times 260 db 0
    number_buffer times 32 db 0
    
    ; Token array (4096 tokens * 32 bytes)
    tokens times 131072 db 0
    
    ; Data
    input_size dq 0
    output_size dq 0
    token_count dq 0
    current_char dq 0
    infile_handle dq 0
    outfile_handle dq 0
    written dq 0
    token_idx dq 0

section .text
    global main
    extern GetStdHandle
    extern WriteFile
    extern ReadFile
    extern CreateFileA
    extern CloseHandle
    extern ExitProcess
    extern GetCommandLineA

; ============================================
; ENTRY POINT
; ============================================
main:
    push rbp
    mov rbp, rsp
    sub rsp, 96

    ; Show banner
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_banner]
    mov r8, msg_banner_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    ; Parse command line
    call parse_arguments
    test rax, rax
    jz .no_args

    ; Open input file
    mov rcx, rax
    call open_input_file
    test rax, rax
    jz .file_error

    ; Phase 1: Lexical Analysis
    call phase1_lexing

    ; Phase 2: Parsing
    call phase2_parsing

    ; Phase 3: Code Generation
    call phase3_codegen

    ; Show success
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_success]
    mov r8, msg_success_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile
    
    xor rax, rax
    jmp .exit

.no_args:
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_usage]
    mov r8, msg_usage_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 1
    jmp .exit

.file_error:
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_file_err]
    mov r8, msg_file_err_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile
    mov rax, 2

.exit:
    mov rcx, rax
    call ExitProcess

; ============================================
; PHASE 1: LEXICAL ANALYSIS
; ============================================
phase1_lexing:
    push rbp
    mov rbp, rsp
    sub rsp, 64

    ; Show lexing message
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_lexing]
    mov r8, msg_lexing_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    ; Initialize lexer
    lea rax, [input_buffer]
    mov [current_char], rax
    mov qword [token_count], 0

.lexer_loop:
    ; Get current character
    mov rsi, [current_char]
    movzx eax, byte [rsi]
    test al, al
    jz .lexer_done

    ; Skip whitespace
    cmp al, ' '
    je .skip_char
    cmp al, 9
    je .skip_char
    cmp al, 13
    je .skip_char
    cmp al, 10
    je .skip_char

    ; Check for comments
    cmp al, '/'
    jne .not_comment
    movzx ebx, byte [rsi+1]
    cmp bl, '/'
    je .skip_line_comment

.not_comment:
    ; Check for identifiers
    call is_alpha
    jnc .not_ident
    call lex_identifier
    jmp .lexer_loop

.not_ident:
    ; Check for numbers
    call is_digit
    jnc .not_number
    call lex_number
    jmp .lexer_loop

.not_number:
    ; Check for string literals
    cmp al, '"'
    jne .not_string
    call lex_string
    jmp .lexer_loop

.not_string:
    ; Check for hash (preprocessor)
    cmp al, '#'
    je .skip_hash_line

    ; Single character tokens
    call lex_symbol
    jmp .lexer_loop

.skip_char:
    inc rsi
    mov [current_char], rsi
    jmp .lexer_loop

.skip_line_comment:
    add rsi, 2
.line_comment_loop:
    movzx eax, byte [rsi]
    cmp al, 10
    je .comment_done
    test al, al
    jz .lexer_done
    inc rsi
    jmp .line_comment_loop
.comment_done:
    mov [current_char], rsi
    jmp .lexer_loop

.skip_hash_line:
    ; Skip preprocessor directive line
    inc rsi
.skip_hash_loop:
    movzx eax, byte [rsi]
    cmp al, 10
    je .hash_done
    test al, al
    jz .lexer_done
    inc rsi
    jmp .skip_hash_loop
.hash_done:
    mov [current_char], rsi
    jmp .lexer_loop

.lexer_done:
    ; Add EOF token
    mov rcx, TOKEN_EOF
    lea rdx, [eof_text]
    call add_token

    ; Show token count
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_tokens]
    mov r8, msg_tokens_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    mov rax, [token_count]
    dec rax
    call print_number

    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [newline]
    mov r8, 2
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    leave
    ret

eof_text: db "EOF", 0

; ============================================
; PHASE 2: PARSING
; ============================================
phase2_parsing:
    push rbp
    mov rbp, rsp
    sub rsp, 64

    ; Show parsing message
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_parsing]
    mov r8, msg_parsing_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    ; Initialize parser
    mov qword [token_idx], 0

    ; Parse program
.parse_loop:
    call get_current_token
    cmp rax, TOKEN_EOF
    je .done
    
    ; Parse statement
    call parse_statement
    
    jmp .parse_loop

.done:
    leave
    ret

; ============================================
; PHASE 3: CODE GENERATION
; ============================================
phase3_codegen:
    push rbp
    mov rbp, rsp
    sub rsp, 64

    ; Show codegen message
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_codegen]
    mov r8, msg_codegen_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    ; Generate assembly output
    call generate_asm

    ; Show output message
    mov rcx, -11
    call GetStdHandle
    mov rcx, rax
    lea rdx, [msg_output]
    mov r8, msg_output_len
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    leave
    ret

; ============================================
; HELPER FUNCTIONS
; ============================================

parse_arguments:
    push rbp
    mov rbp, rsp
    sub rsp, 32

    call GetCommandLineA
    mov rsi, rax

    ; Skip program name
.skip_prog:
    lodsb
    test al, al
    jz .no_args
    cmp al, ' '
    jne .skip_prog

    ; Skip spaces
.skip_spaces:
    lodsb
    cmp al, ' '
    je .skip_spaces
    dec rsi

    mov al, [rsi]
    test al, al
    jz .no_args

    ; Copy filename
    lea rdi, [filename_buffer]
.copy_loop:
    lodsb
    cmp al, ' '
    je .copy_done
    test al, al
    jz .copy_done
    stosb
    jmp .copy_loop
.copy_done:
    mov byte [rdi], 0
    lea rax, [filename_buffer]
    jmp .done

.no_args:
    xor rax, rax

.done:
    leave
    ret

open_input_file:
    push rbp
    mov rbp, rsp
    sub rsp, 64

    mov [rsp+56], rcx

    mov rdx, 0x80000000
    xor r8, r8
    xor r9, r9
    mov qword [rsp+32], 3
    mov qword [rsp+40], 0
    mov qword [rsp+48], 0
    call CreateFileA

    cmp rax, -1
    je .error

    mov [infile_handle], rax

    mov rcx, rax
    lea rdx, [input_buffer]
    mov r8, 65535
    lea r9, [input_size]
    mov qword [rsp+32], 0
    call ReadFile

    test rax, rax
    jz .error

    ; Null terminate the buffer
    mov rax, [input_size]
    lea rdi, [input_buffer]
    add rdi, rax
    mov byte [rdi], 0

    mov rcx, [infile_handle]
    call CloseHandle

    mov rax, 1
    jmp .done

.error:
    xor rax, rax

.done:
    leave
    ret

is_alpha:
    cmp al, 'A'
    jb .not_alpha
    cmp al, 'Z'
    jbe .is_alpha
    cmp al, 'a'
    jb .not_alpha
    cmp al, 'z'
    jbe .is_alpha
    cmp al, '_'
    je .is_alpha
.not_alpha:
    clc
    ret
.is_alpha:
    stc
    ret

is_digit:
    cmp al, '0'
    jb .not_digit
    cmp al, '9'
    ja .not_digit
    stc
    ret
.not_digit:
    clc
    ret

lex_identifier:
    push rbp
    mov rbp, rsp
    sub rsp, 32

    lea rdi, [token_buffer]
    mov rsi, [current_char]

.copy_loop:
    movzx eax, byte [rsi]
    call is_alpha
    jc .copy_char
    call is_digit
    jc .copy_char
    jmp .done_copy
.copy_char:
    stosb
    inc rsi
    jmp .copy_loop

.done_copy:
    mov byte [rdi], 0
    mov [current_char], rsi

    mov rcx, TOKEN_IDENT
    lea rdx, [token_buffer]
    call add_token

    leave
    ret

lex_number:
    push rbp
    mov rbp, rsp
    sub rsp, 32

    lea rdi, [token_buffer]
    mov rsi, [current_char]

.copy_loop:
    movzx eax, byte [rsi]
    call is_digit
    jnc .done_copy
    stosb
    inc rsi
    jmp .copy_loop

.done_copy:
    mov byte [rdi], 0
    mov [current_char], rsi

    mov rcx, TOKEN_NUMBER
    lea rdx, [token_buffer]
    call add_token

    leave
    ret

lex_string:
    push rbp
    mov rbp, rsp
    sub rsp, 32

    mov rsi, [current_char]
    inc rsi
    lea rdi, [token_buffer]

.copy_loop:
    movzx eax, byte [rsi]
    test al, al
    jz .done_copy
    cmp al, '"'
    je .done_copy
    stosb
    inc rsi
    jmp .copy_loop

.done_copy:
    mov byte [rdi], 0
    inc rsi
    mov [current_char], rsi

    mov rcx, TOKEN_STRING
    lea rdx, [token_buffer]
    call add_token

    leave
    ret

lex_symbol:
    push rbp
    mov rbp, rsp
    sub rsp, 32

    mov rsi, [current_char]
    movzx eax, byte [rsi]

    cmp al, '('
    je .lparen
    cmp al, ')'
    je .rparen
    cmp al, '{'
    je .lbrace
    cmp al, '}'
    je .rbrace
    cmp al, ';'
    je .semi
    cmp al, ','
    je .comma
    cmp al, '+'
    je .plus
    cmp al, '-'
    je .minus
    cmp al, '*'
    je .mul
    cmp al, '/'
    je .div
    cmp al, '='
    je .assign

    ; Unknown character - skip it
    inc rsi
    mov [current_char], rsi
    jmp .done

.lparen:
    mov ecx, TOKEN_LPAREN
    jmp .add_single
.rparen:
    mov ecx, TOKEN_RPAREN
    jmp .add_single
.lbrace:
    mov ecx, TOKEN_LBRACE
    jmp .add_single
.rbrace:
    mov ecx, TOKEN_RBRACE
    jmp .add_single
.semi:
    mov ecx, TOKEN_SEMI
    jmp .add_single
.comma:
    mov ecx, TOKEN_COMMA
    jmp .add_single
.plus:
    mov ecx, TOKEN_PLUS
    jmp .add_single
.minus:
    mov ecx, TOKEN_MINUS
    jmp .add_single
.mul:
    mov ecx, TOKEN_MUL
    jmp .add_single
.div:
    mov ecx, TOKEN_DIV
    jmp .add_single
.assign:
    mov ecx, TOKEN_ASSIGN

.add_single:
    lea rdx, [rsi]
    call add_token
    inc rsi
    mov [current_char], rsi

.done:
    leave
    ret

add_token:
    push rbp
    mov rbp, rsp
    sub rsp, 64

    mov [rsp+32], rcx
    mov [rsp+40], rdx

    mov rax, [token_count]
    imul rax, 32
    lea rdi, [tokens + rax]

    mov rcx, [rsp+32]
    mov [rdi], rcx

    lea rdi, [rdi + 8]
    mov rsi, [rsp+40]
.copy_text:
    lodsb
    stosb
    test al, al
    jnz .copy_text

    inc qword [token_count]

    leave
    ret

get_current_token:
    push rbp
    mov rbp, rsp

    mov rax, [token_idx]
    imul rax, 32
    lea rbx, [tokens + rax]
    mov rax, [rbx]

    leave
    ret

consume_token:
    push rbp
    mov rbp, rsp

    inc qword [token_idx]

    leave
    ret

parse_statement:
    push rbp
    mov rbp, rsp
    sub rsp, 32

    ; Simple statement parsing - consume tokens until semicolon
.stmt_loop:
    call get_current_token
    cmp rax, TOKEN_SEMI
    je .stmt_done
    cmp rax, TOKEN_EOF
    je .stmt_done
    call consume_token
    jmp .stmt_loop

.stmt_done:
    call consume_token

    leave
    ret

generate_asm:
    push rbp
    mov rbp, rsp
    sub rsp, 64

    ; Initialize output buffer
    lea rdi, [output_buffer]
    mov byte [rdi], 0

    ; Add header
    lea rsi, [asm_header]
    call strcat

    ; Add source filename
    lea rsi, [filename_buffer]
    call strcat

    lea rsi, [asm_header2]
    call strcat

    ; Generate code for each token
    mov qword [token_idx], 0

.gen_loop:
    call get_current_token
    cmp rax, TOKEN_EOF
    je .gen_done

    ; Generate code based on token type
    cmp rax, TOKEN_IDENT
    je .gen_ident
    cmp rax, TOKEN_NUMBER
    je .gen_number
    cmp rax, TOKEN_LPAREN
    je .gen_lparen
    cmp rax, TOKEN_RPAREN
    je .gen_rparen
    cmp rax, TOKEN_LBRACE
    je .gen_lbrace
    cmp rax, TOKEN_RBRACE
    je .gen_rbrace
    cmp rax, TOKEN_SEMI
    je .gen_semi
    jmp .next_token

.gen_ident:
    lea rsi, [inst_comment]
    call strcat
    ; Get token text from tokens array
    mov rax, [token_idx]
    imul rax, 32
    lea rsi, [tokens + rax + 8]
    call strcat
    lea rsi, [newline]
    call strcat
    jmp .next_token

.gen_number:
    lea rsi, [inst_mov_rcx]
    call strcat
    ; Get number text from tokens array
    mov rax, [token_idx]
    imul rax, 32
    lea rsi, [tokens + rax + 8]
    call strcat
    lea rsi, [newline]
    call strcat
    jmp .next_token

.gen_lparen:
    lea rsi, [inst_comment]
    call strcat
    lea rsi, [lparen_text]
    call strcat
    lea rsi, [newline]
    call strcat
    jmp .next_token

.gen_rparen:
    lea rsi, [inst_comment]
    call strcat
    lea rsi, [rparen_text]
    call strcat
    lea rsi, [newline]
    call strcat
    jmp .next_token

.gen_lbrace:
    lea rsi, [inst_push]
    call strcat
    lea rsi, [inst_mov_rbp]
    call strcat
    jmp .next_token

.gen_rbrace:
    lea rsi, [inst_leave]
    call strcat
    lea rsi, [inst_ret]
    call strcat
    jmp .next_token

.gen_semi:
    ; End of statement

.next_token:
    call consume_token
    jmp .gen_loop

.gen_done:
    ; Add footer
    lea rsi, [asm_footer]
    call strcat

    ; Write to stdout
    mov rcx, -11
    call GetStdHandle

    mov rcx, rax
    lea rdx, [output_buffer]
    
    ; Calculate length
    lea rax, [output_buffer]
    mov rdi, rax
    mov rcx, -1
    xor al, al
    repne scasb
    neg rcx
    dec rcx
    mov r8, rcx
    
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    leave
    ret

lparen_text: db "(", 0
rparen_text: db ")", 0

strcat:
    push rbp
    mov rbp, rsp
    push rdi
    push rsi
    push rbx

    mov rbx, rdi

    mov al, [rbx]
    test al, al
    jz .found_end
.find_end:
    inc rbx
    mov al, [rbx]
    test al, al
    jnz .find_end

.found_end:
    mov rdi, rbx
.copy:
    lodsb
    stosb
    test al, al
    jnz .copy

    pop rbx
    pop rsi
    pop rdi
    leave
    ret

print_number:
    push rbp
    mov rbp, rsp
    sub rsp, 64

    mov rbx, 10
    xor rcx, rcx
    
    test rax, rax
    jnz .convert_loop
    mov byte [number_buffer], '0'
    mov byte [number_buffer+1], 0
    jmp .print_it

.convert_loop:
    xor rdx, rdx
    div rbx
    push rdx
    inc rcx
    test rax, rax
    jnz .convert_loop

    lea rdi, [number_buffer]
.write_loop:
    pop rax
    add al, '0'
    stosb
    dec rcx
    jnz .write_loop
    mov byte [rdi], 0

.print_it:
    mov rcx, -11
    call GetStdHandle

    ; Calculate length
    lea rax, [number_buffer]
    mov rdi, rax
    mov rcx, -1
    xor al, al
    repne scasb
    neg rcx
    dec rcx

    mov r8, rcx
    mov rcx, rax
    lea rdx, [number_buffer]
    lea r9, [written]
    mov qword [rsp+32], 0
    call WriteFile

    leave
    ret
