#pragma once
/* RAWRXD_COPILOT_MARKOV_001 — IDE autocomplete only. Not Deep2. */
#define RAWRXD_COPILOT_MARKOV_001 1
#define PRODUCT_SURFACE_IDE_AUTOCOMPLETE 1
#define DEEP2_HOTPATH 0
#define TRILLION_PARAMETER_NAMESPACE 1
#define TRILLION_PARAMETER_ALLOCATION 0
#define OBSERVED_TRANSITIONS_ONLY 1
#define MODEL_LOAD_ONCE 1
#define PERSISTENT_STDIO 1
#define NETWORK_REQUIRED 0
#define THIRD_PARTY_RUNTIME_REQUIRED 0
#define EDITOR_CONTEXT_IS_QUERY 1
#define GHOST_TEXT_IS_OUTPUT 1
/*
  LOGICAL_ADDRESS_SPACE != PHYSICAL_WORKING_SET
  LOGICAL_PARAMETER_SLOTS = 1_000_000_000_000
  PHYSICAL_MODEL = observed transitions only

  EDITOR → cursor → stdio COMPLETE → sparse backoff → RESULT → ghost

  Do not wire into lavapath / QKV / KVA / BgBmLaw / generateStream.
*/
