// LavapathProductLaw.hpp — product seals only after LavaPath + teardown delta=0.
#pragma once

#define RAWRXD_LAVAPATH 1
#define RAWRXD_REVERSE_COMPLETION 1
#define RAWRXD_PRODUCE_ONE 1
#define RAWRXD_TIMER_START 0
#define RAWRXD_WOULD_START 0
#define RAWRXD_SYNTHETIC_COMPLETE 0
#define RAWRXD_REQUIRE_COMPLETED_RUN 1
#define RAWRXD_REQUIRE_TD11 1
#define RAWRXD_REQUIRE_EXIT0 1
#define RAWRXD_NO_TP 1
#define RAWRXD_CHAIN_OF_THOUGHT_STREAM 0
#define RAWRXD_EXTERNAL_SCRATCH_STREAM 1
#define RAWRXD_FUTURE_PLAN_REQUIRED 0
#define RAWRXD_REOBSERVE_AFTER_EACH_PRODUCE 1
#define RAWRXD_UNAVAILABLE_IF_NO_REAL_ARC 1
#define RAWRXD_HIDDEN_BLOCKER 0
#define RAWRXD_REQUIRE_ALL_FEATURES 0
#define RAWRXD_REQUIRE_ONLY_GOAL_PATH 1

/*
  TERMINAL INTENT → Observe → BuildRequirements → ChoreographOut
    OPTIONAL → ERASE | SATISFIED → ERASE | NEVER_MATERIALIZED_TEARDOWN → ERASE
    FAILED_PATH_WITH_ALTERNATIVE → SUBSTITUTE | DEFERRABLE → DEFER
    ONLY_IRREDUCIBLE_NOW → Produce1 → LavaPath → receipt → observe
  LAVAPATH_COMPLETE = remaining_delta==0 AND lavapath receipts AND TD iff materialized
  PRODUCT_PASS / PROMOTE_IF = PromoteReady tetrad only
    (PRODUCT_OPEN_PASS && SESSION_ENTER_PASS
     && GENERATED_TOKENS>0 && TOKEN_COMMIT_PASS); PROMOTE=0 until probe
  MULTI_FAMILY = next independent gate (≠ TinyLlama R25 ProductOpen)
*/

