// RawrStreamerVocabulary.hpp
#pragma once

#ifndef RAWR_U32
#define RAWR_U32 unsigned int
#endif

#ifndef RAWR_U64
#define RAWR_U64 unsigned long long
#endif

#ifndef RAWR_I32
#define RAWR_I32 int
#endif

#ifndef RAWR_F64
#define RAWR_F64 double
#endif

enum RawrStreamState : RAWR_U32 {
    RAWR_STREAM_COLD = 0,
    RAWR_STREAM_BOOT,
    RAWR_STREAM_MODEL_RESOLVE,
    RAWR_STREAM_MODEL_OPEN,
    RAWR_STREAM_MODEL_INDEX,
    RAWR_STREAM_MODEL_FACTS,
    RAWR_STREAM_TOKENIZER_OPEN,
    RAWR_STREAM_EXEC_CREATE,
    RAWR_STREAM_CAP_DISCOVER,
    RAWR_STREAM_SPACE_SNAPSHOT,
    RAWR_STREAM_PLAN,
    RAWR_STREAM_PREFILL,
    RAWR_STREAM_DECODE,
    RAWR_STREAM_EMIT,
    RAWR_STREAM_COMPLETE,
    RAWR_STREAM_BLOCKED,
    RAWR_STREAM_FAIL
};

enum RawrStreamStage : RAWR_U32 {
    RAWR_STAGE_NONE = 0,

    RAWR_STAGE_CLI_PARSE,
    RAWR_STAGE_ENV_BIND,
    RAWR_STAGE_MODEL_LOCATE,
    RAWR_STAGE_GGUF_OPEN,
    RAWR_STAGE_GGUF_INDEX,
    RAWR_STAGE_TENSOR_INDEX,
    RAWR_STAGE_ARCH_FACTS,
    RAWR_STAGE_TOKENIZER_LOAD,
    RAWR_STAGE_EXEC_INSTANCE,

    RAWR_STAGE_DEVICE_DISCOVER,
    RAWR_STAGE_CAPABILITY_SOLVE,
    RAWR_STAGE_GEOMETRY_PROBE,
    RAWR_STAGE_SHADER_VARIANTS,
    RAWR_STAGE_KERNEL_CANDIDATES,
    RAWR_STAGE_LEGALITY_FILTER,
    RAWR_STAGE_PARITY_MEASURE,
    RAWR_STAGE_WINNER_SELECT,

    RAWR_STAGE_PROMPT_TOKENIZE,
    RAWR_STAGE_EMBED,
    RAWR_STAGE_PREFILL_LAYER,
    RAWR_STAGE_DECODE_LAYER,
    RAWR_STAGE_ATTENTION,
    RAWR_STAGE_Q_PROJ,
    RAWR_STAGE_K_PROJ,
    RAWR_STAGE_V_PROJ,
    RAWR_STAGE_QKV_PROJ,
    RAWR_STAGE_KVA,
    RAWR_STAGE_O_PROJ,
    RAWR_STAGE_FFN_GATE,
    RAWR_STAGE_FFN_UP,
    RAWR_STAGE_FFN_DOWN,
    RAWR_STAGE_RMSNORM,
    RAWR_STAGE_FINAL_NORM,
    RAWR_STAGE_LOGITS,
    RAWR_STAGE_SAMPLE,
    RAWR_STAGE_DETOKENIZE,
    RAWR_STAGE_TOKEN_EMIT,
    RAWR_STAGE_STOP_CHECK,
    RAWR_STAGE_TEARDOWN
};

enum RawrStreamEvent : RAWR_U32 {
    RAWR_EVENT_NONE = 0,

    RAWR_EVENT_RUN_BEGIN,
    RAWR_EVENT_RUN_READY,
    RAWR_EVENT_RUN_BLOCKED,
    RAWR_EVENT_RUN_FAIL,
    RAWR_EVENT_RUN_COMPLETE,

    RAWR_EVENT_MODEL_FOUND,
    RAWR_EVENT_MODEL_OPENED,
    RAWR_EVENT_MODEL_INDEXED,
    RAWR_EVENT_MODEL_FACTS_BOUND,
    RAWR_EVENT_MODEL_EXEC_CREATED,

    RAWR_EVENT_TENSOR_DISCOVERED,
    RAWR_EVENT_TENSOR_ADDRESSED,
    RAWR_EVENT_TENSOR_REGISTERED,
    RAWR_EVENT_TENSOR_ACQUIRE_BEGIN,
    RAWR_EVENT_TENSOR_ACQUIRE_DONE,
    RAWR_EVENT_TENSOR_RELEASE,

    RAWR_EVENT_CAPS_DISCOVERED,
    RAWR_EVENT_SPACE_SNAPSHOT,
    RAWR_EVENT_SHAPE_LEGAL,
    RAWR_EVENT_SHAPE_REJECTED,
    RAWR_EVENT_KERNEL_DISPATCH,
    RAWR_EVENT_KERNEL_PARITY_PASS,
    RAWR_EVENT_KERNEL_PARITY_FAIL,
    RAWR_EVENT_KERNEL_MEASURED,
    RAWR_EVENT_KERNEL_WINNER,

    RAWR_EVENT_PREFILL_BEGIN,
    RAWR_EVENT_PREFILL_DONE,
    RAWR_EVENT_DECODE_BEGIN,
    RAWR_EVENT_DECODE_STEP_BEGIN,
    RAWR_EVENT_DECODE_STEP_DONE,

    RAWR_EVENT_EMBED_WRITTEN,
    RAWR_EVENT_LAYER_WRITTEN,
    RAWR_EVENT_FINAL_NORM_WRITTEN,
    RAWR_EVENT_LOGITS_WRITTEN,
    RAWR_EVENT_TOKEN_SAMPLED,
    RAWR_EVENT_TOKEN_EMITTED,

    RAWR_EVENT_STOP_EOS,
    RAWR_EVENT_STOP_MAX_TOKENS,
    RAWR_EVENT_STOP_USER_CANCEL,
    RAWR_EVENT_STOP_ERROR
};

enum RawrStreamStatus : RAWR_U32 {
    RAWR_STATUS_UNKNOWN = 0,
    RAWR_STATUS_PASS,
    RAWR_STATUS_OPEN,
    RAWR_STATUS_BLOCKED,
    RAWR_STATUS_FAIL,
    RAWR_STATUS_SKIP,
    RAWR_STATUS_RETRY,
    RAWR_STATUS_RECOVERED
};

enum RawrStreamBlocker : RAWR_U32 {
    RAWR_BLOCK_NONE = 0,

    RAWR_BLOCK_MODEL_NOT_FOUND,
    RAWR_BLOCK_MODEL_OPEN_FAIL,
    RAWR_BLOCK_GGUF_INVALID,
    RAWR_BLOCK_TENSOR_MISSING,
    RAWR_BLOCK_TENSOR_UNADDRESSED,
    RAWR_BLOCK_TENSOR_UNACQUIRED,
    RAWR_BLOCK_TOKENIZER_MISSING,
    RAWR_BLOCK_MODEL_FACT_INVALID,
    RAWR_BLOCK_EXEC_INSTANCE_INVALID,

    RAWR_BLOCK_NO_DEVICE,
    RAWR_BLOCK_NO_LEGAL_SHAPE,
    RAWR_BLOCK_NO_SHADER_VARIANT,
    RAWR_BLOCK_NO_PARITY_PASS,
    RAWR_BLOCK_NO_MEASURE,
    RAWR_BLOCK_NO_WINNER,

    RAWR_BLOCK_EMBED_ZERO,
    RAWR_BLOCK_LAYER_ZERO,
    RAWR_BLOCK_FINAL_NORM_ZERO,
    RAWR_BLOCK_LOGITS_ZERO,
    RAWR_BLOCK_SAMPLE_INVALID,

    RAWR_BLOCK_MEMORY_PRESSURE,
    RAWR_BLOCK_DEVICE_LOST,
    RAWR_BLOCK_QUEUE_FAIL,
    RAWR_BLOCK_DISPATCH_FAIL,
    RAWR_BLOCK_PARITY_FAIL,
    RAWR_BLOCK_TIMEOUT
};

enum RawrTokenState : RAWR_U32 {
    RAWR_TOKEN_NONE = 0,
    RAWR_TOKEN_PROMPT,
    RAWR_TOKEN_PREFILL,
    RAWR_TOKEN_DECODE,
    RAWR_TOKEN_SAMPLE,
    RAWR_TOKEN_EMIT,
    RAWR_TOKEN_STOP
};

enum RawrBufferKind : RAWR_U32 {
    RAWR_BUFFER_NONE = 0,
    RAWR_BUFFER_TOKEN_IDS,
    RAWR_BUFFER_EMBED,
    RAWR_BUFFER_HIDDEN_A,
    RAWR_BUFFER_HIDDEN_B,
    RAWR_BUFFER_ATTN_SCRATCH,
    RAWR_BUFFER_FFN_SCRATCH,
    RAWR_BUFFER_FINAL_HIDDEN,
    RAWR_BUFFER_LOGITS,
    RAWR_BUFFER_KV_K,
    RAWR_BUFFER_KV_V,
    RAWR_BUFFER_TENSOR_VIEW,
    RAWR_BUFFER_DEVICE_STORAGE,
    RAWR_BUFFER_HOST_STAGING
};

enum RawrTensorAccess : RAWR_U32 {
    RAWR_ACCESS_NONE = 0,
    RAWR_ACCESS_HOST_READ,
    RAWR_ACCESS_HOST_WRITE,
    RAWR_ACCESS_DEVICE_READ,
    RAWR_ACCESS_DEVICE_WRITE,
    RAWR_ACCESS_HOST_DEVICE_COPY,
    RAWR_ACCESS_EXECUTE
};

enum RawrReceiptField : RAWR_U32 {
    RAWR_FIELD_NONE = 0,

    RAWR_FIELD_STREAM_STATE,
    RAWR_FIELD_STAGE,
    RAWR_FIELD_EVENT,
    RAWR_FIELD_STATUS,
    RAWR_FIELD_BLOCKED_AT,
    RAWR_FIELD_BLOCKED_OWNER,

    RAWR_FIELD_MODEL_PATH,
    RAWR_FIELD_MODEL_ARCH,
    RAWR_FIELD_MODEL_HIDDEN,
    RAWR_FIELD_MODEL_LAYERS,
    RAWR_FIELD_MODEL_HEADS,
    RAWR_FIELD_MODEL_KV_HEADS,
    RAWR_FIELD_MODEL_HEAD_DIM,
    RAWR_FIELD_MODEL_FFN,
    RAWR_FIELD_MODEL_VOCAB,

    RAWR_FIELD_TENSORS_DISCOVERED,
    RAWR_FIELD_TENSORS_ADDRESSED,
    RAWR_FIELD_TENSORS_REGISTERED,
    RAWR_FIELD_INVALID_SHARD,
    RAWR_FIELD_INVALID_RANGE,
    RAWR_FIELD_OVERFLOW_RANGE,
    RAWR_FIELD_ZERO_SIZE,
    RAWR_FIELD_UNADDRESSED,

    RAWR_FIELD_HOST_AVAIL_BYTES,
    RAWR_FIELD_DEVICE_BUDGET_BYTES,
    RAWR_FIELD_DEVICE_USAGE_BYTES,
    RAWR_FIELD_DEVICE_HEADROOM_BYTES,

    RAWR_FIELD_KERNEL_NAME,
    RAWR_FIELD_ROWS_PER_WG,
    RAWR_FIELD_LOCAL_X,
    RAWR_FIELD_LOCAL_Y,
    RAWR_FIELD_LOCAL_Z,
    RAWR_FIELD_SHARED_BYTES,
    RAWR_FIELD_LEGAL,
    RAWR_FIELD_PARITY,
    RAWR_FIELD_MEASURE_COMPLETE,
    RAWR_FIELD_GPU_TIME_US,
    RAWR_FIELD_WALL_TIME_US,
    RAWR_FIELD_WINNER_INDEX,

    RAWR_FIELD_PROMPT_BYTES,
    RAWR_FIELD_PROMPT_TOKENS,
    RAWR_FIELD_POSITION,
    RAWR_FIELD_TOKEN_ID,
    RAWR_FIELD_TOKEN_TEXT,

    RAWR_FIELD_EMBED_NORM,
    RAWR_FIELD_LAYER_IN_NORM,
    RAWR_FIELD_LAYER_OUT_NORM,
    RAWR_FIELD_FINAL_NORM_BEFORE,
    RAWR_FIELD_FINAL_NORM_AFTER,
    RAWR_FIELD_LOGITS_NORM,

    RAWR_FIELD_PREFILL_MS,
    RAWR_FIELD_DECODE_MS,
    RAWR_FIELD_FIRST_TOKEN_MS,
    RAWR_FIELD_NS_PER_TOKEN,
    RAWR_FIELD_DECODE_TPS,
    RAWR_FIELD_GENERATED_TOKENS
};

struct RawrStreamReceipt {
    RAWR_U64 generation;
    RAWR_U64 sequence;
    RAWR_U32 state;
    RAWR_U32 stage;
    RAWR_U32 event;
    RAWR_U32 status;
    RAWR_U32 blocker;
    RAWR_U64 timestamp_ns;
    RAWR_U64 wall_us;
    RAWR_U64 value_u64;
    RAWR_F64 value_f64;
    const char* key;
    const char* text;
};

static const char* RawrStreamStateName(RawrStreamState v) {
    switch (v) {
        case RAWR_STREAM_COLD: return "COLD";
        case RAWR_STREAM_BOOT: return "BOOT";
        case RAWR_STREAM_MODEL_RESOLVE: return "MODEL_RESOLVE";
        case RAWR_STREAM_MODEL_OPEN: return "MODEL_OPEN";
        case RAWR_STREAM_MODEL_INDEX: return "MODEL_INDEX";
        case RAWR_STREAM_MODEL_FACTS: return "MODEL_FACTS";
        case RAWR_STREAM_TOKENIZER_OPEN: return "TOKENIZER_OPEN";
        case RAWR_STREAM_EXEC_CREATE: return "EXEC_CREATE";
        case RAWR_STREAM_CAP_DISCOVER: return "CAP_DISCOVER";
        case RAWR_STREAM_SPACE_SNAPSHOT: return "SPACE_SNAPSHOT";
        case RAWR_STREAM_PLAN: return "PLAN";
        case RAWR_STREAM_PREFILL: return "PREFILL";
        case RAWR_STREAM_DECODE: return "DECODE";
        case RAWR_STREAM_EMIT: return "EMIT";
        case RAWR_STREAM_COMPLETE: return "COMPLETE";
        case RAWR_STREAM_BLOCKED: return "BLOCKED";
        case RAWR_STREAM_FAIL: return "FAIL";
        default: return "UNKNOWN";
    }
}

static const char* RawrStreamStageName(RawrStreamStage v) {
    switch (v) {
        case RAWR_STAGE_NONE: return "NONE";
        case RAWR_STAGE_CLI_PARSE: return "CLI_PARSE";
        case RAWR_STAGE_ENV_BIND: return "ENV_BIND";
        case RAWR_STAGE_MODEL_LOCATE: return "MODEL_LOCATE";
        case RAWR_STAGE_GGUF_OPEN: return "GGUF_OPEN";
        case RAWR_STAGE_GGUF_INDEX: return "GGUF_INDEX";
        case RAWR_STAGE_TENSOR_INDEX: return "TENSOR_INDEX";
        case RAWR_STAGE_ARCH_FACTS: return "ARCH_FACTS";
        case RAWR_STAGE_TOKENIZER_LOAD: return "TOKENIZER_LOAD";
        case RAWR_STAGE_EXEC_INSTANCE: return "EXEC_INSTANCE";
        case RAWR_STAGE_DEVICE_DISCOVER: return "DEVICE_DISCOVER";
        case RAWR_STAGE_CAPABILITY_SOLVE: return "CAPABILITY_SOLVE";
        case RAWR_STAGE_GEOMETRY_PROBE: return "GEOMETRY_PROBE";
        case RAWR_STAGE_SHADER_VARIANTS: return "SHADER_VARIANTS";
        case RAWR_STAGE_KERNEL_CANDIDATES: return "KERNEL_CANDIDATES";
        case RAWR_STAGE_LEGALITY_FILTER: return "LEGALITY_FILTER";
        case RAWR_STAGE_PARITY_MEASURE: return "PARITY_MEASURE";
        case RAWR_STAGE_WINNER_SELECT: return "WINNER_SELECT";
        case RAWR_STAGE_PROMPT_TOKENIZE: return "PROMPT_TOKENIZE";
        case RAWR_STAGE_EMBED: return "EMBED";
        case RAWR_STAGE_PREFILL_LAYER: return "PREFILL_LAYER";
        case RAWR_STAGE_DECODE_LAYER: return "DECODE_LAYER";
        case RAWR_STAGE_ATTENTION: return "ATTENTION";
        case RAWR_STAGE_Q_PROJ: return "Q_PROJ";
        case RAWR_STAGE_K_PROJ: return "K_PROJ";
        case RAWR_STAGE_V_PROJ: return "V_PROJ";
        case RAWR_STAGE_QKV_PROJ: return "QKV_PROJ";
        case RAWR_STAGE_KVA: return "KVA";
        case RAWR_STAGE_O_PROJ: return "O_PROJ";
        case RAWR_STAGE_FFN_GATE: return "FFN_GATE";
        case RAWR_STAGE_FFN_UP: return "FFN_UP";
        case RAWR_STAGE_FFN_DOWN: return "FFN_DOWN";
        case RAWR_STAGE_RMSNORM: return "RMSNORM";
        case RAWR_STAGE_FINAL_NORM: return "FINAL_NORM";
        case RAWR_STAGE_LOGITS: return "LOGITS";
        case RAWR_STAGE_SAMPLE: return "SAMPLE";
        case RAWR_STAGE_DETOKENIZE: return "DETOKENIZE";
        case RAWR_STAGE_TOKEN_EMIT: return "TOKEN_EMIT";
        case RAWR_STAGE_STOP_CHECK: return "STOP_CHECK";
        case RAWR_STAGE_TEARDOWN: return "TEARDOWN";
        default: return "UNKNOWN";
    }
}

static const char* RawrStreamEventName(RawrStreamEvent v) {
    switch (v) {
        case RAWR_EVENT_NONE: return "NONE";
        case RAWR_EVENT_RUN_BEGIN: return "RUN_BEGIN";
        case RAWR_EVENT_RUN_READY: return "RUN_READY";
        case RAWR_EVENT_RUN_BLOCKED: return "RUN_BLOCKED";
        case RAWR_EVENT_RUN_FAIL: return "RUN_FAIL";
        case RAWR_EVENT_RUN_COMPLETE: return "RUN_COMPLETE";
        case RAWR_EVENT_MODEL_FOUND: return "MODEL_FOUND";
        case RAWR_EVENT_MODEL_OPENED: return "MODEL_OPENED";
        case RAWR_EVENT_MODEL_INDEXED: return "MODEL_INDEXED";
        case RAWR_EVENT_MODEL_FACTS_BOUND: return "MODEL_FACTS_BOUND";
        case RAWR_EVENT_MODEL_EXEC_CREATED: return "MODEL_EXEC_CREATED";
        case RAWR_EVENT_TENSOR_DISCOVERED: return "TENSOR_DISCOVERED";
        case RAWR_EVENT_TENSOR_ADDRESSED: return "TENSOR_ADDRESSED";
        case RAWR_EVENT_TENSOR_REGISTERED: return "TENSOR_REGISTERED";
        case RAWR_EVENT_TENSOR_ACQUIRE_BEGIN: return "TENSOR_ACQUIRE_BEGIN";
        case RAWR_EVENT_TENSOR_ACQUIRE_DONE: return "TENSOR_ACQUIRE_DONE";
        case RAWR_EVENT_TENSOR_RELEASE: return "TENSOR_RELEASE";
        case RAWR_EVENT_CAPS_DISCOVERED: return "CAPS_DISCOVERED";
        case RAWR_EVENT_SPACE_SNAPSHOT: return "SPACE_SNAPSHOT";
        case RAWR_EVENT_SHAPE_LEGAL: return "SHAPE_LEGAL";
        case RAWR_EVENT_SHAPE_REJECTED: return "SHAPE_REJECTED";
        case RAWR_EVENT_KERNEL_DISPATCH: return "KERNEL_DISPATCH";
        case RAWR_EVENT_KERNEL_PARITY_PASS: return "KERNEL_PARITY_PASS";
        case RAWR_EVENT_KERNEL_PARITY_FAIL: return "KERNEL_PARITY_FAIL";
        case RAWR_EVENT_KERNEL_MEASURED: return "KERNEL_MEASURED";
        case RAWR_EVENT_KERNEL_WINNER: return "KERNEL_WINNER";
        case RAWR_EVENT_PREFILL_BEGIN: return "PREFILL_BEGIN";
        case RAWR_EVENT_PREFILL_DONE: return "PREFILL_DONE";
        case RAWR_EVENT_DECODE_BEGIN: return "DECODE_BEGIN";
        case RAWR_EVENT_DECODE_STEP_BEGIN: return "DECODE_STEP_BEGIN";
        case RAWR_EVENT_DECODE_STEP_DONE: return "DECODE_STEP_DONE";
        case RAWR_EVENT_EMBED_WRITTEN: return "EMBED_WRITTEN";
        case RAWR_EVENT_LAYER_WRITTEN: return "LAYER_WRITTEN";
        case RAWR_EVENT_FINAL_NORM_WRITTEN: return "FINAL_NORM_WRITTEN";
        case RAWR_EVENT_LOGITS_WRITTEN: return "LOGITS_WRITTEN";
        case RAWR_EVENT_TOKEN_SAMPLED: return "TOKEN_SAMPLED";
        case RAWR_EVENT_TOKEN_EMITTED: return "TOKEN_EMITTED";
        case RAWR_EVENT_STOP_EOS: return "STOP_EOS";
        case RAWR_EVENT_STOP_MAX_TOKENS: return "STOP_MAX_TOKENS";
        case RAWR_EVENT_STOP_USER_CANCEL: return "STOP_USER_CANCEL";
        case RAWR_EVENT_STOP_ERROR: return "STOP_ERROR";
        default: return "UNKNOWN";
    }
}

static const char* RawrStreamStatusName(RawrStreamStatus v) {
    switch (v) {
        case RAWR_STATUS_UNKNOWN: return "UNKNOWN";
        case RAWR_STATUS_PASS: return "PASS";
        case RAWR_STATUS_OPEN: return "OPEN";
        case RAWR_STATUS_BLOCKED: return "BLOCKED";
        case RAWR_STATUS_FAIL: return "FAIL";
        case RAWR_STATUS_SKIP: return "SKIP";
        case RAWR_STATUS_RETRY: return "RETRY";
        case RAWR_STATUS_RECOVERED: return "RECOVERED";
        default: return "UNKNOWN";
    }
}

static const char* RawrStreamBlockerName(RawrStreamBlocker v) {
    switch (v) {
        case RAWR_BLOCK_NONE: return "NONE";
        case RAWR_BLOCK_MODEL_NOT_FOUND: return "MODEL_NOT_FOUND";
        case RAWR_BLOCK_MODEL_OPEN_FAIL: return "MODEL_OPEN_FAIL";
        case RAWR_BLOCK_GGUF_INVALID: return "GGUF_INVALID";
        case RAWR_BLOCK_TENSOR_MISSING: return "TENSOR_MISSING";
        case RAWR_BLOCK_TENSOR_UNADDRESSED: return "TENSOR_UNADDRESSED";
        case RAWR_BLOCK_TENSOR_UNACQUIRED: return "TENSOR_UNACQUIRED";
        case RAWR_BLOCK_TOKENIZER_MISSING: return "TOKENIZER_MISSING";
        case RAWR_BLOCK_MODEL_FACT_INVALID: return "MODEL_FACT_INVALID";
        case RAWR_BLOCK_EXEC_INSTANCE_INVALID: return "EXEC_INSTANCE_INVALID";
        case RAWR_BLOCK_NO_DEVICE: return "NO_DEVICE";
        case RAWR_BLOCK_NO_LEGAL_SHAPE: return "NO_LEGAL_SHAPE";
        case RAWR_BLOCK_NO_SHADER_VARIANT: return "NO_SHADER_VARIANT";
        case RAWR_BLOCK_NO_PARITY_PASS: return "NO_PARITY_PASS";
        case RAWR_BLOCK_NO_MEASURE: return "NO_MEASURE";
        case RAWR_BLOCK_NO_WINNER: return "NO_WINNER";
        case RAWR_BLOCK_EMBED_ZERO: return "EMBED_ZERO";
        case RAWR_BLOCK_LAYER_ZERO: return "LAYER_ZERO";
        case RAWR_BLOCK_FINAL_NORM_ZERO: return "FINAL_NORM_ZERO";
        case RAWR_BLOCK_LOGITS_ZERO: return "LOGITS_ZERO";
        case RAWR_BLOCK_SAMPLE_INVALID: return "SAMPLE_INVALID";
        case RAWR_BLOCK_MEMORY_PRESSURE: return "MEMORY_PRESSURE";
        case RAWR_BLOCK_DEVICE_LOST: return "DEVICE_LOST";
        case RAWR_BLOCK_QUEUE_FAIL: return "QUEUE_FAIL";
        case RAWR_BLOCK_DISPATCH_FAIL: return "DISPATCH_FAIL";
        case RAWR_BLOCK_PARITY_FAIL: return "PARITY_FAIL";
        case RAWR_BLOCK_TIMEOUT: return "TIMEOUT";
        default: return "UNKNOWN";
    }
}

static const char* RawrTokenStateName(RawrTokenState v) {
    switch (v) {
        case RAWR_TOKEN_NONE: return "NONE";
        case RAWR_TOKEN_PROMPT: return "PROMPT";
        case RAWR_TOKEN_PREFILL: return "PREFILL";
        case RAWR_TOKEN_DECODE: return "DECODE";
        case RAWR_TOKEN_SAMPLE: return "SAMPLE";
        case RAWR_TOKEN_EMIT: return "EMIT";
        case RAWR_TOKEN_STOP: return "STOP";
        default: return "UNKNOWN";
    }
}

static const char* RawrBufferKindName(RawrBufferKind v) {
    switch (v) {
        case RAWR_BUFFER_NONE: return "NONE";
        case RAWR_BUFFER_TOKEN_IDS: return "TOKEN_IDS";
        case RAWR_BUFFER_EMBED: return "EMBED";
        case RAWR_BUFFER_HIDDEN_A: return "HIDDEN_A";
        case RAWR_BUFFER_HIDDEN_B: return "HIDDEN_B";
        case RAWR_BUFFER_ATTN_SCRATCH: return "ATTN_SCRATCH";
        case RAWR_BUFFER_FFN_SCRATCH: return "FFN_SCRATCH";
        case RAWR_BUFFER_FINAL_HIDDEN: return "FINAL_HIDDEN";
        case RAWR_BUFFER_LOGITS: return "LOGITS";
        case RAWR_BUFFER_KV_K: return "KV_K";
        case RAWR_BUFFER_KV_V: return "KV_V";
        case RAWR_BUFFER_TENSOR_VIEW: return "TENSOR_VIEW";
        case RAWR_BUFFER_DEVICE_STORAGE: return "DEVICE_STORAGE";
        case RAWR_BUFFER_HOST_STAGING: return "HOST_STAGING";
        default: return "UNKNOWN";
    }
}

static const char* RawrTensorAccessName(RawrTensorAccess v) {
    switch (v) {
        case RAWR_ACCESS_NONE: return "NONE";
        case RAWR_ACCESS_HOST_READ: return "HOST_READ";
        case RAWR_ACCESS_HOST_WRITE: return "HOST_WRITE";
        case RAWR_ACCESS_DEVICE_READ: return "DEVICE_READ";
        case RAWR_ACCESS_DEVICE_WRITE: return "DEVICE_WRITE";
        case RAWR_ACCESS_HOST_DEVICE_COPY: return "HOST_DEVICE_COPY";
        case RAWR_ACCESS_EXECUTE: return "EXECUTE";
        default: return "UNKNOWN";
    }
}

static const char* RawrReceiptFieldName(RawrReceiptField v) {
    switch (v) {
        case RAWR_FIELD_NONE: return "NONE";
        case RAWR_FIELD_STREAM_STATE: return "STREAM_STATE";
        case RAWR_FIELD_STAGE: return "STAGE";
        case RAWR_FIELD_EVENT: return "EVENT";
        case RAWR_FIELD_STATUS: return "STATUS";
        case RAWR_FIELD_BLOCKED_AT: return "BLOCKED_AT";
        case RAWR_FIELD_BLOCKED_OWNER: return "BLOCKED_OWNER";
        case RAWR_FIELD_MODEL_PATH: return "MODEL_PATH";
        case RAWR_FIELD_MODEL_ARCH: return "MODEL_ARCH";
        case RAWR_FIELD_MODEL_HIDDEN: return "MODEL_HIDDEN";
        case RAWR_FIELD_MODEL_LAYERS: return "MODEL_LAYERS";
        case RAWR_FIELD_MODEL_HEADS: return "MODEL_HEADS";
        case RAWR_FIELD_MODEL_KV_HEADS: return "MODEL_KV_HEADS";
        case RAWR_FIELD_MODEL_HEAD_DIM: return "MODEL_HEAD_DIM";
        case RAWR_FIELD_MODEL_FFN: return "MODEL_FFN";
        case RAWR_FIELD_MODEL_VOCAB: return "MODEL_VOCAB";
        case RAWR_FIELD_TENSORS_DISCOVERED: return "TENSORS_DISCOVERED";
        case RAWR_FIELD_TENSORS_ADDRESSED: return "TENSORS_ADDRESSED";
        case RAWR_FIELD_TENSORS_REGISTERED: return "TENSORS_REGISTERED";
        case RAWR_FIELD_INVALID_SHARD: return "INVALID_SHARD";
        case RAWR_FIELD_INVALID_RANGE: return "INVALID_RANGE";
        case RAWR_FIELD_OVERFLOW_RANGE: return "OVERFLOW_RANGE";
        case RAWR_FIELD_ZERO_SIZE: return "ZERO_SIZE";
        case RAWR_FIELD_UNADDRESSED: return "UNADDRESSED";
        case RAWR_FIELD_HOST_AVAIL_BYTES: return "HOST_AVAIL_BYTES";
        case RAWR_FIELD_DEVICE_BUDGET_BYTES: return "DEVICE_BUDGET_BYTES";
        case RAWR_FIELD_DEVICE_USAGE_BYTES: return "DEVICE_USAGE_BYTES";
        case RAWR_FIELD_DEVICE_HEADROOM_BYTES: return "DEVICE_HEADROOM_BYTES";
        case RAWR_FIELD_KERNEL_NAME: return "KERNEL_NAME";
        case RAWR_FIELD_ROWS_PER_WG: return "ROWS_PER_WG";
        case RAWR_FIELD_LOCAL_X: return "LOCAL_X";
        case RAWR_FIELD_LOCAL_Y: return "LOCAL_Y";
        case RAWR_FIELD_LOCAL_Z: return "LOCAL_Z";
        case RAWR_FIELD_SHARED_BYTES: return "SHARED_BYTES";
        case RAWR_FIELD_LEGAL: return "LEGAL";
        case RAWR_FIELD_PARITY: return "PARITY";
        case RAWR_FIELD_MEASURE_COMPLETE: return "MEASURE_COMPLETE";
        case RAWR_FIELD_GPU_TIME_US: return "GPU_TIME_US";
        case RAWR_FIELD_WALL_TIME_US: return "WALL_TIME_US";
        case RAWR_FIELD_WINNER_INDEX: return "WINNER_INDEX";
        case RAWR_FIELD_PROMPT_BYTES: return "PROMPT_BYTES";
        case RAWR_FIELD_PROMPT_TOKENS: return "PROMPT_TOKENS";
        case RAWR_FIELD_POSITION: return "POSITION";
        case RAWR_FIELD_TOKEN_ID: return "TOKEN_ID";
        case RAWR_FIELD_TOKEN_TEXT: return "TOKEN_TEXT";
        case RAWR_FIELD_EMBED_NORM: return "EMBED_NORM";
        case RAWR_FIELD_LAYER_IN_NORM: return "LAYER_IN_NORM";
        case RAWR_FIELD_LAYER_OUT_NORM: return "LAYER_OUT_NORM";
        case RAWR_FIELD_FINAL_NORM_BEFORE: return "FINAL_NORM_BEFORE";
        case RAWR_FIELD_FINAL_NORM_AFTER: return "FINAL_NORM_AFTER";
        case RAWR_FIELD_LOGITS_NORM: return "LOGITS_NORM";
        case RAWR_FIELD_PREFILL_MS: return "PREFILL_MS";
        case RAWR_FIELD_DECODE_MS: return "DECODE_MS";
        case RAWR_FIELD_FIRST_TOKEN_MS: return "FIRST_TOKEN_MS";
        case RAWR_FIELD_NS_PER_TOKEN: return "NS_PER_TOKEN";
        case RAWR_FIELD_DECODE_TPS: return "DECODE_TPS";
        case RAWR_FIELD_GENERATED_TOKENS: return "GENERATED_TOKENS";
        default: return "UNKNOWN";
    }
}
