#!/usr/bin/env python3
"""
Embed SPIR-V shaders as C++ header
Usage: python embed_shaders.py *.spv > embedded_shaders.hpp
"""

import sys
import struct
import os

def embed_shader_header(filepath):
    """Generate header declaration for SPIR-V shader"""
    name = os.path.splitext(os.path.basename(filepath))[0]
    var_name = name.upper() + "_SPV"
    
    print("// " + os.path.basename(filepath))
    print("extern const uint32_t " + var_name + "[];")
    print("extern const size_t " + var_name + "_SIZE;")
    print()

def embed_shader_impl(filepath):
    """Generate implementation definition for SPIR-V shader"""
    name = os.path.splitext(os.path.basename(filepath))[0]
    var_name = name.upper() + "_SPV"
    
    with open(filepath, 'rb') as f:
        data = f.read()
    
    # Parse as 32-bit words
    words = struct.unpack('<' + str(len(data)//4) + 'I', data)
    
    print("// " + os.path.basename(filepath))
    # Use inline const for C++17 ODR compliance - allows multiple definitions
    print("inline const uint32_t " + var_name + "[] = {")
    
    # Print 8 words per line
    for i in range(0, len(words), 8):
        line_words = words[i:i+8]
        hex_words = ["0x{:08X}".format(w) for w in line_words]
        print("    " + ", ".join(hex_words) + ",")
    
    print("};")
    print("inline const size_t " + var_name + "_SIZE = sizeof(" + var_name + ") / sizeof(uint32_t);")
    print()

def main():
    print("#pragma once")
    print("// Auto-generated SPIR-V shader bytecode")
    print("// Generated by embed_shaders.py")
    print()
    print("#include <cstdint>")
    print("#include <cstddef>")
    print()
    
    if len(sys.argv) < 2:
        print("// No shaders provided")
        return
    
    for filepath in sys.argv[1:]:
        if os.path.exists(filepath):
            embed_shader_impl(filepath)
        else:
            print("// Warning: " + filepath + " not found")
            print()

if __name__ == "__main__":
    main()
