// AutonomousAgent.hpp
// Self-Improving Agent with Feedback Loop
// Feature #4: Autonomous Task Planner + Feature #25: Global Consistency

#ifndef AUTONOMOUSAGENT_HPP
#define AUTONOMOUSAGENT_HPP

#include "AgentGraphRuntime.hpp"
#include "../session/SessionStore.hpp"
#include <atomic>
#include <thread>
#include <queue>
#include <functional>

namespace Sovereign {

/**
 * @struct OptimizationAction
 * @brief Action generated by autonomous decision engine
 */
struct OptimizationAction {
    enum Type {
        INCREASE_THREAD_AFFINITY,
        REDUCE_BATCH_SIZE,
        EXPAND_MEMORY_APERTURE,
        TRIGGER_CHECKPOINT,
        INCREASE_BATCH_SIZE,
        APPLY_PATCH,
        ROLLBACK_PATCH,
        SPAWN_SUBAGENT,
        NONE
    } type;
    
    std::string reason;
    std::unordered_map<std::string, std::string> parameters;
    uint64_t timestamp;
};

/**
 * @struct TelemetryMetrics
 * @brief Real-time performance metrics
 */
struct TelemetryMetrics {
    double faultRate = 0.0;           // Page faults per task
    double latencyMs = 0.0;           // Task latency
    double deltaZeroPercent = 0.0;    // Cache hit rate
    double memoryPressureMB = 0.0;    // Memory usage
    double faultTrend = 0.0;          // Trend direction
    uint64_t tasksCompleted = 0;
    uint64_t tasksFailed = 0;
};

/**
 * @class DecisionEngine
 * @brief Threshold-based decision generation
 */
class DecisionEngine {
    struct Threshold {
        double value;
        OptimizationAction::Type action;
        std::string description;
    };
    
    std::vector<Threshold> thresholds;
    
public:
    DecisionEngine() {
        // Configure default thresholds
        thresholds.push_back({10.0, OptimizationAction::INCREASE_THREAD_AFFINITY, 
                              "High fault rate detected"});
        thresholds.push_back({50.0, OptimizationAction::REDUCE_BATCH_SIZE, 
                              "Latency regression detected"});
        thresholds.push_back({20.0, OptimizationAction::EXPAND_MEMORY_APERTURE, 
                              "Low cache hit rate"});
        thresholds.push_back({1024.0, OptimizationAction::TRIGGER_CHECKPOINT, 
                              "Memory pressure high"});
        thresholds.push_back({-5.0, OptimizationAction::INCREASE_BATCH_SIZE, 
                              "Fault trend improving"});
    }
    
    OptimizationAction Evaluate(const TelemetryMetrics& metrics) {
        OptimizationAction action{OptimizationAction::NONE, "", {}, 0};
        
        if (metrics.faultRate > 10.0) {
            action.type = OptimizationAction::INCREASE_THREAD_AFFINITY;
            action.reason = "Fault rate " + std::to_string(metrics.faultRate) + 
                           " exceeds threshold 10.0";
        } else if (metrics.latencyMs > 50.0) {
            action.type = OptimizationAction::REDUCE_BATCH_SIZE;
            action.reason = "Latency " + std::to_string(metrics.latencyMs) + 
                           "ms exceeds threshold 50ms";
        } else if (metrics.deltaZeroPercent < 80.0) {
            action.type = OptimizationAction::EXPAND_MEMORY_APERTURE;
            action.reason = "Cache hit rate below 80%";
        } else if (metrics.memoryPressureMB > 1024.0) {
            action.type = OptimizationAction::TRIGGER_CHECKPOINT;
            action.reason = "Memory pressure critical";
        } else if (metrics.faultTrend < -5.0) {
            action.type = OptimizationAction::INCREASE_BATCH_SIZE;
            action.reason = "Fault trend improving";
        }
        
        action.timestamp = std::chrono::duration_cast<std::chrono::milliseconds>(
            std::chrono::steady_clock::now().time_since_epoch()).count();
        
        return action;
    }
};

/**
 * @class ActionExecutor
 * @brief Applies optimization actions
 */
class ActionExecutor {
    std::function<void(const OptimizationAction&)> callback;
    
public:
    void SetCallback(std::function<void(const OptimizationAction&)> cb) {
        callback = cb;
    }
    
    void Execute(const OptimizationAction& action) {
        if (callback) {
            callback(action);
        }
    }
    
    std::string ActionToString(OptimizationAction::Type type) {
        switch (type) {
            case OptimizationAction::INCREASE_THREAD_AFFINITY: return "INCREASE_THREAD_AFFINITY";
            case OptimizationAction::REDUCE_BATCH_SIZE: return "REDUCE_BATCH_SIZE";
            case OptimizationAction::EXPAND_MEMORY_APERTURE: return "EXPAND_MEMORY_APERTURE";
            case OptimizationAction::TRIGGER_CHECKPOINT: return "TRIGGER_CHECKPOINT";
            case OptimizationAction::INCREASE_BATCH_SIZE: return "INCREASE_BATCH_SIZE";
            case OptimizationAction::APPLY_PATCH: return "APPLY_PATCH";
            case OptimizationAction::ROLLBACK_PATCH: return "ROLLBACK_PATCH";
            case OptimizationAction::SPAWN_SUBAGENT: return "SPAWN_SUBAGENT";
            default: return "NONE";
        }
    }
};

/**
 * @class AutonomousAgent
 * @brief Self-optimizing agent with telemetry-driven decisions
 * 
 * Usage:
 *   AutonomousAgent agent(runtime, store);
 *   agent.SetEvaluationInterval(2000); // 2 seconds
 *   agent.Start();
 *   
 *   // Agent automatically optimizes based on telemetry
 *   agent.Stop();
 */
class AutonomousAgent {
    AgentGraphRuntime* runtime;
    SessionStore* store;
    DecisionEngine decisionEngine;
    ActionExecutor actionExecutor;
    
    std::atomic<bool> running{false};
    std::thread evaluationThread;
    std::thread executionThread;
    std::queue<OptimizationAction> actionQueue;
    std::mutex queueLock;
    std::condition_variable queueCV;
    
    uint64_t evaluationIntervalMs = 2000;
    TelemetryMetrics currentMetrics;
    mutable std::mutex metricsLock;
    
public:
    AutonomousAgent(AgentGraphRuntime* rt, SessionStore* st) 
        : runtime(rt), store(st) {}
    
    ~AutonomousAgent() { Stop(); }
    
    /**
     * @brief Set evaluation interval
     * @param intervalMs Milliseconds between evaluations
     */
    void SetEvaluationInterval(uint64_t intervalMs) {
        evaluationIntervalMs = intervalMs;
    }
    
    /**
     * @brief Start the autonomous agent
     */
    void Start();
    
    /**
     * @brief Stop the autonomous agent
     */
    void Stop();
    
    /**
     * @brief Update telemetry metrics
     * @param metrics Current performance metrics
     */
    void UpdateMetrics(const TelemetryMetrics& metrics);
    
    /**
     * @brief Get current metrics
     * @return Latest telemetry
     */
    TelemetryMetrics GetMetrics() const;
    
    /**
     * @brief Set action callback
     * @param callback Function to call when action generated
     */
    void SetActionCallback(std::function<void(const OptimizationAction&)> callback) {
        actionExecutor.SetCallback(callback);
    }
    
    /**
     * @brief Force immediate evaluation
     */
    void ForceEvaluation();
    
    /**
     * @brief Check if agent is running
     * @return true if active
     */
    bool IsRunning() const { return running.load(); }
    
private:
    void EvaluationLoop();
    void ExecutionLoop();
    void ProcessAction(const OptimizationAction& action);
};

} // namespace Sovereign

#endif // AUTONOMOUSAGENT_HPP
