/*
 * Truth Gate 003: llama.cpp Validator
 * 
 * Compares RawrXD output against llama.cpp reference
 */

#ifndef LLAMACPP_VALIDATOR_H
#define LLAMACPP_VALIDATOR_H

#include "gguf_integration.h"
#include "tokenizer_integration.h"
#include "transformer_executor.h"
#include "sampler_integration.h"

// Comparison result
struct InferenceResult {
    char rawrxd_output[256];
    char expected_output[256];
    bool tokens_match;
    double logit_relative_error;
    int rawrxd_token;
    int expected_token;
    double duration_ms;
};

// Run comparison test
bool LlamaCPPValidator_RunComparison(GGUFModel* model,
                                      TokenizerHandle* tokenizer,
                                      TransformerExecutor* executor,
                                      SamplerHandle* sampler,
                                      const char* prompt,
                                      InferenceResult* result);

// Compare logits
bool LlamaCPPValidator_CompareLogits(const float* rawrxd_logits,
                                        const float* reference_logits,
                                        int vocab_size,
                                        double* relative_error);

// Compare tokens
bool LlamaCPPValidator_CompareTokens(const int* rawrxd_tokens,
                                        const int* reference_tokens,
                                        int num_tokens);

// Load reference output from file (pre-generated by llama.cpp)
bool LlamaCPPValidator_LoadReference(const char* model_name,
                                      const char* prompt,
                                      int* expected_tokens,
                                      int max_tokens,
                                      int* num_tokens);

// Generate reference using llama.cpp (if available)
bool LlamaCPPValidator_GenerateReference(const char* model_path,
                                          const char* prompt,
                                          int* tokens,
                                          int max_tokens,
                                          int* num_tokens);

#endif // LLAMACPP_VALIDATOR_H
