// LavapathProductLaw.hpp — control-plane macros (no timers / no synthetic)
#pragma once

#define RAWRXD_LAVAPATH 1
#define RAWRXD_REVERSE_COMPLETION 1
#define RAWRXD_PRODUCE_ONE 1
#define RAWRXD_TIMER_START 0
#define RAWRXD_WOULD_START 0
#define RAWRXD_SYNTHETIC_COMPLETE 0
#define RAWRXD_REQUIRE_COMPLETED_RUN 1
#define RAWRXD_REQUIRE_TD11 1
#define RAWRXD_REQUIRE_EXIT0 1
#define RAWRXD_NO_TP 1
#define HIDDEN_BLOCKER 0
#define REQUIRE_ALL_FEATURES 0
#define REQUIRE_ONLY_GOAL_PATH 1
#define CHAIN_OF_THOUGHT_STREAM 0
#define EXTERNAL_SCRATCH_STREAM 1
#define FUTURE_PLAN_REQUIRED 0
#define REOBSERVE_AFTER_EACH_PRODUCE 1
#define UNAVAILABLE_IF_NO_REAL_ARC 1

/*
  OPTIONAL → ERASE | SATISFIED → ERASE | NEVER_MATERIALIZED_TEARDOWN → ERASE
  FAILED_PATH_WITH_ALTERNATIVE → SUBSTITUTE
  PRODUCT_TERMINAL = derived (not executable)
  OUTPUT_COMMITTED = token callback only
  ONLY_IRREDUCIBLE_NOW → Produce1 → LavaPath
*/
