# CMake generated Testfile for 
# Source directory: F:/~dev/rawrxd/tests
# Build directory: F:/~dev/rawrxd/build-ninja-fresh/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("test_ai_completions" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_ai_completions.exe")
set_tests_properties("test_ai_completions" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;125;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_llm_connectivity" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_llm_connectivity.exe")
set_tests_properties("test_llm_connectivity" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;142;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_tool_registry" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_tool_registry.exe")
set_tests_properties("test_tool_registry" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;151;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_voice_processor" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_voice_processor.exe")
set_tests_properties("test_voice_processor" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;161;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_zero_retention_manager" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_zero_retention_manager.exe")
set_tests_properties("test_zero_retention_manager" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;171;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_gui_components" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_gui_components.exe")
set_tests_properties("test_gui_components" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;180;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_semantic_diff_analyzer" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_semantic_diff_analyzer.exe")
set_tests_properties("test_semantic_diff_analyzer" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;189;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_ai_merge_resolver" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_ai_merge_resolver.exe")
set_tests_properties("test_ai_merge_resolver" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;201;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_sandboxed_terminal" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_sandboxed_terminal.exe")
set_tests_properties("test_sandboxed_terminal" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;210;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_agentic_file_operations" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_agentic_file_operations.exe")
set_tests_properties("test_agentic_file_operations" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;219;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("model_registry_test" "F:/~dev/rawrxd/build-ninja-fresh/tests/model_registry_test.exe")
set_tests_properties("model_registry_test" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;228;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_gguf_integration" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_gguf_integration.exe")
set_tests_properties("test_gguf_integration" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;246;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_swarm_scheduler_pin" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_swarm_scheduler_pin.exe")
set_tests_properties("test_swarm_scheduler_pin" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;259;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("deterministic_replay_gate" "F:/~dev/rawrxd/build-ninja-fresh/tests/deterministic_replay_gate.exe")
set_tests_properties("deterministic_replay_gate" PROPERTIES  LABELS "deterministic;ide;ghosttext" TIMEOUT "120" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;274;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("VAL063_InferenceGatewayHarness" "F:/~dev/rawrxd/build-ninja-fresh/tests/VAL063_InferenceGatewayHarness.exe")
set_tests_properties("VAL063_InferenceGatewayHarness" PROPERTIES  LABELS "certification;val-063;inference;gateway" TIMEOUT "300" _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;310;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_swarm_expert_heatmap_stress" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_swarm_expert_heatmap_stress.exe")
set_tests_properties("test_swarm_expert_heatmap_stress" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;327;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_moe_mixture_reference" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_moe_mixture_reference.exe")
set_tests_properties("test_moe_mixture_reference" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;335;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_moe_down_project_policy" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_moe_down_project_policy.exe")
set_tests_properties("test_moe_down_project_policy" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;343;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_moe_plan_row_mixture_pack_cache" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_moe_plan_row_mixture_pack_cache.exe")
set_tests_properties("test_moe_plan_row_mixture_pack_cache" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;351;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_basic_profiler" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_basic_profiler.exe")
set_tests_properties("test_basic_profiler" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;370;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_batch3_profiler_smoke" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_batch3_profiler_smoke.exe")
set_tests_properties("test_batch3_profiler_smoke" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;382;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_production_regression" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_production_regression.exe")
set_tests_properties("test_production_regression" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;417;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_instructions_provider" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_instructions_provider.exe")
set_tests_properties("test_instructions_provider" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;438;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_model_loader_streamer_smoke" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_model_loader_streamer_smoke.exe")
set_tests_properties("test_model_loader_streamer_smoke" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;537;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_predictive_memory_subsystem" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_predictive_memory_subsystem.exe")
set_tests_properties("test_predictive_memory_subsystem" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;568;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("smoke_core" "F:/~dev/rawrxd/build-ninja-fresh/tests/smoke_core.exe")
set_tests_properties("smoke_core" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;579;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_rmsnorm_avx2" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_rmsnorm_avx2.exe")
set_tests_properties("test_rmsnorm_avx2" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;600;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_softmax_avx2" "F:/~dev/rawrxd/build-ninja-fresh/tests/test_softmax_avx2.exe")
set_tests_properties("test_softmax_avx2" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;621;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("sovereign_integrated_test" "F:/~dev/rawrxd/build-ninja-fresh/bin/sovereign_integrated_test.exe")
set_tests_properties("sovereign_integrated_test" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;649;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
add_test("test_agentic_supervisor" "F:/~dev/rawrxd/build-ninja-fresh/bin/test_agentic_supervisor.exe")
set_tests_properties("test_agentic_supervisor" PROPERTIES  _BACKTRACE_TRIPLES "F:/~dev/rawrxd/tests/CMakeLists.txt;672;add_test;F:/~dev/rawrxd/tests/CMakeLists.txt;0;")
