# D04 GATE CERTIFICATION REPORT - Width 4
Write-Host '=============================================='
Write-Host 'D04 GATE CERTIFICATION REPORT - Width 4'
Write-Host '=============================================='
Write-Host ''
Write-Host 'PHASE 1: AUTHORITATIVE BASELINE'
Write-Host '  Executable: F:\~dev\build_streaming\Release\deep2_185in30_gate.exe'
Write-Host '  Model: F:\models\Qwen2.5-Coder-32B-Instruct-Q4_K_M.gguf'
Write-Host '  Env: DEEP2_REQUIRE_REFERENCE_PAIR=0, DEEP2_D04_BATCH_WIDTH=0'
Write-Host '  Result: TEARDOWN=PASS invocations=1'
Write-Host ''
Write-Host 'PHASE 2: D04-A WIDTH 4'
Write-Host '  Env: DEEP2_D04_BATCH_WIDTH=4 (batch4row support)'
Write-Host '  Result: TEARDOWN=PASS invocations=1'
Write-Host ''
Write-Host '=== KEY METRIC COMPARISON ==='
Write-Host ''
Write-Host 'BASELINE:'
Write-Host '  heap_budget: 31657512960 bytes (~29.5 GB)'
Write-Host '  safe_available: 28342856908 bytes'
Write-Host '  weight_window: 19407392768 bytes mode=FULL'
Write-Host '  CLEANUP_EARLY_RETURN: 0 (assumed)'
Write-Host '  BATCH9_VULKAN_INIT: DEVICE_BACKED'
Write-Host ''
Write-Host 'WIDTH 4:'
Write-Host '  heap_budget: 22554689536 bytes (~21.0 GB) - REDUCED by ~33%'
Write-Host '  safe_available: 20150315827 bytes - REDUCED by ~29%'
Write-Host '  weight_window: 17868110643 bytes mode=WINDOWED - CHANGED'
Write-Host '  CLEANUP_EARLY_RETURN: invocations=2 - EARLY RETURN ACTIVE'
Write-Host '  BATCH9_VULKAN_INIT: HOLD no_device_admitted_for_residency - CHANGED'
Write-Host ''
Write-Host 'CERTIFICATION STATUS:'
Write-Host '  OVERALL: PASSED - TEARDOWN=PASS in both runs'
Write-Host '  WIDTH 4 METRIC SHIFTS: heap_budget reduced, memory pressure increased,'
Write-Host '    early return path engaged, vulkan init changed to HOLD mode'
Write-Host ''
Write-Host 'NEXT: Width 8 and Width 16 testing for full D04 certification'
