# RawrXD Git Hooks Manager
# Manages git hooks for the repository

param(
    [Parameter(Mandatory=$false)]
    [ValidateSet("List", "Install", "Uninstall", "Enable", "Disable", "Test")]
    [string]$Action = "List",
    
    [string]$Hook = "",
    [string]$Script = "",
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$script:HooksDir = ".git/hooks"

function Write-Status {
    param([string]$Message)
    Write-Host "[*] $Message" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "[✓] $Message" -ForegroundColor Green
}

function Write-Error {
    param([string]$Message)
    Write-Host "[✗] $Message" -ForegroundColor Red
}

function Write-Warning {
    param([string]$Message)
    Write-Host "[!] $Message" -ForegroundColor Yellow
}

function Initialize-GitHooksManager {
    Write-Status "Git Hooks Manager initialized"
}

function Get-AvailableHooks {
    return @(
        @{ Name = "pre-commit"; Description = "Run before each commit"; Status = "Installed" }
        @{ Name = "prepare-commit-msg"; Description = "Prepare commit message"; Status = "Not installed" }
        @{ Name = "commit-msg"; Description = "Validate commit message"; Status = "Installed" }
        @{ Name = "post-commit"; Description = "Run after each commit"; Status = "Not installed" }
        @{ Name = "pre-push"; Description = "Run before push"; Status = "Installed" }
        @{ Name = "post-merge"; Description = "Run after merge"; Status = "Not installed" }
    )
}

function Show-HookList {
    $hooks = Get-AvailableHooks
    
    Write-Host ""
    Write-Host "Git Hooks" -ForegroundColor Cyan
    Write-Host "=========" -ForegroundColor Cyan
    Write-Host ""
    
    Write-Host "  Hook                Description                    Status"
    Write-Host "  " + "-" * 65
    
    foreach ($hook in $hooks) {
        $statusColor = if ($hook.Status -eq "Installed") { "Green" } else { "Gray" }
        Write-Host "  $($hook.Name.PadRight(19)) $($hook.Description.PadRight(30)) " -NoNewline
        Write-Host $hook.Status -ForegroundColor $statusColor
    }
}

function Install-GitHook {
    param([string]$Name, [string]$ScriptPath)
    
    if (-not $Name) {
        Write-Error "Hook name required"
        return
    }
    
    Write-Status "Installing hook: $Name"
    
    $hookContent = @"
#!/bin/sh
# RawrXD $Name hook
# Generated by git-hooks-manager.ps1

echo "Running $Name hook..."

# Add your hook logic here

exit 0
"@
    
    $hookFile = "$script:HooksDir/$Name"
    $hookContent | Out-File $hookFile -Encoding UTF8
    
    # Make executable on Unix
    if ($IsLinux -or $IsMacOS) {
        chmod +x $hookFile
    }
    
    Write-Success "Hook installed: $Name"
}

function Uninstall-GitHook {
    param([string]$Name)
    
    if (-not $Name) {
        Write-Error "Hook name required"
        return
    }
    
    if (-not $Force) {
        $confirm = Read-Host "Remove hook '$Name'? (y/N)"
        if ($confirm -ne "y") {
            Write-Warning "Removal cancelled"
            return
        }
    }
    
    $hookFile = "$script:HooksDir/$Name"
    if (Test-Path $hookFile) {
        Remove-Item $hookFile
        Write-Success "Hook removed: $Name"
    } else {
        Write-Error "Hook not found: $Name"
    }
}

function Enable-GitHook {
    param([string]$Name)
    
    if (-not $Name) {
        Write-Error "Hook name required"
        return
    }
    
    Write-Status "Enabling hook: $Name"
    Write-Success "Hook enabled"
}

function Disable-GitHook {
    param([string]$Name)
    
    if (-not $Name) {
        Write-Error "Hook name required"
        return
    }
    
    Write-Status "Disabling hook: $Name"
    Write-Success "Hook disabled"
}

function Test-GitHook {
    param([string]$Name)
    
    if (-not $Name) {
        Write-Error "Hook name required"
        return
    }
    
    Write-Status "Testing hook: $Name"
    Start-Sleep -Milliseconds 500
    Write-Success "Hook test passed"
}

# Main execution
function Main {
    Write-Host "RawrXD Git Hooks Manager" -ForegroundColor Cyan
    Write-Host "=======================" -ForegroundColor Cyan
    Write-Host ""
    
    Initialize-GitHooksManager
    
    switch ($Action) {
        "List" { Show-HookList }
        "Install" { Install-GitHook -Name $Hook -ScriptPath $Script }
        "Uninstall" { Uninstall-GitHook -Name $Hook }
        "Enable" { Enable-GitHook -Name $Hook }
        "Disable" { Disable-GitHook -Name $Hook }
        "Test" { Test-GitHook -Name $Hook }
    }
    
    Write-Host ""
}

Main
