# RawrXD Template Generator
# Generates project templates and boilerplate code

param(
    [Parameter(Mandatory=$false)]
    [ValidateSet("Model", "Plugin", "API", "Test", "Config", "Script", "List")]
    [string]$TemplateType = "List",
    
    [string]$Name = "",
    [string]$OutputPath = ".",
    [hashtable]$Variables = @{},
    [switch]$Force
)

$ErrorActionPreference = "Stop"

$script:TemplateDir = "templates"

function Write-Status {
    param([string]$Message)
    Write-Host "[*] $Message" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "[✓] $Message" -ForegroundColor Green
}

function Write-Error {
    param([string]$Message)
    Write-Host "[✗] $Message" -ForegroundColor Red
}

function Write-Warning {
    param([string]$Message)
    Write-Host "[!] $Message" -ForegroundColor Yellow
}

function Get-TemplateDefinitions {
    return @{
        Model = @{
            Description = "New GGML model wrapper"
            Files = @{
                "model.json" = @'
{
    "name": "{{Name}}",
    "version": "1.0.0",
    "type": "ggml",
    "architecture": "transformer",
    "parameters": {
        "context_length": 4096,
        "embedding_length": 4096,
        "attention_heads": 32,
        "layers": 32
    },
    "files": [
        "{{Name}}.gguf"
    ]
}
'@
                "README.md" = @'
# {{Name}} Model

## Overview

This is a GGML/GGUF model template.

## Usage

```python
from rawrxd import Model

model = Model("{{Name}}")
output = model.generate("Hello, world!")
```

## Configuration

Edit `model.json` to customize model parameters.

## License

{{License}}
'@
            }
        }
        
        Plugin = @{
            Description = "RawrXD plugin/extension"
            Files = @{
                "plugin.json" = @'
{
    "name": "{{Name}}",
    "version": "1.0.0",
    "description": "A RawrXD plugin",
    "author": "{{Author}}",
    "main": "index.js",
    "entry": "main",
    "hooks": [
        "onInit",
        "onShutdown"
    ],
    "permissions": [
        "model:read",
        "config:read"
    ],
    "dependencies": {}
}
'@
                "index.js" = @'
/**
 * {{Name}} Plugin
 * @version 1.0.0
 */

class {{Name}}Plugin {
    constructor() {
        this.name = "{{Name}}";
        this.version = "1.0.0";
    }

    async onInit(context) {
        console.log(`${this.name} plugin initialized`);
        // Initialize your plugin here
    }

    async onShutdown() {
        console.log(`${this.name} plugin shutting down`);
        // Cleanup here
    }

    // Add your plugin methods here
}

module.exports = {{Name}}Plugin;
'@
                "README.md" = @'
# {{Name}} Plugin

## Description

A RawrXD plugin.

## Installation

```bash
./plugin-manager.ps1 -Action Install -PluginName {{Name}}
```

## Usage

```javascript
const plugin = new {{Name}}Plugin();
await plugin.onInit(context);
```

## Configuration

Edit `plugin.json` to customize plugin settings.
'@
            }
        }
        
        API = @{
            Description = "REST API endpoint"
            Files = @{
                "{{Name}}.py" = @'
"""
{{Name}} API Endpoint
Generated by RawrXD Template Generator
"""

from fastapi import APIRouter, HTTPException
from pydantic import BaseModel
from typing import Optional, List

router = APIRouter(prefix="/{{NameLower}}", tags=["{{Name}}"])

class {{Name}}Request(BaseModel):
    prompt: str
    max_tokens: Optional[int] = 256
    temperature: Optional[float] = 0.7

class {{Name}}Response(BaseModel):
    text: str
    tokens_used: int
    generation_time: float

@router.post("/generate", response_model={{Name}}Response)
async def generate(request: {{Name}}Request):
    """
    Generate text using {{Name}} endpoint
    """
    try:
        # Implementation here
        return {{Name}}Response(
            text="Generated text",
            tokens_used=0,
            generation_time=0.0
        )
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))

@router.get("/health")
async def health_check():
    """Health check endpoint"""
    return {"status": "healthy", "service": "{{Name}}"}
'@
                "test_{{Name}}.py" = @'
"""
Tests for {{Name}} API
"""

import pytest
from fastapi.testclient import TestClient
from .{{Name}} import router

client = TestClient(router)

def test_health_check():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "healthy"

def test_generate():
    response = client.post("/generate", json={
        "prompt": "Hello",
        "max_tokens": 50
    })
    assert response.status_code == 200
    assert "text" in response.json()
'@
            }
        }
        
        Test = @{
            Description = "Unit test suite"
            Files = @{
                "test_{{Name}}.cpp" = @'
/**
 * {{Name}} Test Suite
 * Generated by RawrXD Template Generator
 */

#include <gtest/gtest.h>
#include "{{Name}}.h"

class {{Name}}Test : public ::testing::Test {
protected:
    void SetUp() override {
        // Setup code
    }

    void TearDown() override {
        // Cleanup code
    }
};

TEST_F({{Name}}Test, BasicFunctionality) {
    // Test basic functionality
    EXPECT_TRUE(true);
}

TEST_F({{Name}}Test, EdgeCases) {
    // Test edge cases
    EXPECT_FALSE(false);
}

int main(int argc, char **argv) {
    ::testing::InitGoogleTest(&argc, argv);
    return RUN_ALL_TESTS();
}
'@
                "CMakeLists.txt" = @'
# {{Name}} Test Suite

add_executable({{Name}}_test
    test_{{Name}}.cpp
)

target_link_libraries({{Name}}_test
    gtest
    gtest_main
    rawrxd_core
)

add_test(NAME {{Name}} COMMAND {{Name}}_test)
'@
            }
        }
        
        Config = @{
            Description = "Configuration file"
            Files = @{
                "{{Name}}.json" = @'
{
    "name": "{{Name}}",
    "version": "1.0.0",
    "environment": "development",
    "settings": {
        "debug": true,
        "log_level": "info",
        "max_threads": 4
    },
    "model": {
        "default_model": "llama-7b",
        "context_length": 4096,
        "batch_size": 512
    },
    "server": {
        "host": "0.0.0.0",
        "port": 8080,
        "workers": 2
    }
}
'@
                "{{Name}}.yaml" = @'
name: {{Name}}
version: 1.0.0
environment: development

settings:
  debug: true
  log_level: info
  max_threads: 4

model:
  default_model: llama-7b
  context_length: 4096
  batch_size: 512

server:
  host: 0.0.0.0
  port: 8080
  workers: 2
'@
            }
        }
        
        Script = @{
            Description = "PowerShell automation script"
            Files = @{
                "{{Name}}.ps1" = @'
# RawrXD {{Name}} Script
# {{Description}}

param(
    [Parameter(Mandatory=$false)]
    [string]$Param1 = "default",
    [switch]$Verbose
)

$ErrorActionPreference = "Stop"

function Write-Status {
    param([string]$Message)
    Write-Host "[*] $Message" -ForegroundColor Cyan
}

function Write-Success {
    param([string]$Message)
    Write-Host "[✓] $Message" -ForegroundColor Green
}

function Write-Error {
    param([string]$Message)
    Write-Host "[✗] $Message" -ForegroundColor Red
}

function Main {
    Write-Host "{{Name}} Script" -ForegroundColor Cyan
    Write-Host "===============" -ForegroundColor Cyan
    
    Write-Status "Starting {{Name}}..."
    
    # Your code here
    
    Write-Success "{{Name}} completed"
}

Main
'@
                "README.md" = @'
# {{Name}} Script

## Description

{{Description}}

## Usage

```powershell
.\{{Name}}.ps1 -Param1 "value"
```

## Parameters

- `-Param1`: Description of parameter
- `-Verbose`: Enable verbose output

## Examples

```powershell
# Run with defaults
.\{{Name}}.ps1

# Run with custom parameter
.\{{Name}}.ps1 -Param1 "custom"
```
'@
            }
        }
    }
}

function Show-TemplateList {
    $templates = Get-TemplateDefinitions
    
    Write-Host ""
    Write-Host "Available Templates" -ForegroundColor Cyan
    Write-Host "==================" -ForegroundColor Cyan
    
    foreach ($template in $templates.GetEnumerator()) {
        Write-Host "  $($template.Key)" -ForegroundColor Green
        Write-Host "    $($template.Value.Description)"
    }
}

function Expand-Template {
    param([string]$Content, [hashtable]$Vars)
    
    $result = $Content
    foreach ($key in $Vars.Keys) {
        $result = $result -replace "{{$key}}", $Vars[$key]
    }
    return $result
}

function New-FromTemplate {
    param([string]$Type, [string]$Name, [string]$OutputPath, [hashtable]$Vars)
    
    $templates = Get-TemplateDefinitions
    
    if (-not $templates[$Type]) {
        Write-Error "Unknown template type: $Type"
        return
    }
    
    $template = $templates[$Type]
    
    # Set default variables
    $defaultVars = @{
        Name = $Name
        NameLower = $Name.ToLower()
        Author = $env:USERNAME
        Date = Get-Date -Format "yyyy-MM-dd"
        License = "MIT"
        Description = "Generated by RawrXD Template Generator"
    }
    
    # Merge with user variables
    foreach ($key in $defaultVars.Keys) {
        if (-not $Vars[$key]) {
            $Vars[$key] = $defaultVars[$key]
        }
    }
    
    # Create output directory
    $targetDir = Join-Path $OutputPath $Name
    if (Test-Path $targetDir) {
        if (-not $Force) {
            Write-Error "Directory already exists: $targetDir. Use -Force to overwrite."
            return
        }
        Remove-Item $targetDir -Recurse -Force
    }
    
    New-Item -ItemType Directory -Path $targetDir -Force | Out-Null
    
    Write-Status "Generating $Type template: $Name"
    
    # Generate files
    foreach ($file in $template.Files.GetEnumerator()) {
        $fileName = Expand-Template -Content $file.Key -Vars $Vars
        $fileContent = Expand-Template -Content $file.Value -Vars $Vars
        $filePath = Join-Path $targetDir $fileName
        
        $fileContent | Out-File -FilePath $filePath -Encoding UTF8
        Write-Success "Created: $fileName"
    }
    
    Write-Host ""
    Write-Success "Template generated in: $targetDir"
}

# Main execution
function Main {
    Write-Host "RawrXD Template Generator" -ForegroundColor Cyan
    Write-Host "========================" -ForegroundColor Cyan
    Write-Host ""
    
    if ($TemplateType -eq "List") {
        Show-TemplateList
        return
    }
    
    if (-not $Name) {
        Write-Error "Name is required for template generation"
        return
    }
    
    New-FromTemplate -Type $TemplateType -Name $Name -OutputPath $OutputPath -Vars $Variables
}

Main
