; GGUF_UNIFIED_FINALIZER_CORE.asm - Stub
OPTION CASEMAP:NONE
.code
PUBLIC GGUF_UNIFIED_FINALIZER_CORE_Init
GGUF_UNIFIED_FINALIZER_CORE_Init PROC
    xor eax, eax
    ret
GGUF_UNIFIED_FINALIZER_CORE_Init ENDP
END
