// GET  /api/agents
// RawrNative_RegisterRouteAttachment("/api/agents", RN_HTTP_GET);
// GET  /api/agents/explain
// RawrNative_RegisterRouteAttachment("/api/agents/explain", RN_HTTP_GET);
// GET  /api/agents/explain/stats
// RawrNative_RegisterRouteAttachment("/api/agents/explain/stats", RN_HTTP_GET);
// GET  /api/agents/history
// RawrNative_RegisterRouteAttachment("/api/agents/history", RN_HTTP_GET);
// POST /api/agents/replay
// RawrNative_RegisterRouteAttachment("/api/agents/replay", RN_HTTP_POST);
// GET  /api/agents/status
// RawrNative_RegisterRouteAttachment("/api/agents/status", RN_HTTP_GET);
// GET  /api/backends
// RawrNative_RegisterRouteAttachment("/api/backends", RN_HTTP_GET);
// GET  /api/backends/status
// RawrNative_RegisterRouteAttachment("/api/backends/status", RN_HTTP_GET);
// POST /api/backends/use
// RawrNative_RegisterRouteAttachment("/api/backends/use", RN_HTTP_POST);
// POST /api/chain
// RawrNative_RegisterRouteAttachment("/api/chain", RN_HTTP_POST);
// POST /api/chat
// RawrNative_RegisterRouteAttachment("/api/chat", RN_HTTP_POST);
// POST /api/cli
// RawrNative_RegisterRouteAttachment("/api/cli", RN_HTTP_POST);
// GET  /api/extensions
// RawrNative_RegisterRouteAttachment("/api/extensions", RN_HTTP_GET);
// POST /api/extensions/activate
// RawrNative_RegisterRouteAttachment("/api/extensions/activate", RN_HTTP_POST);
// POST /api/extensions/deactivate
// RawrNative_RegisterRouteAttachment("/api/extensions/deactivate", RN_HTTP_POST);
// POST /api/extensions/disable
// RawrNative_RegisterRouteAttachment("/api/extensions/disable", RN_HTTP_POST);
// POST /api/extensions/enable
// RawrNative_RegisterRouteAttachment("/api/extensions/enable", RN_HTTP_POST);
// GET  /api/extensions/export
// RawrNative_RegisterRouteAttachment("/api/extensions/export", RN_HTTP_GET);
// POST /api/extensions/host/kill
// RawrNative_RegisterRouteAttachment("/api/extensions/host/kill", RN_HTTP_POST);
// GET  /api/extensions/host/logs
// RawrNative_RegisterRouteAttachment("/api/extensions/host/logs", RN_HTTP_GET);
// POST /api/extensions/host/restart
// RawrNative_RegisterRouteAttachment("/api/extensions/host/restart", RN_HTTP_POST);
// GET  /api/extensions/host/status
// RawrNative_RegisterRouteAttachment("/api/extensions/host/status", RN_HTTP_GET);
// POST /api/extensions/import
// RawrNative_RegisterRouteAttachment("/api/extensions/import", RN_HTTP_POST);
// POST /api/extensions/install
// RawrNative_RegisterRouteAttachment("/api/extensions/install", RN_HTTP_POST);
// POST /api/extensions/load-vsix
// RawrNative_RegisterRouteAttachment("/api/extensions/load-vsix", RN_HTTP_POST);
// ANY  /api/extensions/marketplace/*
// RawrNative_RegisterRouteAttachment("/api/extensions/marketplace/*", RN_HTTP_ANY);
// POST /api/extensions/marketplace/search
// RawrNative_RegisterRouteAttachment("/api/extensions/marketplace/search", RN_HTTP_POST);
// POST /api/extensions/scan
// RawrNative_RegisterRouteAttachment("/api/extensions/scan", RN_HTTP_POST);
// POST /api/extensions/uninstall
// RawrNative_RegisterRouteAttachment("/api/extensions/uninstall", RN_HTTP_POST);
// GET  /api/failures
// RawrNative_RegisterRouteAttachment("/api/failures", RN_HTTP_GET);
// POST /api/generate
// RawrNative_RegisterRouteAttachment("/api/generate", RN_HTTP_POST);
// ANY  /api/hotpatch/*
// RawrNative_RegisterRouteAttachment("/api/hotpatch/*", RN_HTTP_ANY);
// POST /api/hotpatch/apply
// RawrNative_RegisterRouteAttachment("/api/hotpatch/apply", RN_HTTP_POST);
// POST /api/hotpatch/revert
// RawrNative_RegisterRouteAttachment("/api/hotpatch/revert", RN_HTTP_POST);
// GET  /api/hotpatch/status
// RawrNative_RegisterRouteAttachment("/api/hotpatch/status", RN_HTTP_GET);
// POST /api/hotpatch/toggle
// RawrNative_RegisterRouteAttachment("/api/hotpatch/toggle", RN_HTTP_POST);
// GET  /api/policies
// RawrNative_RegisterRouteAttachment("/api/policies", RN_HTTP_GET);
// POST /api/policies/apply
// RawrNative_RegisterRouteAttachment("/api/policies/apply", RN_HTTP_POST);
// GET  /api/policies/export
// RawrNative_RegisterRouteAttachment("/api/policies/export", RN_HTTP_GET);
// GET  /api/policies/heuristics
// RawrNative_RegisterRouteAttachment("/api/policies/heuristics", RN_HTTP_GET);
// POST /api/policies/import
// RawrNative_RegisterRouteAttachment("/api/policies/import", RN_HTTP_POST);
// POST /api/policies/reject
// RawrNative_RegisterRouteAttachment("/api/policies/reject", RN_HTTP_POST);
// GET  /api/policies/stats
// RawrNative_RegisterRouteAttachment("/api/policies/stats", RN_HTTP_GET);
// GET  /api/policies/suggestions
// RawrNative_RegisterRouteAttachment("/api/policies/suggestions", RN_HTTP_GET);
// POST /api/read-file
// RawrNative_RegisterRouteAttachment("/api/read-file", RN_HTTP_POST);
// GET  /api/status
// RawrNative_RegisterRouteAttachment("/api/status", RN_HTTP_GET);
// POST /api/subagent
// RawrNative_RegisterRouteAttachment("/api/subagent", RN_HTTP_POST);
// POST /api/swarm
// RawrNative_RegisterRouteAttachment("/api/swarm", RN_HTTP_POST);
// GET  /api/tags
// RawrNative_RegisterRouteAttachment("/api/tags", RN_HTTP_GET);
// POST /api/tool
// RawrNative_RegisterRouteAttachment("/api/tool", RN_HTTP_POST);
// POST /ask
// RawrNative_RegisterRouteAttachment("/ask", RN_HTTP_POST);
// POST /complete
// RawrNative_RegisterRouteAttachment("/complete", RN_HTTP_POST);
// POST /complete/stream
// RawrNative_RegisterRouteAttachment("/complete/stream", RN_HTTP_POST);
// GET  /gui
// RawrNative_RegisterRouteAttachment("/gui", RN_HTTP_GET);
// GET  /health
// RawrNative_RegisterRouteAttachment("/health", RN_HTTP_GET);
// GET  /metrics
// RawrNative_RegisterRouteAttachment("/metrics", RN_HTTP_GET);
// GET  /models
// RawrNative_RegisterRouteAttachment("/models", RN_HTTP_GET);
// GET  /status
// RawrNative_RegisterRouteAttachment("/status", RN_HTTP_GET);
// POST /v1/chat/completions
// RawrNative_RegisterRouteAttachment("/v1/chat/completions", RN_HTTP_POST);
// GET  /v1/models
// RawrNative_RegisterRouteAttachment("/v1/models", RN_HTTP_GET);
