; RAWRXD_DEEP2_GGUF_EXECIMAGE_PROBE_001
; Pure x64 MASM / Win64, no CRT, no third-party runtime.
; Purpose: selected GGUF -> parse -> causal/non-time stamps -> verify -> classify ->
;          generated model/non-model headers -> relocation-safe RXI manifest.
;
; Runtime dependencies: Windows kernel32 only. Build dependencies: ml64 + link.

include deep2_defs.inc

EXTERN GetCommandLineW:PROC
EXTERN GetStdHandle:PROC
EXTERN WriteFile:PROC
EXTERN CreateFileW:PROC
EXTERN GetFileSizeEx:PROC
EXTERN CreateFileMappingW:PROC
EXTERN MapViewOfFile:PROC
EXTERN UnmapViewOfFile:PROC
EXTERN CloseHandle:PROC
EXTERN ExitProcess:PROC

includelib kernel32.lib

.data
align 16
msg_usage db "usage: deep2_gguf_probe.exe <model.gguf>",13,10,0
msg_open_fail db "MODEL_FILE_OPEN=FAIL",13,10,0
msg_map_fail db "MODEL_FILE_MAP=FAIL",13,10,0
msg_bad_gguf db "GGUF_PARSE=FAIL",13,10,0
msg_ok db "RAWRXD_DEEP2_GGUF_EXECIMAGE_PROBE_001=PASS",13,10,0
msg_outputs db "OUTPUTS=deep2_model_identity.inc,deep2_model_tensors.inc,deep2_model_quant.inc,deep2_system_used.inc,deep2_stamp_schema.inc,deep2_execution_image.rxi,deep2_probe.trace",13,10,0

key_arch db "general.architecture"
KEY_ARCH_LEN equ ($-key_arch)
key_align db "general.alignment"
KEY_ALIGN_LEN equ ($-key_align)

w_model_header dw 'd','e','e','p','2','_','m','o','d','e','l','_','i','d','e','n','t','i','t','y','.','i','n','c',0
w_tensor_header dw 'd','e','e','p','2','_','m','o','d','e','l','_','t','e','n','s','o','r','s','.','i','n','c',0
w_quant_header dw 'd','e','e','p','2','_','m','o','d','e','l','_','q','u','a','n','t','.','i','n','c',0
w_system_header dw 'd','e','e','p','2','_','s','y','s','t','e','m','_','u','s','e','d','.','i','n','c',0
w_stamp_header dw 'd','e','e','p','2','_','s','t','a','m','p','_','s','c','h','e','m','a','.','i','n','c',0
w_rxi dw 'd','e','e','p','2','_','e','x','e','c','u','t','i','o','n','_','i','m','a','g','e','.','r','x','i',0
w_trace dw 'd','e','e','p','2','_','p','r','o','b','e','.','t','r','a','c','e',0

hdr_banner db "; AUTO-GENERATED BY RAWRXD_DEEP2_GGUF_EXECIMAGE_PROBE_001 -- DO NOT EDIT",13,10,0
s_equ db " equ ",0
s_crlf db 13,10,0
s_hexprefix db "0",0

s_id_ver db "DEEP2_MODEL_GGUF_VERSION",0
s_id_file db "DEEP2_MODEL_FILE_BYTES",0
s_id_tc db "DEEP2_MODEL_TENSOR_COUNT",0
s_id_mc db "DEEP2_MODEL_METADATA_COUNT",0
s_id_align db "DEEP2_MODEL_ALIGNMENT",0
s_id_data db "DEEP2_MODEL_TENSOR_DATA_START",0
s_id_arch db "DEEP2_MODEL_ARCH_HASH",0
s_id_qlo db "DEEP2_MODEL_QUANT_MASK_LO",0
s_id_qhi db "DEEP2_MODEL_QUANT_MASK_HI",0

s_tensor_prefix db "DEEP2_TENSOR_",0
s_namehash db "_NAME_HASH",0
s_type db "_TYPE",0
s_ndims db "_NDIMS",0
s_dim0 db "_DIM0",0
s_dim1 db "_DIM1",0
s_dim2 db "_DIM2",0
s_dim3 db "_DIM3",0
s_rel db "_REL_OFFSET",0
s_abs db "_ABS_OFFSET",0
s_span db "_STORAGE_SPAN",0

s_qmasklo db "DEEP2_QUANT_MASK_LO",0
s_qmaskhi db "DEEP2_QUANT_MASK_HI",0

s_sys_fileio db "DEEP2_USE_FILE_IO",0
s_sys_map db "DEEP2_USE_FILE_MAPPING",0
s_sys_out db "DEEP2_USE_OUTPUT_FILES",0
s_sys_static db "DEEP2_USE_STATIC_ARENAS",0
s_sys_net db "DEEP2_USE_NETWORK",0
s_sys_heap db "DEEP2_USE_HEAP",0
s_sys_crt db "DEEP2_USE_CRT",0
s_sys_gpu db "DEEP2_USE_GPU",0

s_stamp_rec db "DEEP2_TRACE_REC_BYTES",0
s_tensor_rec db "DEEP2_TENSOR_REC_BYTES",0
s_stamp_not_time db "; Stamp identity is causal/sequence/generation based; no wall-clock field is stored.",13,10,0

.data?
align 64
path_buf dw 32768 dup(?)
arch_buf db 128 dup(?)
arch_len dq ?

file_handle dq ?
map_handle dq ?
map_base dq ?
map_end dq ?
file_size dq ?
cursor dq ?

gguf_version dd ?
tensor_count dq ?
metadata_count dq ?
gguf_alignment dq ?
tensor_data_start dq ?
quant_mask_lo dq ?
quant_mask_hi dq ?
arch_hash dq ?
sys_use_mask dq ?

trace_seq dq ?
trace_count dq ?
trace_records TRACE_REC MAX_TRACE dup(<?>)

tensor_records TENSOR_REC MAX_TENSORS dup(<?>)

rxi_header RXI_HEADER <>

out_handle dq ?
write_count dd ?
linebuf db 4096 dup(?)
hexbuf db 32 dup(?)
decbuf db 32 dup(?)

.code

; ---------------- stdout ----------------
stdout_z PROC
    ; rcx = ASCIIZ
    push rbx
    sub rsp, 40
    mov rbx, rcx
    xor r8d, r8d
@@len:
    cmp byte ptr [rbx+r8], 0
    je @@have
    inc r8
    jmp @@len
@@have:
    mov ecx, STD_OUTPUT_HANDLE
    call GetStdHandle
    mov rcx, rax
    mov rdx, rbx
    lea r9, write_count
    mov qword ptr [rsp+32], 0
    call WriteFile
    add rsp, 40
    pop rbx
    ret
stdout_z ENDP

; ---------------- command line: copy argv[1] to path_buf ----------------
parse_model_arg PROC
    push rsi
    push rdi
    sub rsp, 40
    call GetCommandLineW
    mov rsi, rax
    lea rdi, path_buf
    ; skip leading spaces
@@s0:
    mov ax, [rsi]
    cmp ax, ' '
    jne @@exe
    add rsi,2
    jmp @@s0
@@exe:
    cmp word ptr [rsi], '"'
    jne @@exe_plain
    add rsi,2
@@qskip:
    mov ax,[rsi]
    test ax,ax
    jz @@fail
    add rsi,2
    cmp ax,'"'
    jne @@qskip
    jmp @@after_exe
@@exe_plain:
@@pskip:
    mov ax,[rsi]
    test ax,ax
    jz @@fail
    cmp ax,' '
    je @@after_exe
    add rsi,2
    jmp @@pskip
@@after_exe:
@@sp:
    mov ax,[rsi]
    cmp ax,' '
    jne @@arg
    add rsi,2
    jmp @@sp
@@arg:
    test ax,ax
    jz @@fail
    cmp ax,'"'
    jne @@copy_plain
    add rsi,2
@@copy_q:
    mov ax,[rsi]
    test ax,ax
    jz @@done
    cmp ax,'"'
    je @@done
    mov [rdi],ax
    add rsi,2
    add rdi,2
    jmp @@copy_q
@@copy_plain:
    mov ax,[rsi]
    test ax,ax
    jz @@done
    cmp ax,' '
    je @@done
    mov [rdi],ax
    add rsi,2
    add rdi,2
    jmp @@copy_plain
@@done:
    mov word ptr [rdi],0
    mov eax,1
    add rsp,40
    pop rdi
    pop rsi
    ret
@@fail:
    xor eax,eax
    add rsp,40
    pop rdi
    pop rsi
    ret
parse_model_arg ENDP

; ---------------- bounds-safe readers ----------------
need_bytes PROC
    ; rcx=count; eax=1 if cursor+count <= end
    mov rax,cursor
    mov rdx,rax
    add rdx,rcx
    jc @@bad
    cmp rdx,map_end
    ja @@bad
    mov eax,1
    ret
@@bad:
    xor eax,eax
    ret
need_bytes ENDP

read_u32 PROC
    mov ecx,4
    call need_bytes
    test eax,eax
    jz @@bad
    mov rdx,cursor
    mov eax,dword ptr [rdx]
    add rdx,4
    mov cursor,rdx
    ret
@@bad:
    mov rax,-1
    ret
read_u32 ENDP

read_u64 PROC
    mov ecx,8
    call need_bytes
    test eax,eax
    jz @@bad
    mov rdx,cursor
    mov rax,qword ptr [rdx]
    add rdx,8
    mov cursor,rdx
    ret
@@bad:
    mov rax,-1
    ret
read_u64 ENDP

; returns rax=ptr, rdx=len; CF=1 on failure
read_gguf_string PROC
    call read_u64
    cmp rax,-1
    je @@bad
    mov r8,rax
    mov rcx,r8
    call need_bytes
    test eax,eax
    jz @@bad
    mov rax,cursor
    mov rdx,r8
    add cursor,r8
    clc
    ret
@@bad:
    stc
    ret
read_gguf_string ENDP

; FNV-1a64: rcx=ptr rdx=len => rax
hash64 PROC
    mov rax,1469598103934665603
    mov r8,1099511628211
    xor r9,r9
@@h:
    cmp r9,rdx
    jae @@done
    movzx r10d,byte ptr [rcx+r9]
    xor rax,r10
    imul rax,r8
    inc r9
    jmp @@h
@@done:
    ret
hash64 ENDP

; rcx=p1 rdx=len1 r8=p2 r9=len2; eax bool
bytes_eq PROC
    cmp rdx,r9
    jne @@no
    xor r10,r10
@@loop:
    cmp r10,rdx
    jae @@yes
    mov al,[rcx+r10]
    cmp al,[r8+r10]
    jne @@no
    inc r10
    jmp @@loop
@@yes:
    mov eax,1
    ret
@@no:
    xor eax,eax
    ret
bytes_eq ENDP

; ---------------- causal trace; no time ----------------
; rcx=kind edx=op r8=obj r9=A, stack +40=B +48=flags +56=class +64=parent
trace_emit PROC
    mov rax,trace_count
    cmp rax,MAX_TRACE
    jae @@ret
    imul r10,rax,SIZEOF TRACE_REC
    lea r11,trace_records
    add r11,r10
    inc trace_seq
    mov rax,trace_seq
    mov [r11].TRACE_REC.Seq,rax
    mov rax,qword ptr [rsp+64]
    mov [r11].TRACE_REC.ParentSeq,rax
    mov [r11].TRACE_REC.Kind,ecx
    mov [r11].TRACE_REC.Op,edx
    mov [r11].TRACE_REC.ObjectId,r8
    mov qword ptr [r11].TRACE_REC.InputGen,0
    mov qword ptr [r11].TRACE_REC.OutputGen,0
    mov [r11].TRACE_REC.A,r9
    mov rax,qword ptr [rsp+40]
    mov [r11].TRACE_REC.B,rax
    mov eax,dword ptr [rsp+48]
    mov [r11].TRACE_REC.Flags,eax
    mov eax,dword ptr [rsp+56]
    mov [r11].TRACE_REC.ClassId,eax
    inc trace_count
@@ret:
    ret
trace_emit ENDP

; ---------------- skip GGUF metadata value ----------------
; ecx=type. eax=1 success
skip_value PROC
    push rbx
    push rsi
    push rdi
    sub rsp,32
    mov ebx,ecx
    cmp ebx,GGUF_TYPE_UINT8
    je @@b1
    cmp ebx,GGUF_TYPE_INT8
    je @@b1
    cmp ebx,GGUF_TYPE_BOOL
    je @@b1
    cmp ebx,GGUF_TYPE_UINT16
    je @@b2
    cmp ebx,GGUF_TYPE_INT16
    je @@b2
    cmp ebx,GGUF_TYPE_UINT32
    je @@b4
    cmp ebx,GGUF_TYPE_INT32
    je @@b4
    cmp ebx,GGUF_TYPE_FLOAT32
    je @@b4
    cmp ebx,GGUF_TYPE_UINT64
    je @@b8
    cmp ebx,GGUF_TYPE_INT64
    je @@b8
    cmp ebx,GGUF_TYPE_FLOAT64
    je @@b8
    cmp ebx,GGUF_TYPE_STRING
    je @@str
    cmp ebx,GGUF_TYPE_ARRAY
    je @@arr
    xor eax,eax
    jmp @@out
@@b1:
    mov ecx,1
    call need_bytes
    test eax,eax
    jz @@out
    add cursor,1
    mov eax,1
    jmp @@out
@@b2:
    mov ecx,2
    call need_bytes
    test eax,eax
    jz @@out
    add cursor,2
    mov eax,1
    jmp @@out
@@b4:
    mov ecx,4
    call need_bytes
    test eax,eax
    jz @@out
    add cursor,4
    mov eax,1
    jmp @@out
@@b8:
    mov ecx,8
    call need_bytes
    test eax,eax
    jz @@out
    add cursor,8
    mov eax,1
    jmp @@out
@@str:
    call read_gguf_string
    jc @@fail
    mov eax,1
    jmp @@out
@@arr:
    call read_u32
    cmp rax,-1
    je @@fail
    mov ebx,eax                    ; element type
    call read_u64
    cmp rax,-1
    je @@fail
    mov rdi,rax                    ; count
    xor rsi,rsi
@@aloop:
    cmp rsi,rdi
    jae @@aok
    mov ecx,ebx
    call skip_value
    test eax,eax
    jz @@fail
    inc rsi
    jmp @@aloop
@@aok:
    mov eax,1
    jmp @@out
@@fail:
    xor eax,eax
@@out:
    add rsp,32
    pop rdi
    pop rsi
    pop rbx
    ret
skip_value ENDP

; ---------------- parse metadata ----------------
parse_metadata PROC
    push rbx
    push rsi
    push rdi
    sub rsp,64
    xor rbx,rbx
@@loop:
    cmp rbx,metadata_count
    jae @@ok
    call read_gguf_string
    jc @@fail
    mov rsi,rax                    ; key ptr
    mov rdi,rdx                    ; key len
    mov rcx,rsi
    mov rdx,rdi
    call hash64
    mov qword ptr [rsp+32],rax     ; key hash

    mov ecx,TRACE_KIND_OBSERVE
    mov edx,OP_METADATA_KEY
    mov r8,rax
    mov r9,rbx
    mov qword ptr [rsp+32],rdi
    mov dword ptr [rsp+40],0
    mov dword ptr [rsp+48],CLASS_DECLARED
    mov qword ptr [rsp+56],0
    call trace_emit

    call read_u32
    cmp rax,-1
    je @@fail
    mov dword ptr [rsp+36],eax     ; type

    ; general.architecture
    mov rcx,rsi
    mov rdx,rdi
    lea r8,key_arch
    mov r9d,KEY_ARCH_LEN
    call bytes_eq
    test eax,eax
    jz @@check_align
    cmp dword ptr [rsp+36],GGUF_TYPE_STRING
    jne @@generic
    call read_gguf_string
    jc @@fail
    mov rcx,rax
    ; hash architecture string
    call hash64
    mov arch_hash,rax
    ; The RXI retains a stable architecture-string hash rather than a process pointer.
    jmp @@next

@@check_align:
    mov rcx,rsi
    mov rdx,rdi
    lea r8,key_align
    mov r9d,KEY_ALIGN_LEN
    call bytes_eq
    test eax,eax
    jz @@generic
    mov eax,dword ptr [rsp+36]
    cmp eax,GGUF_TYPE_UINT32
    jne @@align64
    call read_u32
    cmp rax,-1
    je @@fail
    mov gguf_alignment,rax
    jmp @@next
@@align64:
    cmp eax,GGUF_TYPE_UINT64
    jne @@generic
    call read_u64
    cmp rax,-1
    je @@fail
    mov gguf_alignment,rax
    jmp @@next

@@generic:
    mov ecx,dword ptr [rsp+36]
    call skip_value
    test eax,eax
    jz @@fail
@@next:
    inc rbx
    jmp @@loop
@@ok:
    mov eax,1
    jmp @@out
@@fail:
    xor eax,eax
@@out:
    add rsp,64
    pop rdi
    pop rsi
    pop rbx
    ret
parse_metadata ENDP

; ---------------- parse tensor infos ----------------
parse_tensors PROC
    push rbx
    push rsi
    push rdi
    sub rsp,64
    mov rax,tensor_count
    cmp rax,MAX_TENSORS
    ja @@fail
    xor rbx,rbx
@@loop:
    cmp rbx,tensor_count
    jae @@finish
    call read_gguf_string
    jc @@fail
    mov rsi,rax
    mov rdi,rdx
    mov rcx,rsi
    call hash64
    mov qword ptr [rsp+32],rax     ; name hash

    mov ecx,4
    call need_bytes
    test eax,eax
    jz @@fail
    call read_u32
    cmp rax,-1
    je @@fail
    mov dword ptr [rsp+40],eax     ; ndims
    cmp eax,32
    ja @@fail

    mov rax,rbx
    imul rax,SIZEOF TENSOR_REC
    lea r10,tensor_records
    add r10,rax
    mov rax,qword ptr [rsp+32]
    mov [r10].TENSOR_REC.NameHash,rax
    mov eax,dword ptr [rsp+40]
    mov [r10].TENSOR_REC.NDims,eax
    mov qword ptr [r10].TENSOR_REC.Dim0,1
    mov qword ptr [r10].TENSOR_REC.Dim1,1
    mov qword ptr [r10].TENSOR_REC.Dim2,1
    mov qword ptr [r10].TENSOR_REC.Dim3,1

    xor r11d,r11d
@@dims:
    cmp r11d,dword ptr [rsp+40]
    jae @@dtype
    call read_u64
    cmp rax,-1
    je @@fail
    cmp r11d,0
    jne @F
    mov [r10].TENSOR_REC.Dim0,rax
@@: cmp r11d,1
    jne @F
    mov [r10].TENSOR_REC.Dim1,rax
@@: cmp r11d,2
    jne @F
    mov [r10].TENSOR_REC.Dim2,rax
@@: cmp r11d,3
    jne @F
    mov [r10].TENSOR_REC.Dim3,rax
@@:
    inc r11d
    jmp @@dims
@@dtype:
    call read_u32
    cmp rax,-1
    je @@fail
    mov [r10].TENSOR_REC.TypeId,eax
    mov r11d,eax
    cmp r11d,64
    jae @@qhi
    mov rax,1
    mov cl,r11b
    shl rax,cl
    or quant_mask_lo,rax
    jmp @@offset
@@qhi:
    cmp r11d,128
    jae @@offset
    sub r11d,64
    mov rax,1
    mov cl,r11b
    shl rax,cl
    or quant_mask_hi,rax
@@offset:
    call read_u64
    cmp rax,-1
    je @@fail
    mov [r10].TENSOR_REC.RelativeOffset,rax

    mov ecx,TRACE_KIND_OBSERVE
    mov edx,OP_TENSOR_INFO
    mov r8,rbx
    mov r9,qword ptr [rsp+32]
    mov qword ptr [rsp+32],rax
    mov dword ptr [rsp+40],0
    mov dword ptr [rsp+48],CLASS_DECLARED
    mov qword ptr [rsp+56],0
    call trace_emit

    inc rbx
    jmp @@loop
@@finish:
    ; tensor data begins at aligned end of tensor table
    mov rax,cursor
    sub rax,map_base
    mov rcx,gguf_alignment
    test rcx,rcx
    jnz @F
    mov rcx,DEFAULT_GGUF_ALIGNMENT
    mov gguf_alignment,rcx
@@:
    dec rcx
    add rax,rcx
    not rcx
    and rax,rcx
    mov tensor_data_start,rax

    ; absolute offsets
    xor rbx,rbx
@@absloop:
    cmp rbx,tensor_count
    jae @@spans
    mov rax,rbx
    imul rax,SIZEOF TENSOR_REC
    lea r10,tensor_records
    add r10,rax
    mov rax,[r10].TENSOR_REC.RelativeOffset
    add rax,tensor_data_start
    mov [r10].TENSOR_REC.AbsoluteOffset,rax
    cmp rax,file_size
    jae @@fail
    inc rbx
    jmp @@absloop

@@spans:
    ; storage span = next greater tensor absolute offset - current, or EOF-current.
    xor rbx,rbx
@@outer:
    cmp rbx,tensor_count
    jae @@ok
    mov rax,rbx
    imul rax,SIZEOF TENSOR_REC
    lea r10,tensor_records
    add r10,rax
    mov rsi,[r10].TENSOR_REC.AbsoluteOffset
    mov rdi,file_size
    xor r11,r11
@@inner:
    cmp r11,tensor_count
    jae @@span_done
    mov rax,r11
    imul rax,SIZEOF TENSOR_REC
    lea rdx,tensor_records
    add rdx,rax
    mov rax,[rdx].TENSOR_REC.AbsoluteOffset
    cmp rax,rsi
    jbe @@inext
    cmp rax,rdi
    jae @@inext
    mov rdi,rax
@@inext:
    inc r11
    jmp @@inner
@@span_done:
    mov rax,rdi
    sub rax,rsi
    mov [r10].TENSOR_REC.StorageSpan,rax
    inc rbx
    jmp @@outer
@@ok:
    mov eax,1
    jmp @@out
@@fail:
    xor eax,eax
@@out:
    add rsp,64
    pop rdi
    pop rsi
    pop rbx
    ret
parse_tensors ENDP

; ---------------- ASCII file helpers ----------------
open_output PROC
    ; rcx = wide filename
    sub rsp,56
    mov rdx,GENERIC_WRITE
    xor r8d,r8d
    xor r9d,r9d
    mov qword ptr [rsp+32],CREATE_ALWAYS
    mov qword ptr [rsp+40],FILE_ATTRIBUTE_NORMAL
    mov qword ptr [rsp+48],0
    call CreateFileW
    mov out_handle,rax
    add rsp,56
    ret
open_output ENDP

out_z PROC
    ; rcx = z string
    push rbx
    sub rsp,40
    mov rbx,rcx
    xor r8d,r8d
@@l:
    cmp byte ptr [rbx+r8],0
    je @@w
    inc r8
    jmp @@l
@@w:
    mov rcx,out_handle
    mov rdx,rbx
    lea r9,write_count
    mov qword ptr [rsp+32],0
    call WriteFile
    add rsp,40
    pop rbx
    ret
out_z ENDP

u64_to_dec PROC
    ; rcx=value => rax=ptr ASCIIZ in decbuf
    push rdi
    lea rdi,decbuf+31
    mov byte ptr [rdi],0
    mov rax,rcx
    mov r8,10
    test rax,rax
    jnz @@loop
    dec rdi
    mov byte ptr [rdi],'0'
    mov rax,rdi
    pop rdi
    ret
@@loop:
    xor rdx,rdx
    div r8
    add dl,'0'
    dec rdi
    mov [rdi],dl
    test rax,rax
    jnz @@loop
    mov rax,rdi
    pop rdi
    ret
u64_to_dec ENDP

u64_to_hex PROC
    ; rcx=value => 16 hex digits + h
    push rdi
    lea rdi,hexbuf
    mov rax,rcx
    mov r8d,16
@@loop:
    rol rax,4
    mov dl,al
    and dl,0Fh
    cmp dl,9
    jbe @F
    add dl,7
@@: add dl,'0'
    mov [rdi],dl
    inc rdi
    dec r8d
    jnz @@loop
    mov byte ptr [rdi],'h'
    inc rdi
    mov byte ptr [rdi],0
    lea rax,hexbuf
    pop rdi
    ret
u64_to_hex ENDP

emit_equ_dec PROC
    ; rcx=name, rdx=value
    push rdx
    call out_z
    lea rcx,s_equ
    call out_z
    pop rcx
    call u64_to_dec
    mov rcx,rax
    call out_z
    lea rcx,s_crlf
    call out_z
    ret
emit_equ_dec ENDP

emit_equ_hex PROC
    ; rcx=name, rdx=value
    push rdx
    call out_z
    lea rcx,s_equ
    call out_z
    pop rcx
    call u64_to_hex
    mov rcx,rax
    call out_z
    lea rcx,s_crlf
    call out_z
    ret
emit_equ_hex ENDP

emit_model_header PROC
    sub rsp,40
    lea rcx,w_model_header
    call open_output
    cmp rax,INVALID_HANDLE_VALUE
    je @@out
    lea rcx,hdr_banner
    call out_z
    lea rcx,s_id_ver
    mov edx,gguf_version
    call emit_equ_dec
    lea rcx,s_id_file
    mov rdx,file_size
    call emit_equ_dec
    lea rcx,s_id_tc
    mov rdx,tensor_count
    call emit_equ_dec
    lea rcx,s_id_mc
    mov rdx,metadata_count
    call emit_equ_dec
    lea rcx,s_id_align
    mov rdx,gguf_alignment
    call emit_equ_dec
    lea rcx,s_id_data
    mov rdx,tensor_data_start
    call emit_equ_dec
    lea rcx,s_id_arch
    mov rdx,arch_hash
    call emit_equ_hex
    lea rcx,s_id_qlo
    mov rdx,quant_mask_lo
    call emit_equ_hex
    lea rcx,s_id_qhi
    mov rdx,quant_mask_hi
    call emit_equ_hex
    mov rcx,out_handle
    call CloseHandle
@@out:
    add rsp,40
    ret
emit_model_header ENDP

emit_tensor_line PROC
    ; rbx=tensor index, rsi=rec, rdi=suffix, rdx=value, r8d=hex?  build symbolic name into linebuf
    push rax
    push rcx
    push r9
    push r10
    lea r9,linebuf
    lea r10,s_tensor_prefix
@@p:
    mov al,[r10]
    test al,al
    jz @@id
    mov [r9],al
    inc r9
    inc r10
    jmp @@p
@@id:
    ; four hex digits of low 16-bit tensor index
    mov eax,ebx
    mov ecx,4
@@hx:
    rol ax,4
    mov r10b,al
    and r10b,0Fh
    cmp r10b,9
    jbe @F
    add r10b,7
@@: add r10b,'0'
    mov [r9],r10b
    inc r9
    dec ecx
    jnz @@hx
    mov r10,rdi
@@suf:
    mov al,[r10]
    test al,al
    jz @@done
    mov [r9],al
    inc r9
    inc r10
    jmp @@suf
@@done:
    mov byte ptr [r9],0
    lea rcx,linebuf
    test r8d,r8d
    jz @@dec
    call emit_equ_hex
    jmp @@ret
@@dec:
    call emit_equ_dec
@@ret:
    pop r10
    pop r9
    pop rcx
    pop rax
    ret
emit_tensor_line ENDP

emit_tensor_header PROC
    push rbx
    push rsi
    push rdi
    sub rsp,32
    lea rcx,w_tensor_header
    call open_output
    cmp rax,INVALID_HANDLE_VALUE
    je @@out
    lea rcx,hdr_banner
    call out_z
    xor rbx,rbx
@@loop:
    cmp rbx,tensor_count
    jae @@close
    mov rax,rbx
    imul rax,SIZEOF TENSOR_REC
    lea rsi,tensor_records
    add rsi,rax

    lea rdi,s_namehash
    mov rdx,[rsi].TENSOR_REC.NameHash
    mov r8d,1
    call emit_tensor_line
    lea rdi,s_type
    mov edx,[rsi].TENSOR_REC.TypeId
    xor r8d,r8d
    call emit_tensor_line
    lea rdi,s_ndims
    mov edx,[rsi].TENSOR_REC.NDims
    xor r8d,r8d
    call emit_tensor_line
    lea rdi,s_dim0
    mov rdx,[rsi].TENSOR_REC.Dim0
    xor r8d,r8d
    call emit_tensor_line
    lea rdi,s_dim1
    mov rdx,[rsi].TENSOR_REC.Dim1
    xor r8d,r8d
    call emit_tensor_line
    lea rdi,s_dim2
    mov rdx,[rsi].TENSOR_REC.Dim2
    xor r8d,r8d
    call emit_tensor_line
    lea rdi,s_dim3
    mov rdx,[rsi].TENSOR_REC.Dim3
    xor r8d,r8d
    call emit_tensor_line
    lea rdi,s_rel
    mov rdx,[rsi].TENSOR_REC.RelativeOffset
    mov r8d,1
    call emit_tensor_line
    lea rdi,s_abs
    mov rdx,[rsi].TENSOR_REC.AbsoluteOffset
    mov r8d,1
    call emit_tensor_line
    lea rdi,s_span
    mov rdx,[rsi].TENSOR_REC.StorageSpan
    mov r8d,1
    call emit_tensor_line

    inc rbx
    jmp @@loop
@@close:
    mov rcx,out_handle
    call CloseHandle
@@out:
    add rsp,32
    pop rdi
    pop rsi
    pop rbx
    ret
emit_tensor_header ENDP

emit_quant_header PROC
    sub rsp,40
    lea rcx,w_quant_header
    call open_output
    cmp rax,INVALID_HANDLE_VALUE
    je @@out
    lea rcx,hdr_banner
    call out_z
    lea rcx,s_qmasklo
    mov rdx,quant_mask_lo
    call emit_equ_hex
    lea rcx,s_qmaskhi
    mov rdx,quant_mask_hi
    call emit_equ_hex
    mov rcx,out_handle
    call CloseHandle
@@out:
    add rsp,40
    ret
emit_quant_header ENDP

emit_system_header PROC
    sub rsp,40
    lea rcx,w_system_header
    call open_output
    cmp rax,INVALID_HANDLE_VALUE
    je @@out
    lea rcx,hdr_banner
    call out_z
    lea rcx,s_sys_fileio
    mov edx,1
    call emit_equ_dec
    lea rcx,s_sys_map
    mov edx,1
    call emit_equ_dec
    lea rcx,s_sys_out
    mov edx,1
    call emit_equ_dec
    lea rcx,s_sys_static
    mov edx,1
    call emit_equ_dec
    lea rcx,s_sys_net
    xor edx,edx
    call emit_equ_dec
    lea rcx,s_sys_heap
    xor edx,edx
    call emit_equ_dec
    lea rcx,s_sys_crt
    xor edx,edx
    call emit_equ_dec
    lea rcx,s_sys_gpu
    xor edx,edx
    call emit_equ_dec
    mov rcx,out_handle
    call CloseHandle
@@out:
    add rsp,40
    ret
emit_system_header ENDP

emit_stamp_header PROC
    sub rsp,40
    lea rcx,w_stamp_header
    call open_output
    cmp rax,INVALID_HANDLE_VALUE
    je @@out
    lea rcx,hdr_banner
    call out_z
    lea rcx,s_stamp_not_time
    call out_z
    lea rcx,s_stamp_rec
    mov edx,SIZEOF TRACE_REC
    call emit_equ_dec
    lea rcx,s_tensor_rec
    mov edx,SIZEOF TENSOR_REC
    call emit_equ_dec
    mov rcx,out_handle
    call CloseHandle
@@out:
    add rsp,40
    ret
emit_stamp_header ENDP

emit_binary PROC
    ; rcx=wide filename, rdx=ptr, r8=bytes
    push rbx
    push rsi
    sub rsp,56
    mov rbx,rdx
    mov rsi,r8
    call open_output
    cmp rax,INVALID_HANDLE_VALUE
    je @@out
    mov rcx,out_handle
    mov rdx,rbx
    mov r8,rsi
    lea r9,write_count
    mov qword ptr [rsp+32],0
    call WriteFile
    mov rcx,out_handle
    call CloseHandle
@@out:
    add rsp,56
    pop rsi
    pop rbx
    ret
emit_binary ENDP

emit_rxi PROC
    sub rsp,40
    mov dword ptr rxi_header.Magic,31495852h ; "RXI1"
    mov dword ptr rxi_header.Version,1
    mov eax,gguf_version
    mov rxi_header.GGUFVersion,eax
    mov dword ptr rxi_header.Flags,0
    mov rax,file_size
    mov rxi_header.ModelFileBytes,rax
    mov rax,tensor_count
    mov rxi_header.TensorCount,rax
    mov rax,metadata_count
    mov rxi_header.MetadataCount,rax
    mov rax,gguf_alignment
    mov rxi_header.Alignment,rax
    mov rax,tensor_data_start
    mov rxi_header.TensorDataStart,rax
    mov rax,quant_mask_lo
    mov rxi_header.QuantMaskLo,rax
    mov rax,quant_mask_hi
    mov rxi_header.QuantMaskHi,rax
    mov rax,arch_hash
    mov rxi_header.ArchHash,rax
    mov dword ptr rxi_header.TensorRecBytes,SIZEOF TENSOR_REC
    mov dword ptr rxi_header.TraceRecBytes,SIZEOF TRACE_REC

    lea rcx,w_rxi
    call open_output
    cmp rax,INVALID_HANDLE_VALUE
    je @@out
    mov rcx,out_handle
    lea rdx,rxi_header
    mov r8d,SIZEOF RXI_HEADER
    lea r9,write_count
    mov qword ptr [rsp+32],0
    call WriteFile
    mov rcx,out_handle
    lea rdx,tensor_records
    mov rax,tensor_count
    imul rax,SIZEOF TENSOR_REC
    mov r8,rax
    lea r9,write_count
    mov qword ptr [rsp+32],0
    call WriteFile
    mov rcx,out_handle
    call CloseHandle
@@out:
    add rsp,40
    ret
emit_rxi ENDP

emit_trace PROC
    sub rsp,40
    lea rcx,w_trace
    lea rdx,trace_records
    mov rax,trace_count
    imul rax,SIZEOF TRACE_REC
    mov r8,rax
    call emit_binary
    add rsp,40
    ret
emit_trace ENDP

; ---------------- main ----------------
start PROC
    sub rsp,72
    mov gguf_alignment,DEFAULT_GGUF_ALIGNMENT
    mov sys_use_mask,SYS_USE_FILE_IO or SYS_USE_FILE_MAPPING or SYS_USE_OUTPUT_FILES or SYS_USE_STATIC_ARENAS

    call parse_model_arg
    test eax,eax
    jnz @@open
    lea rcx,msg_usage
    call stdout_z
    mov ecx,2
    call ExitProcess

@@open:
    lea rcx,path_buf
    mov rdx,GENERIC_READ
    mov r8d,FILE_SHARE_READ
    xor r9d,r9d
    mov qword ptr [rsp+32],OPEN_EXISTING
    mov qword ptr [rsp+40],FILE_ATTRIBUTE_NORMAL
    mov qword ptr [rsp+48],0
    call CreateFileW
    cmp rax,INVALID_HANDLE_VALUE
    jne @F
    lea rcx,msg_open_fail
    call stdout_z
    mov ecx,3
    call ExitProcess
@@:
    mov file_handle,rax

    mov rcx,TRACE_KIND_OBSERVE
    mov edx,OP_FILE_OPEN
    xor r8,r8
    xor r9,r9
    mov qword ptr [rsp+32],0
    mov dword ptr [rsp+40],0
    mov dword ptr [rsp+48],CLASS_HARD
    mov qword ptr [rsp+56],0
    call trace_emit

    mov rcx,file_handle
    lea rdx,file_size
    call GetFileSizeEx
    test eax,eax
    jz @@bad

    mov rcx,file_handle
    xor rdx,rdx
    mov r8d,PAGE_READONLY
    xor r9d,r9d
    mov qword ptr [rsp+32],0
    mov qword ptr [rsp+40],0
    call CreateFileMappingW
    test rax,rax
    jnz @F
    lea rcx,msg_map_fail
    call stdout_z
    mov ecx,4
    call ExitProcess
@@:
    mov map_handle,rax
    mov rcx,map_handle
    mov edx,FILE_MAP_READ
    xor r8d,r8d
    xor r9d,r9d
    mov qword ptr [rsp+32],0
    call MapViewOfFile
    test rax,rax
    jnz @F
    lea rcx,msg_map_fail
    call stdout_z
    mov ecx,5
    call ExitProcess
@@:
    mov map_base,rax
    mov cursor,rax
    mov rdx,file_size
    add rdx,rax
    mov map_end,rdx

    ; GGUF header
    call read_u32
    cmp eax,GGUF_MAGIC
    jne @@bad
    call read_u32
    cmp rax,-1
    je @@bad
    mov gguf_version,eax
    cmp eax,2
    jb @@bad
    cmp eax,3
    ja @@bad
    call read_u64
    cmp rax,-1
    je @@bad
    mov tensor_count,rax
    call read_u64
    cmp rax,-1
    je @@bad
    mov metadata_count,rax
    cmp rax,MAX_METADATA
    ja @@bad

    mov rcx,TRACE_KIND_VERIFY
    mov edx,OP_GGUF_HEADER
    xor r8,r8
    mov r9,tensor_count
    mov rax,metadata_count
    mov qword ptr [rsp+32],rax
    mov dword ptr [rsp+40],0
    mov dword ptr [rsp+48],CLASS_PROVEN
    mov qword ptr [rsp+56],0
    call trace_emit

    call parse_metadata
    test eax,eax
    jz @@bad
    call parse_tensors
    test eax,eax
    jz @@bad

    ; Verification stamp: all tensor absolute offsets are inside mapped file.
    mov rcx,TRACE_KIND_VERIFY
    mov edx,OP_VERIFY_LAYOUT
    xor r8,r8
    mov r9,tensor_data_start
    mov rax,file_size
    mov qword ptr [rsp+32],rax
    mov dword ptr [rsp+40],0
    mov dword ptr [rsp+48],CLASS_PROVEN
    mov qword ptr [rsp+56],0
    call trace_emit

    call emit_model_header
    call emit_tensor_header
    call emit_quant_header
    call emit_system_header
    call emit_stamp_header
    call emit_rxi

    mov rcx,TRACE_KIND_CLASSIFY
    mov edx,OP_COMPLETE
    xor r8,r8
    mov r9,tensor_count
    mov rax,metadata_count
    mov qword ptr [rsp+32],rax
    mov dword ptr [rsp+40],0
    mov dword ptr [rsp+48],CLASS_PROVEN
    mov qword ptr [rsp+56],0
    call trace_emit
    call emit_trace

    lea rcx,msg_ok
    call stdout_z
    lea rcx,msg_outputs
    call stdout_z

    mov rcx,map_base
    call UnmapViewOfFile
    mov rcx,map_handle
    call CloseHandle
    mov rcx,file_handle
    call CloseHandle
    xor ecx,ecx
    call ExitProcess

@@bad:
    lea rcx,msg_bad_gguf
    call stdout_z
    mov ecx,6
    call ExitProcess
start ENDP

END start
