# CMake generated Testfile for 
# Source directory: D:/rawrxd
# Build directory: D:/rawrxd/build-ninja-clean
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test("test_generation" "D:/rawrxd/build-ninja-clean/tests/test_generation.exe")
set_tests_properties("test_generation" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;10790;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("test_llama_native" "D:/rawrxd/build-ninja-clean/tests/test_llama_native.exe")
set_tests_properties("test_llama_native" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;10834;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_runtime_validation" "D:/rawrxd/build-ninja-clean/tests/k2_runtime_validation.exe")
set_tests_properties("k2_runtime_validation" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;10883;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("test_q4k_decoder" "D:/rawrxd/build-ninja-clean/tests/test_q4k_decoder.exe")
set_tests_properties("test_q4k_decoder" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;10895;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("test_q6k_asm_certification" "D:/rawrxd/build-ninja-clean/tests/test_q6k_asm_certification.exe")
set_tests_properties("test_q6k_asm_certification" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;10902;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("test_quant_dequant_crosscheck" "D:/rawrxd/build-ninja-clean/tests/test_quant_dequant_crosscheck.exe")
set_tests_properties("test_quant_dequant_crosscheck" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;10908;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_native_smoke_test" "D:/rawrxd/build-ninja-clean/tests/k2_native_smoke_test.exe")
set_tests_properties("k2_native_smoke_test" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;10954;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_002_tensor_streaming" "D:/rawrxd/build-ninja-clean/tests/k2_002_tensor_streaming.exe")
set_tests_properties("k2_002_tensor_streaming" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11000;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_003_layer_execution" "D:/rawrxd/build-ninja-clean/tests/k2_003_layer_execution.exe")
set_tests_properties("k2_003_layer_execution" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11046;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_003b_native_gemv_validation" "D:/rawrxd/build-ninja-clean/tests/k2_003b_native_gemv_validation.exe")
set_tests_properties("k2_003b_native_gemv_validation" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11059;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_003c_single_layer_forward" "D:/rawrxd/build-ninja-clean/tests/k2_003c_single_layer_forward.exe")
set_tests_properties("k2_003c_single_layer_forward" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11072;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_004_bounded_prefill" "D:/rawrxd/build-ninja-clean/tests/k2_004_bounded_prefill.exe")
set_tests_properties("k2_004_bounded_prefill" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11118;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_004_bounded_multi_layer_prefill" "D:/rawrxd/build-ninja-clean/tests/k2_004_bounded_multi_layer_prefill.exe")
set_tests_properties("k2_004_bounded_multi_layer_prefill" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11131;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_005_autoregressive_kv_cache" "D:/rawrxd/build-ninja-clean/tests/k2_005_autoregressive_kv_cache.exe")
set_tests_properties("k2_005_autoregressive_kv_cache" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11145;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_006_bounded_token_generation" "D:/rawrxd/build-ninja-clean/tests/k2_006_bounded_token_generation.exe")
set_tests_properties("k2_006_bounded_token_generation" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11159;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_007_real_output_projection" "D:/rawrxd/build-ninja-clean/tests/k2_007_real_output_projection.exe")
set_tests_properties("k2_007_real_output_projection" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11172;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_007a_tokenizer_metadata" "D:/rawrxd/build-ninja-clean/tests/k2_007a_tokenizer_metadata.exe")
set_tests_properties("k2_007a_tokenizer_metadata" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11178;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_007b_projection_logits_interface" "D:/rawrxd/build-ninja-clean/tests/k2_007b_projection_logits_interface.exe")
set_tests_properties("k2_007b_projection_logits_interface" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11191;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_008_end_to_end_semantic_generation" "D:/rawrxd/build-ninja-clean/tests/k2_008_end_to_end_semantic_generation.exe")
set_tests_properties("k2_008_end_to_end_semantic_generation" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11207;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_tls_smoke_test" "D:/rawrxd/build-ninja-clean/tests/k2_tls_smoke_test.exe")
set_tests_properties("k2_tls_smoke_test" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11215;add_test;D:/rawrxd/CMakeLists.txt;0;")
add_test("k2_009_token_embedding_lookup" "D:/rawrxd/build-ninja-clean/tests/k2_009_token_embedding_lookup.exe")
set_tests_properties("k2_009_token_embedding_lookup" PROPERTIES  WORKING_DIRECTORY "D:/rawrxd/build-ninja-clean/tests" _BACKTRACE_TRIPLES "D:/rawrxd/CMakeLists.txt;11229;add_test;D:/rawrxd/CMakeLists.txt;0;")
subdirs("_deps/nlohmann_json-build")
subdirs("src/reverse_engineering")
subdirs("src/ceo")
subdirs("src/repository")
subdirs("src/generation")
subdirs("rguf_source")
subdirs("src/runtime")
subdirs("tests")
subdirs("src/tools")
subdirs("src/validation")
