                << "#include <iostream>\n"
                << "#include <immintrin.h>\n\n"
                << "void " << name << "::initialize() {\n"
                << "    std::cout << \"[" << name << "] Initializing GPU kernel wrapper\\n\";\n"
                << "    // Verify SIMD support for optimized tensor operations\n"
                << "    int cpuInfo[4] = {};\n"
                << "    __cpuid(cpuInfo, 1);\n"
                << "    bool hasAVX2 = (cpuInfo[2] & (1 << 28)) != 0;\n"
                << "    std::cout << \"[" << name << "] AVX2 support: \" << (hasAVX2 ? \"yes\" : \"no\") << \"\\n\";\n"
                << "}\n\n"
                << "void " << name << "::cleanup() {\n"
                << "    std::cout << \"[" << name << "] Cleaning up GPU kernel resources\\n\";\n"
                << "}\n\n"
                << "std::vector<float> " << name << "::wrap(const float* src, size_t n) {\n"
                << "    std::vector<float> res(n);\n"
                << "    if (!src || n == 0) return res;\n"
                << "    // SIMD-accelerated copy using AVX2 (256-bit = 8 floats per op)\n"
                << "    size_t simdEnd = (n / 8) * 8;\n"
                << "    for (size_t i = 0; i < simdEnd; i += 8) {\n"
                << "        __m256 v = _mm256_loadu_ps(src + i);\n"
                << "        _mm256_storeu_ps(res.data() + i, v);\n"
                << "    }\n"
                << "    // Scalar remainder\n"
                << "    for (size_t i = simdEnd; i < n; ++i) res[i] = src[i];\n"

