// Auto-generated by scripts/generate_rawrxd_titan_stubs.ps1
#include "RawrXD_Exports.h"

#include <algorithm>
#include <atomic>
#include <cstdlib>
#include <mutex>
#include <string.h>
#include <unordered_map>

namespace {
std::atomic<bool> g_rawrxd_initialized{false};
std::atomic<int32_t> g_log_level{3};
std::atomic<RAWRXD_STATUS> g_last_error{RAWRXD_SUCCESS};
std::atomic<uint64_t> g_next_model_handle{1};
std::atomic<uint64_t> g_next_inference_handle{1};
std::atomic<uint32_t> g_stub_infer_async_calls{0};
std::atomic<uint32_t> g_stub_infer_sync_calls{0};
std::atomic<uint32_t> g_stub_batch_calls{0};
std::atomic<uint32_t> g_stub_timeout_count{0};
std::atomic<uint32_t> g_stub_invalid_param_count{0};
std::atomic<uint32_t> g_stub_aperture_errors{0};
std::atomic<uint32_t> g_stub_hotpatch_apply_calls{0};
std::atomic<uint32_t> g_stub_diag_callback_calls{0};

std::mutex g_state_mutex;

constexpr const char* kVersion = "1.2.6-alpha";
constexpr uint64_t kApertureBase = 0x0000010000000000ULL;
constexpr uint64_t kApertureTotalBytes = 1099511627776ULL;  // 1 TB
constexpr uint32_t kDefaultVocab = 32000;
constexpr uint32_t kDefaultContext = 8192;
constexpr uint32_t kDefaultPrecisionBits = 16;

struct ModelState {
    bool loaded = false;
    RAWRXD_MODEL_HANDLE handle = 0;
    char path[MAX_PATH] = {};
    char name[256] = "fallback-model";
    uint64_t size_bytes = 0;
    uint32_t parameter_count = 7;
    uint32_t vocab_size = kDefaultVocab;
    uint32_t context_length = kDefaultContext;
    uint32_t precision_bits = kDefaultPrecisionBits;
};

struct InferenceState {
    bool valid = false;
    RAWRXD_INFERENCE_HANDLE handle = 0;
    RAWRXD_INFERENCE_RESULT result{};
};

ModelState g_model;
InferenceState g_last_inference;
RAWRXD_SAMPLING_PARAMS g_sampling{0.7f, 0.9f, 40, 1.0f, 0};
char g_system_prompt[2048] = {};

bool g_aperture_initialized = false;
uint32_t g_aperture_policy = 0;
uint32_t g_mapped_chunks = 0;
bool g_diagnostics_enabled = false;
uint32_t g_hotpatch_status = 0;
uint32_t g_quantization_bits = kDefaultPrecisionBits;
void (*g_diag_callback)(const char*) = nullptr;

RAWRXD_MEMORY_STATS g_mem_stats{};
RAWRXD_PERF_COUNTERS g_perf_counters{};
double g_last_latency_ms = 0.0;

uint64_t g_working_set_limit = 0;
std::unordered_map<void*, size_t> g_allocations;
uint32_t g_stub_latency_bias_ms = 0;

inline RAWRXD_STATUS Finish(RAWRXD_STATUS status) {
    g_last_error.store(status);
    return status;
}

inline RAWRXD_STATUS FailInvalidParam() {
    g_stub_invalid_param_count.fetch_add(1, std::memory_order_relaxed);
    return Finish(RAWRXD_ERROR_INVALID_PARAM);
}

inline uint32_t ClampU32FromEnv(const char* name, uint32_t fallback, uint32_t min_value, uint32_t max_value) {
    if (name == nullptr || min_value > max_value) {
        return fallback;
    }
    const char* raw = std::getenv(name);
    if (raw == nullptr || raw[0] == 0) {
        return fallback;
    }
    char* end = nullptr;
    const unsigned long parsed = std::strtoul(raw, &end, 10);
    if (end == raw || (end != nullptr && *end != 0)) {
        return fallback;
    }
    const uint32_t value = static_cast<uint32_t>(parsed);
    if (value < min_value) {
        return min_value;
    }
    if (value > max_value) {
        return max_value;
    }
    return value;
}

inline RAWRXD_STATUS RequireInitialized() {
    if (!g_rawrxd_initialized.load()) {
        return Finish(RAWRXD_ERROR_NOT_INITIALIZED);
    }
    return RAWRXD_SUCCESS;
}

inline void ZeroIfPresent(void* ptr, size_t bytes) {
    if (ptr != nullptr && bytes > 0) {
        memset(ptr, 0, bytes);
    }
}

inline uint32_t EstimateTokenCount(const char* text, size_t len) {
    if (text == nullptr || len == 0) {
        return 0;
    }
    uint32_t count = 0;
    bool in_token = false;
    for (size_t i = 0; i < len; ++i) {
        const bool is_space = (text[i] == ' ' || text[i] == '\n' || text[i] == '\t' || text[i] == '\r');
        if (is_space) {
            in_token = false;
        } else if (!in_token) {
            ++count;
            in_token = true;
        }
    }
    return (count == 0) ? 1u : count;
}

inline void ResetMutableStateLocked() {
    g_model = ModelState{};
    g_last_inference = InferenceState{};
    g_sampling = {0.7f, 0.9f, 40, 1.0f, 0};
    g_system_prompt[0] = 0;
    g_aperture_initialized = false;
    g_aperture_policy = 0;
    g_mapped_chunks = 0;
    g_diagnostics_enabled = false;
    g_hotpatch_status = 0;
    g_quantization_bits = kDefaultPrecisionBits;
    g_diag_callback = nullptr;
    g_perf_counters = {};
    g_last_latency_ms = 0.0;
}

inline void ResetStubTelemetry() {
    g_stub_infer_async_calls.store(0, std::memory_order_relaxed);
    g_stub_infer_sync_calls.store(0, std::memory_order_relaxed);
    g_stub_batch_calls.store(0, std::memory_order_relaxed);
    g_stub_timeout_count.store(0, std::memory_order_relaxed);
    g_stub_invalid_param_count.store(0, std::memory_order_relaxed);
    g_stub_aperture_errors.store(0, std::memory_order_relaxed);
    g_stub_hotpatch_apply_calls.store(0, std::memory_order_relaxed);
    g_stub_diag_callback_calls.store(0, std::memory_order_relaxed);
}

inline void UpdatePerfLocked(uint32_t in_tokens, uint32_t out_tokens, double latency_ms) {
    ++g_perf_counters.inference_count;
    g_perf_counters.total_input_tokens += in_tokens;
    g_perf_counters.total_output_tokens += out_tokens;
    const double n = static_cast<double>(g_perf_counters.inference_count);
    if (n <= 1.0) {
        g_perf_counters.avg_latency_ms = latency_ms;
    } else {
        g_perf_counters.avg_latency_ms = ((g_perf_counters.avg_latency_ms * (n - 1.0)) + latency_ms) / n;
    }
    g_perf_counters.peak_latency_ms = std::max(g_perf_counters.peak_latency_ms, latency_ms);
    g_last_latency_ms = latency_ms;
    if (latency_ms > 0.0) {
        g_perf_counters.throughput_tokens_sec = (static_cast<double>(out_tokens) * 1000.0) / latency_ms;
    }
}

inline const char* ErrorToString(RAWRXD_STATUS status) {
    switch (status) {
    case RAWRXD_SUCCESS: return "SUCCESS";
    case RAWRXD_ERROR_NOT_INITIALIZED: return "NOT_INITIALIZED";
    case RAWRXD_ERROR_INVALID_PARAM: return "INVALID_PARAM";
    case RAWRXD_ERROR_NOT_READY: return "NOT_READY";
    case RAWRXD_ERROR_NO_MODEL_LOADED: return "NO_MODEL_LOADED";
    case RAWRXD_ERROR_OUT_OF_MEMORY: return "OUT_OF_MEMORY";
    case RAWRXD_ERROR_INFERENCE_FAILED: return "INFERENCE_FAILED";
    case RAWRXD_ERROR_TIMED_OUT: return "TIMED_OUT";
    case RAWRXD_ERROR_APERTURE_UNAVAIL: return "APERTURE_UNAVAILABLE";
    case RAWRXD_ERROR_VA_FRAGMENTED: return "VA_FRAGMENTED";
    case RAWRXD_ERROR_HOTPATCH_FAILED: return "HOTPATCH_FAILED";
    default: return "UNKNOWN_ERROR";
    }
}
}

extern "C" {
RAWRXD_STATUS __stdcall RawrXD_Initialize(void) {
    std::lock_guard<std::mutex> lock(g_state_mutex);
    g_rawrxd_initialized.store(true);
    ResetMutableStateLocked();
    ResetStubTelemetry();
    g_stub_latency_bias_ms = ClampU32FromEnv("RAWRXD_TITAN_STUB_LATENCY_BIAS_MS", 0u, 0u, 10000u);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_Shutdown(void) {
    std::lock_guard<std::mutex> lock(g_state_mutex);
    for (auto& entry : g_allocations) {
        free(entry.first);
    }
    g_allocations.clear();
    g_mem_stats.currently_allocated = 0;
    g_mem_stats.heap_blocks = 0;
    ResetMutableStateLocked();
    g_rawrxd_initialized.store(false);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_Reset(void) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    ResetMutableStateLocked();
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_Abort(void) {
    g_rawrxd_initialized.store(false);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetStatus(RAWRXD_STATUS* status_code) {
    if (status_code == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    *status_code = g_rawrxd_initialized.load() ? RAWRXD_SUCCESS : RAWRXD_ERROR_NOT_INITIALIZED;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetVersion(char* version_string, size_t buffer_size) {
    if (version_string == nullptr || buffer_size == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    const size_t needed = strlen(kVersion) + 1;
    if (buffer_size < needed) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    strcpy_s(version_string, buffer_size, kVersion);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetCapabilities(uint32_t* capabilities) {
    if (capabilities == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    *capabilities = RAWRXD_CAP_GPU_ACCELERATION | RAWRXD_CAP_QUANTIZATION |
        RAWRXD_CAP_APERTURE_MAPPING | RAWRXD_CAP_STREAMING | RAWRXD_CAP_HOTPATCHING |
        RAWRXD_CAP_MULTI_BATCH | RAWRXD_CAP_DIAGNOSTICS;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_SetLogLevel(int32_t level) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (level < 0 || level > 4) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    g_log_level.store(level);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_LoadModel(const char* model_path, RAWRXD_MODEL_HANDLE* model_handle) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (model_path == nullptr || model_handle == nullptr || model_path[0] == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    g_model.loaded = true;
    g_model.handle = g_next_model_handle.fetch_add(1);
    strcpy_s(g_model.path, MAX_PATH, model_path);
    const char* last_slash = strrchr(model_path, '\\');
    const char* name = (last_slash != nullptr) ? (last_slash + 1) : model_path;
    strcpy_s(g_model.name, sizeof(g_model.name), name);
    g_model.size_bytes = static_cast<uint64_t>(strlen(model_path)) * 1024ULL * 1024ULL;
    g_model.precision_bits = g_quantization_bits;
    *model_handle = g_model.handle;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_UnloadModel(RAWRXD_MODEL_HANDLE model_handle) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded || model_handle == 0 || model_handle != g_model.handle) {
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }
    g_model = ModelState{};
    g_last_inference = InferenceState{};
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetModelInfo(RAWRXD_MODEL_HANDLE model_handle, RAWRXD_MODEL_INFO* model_info) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        ZeroIfPresent(model_info, model_info ? sizeof(*model_info) : 0);
        return g_last_error.load();
    }
    if (model_info == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded || (model_handle != 0 && model_handle != g_model.handle)) {
        ZeroIfPresent(model_info, sizeof(*model_info));
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }
    ZeroIfPresent(model_info, sizeof(*model_info));
    model_info->size_bytes = g_model.size_bytes;
    model_info->parameter_count = g_model.parameter_count;
    model_info->vocab_size = g_model.vocab_size;
    model_info->context_length = g_model.context_length;
    model_info->precision_bits = g_model.precision_bits;
    strcpy_s(model_info->model_name, sizeof(model_info->model_name), g_model.name);
    strcpy_s(model_info->model_path, sizeof(model_info->model_path), g_model.path);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_ListModels(char* model_paths, size_t buffer_size, uint32_t* count) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        if (count != nullptr) {
            *count = 0;
        }
        if (model_paths != nullptr && buffer_size > 0) {
            model_paths[0] = 0;
        }
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (count != nullptr) {
        *count = g_model.loaded ? 1u : 0u;
    }
    if (model_paths != nullptr && buffer_size > 0) {
        model_paths[0] = 0;
        if (g_model.loaded) {
            const size_t needed = strlen(g_model.path) + 2;
            if (buffer_size < needed) {
                return Finish(RAWRXD_ERROR_INVALID_PARAM);
            }
            strcpy_s(model_paths, buffer_size, g_model.path);
            model_paths[strlen(g_model.path) + 1] = 0;
        }
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_SelectModel(RAWRXD_MODEL_HANDLE model_handle) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded || model_handle != g_model.handle) {
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetActiveModel(RAWRXD_MODEL_HANDLE* model_handle) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (model_handle == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded) {
        *model_handle = 0;
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }
    *model_handle = g_model.handle;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_PreloadChunks(RAWRXD_MODEL_HANDLE model_handle, uint32_t chunk_start, uint32_t chunk_count) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded || model_handle != g_model.handle) {
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }
    if (chunk_count == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    const uint32_t added = std::min<uint32_t>(chunk_count, 8192u - g_mapped_chunks);
    g_mapped_chunks += added;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_ReleaseChunks(RAWRXD_MODEL_HANDLE model_handle, uint32_t chunk_start, uint32_t chunk_count) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded || model_handle != g_model.handle) {
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }
    const uint32_t removed = std::min<uint32_t>(chunk_count, g_mapped_chunks);
    g_mapped_chunks -= removed;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetChunkStatus(RAWRXD_MODEL_HANDLE model_handle, uint32_t chunk_index, uint32_t* is_mapped) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (is_mapped == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded || model_handle != g_model.handle) {
        *is_mapped = 0;
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }
    *is_mapped = (chunk_index < g_mapped_chunks) ? 1u : 0u;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_ValidateModelIntegrity(RAWRXD_MODEL_HANDLE model_handle, uint32_t* is_valid) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (is_valid == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded || model_handle != g_model.handle) {
        *is_valid = 0;
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }
    *is_valid = 1;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetModelPath(char* model_path, size_t buffer_size) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (model_path == nullptr || buffer_size == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded) {
        model_path[0] = 0;
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }
    if (buffer_size < strlen(g_model.path) + 1) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    strcpy_s(model_path, buffer_size, g_model.path);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_CacheModelMetadata(RAWRXD_MODEL_HANDLE model_handle) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded || model_handle != g_model.handle) {
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_InferAsync(const char* prompt, size_t prompt_len, RAWRXD_INFERENCE_HANDLE* inference_handle) {
    g_stub_infer_async_calls.fetch_add(1, std::memory_order_relaxed);
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (prompt == nullptr || prompt_len == 0 || inference_handle == nullptr) {
        return FailInvalidParam();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded) {
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }
    const uint32_t in_tokens = EstimateTokenCount(prompt, prompt_len);
    g_last_inference.valid = true;
    g_last_inference.handle = g_next_inference_handle.fetch_add(1);
    g_last_inference.result = {};
    g_last_inference.result.input_token_count = in_tokens;
    g_last_inference.result.status = RAWRXD_ERROR_NOT_READY;
    *inference_handle = g_last_inference.handle;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_InferSync(const char* prompt, size_t prompt_len, RAWRXD_INFERENCE_RESULT* result, uint32_t timeout_ms) {
    g_stub_infer_sync_calls.fetch_add(1, std::memory_order_relaxed);
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        ZeroIfPresent(result, result ? sizeof(*result) : 0);
        return g_last_error.load();
    }
    if (prompt == nullptr || prompt_len == 0 || result == nullptr) {
        ZeroIfPresent(result, result ? sizeof(*result) : 0);
        return FailInvalidParam();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded) {
        ZeroIfPresent(result, sizeof(*result));
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }

    const uint32_t in_tokens = EstimateTokenCount(prompt, prompt_len);
    const uint32_t max_tokens = (g_sampling.max_tokens > 0) ? static_cast<uint32_t>(g_sampling.max_tokens) : 128u;
    const uint32_t out_tokens = std::max<uint32_t>(1u, std::min<uint32_t>(max_tokens, (in_tokens / 2u) + 8u));
    const uint64_t latency = std::max<uint64_t>(1ULL, static_cast<uint64_t>((out_tokens / 2u) + 2u + g_stub_latency_bias_ms));
    if (timeout_ms > 0 && latency > timeout_ms) {
        g_stub_timeout_count.fetch_add(1, std::memory_order_relaxed);
        ZeroIfPresent(result, sizeof(*result));
        result->status = RAWRXD_ERROR_TIMED_OUT;
        return Finish(RAWRXD_ERROR_TIMED_OUT);
    }

    ZeroIfPresent(result, sizeof(*result));
    result->input_token_count = in_tokens;
    result->output_token_count = out_tokens;
    result->latency_ms = latency;
    result->status = RAWRXD_SUCCESS;

    g_last_inference.valid = true;
    g_last_inference.handle = g_next_inference_handle.fetch_add(1);
    g_last_inference.result = *result;
    UpdatePerfLocked(in_tokens, out_tokens, static_cast<double>(latency));

    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_CancelInference(RAWRXD_INFERENCE_HANDLE inference_handle) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_last_inference.valid || inference_handle != g_last_inference.handle) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    g_last_inference.result.status = RAWRXD_ERROR_INFERENCE_FAILED;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_WaitForInference(RAWRXD_INFERENCE_HANDLE inference_handle, uint32_t timeout_ms) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_last_inference.valid || inference_handle != g_last_inference.handle) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (g_last_inference.result.status == RAWRXD_ERROR_NOT_READY && timeout_ms < 1) {
        return Finish(RAWRXD_ERROR_TIMED_OUT);
    }
    if (g_last_inference.result.status == RAWRXD_ERROR_NOT_READY) {
        g_last_inference.result.status = RAWRXD_SUCCESS;
        g_last_inference.result.output_token_count = std::max<uint32_t>(1u, g_last_inference.result.input_token_count / 2u);
        g_last_inference.result.latency_ms = 3;
        UpdatePerfLocked(g_last_inference.result.input_token_count,
            g_last_inference.result.output_token_count,
            static_cast<double>(g_last_inference.result.latency_ms));
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetInferenceResult(RAWRXD_INFERENCE_HANDLE inference_handle, RAWRXD_INFERENCE_RESULT* result) {
    if (result == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    ZeroIfPresent(result, sizeof(*result));
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_last_inference.valid || inference_handle != g_last_inference.handle) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    *result = g_last_inference.result;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetInferenceTokenCount(RAWRXD_INFERENCE_HANDLE inference_handle, uint32_t* token_count) {
    if (token_count == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *token_count = 0;
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_last_inference.valid || inference_handle != g_last_inference.handle) {
        *token_count = 0;
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    *token_count = g_last_inference.result.output_token_count;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_SetSamplingParams(const RAWRXD_SAMPLING_PARAMS* params) {
    if (params == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (params->temperature < 0.0f || params->temperature > 2.0f ||
        params->top_p < 0.0f || params->top_p > 1.0f ||
        params->top_k < 0 || params->top_k > 100 ||
        params->repetition_penalty < 0.0f || params->repetition_penalty > 2.0f ||
        params->max_tokens < 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    g_sampling = *params;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetSamplingParams(RAWRXD_SAMPLING_PARAMS* params) {
    if (params == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        ZeroIfPresent(params, sizeof(*params));
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    *params = g_sampling;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_SetSystemPrompt(const char* system_prompt) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (system_prompt == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    strcpy_s(g_system_prompt, sizeof(g_system_prompt), system_prompt);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetSystemPrompt(char* buffer, size_t buffer_size) {
    if (buffer == nullptr || buffer_size == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        buffer[0] = 0;
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (buffer_size < strlen(g_system_prompt) + 1) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    strcpy_s(buffer, buffer_size, g_system_prompt);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_TokenizeInput(const char* prompt, int32_t* tokens, size_t max_tokens, uint32_t* token_count) {
    if (token_count == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    *token_count = 0;
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (prompt == nullptr || tokens == nullptr || max_tokens == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    const size_t len = strlen(prompt);
    uint32_t count = 0;
    size_t i = 0;
    while (i < len && count < max_tokens) {
        while (i < len && (prompt[i] == ' ' || prompt[i] == '\n' || prompt[i] == '\t' || prompt[i] == '\r')) {
            ++i;
        }
        if (i >= len) {
            break;
        }
        size_t start = i;
        while (i < len && prompt[i] != ' ' && prompt[i] != '\n' && prompt[i] != '\t' && prompt[i] != '\r') {
            ++i;
        }
        tokens[count++] = static_cast<int32_t>((i - start) + 100);
    }
    *token_count = count;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_DetokenizeOutput(const int32_t* tokens, uint32_t token_count, char* output, size_t output_size) {
    if (output == nullptr || output_size == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    output[0] = 0;
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (tokens == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    size_t used = 0;
    for (uint32_t i = 0; i < token_count; ++i) {
        char chunk[24];
        int written = _snprintf_s(chunk, sizeof(chunk), _TRUNCATE, "%d", tokens[i]);
        if (written <= 0) {
            break;
        }
        size_t need = static_cast<size_t>(written) + ((i + 1 < token_count) ? 1 : 0);
        if (used + need + 1 > output_size) {
            break;
        }
        memcpy(output + used, chunk, static_cast<size_t>(written));
        used += static_cast<size_t>(written);
        if (i + 1 < token_count) {
            output[used++] = ' ';
        }
    }
    output[used] = 0;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetTokenizerInfo(uint32_t* vocab_size, int32_t* bos_token, int32_t* eos_token) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (vocab_size != nullptr) {
        *vocab_size = kDefaultVocab;
    }
    if (bos_token != nullptr) {
        *bos_token = 1;
    }
    if (eos_token != nullptr) {
        *eos_token = 2;
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_EstimateTokens(const char* prompt, uint32_t* token_count) {
    if (token_count == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    *token_count = 0;
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (prompt == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    *token_count = EstimateTokenCount(prompt, strlen(prompt));
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_BeginStreaming(RAWRXD_INFERENCE_HANDLE* stream_handle) {
    if (stream_handle == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *stream_handle = 0;
        return g_last_error.load();
    }
    *stream_handle = g_next_inference_handle.fetch_add(1);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_EndStreaming(RAWRXD_INFERENCE_HANDLE stream_handle) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (stream_handle == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_ApertureInit(void) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    g_aperture_initialized = true;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_ApertureShutdown(void) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    g_aperture_initialized = false;
    g_mapped_chunks = 0;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_MapChunk(uint32_t chunk_index, uint64_t* mapped_address) {
    if (mapped_address == nullptr) {
        return FailInvalidParam();
    }
    *mapped_address = 0;
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_aperture_initialized) {
        g_stub_aperture_errors.fetch_add(1, std::memory_order_relaxed);
        return Finish(RAWRXD_ERROR_APERTURE_UNAVAIL);
    }
    ++g_mapped_chunks;
    *mapped_address = kApertureBase + (static_cast<uint64_t>(chunk_index) * 64ULL * 1024ULL * 1024ULL);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_UnmapChunk(uint32_t chunk_index) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_aperture_initialized) {
        return Finish(RAWRXD_ERROR_APERTURE_UNAVAIL);
    }
    if (g_mapped_chunks > 0) {
        --g_mapped_chunks;
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetApertureBase(uint64_t* base_address) {
    if (base_address == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *base_address = 0;
        return g_last_error.load();
    }
    *base_address = kApertureBase;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetApertureUtilization(RAWRXD_APERTURE_STATUS* status) {
    if (status == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    ZeroIfPresent(status, sizeof(*status));
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    status->aperture_base = kApertureBase;
    status->aperture_total_bytes = kApertureTotalBytes;
    status->mapped_chunks = g_mapped_chunks;
    status->mapped_bytes = static_cast<uint64_t>(g_mapped_chunks) * 64ULL * 1024ULL * 1024ULL;
    status->unmapped_bytes = (status->mapped_bytes < kApertureTotalBytes) ?
        (kApertureTotalBytes - status->mapped_bytes) : 0;
    status->fragment_count = (g_mapped_chunks > 0) ? 1u : 0u;
    status->fragmentation_ratio = (g_mapped_chunks > 0) ? 0.05f : 0.0f;
    status->utilization_pct10000 = static_cast<uint32_t>((status->mapped_bytes * 1000000ULL) / kApertureTotalBytes);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_CompactAperture(void) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_PreAllocateChunks(uint32_t chunk_count) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_aperture_initialized) {
        return Finish(RAWRXD_ERROR_APERTURE_UNAVAIL);
    }
    g_mapped_chunks += chunk_count;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetChunkMappingLatency(double* latency_ms) {
    if (latency_ms == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *latency_ms = 0.0;
        return g_last_error.load();
    }
    *latency_ms = 0.25;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetChunkUnmapLatency(double* latency_ms) {
    if (latency_ms == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *latency_ms = 0.0;
        return g_last_error.load();
    }
    *latency_ms = 0.20;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_SetAperturePolicy(uint32_t policy_flags) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    g_aperture_policy = policy_flags;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetAperturePolicy(uint32_t* policy_flags) {
    if (policy_flags == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *policy_flags = 0;
        return g_last_error.load();
    }
    *policy_flags = g_aperture_policy;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_AllocateBuffer(size_t size, void** buffer) {
    if (buffer == nullptr || size == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    *buffer = nullptr;
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    void* mem = malloc(size);
    if (mem == nullptr) {
        return Finish(RAWRXD_ERROR_OUT_OF_MEMORY);
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    g_allocations[mem] = size;
    g_mem_stats.total_allocated += size;
    g_mem_stats.currently_allocated += size;
    g_mem_stats.peak_allocated = std::max<uint64_t>(g_mem_stats.peak_allocated, g_mem_stats.currently_allocated);
    g_mem_stats.heap_blocks = static_cast<uint32_t>(g_allocations.size());
    g_mem_stats.heap_fragmentation = (g_mem_stats.heap_blocks > 1) ? 0.1f : 0.0f;
    g_mem_stats.virtual_address_space = g_mem_stats.currently_allocated;
    *buffer = mem;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_FreeBuffer(void* buffer) {
    if (buffer == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    auto it = g_allocations.find(buffer);
    if (it == g_allocations.end()) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    const size_t size = it->second;
    g_allocations.erase(it);
    free(buffer);
    g_mem_stats.currently_allocated = (g_mem_stats.currently_allocated >= size)
        ? (g_mem_stats.currently_allocated - size)
        : 0;
    g_mem_stats.heap_blocks = static_cast<uint32_t>(g_allocations.size());
    g_mem_stats.heap_fragmentation = (g_mem_stats.heap_blocks > 1) ? 0.1f : 0.0f;
    g_mem_stats.virtual_address_space = g_mem_stats.currently_allocated;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetMemoryStats(RAWRXD_MEMORY_STATS* stats) {
    if (stats == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    ZeroIfPresent(stats, sizeof(*stats));
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    *stats = g_mem_stats;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetHeapStats(RAWRXD_MEMORY_STATS* heap_stats) {
    return RawrXD_GetMemoryStats(heap_stats);
}

RAWRXD_STATUS __stdcall RawrXD_MemoryGC(void) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_SetWorkingSetLimit(uint64_t max_bytes) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    g_working_set_limit = max_bytes;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetWorkingSetLimit(uint64_t* limit_bytes) {
    if (limit_bytes == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *limit_bytes = 0;
        return g_last_error.load();
    }
    *limit_bytes = g_working_set_limit;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetPeakMemoryUsage(uint64_t* peak_bytes) {
    if (peak_bytes == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *peak_bytes = 0;
        return g_last_error.load();
    }
    *peak_bytes = g_mem_stats.peak_allocated;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_ResetMemoryStatistics(void) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    const uint64_t current = g_mem_stats.currently_allocated;
    g_mem_stats = {};
    g_mem_stats.currently_allocated = current;
    g_mem_stats.virtual_address_space = current;
    g_mem_stats.heap_blocks = static_cast<uint32_t>(g_allocations.size());
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetVAFragmentation(float* fragmentation) {
    if (fragmentation == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *fragmentation = 0.0f;
        return g_last_error.load();
    }
    *fragmentation = (g_mapped_chunks > 64) ? 0.12f : 0.03f;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetCacheMissRate(float* miss_rate) {
    if (miss_rate == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *miss_rate = 0.0f;
        return g_last_error.load();
    }
    *miss_rate = g_model.loaded ? 0.08f : 1.0f;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetInferenceLatency(double* latency_ms) {
    if (latency_ms == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *latency_ms = 0.0;
        return g_last_error.load();
    }
    *latency_ms = g_last_latency_ms;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetThroughputTokensPerSec(double* throughput) {
    if (throughput == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *throughput = 0.0;
        return g_last_error.load();
    }
    *throughput = g_perf_counters.throughput_tokens_sec;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_ResetPerformanceCounters(void) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    g_perf_counters = {};
    g_last_latency_ms = 0.0;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetLastError(void) {
    return g_last_error.load();
}

RAWRXD_STATUS __stdcall RawrXD_GetErrorString(RAWRXD_STATUS error_code, char* message, size_t buffer_size) {
    if (message == nullptr || buffer_size == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    const char* msg = ErrorToString(error_code);
    const size_t needed = strlen(msg) + 1;
    if (buffer_size < needed) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    strcpy_s(message, buffer_size, msg);
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_ClearError(void) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    g_last_error.store(RAWRXD_SUCCESS);
    return RAWRXD_SUCCESS;
}

RAWRXD_STATUS __stdcall RawrXD_EnableDiagnostics(void) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    g_diagnostics_enabled = true;
    if (g_diag_callback != nullptr) {
        g_stub_diag_callback_calls.fetch_add(1, std::memory_order_relaxed);
        g_diag_callback("RawrXD diagnostics enabled");
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_DisableDiagnostics(void) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    g_diagnostics_enabled = false;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GetDiagnosticLog(char* log_buffer, size_t buffer_size, size_t* bytes_written) {
    if (bytes_written != nullptr) {
        *bytes_written = 0;
    }
    if (log_buffer == nullptr || buffer_size == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    log_buffer[0] = 0;
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    char line[256];
    const int written = _snprintf_s(line, sizeof(line), _TRUNCATE,
        "diag=%u model=%u inferences=%llu mapped_chunks=%u",
        g_diagnostics_enabled ? 1u : 0u,
        g_model.loaded ? 1u : 0u,
        static_cast<unsigned long long>(g_perf_counters.inference_count),
        g_mapped_chunks);
    if (written < 0 || static_cast<size_t>(written + 1) > buffer_size) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    strcpy_s(log_buffer, buffer_size, line);
    if (bytes_written != nullptr) {
        *bytes_written = static_cast<size_t>(written);
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_SetDiagnosticCallback(void (*callback)(const char*)) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    g_diag_callback = callback;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_GenerateAuditReport(char* report_buffer, size_t buffer_size, size_t* bytes_written) {
    if (bytes_written != nullptr) {
        *bytes_written = 0;
    }
    if (report_buffer == nullptr || buffer_size == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    report_buffer[0] = 0;
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    char report[384];
    const int written = _snprintf_s(report, sizeof(report), _TRUNCATE,
        "RawrXD fallback audit\nversion=%s\ninitialized=1\nmodel_loaded=%u\nalloc_blocks=%u\ninference_count=%llu\n",
        kVersion,
        g_model.loaded ? 1u : 0u,
        g_mem_stats.heap_blocks,
        static_cast<unsigned long long>(g_perf_counters.inference_count));
    if (written < 0 || static_cast<size_t>(written + 1) > buffer_size) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    strcpy_s(report_buffer, buffer_size, report);
    if (bytes_written != nullptr) {
        *bytes_written = static_cast<size_t>(written);
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_ValidateInternalConsistency(uint32_t* is_consistent) {
    if (is_consistent == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    *is_consistent = 0;
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    const bool mem_ok = (g_mem_stats.currently_allocated == 0) || (!g_allocations.empty());
    const bool model_ok = (!g_model.loaded) || (g_model.handle != 0);
    *is_consistent = (mem_ok && model_ok) ? 1u : 0u;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_DumpHeapWalker(char* output_buffer, size_t buffer_size, size_t* bytes_written) {
    if (bytes_written != nullptr) {
        *bytes_written = 0;
    }
    if (output_buffer == nullptr || buffer_size == 0) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    output_buffer[0] = 0;
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    char text[256];
    const int written = _snprintf_s(text, sizeof(text), _TRUNCATE,
        "heap_blocks=%u current=%llu peak=%llu",
        g_mem_stats.heap_blocks,
        static_cast<unsigned long long>(g_mem_stats.currently_allocated),
        static_cast<unsigned long long>(g_mem_stats.peak_allocated));
    if (written < 0 || static_cast<size_t>(written + 1) > buffer_size) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    strcpy_s(output_buffer, buffer_size, text);
    if (bytes_written != nullptr) {
        *bytes_written = static_cast<size_t>(written);
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_EnableHotpatch(void) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    g_hotpatch_status |= 0x1u;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_ApplyHotpatch(const uint8_t* patch_data, size_t patch_size) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if ((g_hotpatch_status & 0x1u) == 0) {
        return Finish(RAWRXD_ERROR_HOTPATCH_FAILED);
    }
    if (patch_data == nullptr || patch_size == 0) {
        return FailInvalidParam();
    }
    g_stub_hotpatch_apply_calls.fetch_add(1, std::memory_order_relaxed);
    g_hotpatch_status |= 0x2u;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_QueryHotpatchStatus(uint32_t* status) {
    if (status == nullptr) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *status = 0;
        return g_last_error.load();
    }
    *status = g_hotpatch_status;
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_EnableQuantization(uint32_t bits) {
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        return g_last_error.load();
    }
    if (bits != 4 && bits != 8 && bits != 16 && bits != 32) {
        return Finish(RAWRXD_ERROR_INVALID_PARAM);
    }
    g_quantization_bits = bits;
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (g_model.loaded) {
        g_model.precision_bits = bits;
    }
    return Finish(RAWRXD_SUCCESS);
}

RAWRXD_STATUS __stdcall RawrXD_BatchInferences(const char** prompts, uint32_t prompt_count, RAWRXD_INFERENCE_HANDLE* batch_handle) {
    g_stub_batch_calls.fetch_add(1, std::memory_order_relaxed);
    if (batch_handle == nullptr || prompts == nullptr || prompt_count == 0) {
        return FailInvalidParam();
    }
    if (RequireInitialized() != RAWRXD_SUCCESS) {
        *batch_handle = 0;
        return g_last_error.load();
    }
    std::lock_guard<std::mutex> lock(g_state_mutex);
    if (!g_model.loaded) {
        *batch_handle = 0;
        return Finish(RAWRXD_ERROR_NO_MODEL_LOADED);
    }

    uint64_t total_in = 0;
    for (uint32_t i = 0; i < prompt_count; ++i) {
        if (prompts[i] == nullptr) {
            return FailInvalidParam();
        }
        total_in += EstimateTokenCount(prompts[i], strlen(prompts[i]));
    }

    const uint32_t in_tokens = static_cast<uint32_t>(std::min<uint64_t>(total_in, 0xFFFFFFFFULL));
    const uint32_t out_tokens = std::max<uint32_t>(1u, in_tokens / 2u);
    const double latency = static_cast<double>(prompt_count) * 3.0;
    UpdatePerfLocked(in_tokens, out_tokens, latency);

    g_last_inference.valid = true;
    g_last_inference.handle = g_next_inference_handle.fetch_add(1);
    g_last_inference.result = {};
    g_last_inference.result.input_token_count = in_tokens;
    g_last_inference.result.output_token_count = out_tokens;
    g_last_inference.result.latency_ms = static_cast<uint64_t>(latency);
    g_last_inference.result.status = RAWRXD_SUCCESS;

    *batch_handle = g_last_inference.handle;
    return Finish(RAWRXD_SUCCESS);
}

uint64_t __stdcall RawrXD_TitanStub_GetTelemetryPacked(void) {
    const uint64_t infer_async = static_cast<uint64_t>(g_stub_infer_async_calls.load(std::memory_order_relaxed) & 0xFFFFu);
    const uint64_t infer_sync = static_cast<uint64_t>(g_stub_infer_sync_calls.load(std::memory_order_relaxed) & 0xFFFFu);
    const uint64_t timeout_count = static_cast<uint64_t>(g_stub_timeout_count.load(std::memory_order_relaxed) & 0xFFFFu);
    const uint64_t invalid_count = static_cast<uint64_t>(g_stub_invalid_param_count.load(std::memory_order_relaxed) & 0xFFFFu);
    return infer_async | (infer_sync << 16) | (timeout_count << 32) | (invalid_count << 48);
}

uint64_t __stdcall RawrXD_TitanStub_GetTelemetryExtended(void) {
    const uint64_t batch_calls = static_cast<uint64_t>(g_stub_batch_calls.load(std::memory_order_relaxed) & 0xFFFFu);
    const uint64_t aperture_errors = static_cast<uint64_t>(g_stub_aperture_errors.load(std::memory_order_relaxed) & 0xFFFFu);
    const uint64_t hotpatch_calls = static_cast<uint64_t>(g_stub_hotpatch_apply_calls.load(std::memory_order_relaxed) & 0xFFFFu);
    const uint64_t diag_callback_calls = static_cast<uint64_t>(g_stub_diag_callback_calls.load(std::memory_order_relaxed) & 0xFFFFu);
    return batch_calls | (aperture_errors << 16) | (hotpatch_calls << 32) | (diag_callback_calls << 48);
}

void __stdcall RawrXD_TitanStub_ResetTelemetry(void) {
    ResetStubTelemetry();
}

}  // extern "C"