# Phase 22: ASM Error Parsing & IDE Integration
# cmake/Phase22_ASMErrorParsing.cmake
# ============================================================================
# Captures ml64.exe errors and converts them to IDE-friendly format
# ============================================================================

# -----------------------------------------------------------------------------
# 1. Custom MASM Compilation with Error Capture
# -----------------------------------------------------------------------------
# Override the default MASM compilation to capture and parse errors

if(RAWR_HAS_MASM)
    # Create a wrapper script that captures ml64 output
    set(MASM_ERROR_PARSER "${CMAKE_BINARY_DIR}/tools/parse_masm_errors.ps1")
    
    file(WRITE ${MASM_ERROR_PARSER} "# MASM Error Parser for RawrXD IDE
# Auto-generated by CMake Phase 22

param(
    [Parameter(Mandatory=$true)]$SourceFile,
    [Parameter(Mandatory=$true)]$ObjectFile,
    [Parameter(Mandatory=$true)]$CompilerPath,
    [Parameter(Mandatory=$true)]$WorkingDir
)

$ErrorActionPreference = 'Continue'
$errors = @()
$warnings = @()

# Run ml64 and capture output
$proc = Start-Process -FilePath $CompilerPath `
    -ArgumentList '/c', '/W3', '/nologo', '/Fo', $ObjectFile, $SourceFile `
    -WorkingDirectory $WorkingDir `
    -RedirectStandardError 'ml64.err' `
    -RedirectStandardOutput 'ml64.out' `
    -PassThru `
    -Wait

# Parse error file
if (Test-Path 'ml64.err') {
    $errContent = Get-Content 'ml64.err' -Raw
    
    # Pattern: file(line) : error code: message
    $pattern = '(\S+)\s*\((\d+)\)\s*:\s*(error|warning)\s+(\w+):\s*(.+)'
    
    $matches = [regex]::Matches($errContent, $pattern, 'Multiline')
    foreach ($match in $matches) {
        $file = $match.Groups[1].Value
        $line = [int]$match.Groups[2].Value
        $severity = $match.Groups[3].Value.ToLower()
        $code = $match.Groups[4].Value
        $message = $match.Groups[5].Value.Trim()
        
        # Convert to VS-compatible format
        $vsFormat = \"$file($line): $severity $code`: $message\"
        Write-Output $vsFormat
        
        if ($severity -eq 'error') {
            $errors += $vsFormat
        } else {
            $warnings += $vsFormat
        }
    }
    
    Remove-Item 'ml64.err' -ErrorAction SilentlyContinue
}

if (Test-Path 'ml64.out') {
    Get-Content 'ml64.out' | Write-Output
    Remove-Item 'ml64.out' -ErrorAction SilentlyContinue
}

# Exit with ml64 exit code
exit $proc.ExitCode
")

    message(STATUS "[Phase 22] MASM error parser configured: ${MASM_ERROR_PARSER}")
endif()

# -----------------------------------------------------------------------------
# 2. Problem Matcher Configuration for IDE
# -----------------------------------------------------------------------------
# Generate tasks.json-compatible problem matchers

set(PHASE22_PROBLEM_MATCHERS "${CMAKE_BINARY_DIR}/generated/asm_problem_matchers.json")

file(WRITE ${PHASE22_PROBLEM_MATCHERS} "{
  // Auto-generated by CMake Phase 22
  // MASM Error Patterns for RawrXD IDE Problem Matchers
  \"problemMatchers\": [
    {
      \"name\": \"masm-error\",
      \"pattern\": {
        \"regexp\": \"^(.*)\\((\\d+)\\)\\s*:\\s*(error)\\s+(\\w+):\\s*(.*)$\",
        \"file\": 1,
        \"line\": 2,
        \"severity\": 3,
        \"code\": 4,
        \"message\": 5
      },
      \"fileLocation\": [\"relative\", \"${CMAKE_SOURCE_DIR}\"]
    },
    {
      \"name\": \"masm-warning\",
      \"pattern\": {
        \"regexp\": \"^(.*)\\((\\d+)\\)\\s*:\\s*(warning)\\s+(\\w+):\\s*(.*)$\",
        \"file\": 1,
        \"line\": 2,
        \"severity\": 3,
        \"code\": 4,
        \"message\": 5
      },
      \"fileLocation\": [\"relative\", \"${CMAKE_SOURCE_DIR}\"]
    }
  ],
  \"errorCodes\": {
    // Common ml64 error codes with explanations
    \"A2008\": \"Syntax error - check instruction format and operands\",
    \"A2013\": \"Invalid use of register - verify register size matches operation\",
    \"A2032\": \"Invalid use of register in current context\",
    \"A2070\": \"Invalid instruction operands - check operand types\",
    \"A2074\": \"Cannot access label through segment registers\",
    \"A2102\": \"Unmatched block nesting - check PROC/ENDP pairs\",
    \"A2206\": \"Missing operator in expression\",
    \"A2210\": \"Syntax error in expression\",
    \"A3000\": \"Cannot open file - check include paths\",
    \"A5000\": \"Internal assembler error\"
  }
}")

message(STATUS "[Phase 22] Problem matchers generated: ${PHASE22_PROBLEM_MATCHERS}")

# -----------------------------------------------------------------------------
# 3. IDE Integration Target
# -----------------------------------------------------------------------------
# Create a target that validates ASM error parsing works

if(RAWR_HAS_MASM)
    add_custom_target(test_asm_error_parsing
        COMMAND ${CMAKE_COMMAND} -E echo "Testing ASM error parsing..."
        COMMAND powershell -NoProfile -ExecutionPolicy Bypass
                -File ${MASM_ERROR_PARSER}
                -SourceFile ${CMAKE_SOURCE_DIR}/src/lora/ApplyLoRA_Fixed.asm
                -ObjectFile ${CMAKE_BINARY_DIR}/test.obj
                -CompilerPath ${CMAKE_ASM_MASM_COMPILER}
                -WorkingDir ${CMAKE_BINARY_DIR}
        WORKING_DIRECTORY ${CMAKE_BINARY_DIR}
        COMMENT "Validating MASM error parsing pipeline"
        VERBATIM
    )
endif()

# -----------------------------------------------------------------------------
# 4. Build Output Integration
# -----------------------------------------------------------------------------
# Ensure ASM errors appear in IDE build output

message(STATUS "")
message(STATUS "=== Phase 22: ASM Error Parsing ===")
message(STATUS "  Error Parser:       ${MASM_ERROR_PARSER}")
message(STATUS "  Problem Matchers:   ${PHASE22_PROBLEM_MATCHERS}")
message(STATUS "  Test Target:        test_asm_error_parsing")
message(STATUS "=====================================")
message(STATUS "")
