# RawrXDBuildOptions.cmake
# Comprehensive build configuration options for RawrXD
#
# Usage:
#   include(RawrXDBuildOptions)
#   rawrxd_configure_build_options()

# Build type options
set(RAWRXD_BUILD_TYPES "Debug;Release;RelWithDebInfo;MinSizeRel")
if(NOT CMAKE_BUILD_TYPE)
    set(CMAKE_BUILD_TYPE "Release" CACHE STRING "Build type")
endif()
set_property(CACHE CMAKE_BUILD_TYPE PROPERTY STRINGS ${RAWRXD_BUILD_TYPES})

# Feature options
option(RAWRXD_ENABLE_MASM "Enable MASM64 assembly kernels" ON)
option(RAWRXD_ENABLE_AVX512 "Enable AVX-512 optimizations" ON)
option(RAWRXD_ENABLE_AMX "Enable Intel AMX (Advanced Matrix Extensions)" OFF)
option(RAWRXD_ENABLE_VULKAN "Enable Vulkan compute backend" ON)
option(RAWRXD_ENABLE_CUDA "Enable CUDA backend" OFF)
option(RAWRXD_ENABLE_ROCM "Enable ROCm/HIP backend" OFF)
option(RAWRXD_ENABLE_OPENCL "Enable OpenCL backend" OFF)
option(RAWRXD_ENABLE_METAL "Enable Metal backend (macOS)" OFF)

# Inference options
option(RAWRXD_ENABLE_FLASH_ATTENTION "Enable Flash Attention optimizations" ON)
option(RAWRXD_ENABLE_SPECULATIVE "Enable speculative decoding" ON)
option(RAWRXD_ENABLE_STREAMING "Enable streaming generation" ON)
option(RAWRXD_ENABLE_BATCHING "Enable request batching" ON)
option(RAWRXD_ENABLE_DISTRIBUTED "Enable distributed inference" OFF)

# Security options
option(RAWRXD_ENABLE_ENCRYPTION "Enable model encryption support" ON)
option(RAWRXD_ENABLE_SANDBOX "Enable sandboxed execution" ON)
option(RAWRXD_ENABLE_AUDIT "Enable security audit logging" ON)

# Developer options
option(RAWRXD_BUILD_TESTS "Build test suite" ON)
option(RAWRXD_BUILD_BENCHMARKS "Build benchmarks" ON)
option(RAWRXD_BUILD_EXAMPLES "Build example applications" ON)
option(RAWRXD_BUILD_DOCS "Build documentation" OFF)
option(RAWRXD_ENABLE_PROFILING "Enable performance profiling" OFF)
option(RAWRXD_ENABLE_SANITIZERS "Enable address/UB sanitizers" OFF)
option(RAWRXD_ENABLE_COVERAGE "Enable code coverage" OFF)

# Platform-specific defaults
if(WIN32)
    set(RAWRXD_PLATFORM "windows")
    if(MSVC)
        set(RAWRXD_ENABLE_MASM ON)
    else()
        set(RAWRXD_ENABLE_MASM OFF)
    endif()
elseif(APPLE)
    set(RAWRXD_PLATFORM "macos")
    set(RAWRXD_ENABLE_METAL ON)
    set(RAWRXD_ENABLE_MASM OFF)
elseif(UNIX)
    set(RAWRXD_PLATFORM "linux")
    set(RAWRXD_ENABLE_MASM OFF)
endif()

# Architecture detection
if(CMAKE_SYSTEM_PROCESSOR MATCHES "AMD64|x86_64|x64")
    set(RAWRXD_ARCH "x64")
    set(RAWRXD_ENABLE_AVX512 ON)
elseif(CMAKE_SYSTEM_PROCESSOR MATCHES "ARM64|aarch64")
    set(RAWRXD_ARCH "arm64")
    set(RAWRXD_ENABLE_AVX512 OFF)
    set(RAWRXD_ENABLE_MASM OFF)
else()
    set(RAWRXD_ARCH "x86")
    set(RAWRXD_ENABLE_AVX512 OFF)
endif()

# Compiler-specific options
if(MSVC)
    set(RAWRXD_COMPILER "msvc")
    add_compile_options(/W4 /WX-)
    if(RAWRXD_ENABLE_AVX512)
        add_compile_options(/arch:AVX512)
    endif()
elseif(CMAKE_CXX_COMPILER_ID MATCHES "GNU")
    set(RAWRXD_COMPILER "gcc")
    add_compile_options(-Wall -Wextra -Wpedantic)
    if(RAWRXD_ENABLE_AVX512)
        add_compile_options(-mavx512f -mavx512dq -mavx512bw -mavx512vl)
    endif()
elseif(CMAKE_CXX_COMPILER_ID MATCHES "Clang")
    set(RAWRXD_COMPILER "clang")
    add_compile_options(-Wall -Wextra -Wpedantic)
    if(RAWRXD_ENABLE_AVX512)
        add_compile_options(-mavx512f -mavx512dq -mavx512bw -mavx512vl)
    endif()
endif()

# Sanitizer options
if(RAWRXD_ENABLE_SANITIZERS)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        add_compile_options(-fsanitize=address,undefined)
        add_link_options(-fsanitize=address,undefined)
    endif()
endif()

# Coverage options
if(RAWRXD_ENABLE_COVERAGE)
    if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang")
        add_compile_options(--coverage)
        add_link_options(--coverage)
    endif()
endif()

# Print configuration summary
function(rawrxd_print_build_config)
    message(STATUS "")
    message(STATUS "RawrXD Build Configuration:")
    message(STATUS "  Platform: ${RAWRXD_PLATFORM}")
    message(STATUS "  Architecture: ${RAWRXD_ARCH}")
    message(STATUS "  Compiler: ${RAWRXD_COMPILER}")
    message(STATUS "  Build Type: ${CMAKE_BUILD_TYPE}")
    message(STATUS "")
    message(STATUS "  Features:")
    message(STATUS "    MASM Kernels: ${RAWRXD_ENABLE_MASM}")
    message(STATUS "    AVX-512: ${RAWRXD_ENABLE_AVX512}")
    message(STATUS "    AMX: ${RAWRXD_ENABLE_AMX}")
    message(STATUS "    Vulkan: ${RAWRXD_ENABLE_VULKAN}")
    message(STATUS "    CUDA: ${RAWRXD_ENABLE_CUDA}")
    message(STATUS "    ROCm: ${RAWRXD_ENABLE_ROCM}")
    message(STATUS "    OpenCL: ${RAWRXD_ENABLE_OPENCL}")
    message(STATUS "    Metal: ${RAWRXD_ENABLE_METAL}")
    message(STATUS "")
    message(STATUS "  Inference:")
    message(STATUS "    Flash Attention: ${RAWRXD_ENABLE_FLASH_ATTENTION}")
    message(STATUS "    Speculative: ${RAWRXD_ENABLE_SPECULATIVE}")
    message(STATUS "    Streaming: ${RAWRXD_ENABLE_STREAMING}")
    message(STATUS "    Batching: ${RAWRXD_ENABLE_BATCHING}")
    message(STATUS "    Distributed: ${RAWRXD_ENABLE_DISTRIBUTED}")
    message(STATUS "")
    message(STATUS "  Build Targets:")
    message(STATUS "    Tests: ${RAWRXD_BUILD_TESTS}")
    message(STATUS "    Benchmarks: ${RAWRXD_BUILD_BENCHMARKS}")
    message(STATUS "    Examples: ${RAWRXD_BUILD_EXAMPLES}")
    message(STATUS "    Docs: ${RAWRXD_BUILD_DOCS}")
    message(STATUS "")
endfunction()

# Export configuration header
function(rawrxd_generate_config_header output_dir)
    set(_config_h "${output_dir}/rawrxd_build_config.h")
    
    file(WRITE ${_config_h} "/* Auto-generated build configuration */\n")
    file(APPEND ${_config_h} "#ifndef RAWRXD_BUILD_CONFIG_H\n")
    file(APPEND ${_config_h} "#define RAWRXD_BUILD_CONFIG_H\n\n")
    
    file(APPEND ${_config_h} "#define RAWRXD_VERSION_MAJOR ${PROJECT_VERSION_MAJOR}\n")
    file(APPEND ${_config_h} "#define RAWRXD_VERSION_MINOR ${PROJECT_VERSION_MINOR}\n")
    file(APPEND ${_config_h} "#define RAWRXD_VERSION_PATCH ${PROJECT_VERSION_PATCH}\n")
    file(APPEND ${_config_h} "#define RAWRXD_VERSION \"${PROJECT_VERSION}\"\n\n")
    
    file(APPEND ${_config_h} "#define RAWRXD_PLATFORM_${RAWRXD_PLATFORM_UPPER} 1\n")
    file(APPEND ${_config_h} "#define RAWRXD_ARCH_${RAWRXD_ARCH_UPPER} 1\n\n")
    
    if(RAWRXD_ENABLE_MASM)
        file(APPEND ${_config_h} "#define RAWRXD_ENABLE_MASM 1\n")
    endif()
    if(RAWRXD_ENABLE_AVX512)
        file(APPEND ${_config_h} "#define RAWRXD_ENABLE_AVX512 1\n")
    endif()
    if(RAWRXD_ENABLE_AMX)
        file(APPEND ${_config_h} "#define RAWRXD_ENABLE_AMX 1\n")
    endif()
    if(RAWRXD_ENABLE_VULKAN)
        file(APPEND ${_config_h} "#define RAWRXD_ENABLE_VULKAN 1\n")
    endif()
    if(RAWRXD_ENABLE_CUDA)
        file(APPEND ${_config_h} "#define RAWRXD_ENABLE_CUDA 1\n")
    endif()
    if(RAWRXD_ENABLE_FLASH_ATTENTION)
        file(APPEND ${_config_h} "#define RAWRXD_ENABLE_FLASH_ATTENTION 1\n")
    endif()
    if(RAWRXD_ENABLE_SPECULATIVE)
        file(APPEND ${_config_h} "#define RAWRXD_ENABLE_SPECULATIVE 1\n")
    endif()
    if(RAWRXD_ENABLE_STREAMING)
        file(APPEND ${_config_h} "#define RAWRXD_ENABLE_STREAMING 1\n")
    endif()
    
    file(APPEND ${_config_h} "\n#endif /* RAWRXD_BUILD_CONFIG_H */\n")
    
    message(STATUS "Generated build config: ${_config_h}")
endfunction()

string(TOUPPER ${RAWRXD_PLATFORM} RAWRXD_PLATFORM_UPPER)
string(TOUPPER ${RAWRXD_ARCH} RAWRXD_ARCH_UPPER)
