# CMake generated Testfile for 
# Source directory: F:/rawrxd/tests
# Build directory: F:/rawrxd/vs_validation/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("VS_DLL_LoadUnload_DEBUG" "F:/rawrxd/vs_validation/bin/Debug/test_dll_load_unloadd.exe")
  set_tests_properties("VS_DLL_LoadUnload_DEBUG" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;66;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("VS_DLL_LoadUnload_RELEASE" "F:/rawrxd/vs_validation/bin/Release/test_dll_load_unload.exe")
  set_tests_properties("VS_DLL_LoadUnload_RELEASE" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;70;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("VS_DLL_Multithread_DEBUG" "F:/rawrxd/vs_validation/bin/Debug/test_dll_multithreadd.exe")
  set_tests_properties("VS_DLL_Multithread_DEBUG" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;94;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("VS_DLL_Multithread_RELEASE" "F:/rawrxd/vs_validation/bin/Release/test_dll_multithread.exe")
  set_tests_properties("VS_DLL_Multithread_RELEASE" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;98;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("VS_CPP_API_DEBUG" "F:/rawrxd/vs_validation/bin/Debug/test_cpp_apid.exe")
  set_tests_properties("VS_CPP_API_DEBUG" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;122;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("VS_CPP_API_RELEASE" "F:/rawrxd/vs_validation/bin/Release/test_cpp_api.exe")
  set_tests_properties("VS_CPP_API_RELEASE" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;126;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("VS_InferenceIntegration_DEBUG" "F:/rawrxd/vs_validation/bin/Debug/test_inference_integrationd.exe")
  set_tests_properties("VS_InferenceIntegration_DEBUG" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;150;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("VS_InferenceIntegration_RELEASE" "F:/rawrxd/vs_validation/bin/Release/test_inference_integration.exe")
  set_tests_properties("VS_InferenceIntegration_RELEASE" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;154;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("VS_Win32IDE_Integration_DEBUG" "F:/rawrxd/vs_validation/bin/Debug/test_win32ide_integrationd.exe")
  set_tests_properties("VS_Win32IDE_Integration_DEBUG" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;178;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("VS_Win32IDE_Integration_RELEASE" "F:/rawrxd/vs_validation/bin/Release/test_win32ide_integration.exe")
  set_tests_properties("VS_Win32IDE_Integration_RELEASE" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;182;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("VS_Config_Roundtrip_DEBUG" "F:/rawrxd/vs_validation/bin/Debug/test_config_roundtripd.exe")
  set_tests_properties("VS_Config_Roundtrip_DEBUG" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;206;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("VS_Config_Roundtrip_RELEASE" "F:/rawrxd/vs_validation/bin/Release/test_config_roundtrip.exe")
  set_tests_properties("VS_Config_Roundtrip_RELEASE" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;210;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("VS_Memory_Stress_DEBUG" "F:/rawrxd/vs_validation/bin/Debug/test_memory_stressd.exe")
  set_tests_properties("VS_Memory_Stress_DEBUG" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;234;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("VS_Memory_Stress_RELEASE" "F:/rawrxd/vs_validation/bin/Release/test_memory_stress.exe")
  set_tests_properties("VS_Memory_Stress_RELEASE" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;238;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("VS_Symbol_Exports_DEBUG" "F:/rawrxd/vs_validation/bin/Debug/test_symbol_exportsd.exe")
  set_tests_properties("VS_Symbol_Exports_DEBUG" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;262;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("VS_Symbol_Exports_RELEASE" "F:/rawrxd/vs_validation/bin/Release/test_symbol_exports.exe")
  set_tests_properties("VS_Symbol_Exports_RELEASE" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;266;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("VS_Cross_Config_DEBUG" "F:/rawrxd/vs_validation/bin/Debug/test_cross_configd.exe")
  set_tests_properties("VS_Cross_Config_DEBUG" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;292;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("VS_Cross_Config_RELEASE" "F:/rawrxd/vs_validation/bin/Release/test_cross_config.exe")
  set_tests_properties("VS_Cross_Config_RELEASE" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;296;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test("VS_Debug_Info_DEBUG" "F:/rawrxd/vs_validation/bin/Debug/test_debug_infod.exe")
  set_tests_properties("VS_Debug_Info_DEBUG" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;320;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test("VS_Debug_Info_RELEASE" "F:/rawrxd/vs_validation/bin/Release/test_debug_info.exe")
  set_tests_properties("VS_Debug_Info_RELEASE" PROPERTIES  _BACKTRACE_TRIPLES "F:/rawrxd/tests/CMakeLists.txt;324;add_test;F:/rawrxd/tests/CMakeLists.txt;0;")
endif()
