name: Build Windows EXE

on:
  workflow_dispatch:
  push:
    paths:
      - ai_coder_windows.py
      - .github/workflows/build-windows.yml

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build EXE
        run: |
          pyinstaller --noconfirm --onefile --console --name AICodeGenerator ai_coder_windows.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: AICodeGenerator-exe
          path: dist/AICodeGenerator.exe