#ifndef CAPABILITY_MANIFEST_GENERATED_HPP
#define CAPABILITY_MANIFEST_GENERATED_HPP

//=============================================================================
// AUTO-GENERATED by RAWRXD_MODEL_GENIE_HEADER_EXPORT_001
// DO NOT EDIT MANUALLY
// Source: NUGVERSE_ESTIMATOR_001 (frozen)
//=============================================================================

#pragma once

#include <cstdint>
#include <array>
#include <optional>
#include "ModelGenome.hpp"

// Primitive requirements and availability
// Generated from ModelGenome: CAPABILITY_MANIFEST_GENERATED_HPP

namespace RawrXD {
namespace Deep2 {
namespace Generated {

struct CapabilityManifest {
    std::array<Primitive, 10> requiredPrimitives;
    uint32_t requiredCount;
    std::array<Primitive, 9> availablePrimitives;
    uint32_t availableCount;
    std::array<Primitive, 1> unimplementedPrimitives;
    uint32_t unimplementedCount;
    Primitive firstUnimplementedPrimitive;
    bool runtimeExecutable;
};

inline constexpr CapabilityManifest kCapabilityManifest = {
    .requiredPrimitives = {Primitive::LinearFwd, Primitive::RmsNormFwd, Primitive::MlaDecompressFwd, Primitive::AttentionFwd, Primitive::ResidualAddFwd, Primitive::RouterFwd, Primitive::TopKFwd, Primitive::MoEExecuteFwd, Primitive::LMHeadFwd},
    .requiredCount = 9,
    .availablePrimitives = {Primitive::LinearFwd, Primitive::RmsNormFwd, Primitive::MlaDecompressFwd, Primitive::AttentionFwd, Primitive::ResidualAddFwd, Primitive::RouterFwd, Primitive::TopKFwd, Primitive::MoEExecuteFwd, Primitive::LMHeadFwd},
    .availableCount = 9,
    .unimplementedPrimitives = {Primitive::MlaDecompressFwd},
    .unimplementedCount = 1,
    .firstUnimplementedPrimitive = Primitive::MlaDecompressFwd,
    .runtimeExecutable = false
};

} // namespace Generated
} // namespace Deep2
} // namespace RawrXD

#endif // CAPABILITY_MANIFEST_GENERATED_HPP
